"""Small, static, manually governed public API manifest for contract tests."""

PUBLIC_API_EXPORTS: dict[str, tuple[str, ...]] = {
    "cpmoakb.domain": (
        "AuthorityIdentifier",
        "AuthorityReference",
        "AuthorityRepository",
        "CandidateIdentifier",
        "CandidateRecord",
        "CanonicalIdentifier",
        "ClassificationReference",
        "CreationProvenance",
        "DomainError",
        "DuplicatePreferredLabelError",
        "DuplicateRecordError",
        "EntityRecord",
        "EvidenceReference",
        "EvidenceRole",
        "ExternalIdentifier",
        "InvalidIdentifierError",
        "InvalidLabelError",
        "InvalidRecordError",
        "InvalidRelationshipError",
        "Label",
        "LabelSet",
        "LabelStatus",
        "Provenance",
        "RecordKind",
        "RecordLifecycle",
        "RecordNotFoundError",
        "RecordRepository",
        "RelationshipRecord",
        "RepositoryError",
        "ReviewProvenance",
        "ScientificName",
        "SourceIdentifier",
        "SourceReference",
        "SourceRepository",
        "SupersessionProvenance",
        "ValidationIssue",
        "ValidationResult",
        "ValidationSeverity",
        "Validator",
    ),
    "cpmoakb.adapters": (
        "SUPPORTED_SCHEMA_VERSIONS",
        "UnsupportedYamlFeatureError",
        "YamlAdapterError",
        "YamlFileError",
        "YamlMappingError",
        "YamlRestrictionError",
        "YamlSchemaVersionError",
        "YamlStructureError",
        "YamlSyntaxError",
        "load_candidate_yaml",
        "load_candidate_yaml_bytes",
        "load_candidate_yaml_file",
        "parse_candidate_yaml",
        "parse_candidate_yaml_bytes",
    ),
    "cpmoakb.adapters.yaml": (
        "SUPPORTED_SCHEMA_VERSIONS",
        "UnsupportedYamlFeatureError",
        "YamlAdapterError",
        "YamlFileError",
        "YamlMappingError",
        "YamlRestrictionError",
        "YamlSchemaVersionError",
        "YamlStructureError",
        "YamlSyntaxError",
        "load_candidate_yaml",
        "load_candidate_yaml_bytes",
        "load_candidate_yaml_file",
        "parse_candidate_yaml",
        "parse_candidate_yaml_bytes",
    ),
    "cpmoakb.validation": (
        "DuplicateRuleIdentifierError",
        "GENERIC_BATCH_PROFILE",
        "GENERIC_CANDIDATE_PROFILE",
        "InvalidValidationContextError",
        "InvalidValidationProfileError",
        "RuleApplicability",
        "RuleMetadata",
        "UnsupportedValidationTargetError",
        "ValidationContext",
        "ValidationFinding",
        "ValidationFrameworkError",
        "ValidationLayer",
        "ValidationProfile",
        "ValidationRule",
        "validate_record",
        "validate_records",
        "validate_irac_document",
        "validate_irac_v11_5",
    ),
    "cpmoakb.registries": (
        "AuthorityRegistry",
        "AuthorityRegistrySnapshot",
        "CandidateIdentifierRegistry",
        "CandidateIdentifierRegistryEntry",
        "CandidateIdentifierRegistrySnapshot",
        "CandidateIdentifierState",
        "IdentifierAlreadyReservedError",
        "IdentifierNotReservedError",
        "IdentifierStateTransitionError",
        "InvalidRegistryOperationError",
        "RegistryConflictError",
        "RegistryError",
        "RegistryItemNotFoundError",
        "SourceRegistry",
        "SourceRegistrySnapshot",
    ),
    "cpmoakb.query": (
        "DuplicateQueryRecordError",
        "InvalidQueryCriteriaError",
        "LabelScope",
        "QueryCriteria",
        "QueryError",
        "QueryItemNotFoundError",
        "QueryMatch",
        "QueryResult",
        "QueryService",
        "ReadOnlyQueryIndex",
        "RegistrySnapshotQueryService",
        "TextMatchMode",
        "UnsupportedQueryOperationError",
    ),
    "cpmoakb.explain": (
        "Explanation",
        "ExplanationAvailability",
        "ExplanationError",
        "ExplanationFact",
        "ExplanationLimitation",
        "ExplanationReference",
        "ExplanationReferenceType",
        "ExplanationRenderingError",
        "ExplanationService",
        "ExplanationType",
        "InvalidExplanationInputError",
        "UnavailableRequestType",
        "UnsupportedExplanationTargetError",
        "build_query_match_explanation",
        "build_record_evidence_explanation",
        "build_record_status_explanation",
        "build_unavailable_explanation",
        "build_validation_issue_explanation",
        "render_explanation",
    ),
    "cpmoakb.serialization": (
        "JsonScalar",
        "JsonValue",
        "ProjectionContractError",
        "RUNTIME_JSON_PROJECTION_VERSION",
        "SerializationError",
        "UnsupportedProjectionTypeError",
        "project_query_result",
        "project_registry_snapshot",
        "project_runtime_value",
        "project_structured_explanation",
        "project_validation_result",
        "to_canonical_json",
    ),
    "cpmoakb.application": (
        "ApplicationContractError",
        "ApplicationDependencyError",
        "ApplicationServiceError",
        "ExplainQueryRequest",
        "ExplainQueryResponse",
        "ProjectedApplicationResponse",
        "QueryAndExplainRequest",
        "QueryAndExplainResponse",
        "QueryRecordsRequest",
        "QueryRecordsResponse",
        "RUNTIME_APPLICATION_API_VERSION",
        "RuntimeApplicationService",
        "UnsupportedApplicationRequestError",
        "classify_application_error",
    ),
    "cpmoakb.http_api": (
        "RUNTIME_HTTP_API_VERSION",
        "create_http_app",
    ),
    "cpmoakb.cli": (
        "RUNTIME_CLI_API_VERSION",
        "run_cli",
    ),
}

EXPERIMENTAL_EXPORTS: frozenset[tuple[str, str]] = frozenset(
    {
        ("cpmoakb.domain", "AuthorityRepository"),
        ("cpmoakb.domain", "CanonicalIdentifier"),
        ("cpmoakb.domain", "ClassificationReference"),
        ("cpmoakb.domain", "RecordRepository"),
        ("cpmoakb.domain", "ScientificName"),
        ("cpmoakb.domain", "SourceRepository"),
        ("cpmoakb.domain", "Validator"),
        ("cpmoakb.validation", "RuleMetadata"),
        ("cpmoakb.validation", "ValidationContext"),
        ("cpmoakb.validation", "ValidationProfile"),
        ("cpmoakb.validation", "ValidationRule"),
        ("cpmoakb.query", "ReadOnlyQueryIndex"),
        ("cpmoakb.query", "RegistrySnapshotQueryService"),
        ("cpmoakb.explain", "build_query_match_explanation"),
        ("cpmoakb.explain", "build_record_evidence_explanation"),
        ("cpmoakb.explain", "build_record_status_explanation"),
        ("cpmoakb.explain", "build_unavailable_explanation"),
        ("cpmoakb.explain", "build_validation_issue_explanation"),
    }
)
