import { createServer } from "node:http";
import { createHash, randomUUID } from "node:crypto";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import { extname, resolve, sep } from "node:path";
import { fileURLToPath } from "node:url";
import { PilotStore } from "./pilot-store.mjs";
import { PilotKnowledgeStore } from "./knowledge-store.mjs";
import { createConfiguredVisualPerceptionProvider } from "./visual-perception.mjs";
import { validatePilotConfiguration } from "./pilot-hardening-runtime.mjs";
import { createPilotCredentialRegistry } from "./pilot-auth.mjs";

const ROOT = fileURLToPath(new URL(".", import.meta.url));
const MIME = { ".html":"text/html; charset=utf-8", ".js":"text/javascript; charset=utf-8", ".mjs":"text/javascript; charset=utf-8", ".css":"text/css; charset=utf-8", ".json":"application/json; charset=utf-8", ".svg":"image/svg+xml", ".png":"image/png", ".ico":"image/x-icon", ".txt":"text/plain; charset=utf-8" };

export function validateChatPayload(value) {
  if (!value || typeof value !== "object" || Array.isArray(value)) throw new Error("invalid request");
  const allowed = new Set(["message", "scope", "field_id", "season_id"]); if (Object.keys(value).some((key) => !allowed.has(key))) throw new Error("invalid request");
  if (typeof value.message !== "string" || !value.message.trim() || value.message.length > 4_000) throw new Error("invalid message");
  if (!["FIELD_SCOPED", "CASE_SCOPED"].includes(value.scope)) throw new Error("invalid scope");
  for (const key of ["field_id", "season_id"]) if (value[key] != null && (typeof value[key] !== "string" || value[key].length > 128)) throw new Error(`invalid ${key}`);
  return { message:value.message.trim(), scope:value.scope, field_id:value.field_id ?? null, season_id:value.season_id ?? null };
}

export function extractOutputText(response) { return (response?.output ?? []).flatMap((item) => item?.content ?? []).filter((item) => item?.type === "output_text").map((item) => item.text).join("\n").trim(); }

async function loadLocalEnvironment() { try { const text = await readFile(resolve(ROOT, ".env.local"), "utf8"); for (const line of text.split(/\r?\n/)) { const match = line.match(/^([A-Z][A-Z0-9_]*)=(.*)$/); if (match && process.env[match[1]] === undefined) process.env[match[1]] = match[2].trim(); } } catch { /* Host environment may provide configuration. */ } }
async function readJson(request, limit = 32_768) { if(!String(request.headers["content-type"]??"").toLowerCase().startsWith("application/json"))throw Object.assign(new Error("application/json required"),{code:"UNSUPPORTED_MEDIA_TYPE",status:415});const chunks = []; let size = 0; for await (const chunk of request) { size += chunk.length; if (size > limit) throw Object.assign(new Error("request too large"),{code:"PAYLOAD_TOO_LARGE",status:413}); chunks.push(chunk); } try{return JSON.parse(Buffer.concat(chunks).toString("utf8"));}catch{throw Object.assign(new Error("malformed JSON"),{code:"VALIDATION_ERROR",status:400});} }
function json(response, status, payload) { response.writeHead(status, { "content-type":"application/json; charset=utf-8", "cache-control":"no-store", "x-content-type-options":"nosniff" }); response.end(JSON.stringify(payload)); }
function contractError(message) { return Object.assign(new Error(message),{code:"VALIDATION_ERROR",status:400}); }
function sessionToken(request) { return request.headers.cookie?.split(";").map((item) => item.trim()).find((item) => item.startsWith("pilot_session="))?.slice("pilot_session=".length) ?? null; }
const FEATURE_ROUTE_CONTRACT=Object.freeze([
  {feature:"conversation_provider",methods:["POST"],prefixes:["/api/pilot/conversation-turns"]},
  {feature:"visual_perception_provider",methods:["GET","POST"],prefixes:["/api/pilot/visual-perception"]},
  {feature:"f1_management_review",methods:["GET"],prefixes:["/api/pilot/management-options","/api/pilot/management-review-context"]},
  {feature:"f2_management_action",methods:["POST"],prefixes:["/api/pilot/human-decisions","/api/pilot/management-actions","/api/pilot/outcome-observations","/api/pilot/outcome-comparisons"]},
  {feature:"f2_management_action",methods:["GET"],paths:["/api/pilot/outcome-review","/api/pilot/decision-action-outcome-context"]},
  {feature:"step_h_local_pattern",methods:["GET","POST"],prefixes:["/api/pilot/cross-case-comparisons","/api/pilot/local-pattern","/api/pilot/spatial-pattern"]},
  {feature:"step_i_learning",methods:["GET","POST"],prefixes:["/api/pilot/learning-","/api/pilot/reviewed-case","/api/pilot/knowledge-"]}
]);
export function featureForRequest(method,path){if(path==="/api/pilot/learning-signals"||path==="/api/pilot/admin/learning-signals")return null;return FEATURE_ROUTE_CONTRACT.find((item)=>item.methods.includes(method)&&((item.paths??[]).includes(path)||(item.prefixes??[]).some((prefix)=>path.startsWith(prefix))))?.feature??null;}

async function serveStatic(request, response) {
  const pathname = decodeURIComponent(new URL(request.url, "http://localhost").pathname), relative = pathname === "/" ? "index.html" : pathname.replace(/^\/+/, "");
  if (relative.startsWith(".") || relative.includes(`..${sep}`) || relative === ".env.local") return json(response, 404, { status:"NOT_FOUND" });
  const filePath = resolve(ROOT, relative); if (!filePath.startsWith(resolve(ROOT) + sep)) return json(response, 404, { status:"NOT_FOUND" });
  try { const body = await readFile(filePath); response.writeHead(200, { "content-type":MIME[extname(filePath)] ?? "application/octet-stream", "x-content-type-options":"nosniff" }); response.end(body); }
  catch { json(response, 404, { status:"NOT_FOUND" }); }
}

export async function startServer({ port, host, publicBaseUrl = null, allowExternalBinding = null, dbPath, exportDir, uploadDir: configuredUploadDir, pilotProfile = null, authPassword = null, pilotUsers = null, pilotUserId = null, pilotLoginId = null, featureFlags = null, requestLimits = null, sessionTtlMs = null, investigationRuleProvider = null, investigationCandidateProvider = null, intelligenceClock = null, intelligenceIdProvider = null, guidanceRuleProvider = null, guidanceClock = null, guidanceIdProvider = null, visualPerceptionProvider = null, visualClock = null, visualIdProvider = null, visualPerceptionAdapter = null, visualPerceptionClock = null, visualPerceptionIdProvider = null, visualPerceptionContextResolver = null, managementRuleProvider = null, managementClock = null, managementIdProvider = null, decisionActionOutcomeClock = null, decisionActionOutcomeIdProvider = null, followupClock = null, followupIdProvider = null, followupTimezone = "UTC", spatialPatternClock = null, spatialPatternIdProvider = null, learningClock = null, learningIdProvider = null, conversationProvider = null, conversationClock = null, conversationIdProvider = null } = {}) {
  await loadLocalEnvironment();
  const selectedPort = Number(port ?? process.env.PORT ?? 4173), selectedHost = host ?? process.env.PILOT_HOST ?? "127.0.0.1",selectedDbPath=resolve(dbPath ?? process.env.PILOT_DB_PATH ?? resolve(ROOT,"data/pilot.sqlite")),selectedExportDir=resolve(exportDir ?? process.env.PILOT_EXPORT_DIR ?? resolve(ROOT,"data/exports"));
  const uploadDir = resolve(configuredUploadDir ?? process.env.PILOT_UPLOAD_DIR ?? resolve(ROOT, "data/uploads"));
  const configuration=validatePilotConfiguration({profile:pilotProfile??process.env.PILOT_PROFILE??"DEVELOPMENT",host:selectedHost,allow_external_binding:allowExternalBinding??process.env.PILOT_ALLOW_LAN==="true",public_base_url:publicBaseUrl??process.env.PILOT_PUBLIC_BASE_URL,db_path:selectedDbPath,export_dir:selectedExportDir,upload_dir:uploadDir,auth_password:authPassword??process.env.PILOT_AUTH_PASSWORD,session_ttl_ms:sessionTtlMs??43_200_000,limits:requestLimits??undefined,feature_flags:featureFlags??undefined});
  let configuredUsers=pilotUsers;if(configuredUsers==null&&process.env.PILOT_USERS_JSON){try{configuredUsers=JSON.parse(process.env.PILOT_USERS_JSON);}catch{throw Object.assign(new Error("invalid PILOT_USERS_JSON"),{code:"CONFIGURATION_ERROR",status:503});}}
  if(configuration.profile==="FIELD_CAPTURE_ALPHA"&&(!Array.isArray(configuredUsers)||configuredUsers.filter((user)=>user?.enabled!==false).length<3))throw Object.assign(new Error("FIELD_CAPTURE_ALPHA requires at least three enabled configured users"),{code:"CONFIGURATION_ERROR",status:503});
  const credentials=createPilotCredentialRegistry({users:configuredUsers,defaultPassword:configuration.auth_password,defaultUserId:pilotUserId??process.env.PILOT_USER_ID??"prototype-spa-001",defaultLoginId:pilotLoginId??process.env.PILOT_LOGIN_ID??"pilot"});await mkdir(uploadDir, { recursive:true });
  const selectedVisualPerceptionAdapter = visualPerceptionAdapter ?? createConfiguredVisualPerceptionProvider();
  const visualPerceptionImageLoader = async (storageKey) => { const path=resolve(uploadDir,storageKey);if(!path.startsWith(uploadDir+sep))throw contractError("invalid server-managed image reference");return readFile(path); };
  const store = await new PilotStore({ dbPath:selectedDbPath,exportDir:selectedExportDir,pilotProfile:configuration.profile,pilotConfiguration:configuration, investigationRuleProvider, investigationCandidateProvider, intelligenceClock, intelligenceIdProvider, guidanceRuleProvider, guidanceClock, guidanceIdProvider, visualPerceptionProvider, visualClock, visualIdProvider, visualPerceptionAdapter:selectedVisualPerceptionAdapter, visualPerceptionClock, visualPerceptionIdProvider, visualPerceptionImageLoader, visualPerceptionContextResolver, managementRuleProvider, managementClock, managementIdProvider, decisionActionOutcomeClock, decisionActionOutcomeIdProvider, followupClock, followupIdProvider, followupTimezone, spatialPatternClock, spatialPatternIdProvider, learningClock, learningIdProvider, conversationProvider, conversationClock, conversationIdProvider }).open();
  const knowledge = await new PilotKnowledgeStore().open(), sessions = new Map();
  const server = createServer(async (request, response) => {
    const url = new URL(request.url, "http://localhost");
    const correlationId=/^[A-Za-z0-9._:-]{1,160}$/.test(String(request.headers["x-request-id"]??""))?String(request.headers["x-request-id"]):randomUUID();response.setHeader("x-correlation-id",correlationId);
    try {
      if (request.method === "GET" && url.pathname === "/health") return json(response, 200, {...store.getPilotHealth(),network_mode:configuration.mode,bind_host:configuration.host,public_base_url:configuration.public_base_url,secure_cookie:configuration.secure_cookie});
      if (request.method === "GET" && url.pathname === "/readiness") return json(response,200,store.getPilotReadiness({provider_state:conversationProvider?"READY":"UNAVAILABLE"}));
      if (request.method === "POST" && url.pathname === "/api/pilot/session") { const payload = await readJson(request,configuration.limits.json_bytes),identity=credentials.authenticate(payload); if (!identity) {store.recordOperationalAudit("AUTH_FAILURE",{severity:"WARN",correlation_id:correlationId,detail_code:"INVALID_CREDENTIALS"});return json(response, 401, { status:"DENIED",correlation_id:correlationId });} const token = randomUUID(); sessions.set(token, { user_id:identity.user_id, identity, expires_at:Date.now() + configuration.session_ttl_ms });store.recordOperationalAudit("AUTH_SUCCESS",{correlation_id:correlationId,actor_user_id:identity.user_id,detail_code:"SESSION_CREATED"}); response.writeHead(200, { "content-type":"application/json; charset=utf-8", "cache-control":"no-store", "set-cookie":`pilot_session=${token}; HttpOnly; SameSite=Strict; Path=/; Max-Age=${Math.floor(configuration.session_ttl_ms/1000)}${configuration.secure_cookie?"; Secure":""}` }); return response.end(JSON.stringify({ status:"AUTHENTICATED",identity })); }
      const session = sessions.get(sessionToken(request));
      if (request.method === "GET" && url.pathname === "/api/pilot/session") return session && session.expires_at >= Date.now() ? json(response, 200, { status:"AUTHENTICATED",identity:session.identity }) : json(response, 401, { status:"AUTHENTICATION_REQUIRED" });
      if (url.pathname.startsWith("/api/") && (!session || session.expires_at < Date.now())) return json(response, 401, { status:"AUTHENTICATION_REQUIRED" });
      if(["POST","PUT","PATCH","DELETE"].includes(request.method)&&request.headers.origin){const origin=new URL(request.headers.origin);if(origin.host!==request.headers.host)throw Object.assign(new Error("same-origin request required"),{code:"CSRF_REJECTED",status:403});}
      if(request.method==="POST"&&url.pathname==="/api/pilot/session/logout"){sessions.delete(sessionToken(request));response.setHeader("set-cookie",`pilot_session=; HttpOnly; SameSite=Strict; Path=/; Max-Age=0${configuration.secure_cookie?"; Secure":""}`);return json(response,200,{status:"SIGNED_OUT"});}
      const governedFeature=featureForRequest(request.method,url.pathname);if(governedFeature&&configuration.feature_flags[governedFeature]!==true){store.recordOperationalAudit("FEATURE_DISABLED_REQUEST",{severity:"WARN",correlation_id:correlationId,actor_user_id:session.user_id,detail_code:governedFeature});return json(response,503,{status:"FEATURE_DISABLED",error_code:"FEATURE_DISABLED",feature:governedFeature,availability:"DISABLED",authority:"SERVER_STARTUP_CONFIGURATION",runtime_version:store.getPilotCapabilities().runtime_version,correlation_id:correlationId});}
      if(request.method==="GET"&&url.pathname==="/api/pilot/readiness")return json(response,200,store.getPilotReadiness({provider_state:conversationProvider?"READY":"UNAVAILABLE"}));
      if(request.method==="GET"&&url.pathname==="/api/pilot/capabilities")return json(response,200,store.getPilotCapabilities());
      if(request.method==="GET"&&url.pathname==="/api/pilot/operational-audit")return json(response,200,{events:store.getOperationalAudit(session.user_id)});
      if(request.method==="GET"&&url.pathname==="/api/pilot/debt-register")return json(response,200,{debts:store.getPilotDebtRegister()});
      if(request.method==="POST"&&url.pathname==="/api/pilot/verified-backups")return json(response,201,{status:"BACKUP_VERIFIED",...(await store.createVerifiedBackup())});
      if(request.method==="POST"&&url.pathname==="/api/pilot/restore-verifications"){const payload=await readJson(request,configuration.limits.json_bytes),target=resolve(selectedExportDir,"restore-rehearsals",`restore-${randomUUID()}.sqlite`);return json(response,200,{status:"RESTORE_VERIFIED",...(await store.verifyBackupRestore(payload.backup_file,target))});}
      if(request.method==="POST"&&url.pathname==="/api/pilot/validation-records")return json(response,201,{status:"VALIDATION_RECORDED",record:store.createPilotValidationRecord(session.user_id,await readJson(request,configuration.limits.json_bytes))});
      if(request.method==="GET"&&url.pathname==="/api/pilot/validation-records")return json(response,200,{records:store.getPilotValidationRecords(session.user_id)});
      if (request.method === "GET" && url.pathname === "/api/pilot/workspace") { const record = store.getWorkspace(session.user_id); return record ? json(response, 200, record) : json(response, 404, { status:"NOT_FOUND" }); }
      if (request.method === "PUT" && url.pathname === "/api/pilot/workspace") return json(response,410,{status:"WORKSPACE_WRITE_RETIRED",authority:"SERVER_A_J_NORMALIZED_RECORDS",message:"การเขียนทับ Workspace ทั้งชุดถูกยกเลิกแล้ว กรุณาใช้ API ของรายการที่กำกับไว้"});
      if (request.method === "GET" && url.pathname === "/api/pilot/lifecycle") { const lifecycle = store.getLifecycle(session.user_id); return lifecycle ? json(response, 200, lifecycle) : json(response, 404, { status:"NOT_FOUND" }); }
      if (request.method === "POST" && url.pathname === "/api/pilot/fields") { const lifecycle=store.createFieldLifecycle(session.user_id,await readJson(request,256_000));return json(response,201,{status:"SERVER_CONFIRMED",...lifecycle}); }
      if (request.method === "GET" && url.pathname === "/api/pilot/guidance") { const caseId=url.searchParams.get("case_id"); if(caseId){const guidance=store.getCurrentGovernedGuidance(session.user_id,{field_id:url.searchParams.get("field_id"),season_id:url.searchParams.get("season_id"),case_id:caseId});return json(response,200,{status:"ok",authority:"SERVER_DERIVED_GUIDANCE",guidance});} const guidance = store.getGuidance(session.user_id,url.searchParams.get("field_id"),url.searchParams.get("season_id")); return guidance ? json(response,200,{ status:"ok", authority:"SERVER", user_id:session.user_id, field_id:url.searchParams.get("field_id"), season_id:url.searchParams.get("season_id"), guidance }) : json(response,404,{ status:"NOT_FOUND" }); }
      if (request.method === "GET" && url.pathname === "/api/pilot/guidance-history") { const scope={field_id:url.searchParams.get("field_id"),season_id:url.searchParams.get("season_id"),case_id:url.searchParams.get("case_id")}; return json(response,200,{status:"ok",authority:"SERVER",history:store.getGovernedGuidanceHistory(session.user_id,scope)}); }
      if (request.method === "GET" && url.pathname === "/api/pilot/guidance-diagnostics") { const scope={field_id:url.searchParams.get("field_id"),season_id:url.searchParams.get("season_id"),case_id:url.searchParams.get("case_id")}; return json(response,200,store.getGovernedGuidanceDiagnostics(session.user_id,scope)); }
      if (request.method === "POST" && url.pathname === "/api/pilot/guidance-actions") { const guidance=store.transitionGovernedGuidance(session.user_id,await readJson(request,64_000)); return json(response,200,{status:"UPDATED",authority:"SERVER",guidance}); }
      if (request.method === "POST" && url.pathname === "/api/pilot/visual-evidence") { const payload=await readJson(request,9_000_000),keys=["field_id","crop_season_id","case_id","observation_id","guidance_id","sampling_event_id","capture_session_id","site_reference","captured_at","source","capture_intent","plant_part_scope","spatial_scope","view_type","original_filename","media_type","size_bytes","width","height","orientation","comparison_pair_id","comparison_role","comparison_role_source","content_base64"]; if(!payload||Object.keys(payload).some((key)=>!keys.includes(key))||!Number.isInteger(payload.size_bytes)||payload.size_bytes>6_000_000)throw contractError("invalid visual evidence request");const bytes=Buffer.from(payload.content_base64,"base64");if(bytes.length!==payload.size_bytes)throw contractError("invalid visual evidence size");const contentHash=createHash("sha256").update(bytes).digest("hex"),existing=store.findDuplicateImageEvidence(session.user_id,{field_id:payload.field_id,season_id:payload.crop_season_id,content_hash:contentHash}),extension={"image/jpeg":"jpg","image/png":"png","image/webp":"webp"}[payload.media_type];if(!extension)throw contractError("invalid visual evidence media type");const storageKey=existing?.storage_key??`visual-${randomUUID()}.${extension}`;if(!existing)await writeFile(resolve(uploadDir,storageKey),bytes,{flag:"wx"});const {content_base64,...metadata}=payload,image=store.createImageEvidence(session.user_id,{...metadata,content_hash:contentHash,storage_key:storageKey});return json(response,image.exact_duplicate?200:201,{status:image.exact_duplicate?"EXACT_DUPLICATE":"CREATED",authority:"SERVER_VISUAL_EVIDENCE",image}); }
      if (request.method === "GET" && url.pathname === "/api/pilot/visual-evidence") { const image=store.getImageEvidence(session.user_id,url.searchParams.get("image_evidence_id"));return json(response,200,{status:"ok",authority:"SERVER_VISUAL_EVIDENCE",image}); }
      if (request.method === "GET" && url.pathname === "/api/pilot/visual-evidence-bundle") { const visualBundle=store.getVisualEvidenceBundle(session.user_id,{field_id:url.searchParams.get("field_id"),crop_season_id:url.searchParams.get("crop_season_id"),case_id:url.searchParams.get("case_id")});return json(response,200,visualBundle); }
      if (request.method === "POST" && url.pathname === "/api/pilot/visual-evidence-assessments") { const payload=await readJson(request,128_000);if(!payload||Object.keys(payload).some((key)=>!["image_evidence_id","assessment"].includes(key)))throw contractError("invalid visual assessment request");return json(response,201,{status:"ASSESSED",image:store.addVisualAssessment(session.user_id,payload.image_evidence_id,payload.assessment)}); }
      if (request.method === "POST" && url.pathname === "/api/pilot/visual-evidence-reviews") { return json(response,201,{status:"REVIEW_RECORDED",result:store.reviewVisualObservation(session.user_id,await readJson(request,128_000))}); }
      if (request.method === "GET" && url.pathname === "/api/pilot/visual-evidence-request") { const visualRequest=store.getNextVisualRequest(session.user_id,{field_id:url.searchParams.get("field_id"),crop_season_id:url.searchParams.get("crop_season_id"),case_id:url.searchParams.get("case_id")});return json(response,200,{status:"ok",authority:"SERVER_VISUAL_EVIDENCE",visual_request:visualRequest}); }
      if (request.method === "POST" && url.pathname === "/api/pilot/visual-perception") { const result=await store.requestVisualPerception(session.user_id,await readJson(request,256_000)),status=result.status==="COMPLETED"?200:result.status==="REJECTED"?422:503;return json(response,status,result); }
      if (request.method === "GET" && url.pathname === "/api/pilot/visual-perception") { return json(response,200,{status:"ok",authority:"SERVER_VISUAL_PERCEPTION",...store.getVisualPerceptionResult(session.user_id,url.searchParams.get("analysis_request_id"))}); }
      if (request.method === "GET" && url.pathname === "/api/pilot/visual-perception-history") { return json(response,200,store.getVisualPerceptionHistory(session.user_id,url.searchParams.get("image_evidence_id"))); }
      if (request.method === "GET" && url.pathname === "/api/pilot/visual-perception-health") { return json(response,200,store.getVisualPerceptionHealth(session.user_id)); }
      if (request.method === "GET" && url.pathname === "/api/pilot/management-options") { const scope={field_id:url.searchParams.get("field_id"),season_id:url.searchParams.get("season_id"),case_id:url.searchParams.get("case_id")};return json(response,200,store.getCurrentManagementReview(session.user_id,scope)); }
      if (request.method === "GET" && url.pathname === "/api/pilot/management-option-history") { const scope={field_id:url.searchParams.get("field_id"),season_id:url.searchParams.get("season_id"),case_id:url.searchParams.get("case_id")};return json(response,200,{authority:"SERVER_GOVERNED_MANAGEMENT_REVIEW",history:store.getManagementReviewHistory(session.user_id,scope)}); }
      if (request.method === "GET" && url.pathname === "/api/pilot/management-review-context") { const scope={field_id:url.searchParams.get("field_id"),season_id:url.searchParams.get("season_id"),case_id:url.searchParams.get("case_id")};return json(response,200,store.getManagementReviewContext(session.user_id,scope)); }
      if (request.method === "POST" && url.pathname === "/api/pilot/human-decisions") { const decision=store.createHumanDecision(session.user_id,await readJson(request,128_000));return json(response,decision.idempotent_replay?200:201,{status:decision.idempotent_replay?"IDEMPOTENT_REPLAY":"DECISION_RECORDED",authority:"EXPLICIT_HUMAN_DECISION",decision}); }
      if (request.method === "GET" && url.pathname === "/api/pilot/human-decision-history") { const scope={field_id:url.searchParams.get("field_id"),season_id:url.searchParams.get("season_id"),case_id:url.searchParams.get("case_id")};return json(response,200,{authority:"SERVER_GOVERNED_DECISION_HISTORY",current:store.getCurrentHumanDecision(session.user_id,scope),history:store.getHumanDecisionHistory(session.user_id,scope)}); }
      if (request.method === "POST" && url.pathname === "/api/pilot/management-actions") { const action=store.createManagementAction(session.user_id,await readJson(request,128_000));return json(response,action.idempotent_replay?200:201,{status:action.idempotent_replay?"IDEMPOTENT_REPLAY":"ACTION_RECORDED",authority:"EXPLICIT_HUMAN_ACTION_RECORD",action}); }
      if (request.method === "GET" && url.pathname === "/api/pilot/management-action-history") { const scope={field_id:url.searchParams.get("field_id"),season_id:url.searchParams.get("season_id"),case_id:url.searchParams.get("case_id")};return json(response,200,{authority:"SERVER_GOVERNED_MANAGEMENT_ACTION_HISTORY",history:store.getManagementActionHistory(session.user_id,scope)}); }
      if (request.method === "POST" && url.pathname === "/api/pilot/outcome-observations") { const result=store.createOutcomeObservation(session.user_id,await readJson(request,256_000));return json(response,result.observation.idempotent_replay?200:201,{status:result.observation.idempotent_replay?"IDEMPOTENT_REPLAY":"OUTCOME_RECORDED",authority:"EXPLICIT_OUTCOME_SUBMISSION",...result}); }
      if (request.method === "POST" && url.pathname === "/api/pilot/outcome-comparisons") { const result=store.createOutcomeComparison(session.user_id,await readJson(request,128_000));return json(response,result.comparison.idempotent_replay?200:201,{status:result.comparison.idempotent_replay?"IDEMPOTENT_REPLAY":"COMPARISON_RECORDED",authority:"EXPLICIT_HUMAN_COMPARISON",...result}); }
      if (request.method === "GET" && url.pathname === "/api/pilot/outcome-review") { return json(response,200,store.getGovernedOutcomeReview(session.user_id,url.searchParams.get("management_action_id"))); }
      if (request.method === "GET" && url.pathname === "/api/pilot/outcome-review-history") { return json(response,200,{authority:"SERVER_GOVERNED_OUTCOME_REVIEW_HISTORY",history:store.getGovernedOutcomeReviewHistory(session.user_id,url.searchParams.get("management_action_id"))}); }
      if (request.method === "GET" && url.pathname === "/api/pilot/decision-action-outcome-context") { const scope={field_id:url.searchParams.get("field_id"),season_id:url.searchParams.get("season_id"),case_id:url.searchParams.get("case_id")};return json(response,200,store.getDecisionActionOutcomeContext(session.user_id,scope)); }
      if (request.method === "POST" && url.pathname === "/api/pilot/follow-up-plans") { const result=store.createGovernedFollowUpPlan(session.user_id,await readJson(request,256_000));return json(response,result.plan.idempotent_replay?200:201,{status:result.plan.idempotent_replay?"IDEMPOTENT_REPLAY":"FOLLOW_UP_PLAN_RECORDED",authority:"SERVER_GOVERNED_FOLLOW_UP",...result}); }
      if (request.method === "GET" && url.pathname === "/api/pilot/follow-up-plans") { const scope={field_id:url.searchParams.get("field_id"),season_id:url.searchParams.get("season_id"),case_id:url.searchParams.get("case_id")};return json(response,200,{authority:"SERVER_GOVERNED_FOLLOW_UP",plans:store.getGovernedFollowUpPlans(session.user_id,scope)}); }
      if (request.method === "GET" && url.pathname === "/api/pilot/follow-up-history") { const scope={field_id:url.searchParams.get("field_id"),season_id:url.searchParams.get("season_id"),case_id:url.searchParams.get("case_id")};return json(response,200,{authority:"SERVER_GOVERNED_FOLLOW_UP_HISTORY",history:store.getGovernedFollowUpHistory(session.user_id,scope)}); }
      if (request.method === "POST" && url.pathname === "/api/pilot/reminders") { const reminder=store.createGovernedReminder(session.user_id,await readJson(request,128_000));return json(response,reminder.idempotent_replay?200:201,{status:reminder.idempotent_replay?"IDEMPOTENT_REPLAY":"REMINDER_SCHEDULED",authority:"SERVER_GOVERNED_REMINDER",reminder}); }
      if (request.method === "GET" && url.pathname === "/api/pilot/reminders") { const scope={field_id:url.searchParams.get("field_id"),season_id:url.searchParams.get("season_id"),case_id:url.searchParams.get("case_id")};return json(response,200,{authority:"SERVER_GOVERNED_REMINDER",reminders:store.getGovernedReminders(session.user_id,scope)}); }
      if (request.method === "POST" && url.pathname === "/api/pilot/reminder-actions") { const reminder=store.actOnGovernedReminder(session.user_id,await readJson(request,64_000));return json(response,reminder.idempotent_replay?200:201,{status:reminder.idempotent_replay?"IDEMPOTENT_REPLAY":"REMINDER_TRANSITION_RECORDED",authority:"SERVER_GOVERNED_REMINDER",reminder}); }
      if (request.method === "GET" && url.pathname === "/api/pilot/reminder-history") { return json(response,200,{authority:"SERVER_GOVERNED_REMINDER_HISTORY",history:store.getGovernedReminderHistory(session.user_id,url.searchParams.get("follow_up_plan_id"))}); }
      if (request.method === "GET" && url.pathname === "/api/pilot/reminder-due") { const scope={field_id:url.searchParams.get("field_id"),season_id:url.searchParams.get("season_id"),case_id:url.searchParams.get("case_id")};return json(response,200,{authority:"SERVER_GOVERNED_REMINDER",due:store.getDueGovernedReminders(session.user_id,scope),notification_eligibility:store.getNotificationEligibility(session.user_id,scope)}); }
      if (request.method === "GET" && url.pathname === "/api/pilot/timeline") { const eventTypes=url.searchParams.getAll("event_type"),scope={field_id:url.searchParams.get("field_id"),season_id:url.searchParams.get("season_id"),case_id:url.searchParams.get("case_id"),from:url.searchParams.get("from"),to:url.searchParams.get("to"),...(eventTypes.length?{event_types:eventTypes}:{})};return json(response,200,store.getAuthoritativeTimeline(session.user_id,scope)); }
      if (request.method === "POST" && url.pathname === "/api/pilot/follow-up-reconcile") { return json(response,200,store.reconcileGovernedFollowUps(session.user_id,await readJson(request,64_000))); }
      if (request.method === "GET" && url.pathname === "/api/pilot/follow-up-reminder-context") { const scope={field_id:url.searchParams.get("field_id"),season_id:url.searchParams.get("season_id"),case_id:url.searchParams.get("case_id")};return json(response,200,store.getFollowUpReminderContext(session.user_id,scope)); }
      if (request.method === "POST" && url.pathname === "/api/pilot/cross-case-comparisons") { const comparison=store.createCrossCaseComparison(session.user_id,await readJson(request,512_000));return json(response,comparison.idempotent_replay?200:201,{status:comparison.idempotent_replay?"IDEMPOTENT_REPLAY":"COMPARISON_RECORDED",authority:"SERVER_GOVERNED_CROSS_CASE_COMPARISON",comparison}); }
      if (request.method === "GET" && url.pathname === "/api/pilot/cross-case-comparisons") { return json(response,200,{authority:"SERVER_GOVERNED_CROSS_CASE_COMPARISON",comparisons:store.getCrossCaseComparisons(session.user_id)}); }
      if (request.method === "POST" && url.pathname === "/api/pilot/local-pattern-candidates") { const candidate=store.createLocalPatternCandidate(session.user_id,await readJson(request,256_000));return json(response,candidate.idempotent_replay?200:201,{status:candidate.idempotent_replay?"IDEMPOTENT_REPLAY":"PATTERN_CANDIDATE_RECORDED",authority:"SERVER_GOVERNED_LOCAL_PATTERN",candidate}); }
      if (request.method === "GET" && url.pathname === "/api/pilot/local-pattern-candidates") { return json(response,200,{authority:"SERVER_GOVERNED_LOCAL_PATTERN",candidates:store.getLocalPatternCandidates(session.user_id)}); }
      if (request.method === "POST" && url.pathname === "/api/pilot/local-pattern-adjudications") { const adjudication=store.createLocalPatternAdjudication(session.user_id,await readJson(request,512_000));return json(response,adjudication.idempotent_replay?200:201,{status:adjudication.idempotent_replay?"IDEMPOTENT_REPLAY":"ADJUDICATION_RECORDED",authority:"EXPLICIT_HUMAN_ADJUDICATION",adjudication}); }
      if (request.method === "GET" && url.pathname === "/api/pilot/local-pattern-adjudications") { return json(response,200,{authority:"SERVER_GOVERNED_LOCAL_PATTERN",adjudications:store.getLocalPatternAdjudications(session.user_id,url.searchParams.get("local_pattern_candidate_id"))}); }
      if (request.method === "GET" && url.pathname === "/api/pilot/local-pattern-context") { return json(response,200,store.getLocalPatternContext(session.user_id,url.searchParams.get("local_pattern_candidate_id"))); }
      if (request.method === "GET" && url.pathname === "/api/pilot/local-pattern-gaps") { return json(response,200,store.getLocalPatternGaps(session.user_id,url.searchParams.get("local_pattern_candidate_id"))); }
      if (request.method === "GET" && url.pathname === "/api/pilot/spatial-pattern-projection") { return json(response,200,store.getSpatialPatternProjection(session.user_id,url.searchParams.get("local_pattern_candidate_id"))); }
      if (request.method === "POST" && url.pathname === "/api/pilot/learning-nominations") { const nomination=store.createLearningNomination(session.user_id,await readJson(request,256_000));return json(response,nomination.idempotent_replay?200:201,{status:nomination.idempotent_replay?"IDEMPOTENT_REPLAY":"LEARNING_NOMINATION_RECORDED",authority:"SERVER_GOVERNED_LEARNING",nomination}); }
      if (request.method === "GET" && url.pathname === "/api/pilot/learning-nominations") { return json(response,200,{authority:"SERVER_GOVERNED_LEARNING",nominations:store.getLearningNominations(session.user_id)}); }
      if (request.method === "POST" && url.pathname === "/api/pilot/learning-intent") { const payload=await readJson(request,32_000);if(!payload||Object.keys(payload).some((key)=>key!=="text"))throw contractError("invalid learning intent request");return json(response,200,store.interpretLearningIntent(payload.text)); }
      if (request.method === "GET" && url.pathname === "/api/pilot/knowledge-gaps") { return json(response,200,{authority:"SERVER_KNOWLEDGE_GAP_REGISTER",gaps:store.getKnowledgeGaps(session.user_id)}); }
      if (request.method === "GET" && url.pathname === "/api/pilot/knowledge-work-queue") { return json(response,200,{authority:"SERVER_KNOWLEDGE_WORK_QUEUE",items:store.getKnowledgeWorkQueue(session.user_id)}); }
      if (request.method === "POST" && url.pathname === "/api/pilot/reviewed-case-bundles") { const bundle=store.createReviewedCaseBundle(session.user_id,await readJson(request,1_000_000));return json(response,bundle.idempotent_replay?200:201,{status:bundle.idempotent_replay?"IDEMPOTENT_REPLAY":"REVIEWED_CASE_BUNDLE_RECORDED",authority:"SERVER_GOVERNED_LEARNING",bundle}); }
      if (request.method === "GET" && url.pathname === "/api/pilot/reviewed-case-bundles") { return json(response,200,{authority:"SERVER_GOVERNED_LEARNING",bundles:store.getReviewedCaseBundles(session.user_id)}); }
      if (request.method === "POST" && url.pathname === "/api/pilot/knowledge-assertion-candidates") { const candidate=store.createKnowledgeAssertionCandidate(session.user_id,await readJson(request,512_000));return json(response,candidate.idempotent_replay?200:201,{status:candidate.idempotent_replay?"IDEMPOTENT_REPLAY":"ASSERTION_CANDIDATE_RECORDED",authority:"SERVER_GOVERNED_LEARNING",candidate}); }
      if (request.method === "GET" && url.pathname === "/api/pilot/knowledge-assertion-candidates") { return json(response,200,{authority:"SERVER_GOVERNED_LEARNING",candidates:store.getKnowledgeAssertionCandidates(session.user_id)}); }
      if (request.method === "POST" && url.pathname === "/api/pilot/knowledge-promotion-reviews") { const promotion=store.createKnowledgePromotionReview(session.user_id,await readJson(request,512_000));return json(response,promotion.idempotent_replay?200:201,{status:promotion.idempotent_replay?"IDEMPOTENT_REPLAY":"PROMOTION_REVIEW_RECORDED",authority:"EXPLICIT_HUMAN_DOMAIN_REVIEW",promotion}); }
      if (request.method === "GET" && url.pathname === "/api/pilot/knowledge-promotion-history") { return json(response,200,{authority:"SERVER_GOVERNED_LEARNING",history:store.getKnowledgePromotionHistory(session.user_id)}); }
      if (request.method === "GET" && url.pathname === "/api/pilot/knowledge-graph") { return json(response,200,store.getUnifiedKnowledgeGraph(session.user_id,url.searchParams.get("subject_entity_id"))); }
      if (request.method === "GET" && url.pathname === "/api/pilot/knowledge-graph-context") { return json(response,200,store.getUnifiedKnowledgeGraphContext(session.user_id,url.searchParams.get("subject_entity_id"))); }
      if (request.method === "POST" && url.pathname === "/api/pilot/conversation-turns") { const result=await store.orchestrateConversationTurn(session.user_id,await readJson(request,256_000));return json(response,result.idempotent_replay?200:201,{status:result.idempotent_replay?"IDEMPOTENT_REPLAY":"TURN_COMPLETED",...result}); }
      if (request.method === "GET" && url.pathname === "/api/pilot/conversations") { return json(response,200,store.listGovernedConversations(session.user_id)); }
      if (request.method === "GET" && url.pathname === "/api/pilot/conversation-history") { return json(response,200,store.getGovernedConversationHistory(session.user_id,url.searchParams.get("conversation_id"))); }
      if (request.method === "GET" && url.pathname === "/api/pilot/conversation-context") { return json(response,200,store.rebuildGovernedConversationContext(session.user_id,url.searchParams.get("conversation_id"))); }
      if (request.method === "GET" && url.pathname === "/api/pilot/learning-signals") { return json(response,200,{authority:"SERVER_OPERATIONAL_REVIEW_INPUT",signals:store.getLearningSignals(session.user_id)}); }
      if (request.method === "GET" && url.pathname === "/api/pilot/admin/learning-signals") { if(!["ADMIN","SPA","TEST_ADMIN"].includes(session.identity.role))return json(response,403,{status:"FORBIDDEN"});return json(response,200,{authority:"PROTECTED_ADMIN_REVIEW",signals:store.getAdminLearningSignals()}); }
      if (request.method === "POST" && url.pathname === "/api/pilot/investigation-records") { const payload = await readJson(request, 256_000); if (!payload || Object.keys(payload).some((key) => !["record_type","record","request_id"].includes(key)) || !payload.record_type || !payload.record) throw contractError("invalid investigation record request"); const result = store.createInvestigationRecord(session.user_id,payload.record_type,payload.record,payload.request_id??null),wrapped=payload.request_id?result:{record:result,replayed:false}; return json(response,wrapped.replayed?200:201,{ status:wrapped.replayed?"IDEMPOTENT_REPLAY":"CREATED", authority:"SERVER", record_type:payload.record_type, ...wrapped }); }
      if (request.method === "PATCH" && url.pathname === "/api/pilot/investigation-records") { const payload = await readJson(request,256_000); if (!payload || Object.keys(payload).some((key)=>!["record_type","record_id","expected_revision","record","request_id"].includes(key)) || !payload.record_type || !payload.record_id || !Number.isInteger(payload.expected_revision) || !payload.record || !payload.request_id) throw contractError("invalid investigation update request"); const result=store.updateInvestigationRecord(session.user_id,payload.record_type,payload.record_id,payload.expected_revision,payload.record,payload.request_id); return json(response,200,{status:result.replayed?"IDEMPOTENT_REPLAY":"UPDATED",authority:"SERVER",record_type:payload.record_type,...result}); }
      if (request.method === "GET" && url.pathname === "/api/pilot/investigation-bundle") { const bundle = store.getInvestigationBundle(session.user_id,{ field_id:url.searchParams.get("field_id"), season_id:url.searchParams.get("season_id"), case_id:url.searchParams.get("case_id"), observation_id:url.searchParams.get("observation_id") }); return json(response,200,bundle); }
      if (request.method === "GET" && url.pathname === "/api/pilot/investigation-timeline") { const timeline = store.getInvestigationTimeline(session.user_id,{ field_id:url.searchParams.get("field_id"), season_id:url.searchParams.get("season_id"), case_id:url.searchParams.get("case_id") }); return json(response,200,timeline); }
      if (request.method === "GET" && url.pathname === "/api/pilot/investigation-assessment") { const assessment=store.assessInvestigation(session.user_id,{field_id:url.searchParams.get("field_id"),season_id:url.searchParams.get("season_id"),case_id:url.searchParams.get("case_id")}); return json(response,200,assessment); }
      if (request.method === "GET" && url.pathname === "/api/pilot/investigation-assessment-history") { const history=store.getInvestigationAssessmentHistory(session.user_id,{field_id:url.searchParams.get("field_id"),season_id:url.searchParams.get("season_id"),case_id:url.searchParams.get("case_id")}); return json(response,200,{authority:"SERVER",history}); }
      if (request.method === "POST" && url.pathname === "/api/pilot/investigation-assessment-reviews") { const review=store.reviewInvestigationAssessment(session.user_id,await readJson(request,128_000)); return json(response,201,{status:"REVIEW_RECORDED",authority:"HUMAN_REVIEW",...review}); }
      if (request.method === "GET" && url.pathname === "/api/pilot/summary") return json(response, 200, { status:"ok", ...store.summaryUser(session.user_id), provider_configured:Boolean(process.env.OPENAI_API_KEY && !process.env.OPENAI_API_KEY.startsWith("YOUR_")) });
      if (request.method === "GET" && url.pathname === "/api/pilot/data-catalog") return json(response, 200, JSON.parse(await readFile(resolve(ROOT, "data-catalog.json"), "utf8")));
      if (request.method === "GET" && url.pathname === "/api/knowledge/summary") return json(response, 200, { status:"ok", ...knowledge.summary() });
      if (request.method === "GET" && url.pathname === "/api/knowledge/search") return json(response, 200, { status:"ok", query:url.searchParams.get("q") ?? "", results:knowledge.search({ query:url.searchParams.get("q"), domain:url.searchParams.get("domain") || null }) });
      if (request.method === "GET" && url.pathname === "/api/knowledge/company-program") return json(response, 200, { status:"ok", ...knowledge.program(url.searchParams.get("stage_id") || null) });
      if (request.method === "POST" && url.pathname === "/api/pilot/feedback") { const payload = await readJson(request); if (!payload || Object.keys(payload).some((key) => !["route","subject_id","rating","category","note","storage_key"].includes(key))) throw new Error("invalid feedback"); return json(response, 201, { status:"SAVED", ...store.addFeedback(session.user_id, payload) }); }
      if (request.method === "POST" && url.pathname === "/api/pilot/feedback-evidence") { const payload = await readJson(request, 9_000_000), allowed = { "image/jpeg":"jpg", "image/png":"png", "image/webp":"webp" }; if (!payload || Object.keys(payload).some((key) => !["original_filename","media_type","size_bytes","content_base64"].includes(key)) || !allowed[payload.media_type] || !Number.isInteger(payload.size_bytes) || payload.size_bytes > 6_000_000) throw new Error("invalid feedback evidence"); const bytes = Buffer.from(payload.content_base64, "base64"); if (bytes.length !== payload.size_bytes) throw new Error("invalid feedback evidence size"); const storageKey = `feedback-${randomUUID()}.${allowed[payload.media_type]}`; await writeFile(resolve(uploadDir, storageKey), bytes, { flag:"wx" }); return json(response, 201, { status:"STORED", storage_key:storageKey }); }
      if (request.method === "POST" && url.pathname === "/api/pilot/export") return json(response, 200, { status:"EXPORTED", ...(await store.exportUser(session.user_id)) });
      if (request.method === "POST" && url.pathname === "/api/pilot/backup") return json(response, 200, { status:"BACKUP_VERIFIED", ...(await store.createVerifiedBackup()) });
      if (request.method === "POST" && url.pathname === "/api/pilot/evidence") { const payload = await readJson(request, 9_000_000), allowed = { "image/jpeg":"jpg", "image/png":"png", "image/webp":"webp" }; if (!payload || Object.keys(payload).some((key) => !["field_id","season_id","original_filename","media_type","size_bytes","content_base64"].includes(key)) || !allowed[payload.media_type] || !Number.isInteger(payload.size_bytes) || payload.size_bytes > 6_000_000) throw new Error("invalid evidence"); const workspace = store.getWorkspace(session.user_id)?.state; if (!workspace?.fields?.some((item) => item.field_id === payload.field_id && item.owner_user_id === session.user_id) || !workspace?.seasons?.some((item) => item.season_id === payload.season_id && item.field_id === payload.field_id)) throw new Error("evidence context mismatch"); const bytes = Buffer.from(payload.content_base64, "base64"); if (bytes.length !== payload.size_bytes) throw new Error("invalid evidence size"); const storageKey = `${randomUUID()}.${allowed[payload.media_type]}`; await writeFile(resolve(uploadDir, storageKey), bytes, { flag:"wx" }); return json(response, 201, { status:"STORED", storage_key:storageKey, analysis_state:"NOT_ANALYZED" }); }
      if (request.method === "POST" && url.pathname === "/api/assistant/chat") return json(response,410,{status:"MIGRATION_REQUIRED",message:"การสนทนาที่ผูกกับแปลงต้องใช้ Governed Conversation Orchestrator",governed_endpoint:"/api/pilot/conversation-turns",legacy_free_form_authoritative:false});
      if (request.method === "GET" || request.method === "HEAD") return serveStatic(request, response);
      return json(response, 405, { status:"METHOD_NOT_ALLOWED" });
    } catch (error) { if(url.pathname.startsWith("/api/pilot/")){ const code=error?.code??"SERVER_ERROR",status=error?.status??(code==="VALIDATION_ERROR"?400:code==="VERSION_CONFLICT"?409:500),serviceUnavailable="บริการที่กำกับไว้ไม่พร้อมใช้งาน",message=code==="AUTHORIZATION_ERROR"?"ไม่มีสิทธิ์เข้าถึงข้อมูลการตรวจนี้":code==="SERVER_ERROR"?serviceUnavailable:error.message;try{store.recordOperationalAudit("REQUEST_FAILURE",{severity:status>=500?"ERROR":"WARN",correlation_id:correlationId,actor_user_id:sessions.get(sessionToken(request))?.user_id??null,detail_code:code});}catch{/* audit failure must not expose internals */}return json(response,status,{status:"ERROR",error_code:code,message,correlation_id:correlationId}); } return json(response, 400, { status:"INVALID_REQUEST", message:"คำขอไม่ถูกต้อง",correlation_id:correlationId }); }
  });
  server.once("close", () => store.close());
  server.pilotRuntime={mode:configuration.mode,profile:configuration.profile,bind_host:configuration.host,public_base_url:configuration.public_base_url,secure_cookie:configuration.secure_cookie};
  return new Promise((done, reject) => { server.once("error", reject); server.listen(selectedPort, selectedHost, () => done(server)); });
}
if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) startServer().then((server) => console.log(`SP Assistant ready mode=${server.pilotRuntime.mode} bind=${server.pilotRuntime.bind_host}:${server.address().port} public_base_url=${server.pilotRuntime.public_base_url??"NOT_CONFIGURED"} secure_cookie=${server.pilotRuntime.secure_cookie}`)).catch((error) => { console.error(error.message); process.exitCode = 1; });
