import test from "node:test";
import assert from "node:assert/strict";
import { createHash } from "node:crypto";
import { mkdtemp, readFile, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { PilotStore } from "../pilot-store.mjs";
import { startServer } from "../server.mjs";
import { ServerWorkspaceAdapter } from "../assets/server-workspace-adapter.js";
import { createEmptyCandidateProvider } from "../candidate-provider.mjs";

const users=[
  {login_id:"owner",user_id:"owner",password:"owner-secret",role:"FIELD_USER",tenant_id:"tenant-a",enabled:true},
  {login_id:"spa",user_id:"spa",password:"spa-secret",role:"SPA",tenant_id:"tenant-a",enabled:true},
  {login_id:"coordinator",user_id:"coordinator",password:"coordinator-secret",role:"SPA",tenant_id:"tenant-a",capabilities:["REVIEW_COORDINATE"],enabled:true},
  {login_id:"foreign",user_id:"foreign",password:"foreign-secret",role:"SPA",tenant_id:"tenant-b",enabled:true},
];
const identities=users.map(({user_id,role,tenant_id,enabled,capabilities})=>({user_id,role,tenant_id,enabled,capabilities}));
const field={field_id:"field-r1",season_id:"season-r1",owner_user_id:"owner",name:"Assigned rice field",crop:"rice",planting_date:"2026-08-01",current_crop_stage:{code:"TILLERING",label:"แตกกอ"},current_cmp_stage:{stage_id:"CMP-03",label:"ระยะแตกกอ"},created_at:"2026-09-01T00:00:00.000Z",updated_at:"2026-09-01T00:00:00.000Z"};
function lifecycle(){return{schema_version:2,users:[{user_id:"owner",role:"FIELD_USER"}],fields:[field],seasons:[{field_id:field.field_id,season_id:field.season_id,crop:"rice",status:"ACTIVE"}],guidance:[],activities:[],cases:[],observations:[],evidence:[],conversations:[],messages:[],decision_logs:[],case_summaries:[],weather_snapshots:[]};}
async function setup({twoCases=false}={}){const root=await mkdtemp(join(tmpdir(),"cpmoakb-fw01r1-")),dbPath=join(root,"pilot.sqlite"),exportDir=join(root,"exports"),uploadDir=join(root,"uploads"),store=await new PilotStore({dbPath,exportDir,pilotProfile:"FIELD_CAPTURE_ALPHA",scopedIdentities:identities,investigationCandidateProvider:createEmptyCandidateProvider()}).open();store.putWorkspace("owner",lifecycle());const first=store.createInvestigationRecord("owner","CASE",{field_id:field.field_id,season_id:field.season_id,case_id:"case-r1-a",purpose:"Assigned inspection"}),second=twoCases?store.createInvestigationRecord("owner","CASE",{field_id:field.field_id,season_id:field.season_id,case_id:"case-r1-b",purpose:"Unrelated issue"}):null;return{root,dbPath,exportDir,uploadDir,store,first,second,close:async()=>{store.close();await rm(root,{recursive:true,force:true,maxRetries:5,retryDelay:50});}};}
async function serve(h){h.store.close();const server=await startServer({port:0,dbPath:h.dbPath,exportDir:h.exportDir,uploadDir:h.uploadDir,pilotProfile:"FIELD_CAPTURE_ALPHA",pilotUsers:users,investigationCandidateProvider:createEmptyCandidateProvider()}),base=`http://127.0.0.1:${server.address().port}`,cookies={};for(const user of users){const response=await fetch(`${base}/api/pilot/session`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({login_id:user.login_id,password:user.password})});assert.equal(response.status,200);cookies[user.user_id]=response.headers.get("set-cookie").split(";")[0];}return{server,base,cookies,close:()=>new Promise((done)=>server.close(done))};}
const get=(app,user,path)=>fetch(app.base+path,{headers:{cookie:app.cookies[user]}});
const post=(app,user,path,body)=>fetch(app.base+path,{method:"POST",headers:{cookie:app.cookies[user],"content-type":"application/json"},body:JSON.stringify(body)});

test("FW01R1 primary SPA has owned/assigned sections and server-backed permission controls",async()=>{const source=await readFile(new URL("../assets/field-app.js",import.meta.url),"utf8");for(const marker of ["แปลงของฉัน","แปลงที่ได้รับมอบหมาย","data-assigned-field-open","data-assigned-case-open","data-assigned-case-form","field.permissions.case_create","caseItem.permissions?.case_investigate","renderAssignedFieldDetail","renderAssignedCase"])assert.ok(source.includes(marker),marker);assert.ok(!source.includes('role === "SPA" ? "case_investigate"'));const calls=[],adapter=new ServerWorkspaceAdapter(async(url,options)=>{calls.push({url,options});return new Response(JSON.stringify(url.includes("/fields")?{fields:[]}:url.includes("/cases")?{cases:[]}:{}),{status:200,headers:{"content-type":"application/json"}});});await adapter.getScopedFields();await adapter.getScopedCases();assert.deepEqual(calls.map((item)=>item.url),["/api/pilot/access/fields?","/api/pilot/access/cases?"]);});

test("FW01R1 owner sees own Field; SPA without grant and foreign tenant cannot discover or open it",async()=>{const h=await setup();let app;try{app=await serve(h);const owned=await(await get(app,"owner","/api/pilot/access/fields")).json();assert.equal(owned.fields[0].access_kind,"OWNED");assert.equal(owned.fields[0].permissions.field_view,true);assert.equal((await get(app,"owner","/api/pilot/lifecycle")).status,200);for(const user of ["spa","foreign"]){assert.deepEqual((await(await get(app,user,"/api/pilot/access/fields")).json()).fields,[]);assert.equal((await get(app,user,"/api/pilot/access/field?field_id=field-r1")).status,404);assert.equal((await get(app,user,"/api/pilot/access/case?case_id=case-r1-a")).status,404);assert.equal((await post(app,user,"/api/pilot/access/case-turns",{case_id:"case-r1-a",request_id:"tampered-r1",message:"รายงานจากแปลงอื่น"})).status,403);}}finally{await app?.close();await h.close();}});

test("FW01R1 FIELD assignment opens reviewed Field detail, resumes one Case, and revocation removes reachability",async()=>{const h=await setup(),grant=h.store.access.grant("coordinator",{subject_user_id:"spa",scope_type:"FIELD",scope_id:field.field_id,capability:"FIELD_OPERATE",reason:"Assigned field investigation"});let app;try{app=await serve(h);const listing=await(await get(app,"spa","/api/pilot/access/fields")).json();assert.equal(listing.fields.length,1);assert.equal(listing.fields[0].access_kind,"ASSIGNED");assert.equal(listing.fields[0].permissions.case_investigate,true);assert.equal(listing.fields[0].permissions.field_edit,false);const detail=await(await get(app,"spa","/api/pilot/access/field?field_id=field-r1")).json();assert.equal(detail.field.current_crop_stage.code,"TILLERING");assert.equal(detail.history.authority,"SERVER_GOVERNED_FIELD_HISTORY");assert.deepEqual(detail.cases.map((item)=>item.case_id),["case-r1-a"]);const resume=await post(app,"spa","/api/pilot/access/cases",{field_id:field.field_id,season_id:field.season_id,purpose:"Do not duplicate"});assert.equal(resume.status,200);assert.equal((await resume.json()).case.case_id,"case-r1-a");const turn=await post(app,"spa","/api/pilot/access/case-turns",{case_id:"case-r1-a",request_id:"r1-assigned-turn",message:"ข้าวเหลืองเป็นหย่อม"});assert.equal(turn.status,201);const caseDetail=await(await get(app,"spa","/api/pilot/access/case?case_id=case-r1-a")).json();assert.equal(caseDetail.conversation.turns.at(-1).raw_message,"ข้าวเหลืองเป็นหย่อม");assert.equal(caseDetail.case.permissions.case_investigate,true);assert.equal(caseDetail.bundle.cases.length,1);assert.equal(caseDetail.bundle.cases[0].case_id,"case-r1-a");assert.equal((await get(app,"owner","/api/pilot/investigation-bundle?field_id=field-r1&season_id=season-r1")).status,200);const count=await(await get(app,"owner","/api/pilot/access/cases")).json();assert.equal(count.cases.filter((item)=>item.case_id==="case-r1-a").length,1);const revoked=await post(app,"coordinator","/api/pilot/access/revocations",{grant_id:grant.grant_id,reason:"Assignment ended"});assert.equal(revoked.status,200);assert.deepEqual((await(await get(app,"spa","/api/pilot/access/fields")).json()).fields,[]);assert.equal((await get(app,"spa","/api/pilot/access/field?field_id=field-r1")).status,404);assert.equal((await get(app,"spa","/api/pilot/access/case?case_id=case-r1-a")).status,404);assert.equal((await post(app,"spa","/api/pilot/access/case-turns",{case_id:"case-r1-a",request_id:"after-revoke",message:"ไม่ควรเขียนได้"})).status,403);}finally{await app?.close();await h.close();}});

test("FW01R1 CASE-only scope reaches only its Case and cannot browse Field history or unrelated Case",async()=>{const h=await setup({twoCases:true});h.store.access.grant("coordinator",{subject_user_id:"spa",scope_type:"CASE",scope_id:h.first.case_id,capability:"CASE_OPERATE",reason:"Only this Case"});let app;try{app=await serve(h);assert.deepEqual((await(await get(app,"spa","/api/pilot/access/fields")).json()).fields,[]);const cases=(await(await get(app,"spa","/api/pilot/access/cases")).json()).cases;assert.deepEqual(cases.map((item)=>item.case_id),[h.first.case_id]);assert.equal(cases[0].permissions.case_investigate,true);const detail=await(await get(app,"spa",`/api/pilot/access/case?case_id=${h.first.case_id}`)).json();assert.equal(detail.bundle.cases.length,1);assert.equal(detail.bundle.field_context.field_name,field.name);assert.equal(detail.bundle.stage_assessment?.crop_stage?.code,"TILLERING");assert.equal((await get(app,"spa",`/api/pilot/access/case?case_id=${h.second.case_id}`)).status,404);assert.equal((await get(app,"spa",`/api/pilot/access/field?field_id=${field.field_id}`)).status,404);assert.equal((await get(app,"spa",`/api/pilot/field-history?field_id=${field.field_id}&season_id=${field.season_id}`)).status,403);assert.equal((await get(app,"spa",`/api/pilot/attachments?case_id=${h.second.case_id}`)).status,200);assert.deepEqual((await(await get(app,"spa",`/api/pilot/attachments?case_id=${h.second.case_id}`)).json()).attachments,[]);assert.equal((await post(app,"spa","/api/pilot/access/case-turns",{case_id:h.second.case_id,request_id:"cross-case",message:"ไม่เกี่ยวข้อง"})).status,403);}finally{await app?.close();await h.close();}});

test("FW01R1 CASE-only permission cannot open unrelated same-Field attachment",async()=>{const h=await setup({twoCases:true}),conversation=h.store.ensureGovernedConversation("owner",{field_id:field.field_id,season_id:field.season_id,case_id:h.second.case_id,entry_point:"CASE"}),bytes=Buffer.from("%PDF-1.7\nnotes"),attachment=h.store.createUserAttachment("owner",{field_id:field.field_id,season_id:field.season_id,case_id:h.second.case_id,conversation_id:conversation.conversation_id,original_filename:"other.pdf",mime_type:"application/pdf",size_bytes:bytes.length,storage_reference:"attachment-r1-other.pdf",sha256:createHash("sha256").update(bytes).digest("hex")});h.store.access.grant("coordinator",{subject_user_id:"spa",scope_type:"CASE",scope_id:h.first.case_id,capability:"CASE_OPERATE",reason:"Only first Case"});let app;try{app=await serve(h);assert.equal((await get(app,"spa",`/api/pilot/attachment?attachment_id=${attachment.attachment_id}`)).status,404);assert.equal((await get(app,"spa",`/api/pilot/attachment-content?attachment_id=${attachment.attachment_id}`)).status,404);assert.deepEqual((await(await get(app,"spa",`/api/pilot/attachments?case_id=${h.second.case_id}`)).json()).attachments,[]);}finally{await app?.close();await h.close();}});

test("FW01R1 CASE-operate image capture remains Case-scoped and unreviewed",async()=>{const h=await setup({twoCases:true});h.store.access.grant("coordinator",{subject_user_id:"spa",scope_type:"CASE",scope_id:h.first.case_id,capability:"CASE_OPERATE",reason:"Capture evidence only for this Case"});let app;try{app=await serve(h);const turn=await post(app,"spa","/api/pilot/access/case-turns",{case_id:h.first.case_id,request_id:"r1-visual-context",message:"ข้าวเหลืองเป็นหย่อม"});assert.equal(turn.status,201);const before=await(await get(app,"spa",`/api/pilot/access/case?case_id=${h.first.case_id}`)).json(),bytes=Buffer.from("visual-api"),payload={field_id:field.field_id,crop_season_id:field.season_id,case_id:h.first.case_id,observation_id:before.bundle.observations.at(-1).observation_id,conversation_id:before.conversation.conversation.conversation_id,captured_at:"2026-09-13T08:00:00Z",source:"UPLOAD",capture_intent:"LEAF",plant_part_scope:"LEAF_BLADE",spatial_scope:"SAMPLED_OBJECT",view_type:"DETAIL",original_filename:"leaf.png",media_type:"image/png",size_bytes:bytes.length,comparison_role:"UNKNOWN_ROLE",comparison_role_source:"UNKNOWN",content_base64:bytes.toString("base64")},uploaded=await post(app,"spa","/api/pilot/visual-evidence",payload);assert.equal(uploaded.status,201);const after=await(await get(app,"spa",`/api/pilot/access/case?case_id=${h.first.case_id}`)).json();assert.equal(after.visual.images.length,1);assert.equal(after.visual.images[0].ve_level,"VE0_RAW_IMAGE_ONLY");assert.equal(after.bundle.cases.length,1);assert.equal((await post(app,"spa","/api/pilot/visual-evidence",{...payload,case_id:h.second.case_id,original_filename:"other.png"})).status!==201,true);}finally{await app?.close();await h.close();}});

test("FW01R1 CASE_REVIEW can read its Case but cannot investigate or capture a photo",async()=>{const h=await setup();h.store.access.grant("coordinator",{subject_user_id:"spa",scope_type:"CASE",scope_id:h.first.case_id,capability:"CASE_REVIEW",reason:"Review only"});let app;try{app=await serve(h);const detail=await(await get(app,"spa",`/api/pilot/access/case?case_id=${h.first.case_id}`)).json();assert.equal(detail.case.permissions.case_view,true);assert.equal(detail.case.permissions.case_investigate,false);assert.equal(detail.case.permissions.review_perform,true);assert.equal((await post(app,"spa","/api/pilot/access/case-turns",{case_id:h.first.case_id,request_id:"review-cannot-operate",message:"ไม่ควรเขียนได้"})).status,403);const bytes=Buffer.from("visual-api");assert.equal((await post(app,"spa","/api/pilot/visual-evidence",{field_id:field.field_id,crop_season_id:field.season_id,case_id:h.first.case_id,captured_at:"2026-09-13T08:00:00Z",source:"UPLOAD",capture_intent:"LEAF",plant_part_scope:"LEAF_BLADE",spatial_scope:"SAMPLED_OBJECT",view_type:"DETAIL",original_filename:"leaf.png",media_type:"image/png",size_bytes:bytes.length,content_base64:bytes.toString("base64")})).status,403);}finally{await app?.close();await h.close();}});

test("FW01R1 REVIEW_ITEM-only grant never yields Field or Case workspace access",async()=>{const h=await setup();try{const result=await h.store.orchestrateConversationTurn("owner",{request_id:"r1-signal",field_id:field.field_id,season_id:field.season_id,case_id:h.first.case_id,entry_point:"CASE",message:"ไม่รู้"}),signalId=result.learning_signals[0].signal_id;h.store.access.grant("coordinator",{subject_user_id:"spa",scope_type:"REVIEW_ITEM",scope_id:signalId,capability:"REVIEW_ITEM_REVIEW",reason:"Review one item"});let app;try{app=await serve(h);assert.deepEqual((await(await get(app,"spa","/api/pilot/access/fields")).json()).fields,[]);assert.deepEqual((await(await get(app,"spa","/api/pilot/access/cases")).json()).cases,[]);assert.equal((await get(app,"spa",`/api/pilot/access/field?field_id=${field.field_id}`)).status,404);assert.equal((await get(app,"spa",`/api/pilot/access/case?case_id=${h.first.case_id}`)).status,404);assert.equal((await get(app,"spa",`/api/pilot/admin/learning-review/detail?signal_id=${signalId}`)).status,200);}finally{await app?.close();}}finally{await h.close();}});
