import test from "node:test";
import assert from "node:assert/strict";
import { mkdtemp, readFile, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";

import { createEmptyCandidateProvider } from "../candidate-provider.mjs";
import { StaticInvestigationRuleProvider } from "../investigation-intelligence.mjs";
import { createTestOnlyManagementRuleProvider } from "../management-option-runtime.mjs";
import { startServer } from "../server.mjs";
import { ServerLLMAdapter } from "../assets/server-llm-adapter.js";
import { ServerWorkspaceAdapter } from "../assets/server-workspace-adapter.js";
import { GovernedSpaRuntime } from "../assets/governed-spa-runtime.js";

const now="2026-08-31T05:00:00.000Z";
const fieldInput={name:"Test",polygon:{type:"Polygon",coordinates:[[[100,13],[100.01,13],[100,13.01],[100,13]]]},centroid:{latitude:13.003,longitude:100.003},area:{rai:1.2},crop:"rice",variety:"test",planting_method:"TRANSPLANTED",planting_date:"2026-07-01",expected_planting_date:null,current_crop_stage:{code:"TILLERING",label:"แตกกอ",model_version:"field-stage-model/v1"},current_cmp_stage:{stage_id:"CMP-03",label:"ระยะแตกกอ",model_version:"field-stage-model/v1"},stage_provenance:"USER_CONFIRMED"};
const stepC=()=>new StaticInvestigationRuleProvider({rule_version:"step-c-r2a1/v1",rule_authority:"BOUNDED_RUNTIME_RULE",rule_review_state:"HUMAN_REVIEWED",sufficiency_state:"SUFFICIENT_FOR_MANAGEMENT_OPTION_REVIEW",rules:[]});
const management=()=>createTestOnlyManagementRuleProvider({need_for_action:{state:"MANAGEMENT_REVIEW_JUSTIFIED",reason:"Governed R2A.1 review fixture.",supporting_evidence_refs:[],missing_evidence_refs:[],source_rule_id:"NFA-R2A1/v1",source_refs:["TEST-R2A1-SOURCE/v1"],limitations:["Bounded deterministic fixture."]},management_relationships:[{rule_id:"CULTURAL-R2A1/v1",option_class:"CULTURAL_MANAGEMENT",case_relevant:true,reason:"Governed cultural relationship supports review.",source_refs:["TEST-R2A1-SOURCE/v1"],limitations:[]},{rule_id:"BIOLOGICAL-R2A1/v1",option_class:"BIOLOGICAL_MANAGEMENT",case_relevant:true,reason:"Governed biological relationship supports review.",source_refs:["TEST-R2A1-SOURCE/v1"],limitations:[]}],regulatory_authority:{jurisdiction:"TH",authority_class:"PRIMARY_OFFICIAL_REGULATOR",current:false,conflicting:false,defensible_join_key:false,exact_chain:{crop:"rice",target:null,use:null,registration:"IDENTITY-ONLY-R2A1"},authority_refs:["GS-DOA-HAZARDOUS-REGISTRY-2026-001/v1"],limitation:"No exact current Thai CTU."}});

async function harness(){
  const root=await mkdtemp(join(tmpdir(),"cpmoakb-r2a1-"));
  const server=await startServer({port:0,dbPath:join(root,"pilot.sqlite"),exportDir:join(root,"exports"),uploadDir:join(root,"uploads"),pilotUserId:"user-r2a1",investigationRuleProvider:stepC(),investigationCandidateProvider:createEmptyCandidateProvider(),managementRuleProvider:management(),intelligenceClock:()=>new Date(now),managementClock:()=>new Date(now),decisionActionOutcomeClock:()=>new Date(now),followupClock:()=>new Date(now),followupTimezone:"Asia/Bangkok"});
  const base=`http://127.0.0.1:${server.address().port}`;let cookie="";
  const fetcher=async(path,options={})=>{const headers=new Headers(options.headers);if(cookie)headers.set("cookie",cookie);const response=await fetch(base+path,{...options,headers});const setCookie=response.headers.get("set-cookie");if(setCookie)cookie=setCookie.split(";")[0];return response;};
  const workspace=new ServerWorkspaceAdapter(fetcher);await workspace.authenticate("1234");await workspace.createField(fieldInput);let value=0;const idProvider=()=>`r2a1-${++value}`,runtime=new GovernedSpaRuntime({workspace,llm:new ServerLLMAdapter({fetcher}),idProvider});await runtime.synchronize();await runtime.startCase(runtime.lifecycleState.fields[0]);await runtime.captureStatement("ข้าวเหลืองเป็นหย่อมตรงจุดต่ำ");
  return{root,server,workspace,runtime,idProvider,close:async()=>{await new Promise((done)=>server.close(done));await rm(root,{recursive:true,force:true,maxRetries:5,retryDelay:100});}};
}

test("R2A.1 canonical F1 eligibility matrix has no browser synonym authority",()=>{const states=["SUPPORTED_FOR_REVIEW","MORE_EVIDENCE_REQUIRED","NOT_SUPPORTED_BY_CURRENT_EVIDENCE","BLOCKED_BY_AUTHORITY","HUMAN_REVIEW_REQUIRED","NOT_APPLICABLE"],runtime=new GovernedSpaRuntime({workspace:{},llm:{}});runtime.caseState={management:{all_option_evaluations:states.map((eligibility_state,index)=>({management_option_id:`option-${index}`,option_class:index===4?"EXPERT_REVIEW":"CULTURAL_MANAGEMENT",eligibility_state}))}};const options=runtime.managementOptions();assert.deepEqual(options.map((item)=>item.selectable),[true,false,false,false,true,false]);assert.equal(options[0].decision_state_on_selection,"CONFIRMED");assert.equal(options[4].decision_state_on_selection,"REVIEW_REQUIRED");assert.equal(options[4].action_allowed,false);});

test("R2A.1 A canonical F1 states drive UI interaction and an actual immutable server Decision",async()=>{const h=await harness();try{const options=h.runtime.managementOptions(),cultural=options.find((item)=>item.option_class==="CULTURAL_MANAGEMENT"),biological=options.find((item)=>item.option_class==="BIOLOGICAL_MANAGEMENT"),chemical=options.find((item)=>item.option_class==="CHEMICAL_REVIEW");assert.equal(cultural.eligibility_state,"SUPPORTED_FOR_REVIEW");assert.equal(cultural.selectable,true);assert.equal(cultural.decision_state_on_selection,"CONFIRMED");assert.equal(biological.label,"ทบทวนทางเลือกชีวภาพ");assert.doesNotMatch(biological.label,/BIOLOGICAL_MANAGEMENT/);assert.equal(chemical.eligibility_state,"BLOCKED_BY_AUTHORITY");assert.equal(chemical.selectable,false);await assert.rejects(()=>h.runtime.selectManagementOption(chemical),/ยังไม่เปิด/);const decision=await h.runtime.selectManagementOption(cultural,"ผู้ใช้เลือกการจัดการเชิงเขตกรรม");assert.equal(decision.decision_state,"CONFIRMED");assert.equal(decision.immutable_snapshot,true);const reloaded=new GovernedSpaRuntime({workspace:h.workspace,llm:new ServerLLMAdapter({fetcher:h.workspace.fetcher}),idProvider:h.idProvider});await reloaded.synchronize();await reloaded.resumeCase(h.runtime.caseState.scope);assert.equal(reloaded.currentDecision().decision_id,decision.decision_id);assert.equal(reloaded.currentDecision().selected_option_class,"CULTURAL_MANAGEMENT");}finally{await h.close();}});

test("R2A.1 B/C primary runtime preserves Planned, explicit Performed, bounded Outcome, and timeline",async()=>{const h=await harness();try{const cultural=h.runtime.managementOptions().find((item)=>item.option_class==="CULTURAL_MANAGEMENT"),decision=await h.runtime.selectManagementOption(cultural),plan=await h.runtime.planAction("ผู้ใช้วางแผนถอนวัชพืชเฉพาะจุด");assert.equal(plan.status,"PLANNED");assert.equal(plan.actual_execution_confirmed,false);assert.equal(h.runtime.caseState.decision.management_action_history.length,1);const performed=await h.runtime.confirmPerformed("2026-08-31T04:00:00.000Z");assert.equal(performed.status,"PERFORMED");assert.equal(performed.supersedes_action_id,plan.management_action_id);assert.deepEqual(h.runtime.caseState.decision.management_action_history.map((item)=>item.status),["PLANNED","PERFORMED"]);const outcome=await h.runtime.recordOutcome({observed_at:now,note:"รอบนี้บันทึกว่าจำนวนที่เห็นลดลง"});assert.equal(outcome.phase,"T1");const review=h.runtime.caseState.decision.current_outcome_reviews[0];assert.equal(review.non_conclusions.efficacy_percentage,null);assert.equal(review.non_conclusions.causal_effect,null);assert.ok(h.runtime.caseState.timeline.events.some((item)=>item.source_record_type==="OUTCOME_OBSERVATION"));assert.equal(decision.field_action_created,false);}finally{await h.close();}});

test("R2A.1 D Reminder acknowledge and complete are server transitions without Outcome or Case closure",async()=>{const h=await harness();try{const scope=h.runtime.caseState.scope,created=await h.workspace.createFollowUpPlan({request_id:"r2a1-follow-up",...scope,source_type:"HUMAN_AUTHORED_FOLLOW_UP",source_ref:"PRIMARY-SPA-R2A1",purpose:"กลับไปตรวจตามที่ผู้ใช้กำหนด",target_subject:"บริเวณเดิม",what_to_check:["สิ่งที่เห็นในบริเวณเดิม"],where_to_check:"แปลงเดิม",expected_evidence_type:"OBSERVATION",timing_mode:"EXACT_TIME",timing_basis:"เวลาที่ผู้ใช้ระบุ",due_at:"2026-08-31T04:00:00.000Z",timing_authority:"HUMAN_AUTHORED",timing_source_ref:"PRIMARY-SPA-R2A1",limitations:["การเตือนเป็นสถานะปฏิบัติการ ไม่ใช่ความเร่งด่วนทางวิทยาศาสตร์"],status:"ACTIVE",create_reminder:true,timezone:"Asia/Bangkok",reminder_reason:"กลับไปตรวจ"});await h.runtime.refreshCase();let current=h.runtime.caseState.followUp.current_reminders.find((item)=>item.follow_up_plan_id===created.plan.follow_up_plan_id);const acknowledged=await h.runtime.transitionReminder(current,"ACKNOWLEDGE");assert.equal(acknowledged.status,"ACKNOWLEDGED");assert.equal(acknowledged.completed_at,null);current=h.runtime.caseState.followUp.current_reminders.find((item)=>item.follow_up_plan_id===created.plan.follow_up_plan_id);const completed=await h.runtime.transitionReminder(current,"COMPLETE");assert.equal(completed.status,"COMPLETED");assert.equal(completed.outcome_created,false);assert.equal(h.runtime.caseState.bundle.outcomes.length,0);assert.equal(h.runtime.caseState.bundle.cases[0].status,"OPEN");}finally{await h.close();}});

test("R2A.1 E Case photo uses B1, no-Case photo fails closed, and B2 outage keeps manual review",async()=>{const h=await harness();try{const bytes=new TextEncoder().encode("r2a1-image"),file={name:"field.png",type:"image/png",size:bytes.byteLength,arrayBuffer:async()=>bytes.buffer},uploaded=await h.runtime.uploadPhoto(file);assert.match(uploaded.image.image_evidence_id,/^image-evidence-/);assert.equal(uploaded.image.ve_level,"VE0_RAW_IMAGE_ONLY");const degraded=await h.workspace.requestVisualPerception({image_evidence_id:uploaded.image.image_evidence_id,request_id:"r2a1-b2-off"});assert.equal(degraded.analysis_performed,false);await h.runtime.manualPhotoReview(uploaded.image.image_evidence_id);assert.equal(h.runtime.caseState.visual.images[0].ve_level,"VE1_QUALITY_AND_CONTEXT_ESTABLISHED");const noCase=new GovernedSpaRuntime({workspace:{uploadVisualEvidence:async()=>{throw new Error("must not upload");}},llm:{analyze_image:async()=>{throw new Error("must not analyze");}}});await assert.rejects(()=>noCase.uploadPhoto(file),/เริ่มเคส/);const app=await readFile(new URL("../assets/field-app.js",import.meta.url),"utf8");assert.doesNotMatch(app,/llmGateway\.analyze_image/);assert.doesNotMatch(app,/serverWorkspace\.uploadEvidence/);}finally{await h.close();}});
