import test from "node:test";
import assert from "node:assert/strict";
import {mkdtemp,readFile,rm} from "node:fs/promises";
import {tmpdir} from "node:os";
import {join} from "node:path";
import {PilotStore} from "../pilot-store.mjs";
import {startServer} from "../server.mjs";
import {createEmptyCandidateProvider} from "../candidate-provider.mjs";
import {ServerWorkspaceAdapter} from "../assets/server-workspace-adapter.js";
import {ServerLLMAdapter} from "../assets/server-llm-adapter.js";
import {GovernedSpaRuntime,casePresentation} from "../assets/governed-spa-runtime.js";

const fieldInput={name:"Test",polygon:{type:"Polygon",coordinates:[[[100,13],[100.01,13],[100,13.01],[100,13]]]},centroid:{latitude:13.003,longitude:100.003},area:{rai:1.2},crop:"rice",variety:"test",planting_method:"TRANSPLANTED",planting_date:"2026-07-01",expected_planting_date:null,current_crop_stage:{code:"TILLERING",label:"แตกกอ",model_version:"field-stage-model/v1"},current_cmp_stage:{stage_id:"CMP-03",label:"ระยะแตกกอ",model_version:"field-stage-model/v1"},stage_provenance:"USER_CONFIRMED"};
async function harness(){const root=await mkdtemp(join(tmpdir(),"cpmoakb-r2a-")),server=await startServer({port:0,dbPath:join(root,"pilot.sqlite"),exportDir:join(root,"exports"),uploadDir:join(root,"uploads"),pilotUserId:"user-r2a",investigationCandidateProvider:createEmptyCandidateProvider()}),base=`http://127.0.0.1:${server.address().port}`;let cookie="";const fetcher=async(path,options={})=>{const headers=new Headers(options.headers);if(cookie)headers.set("cookie",cookie);const response=await fetch(base+path,{...options,headers});const setCookie=response.headers.get("set-cookie");if(setCookie)cookie=setCookie.split(";")[0];return response;};return{root,server,base,fetcher,close:async()=>{await new Promise((done)=>server.close(done));await rm(root,{recursive:true,force:true,maxRetries:5,retryDelay:100});}};}

test("R2A-G1/G2 server creates authoritative Field and Case without client identity",async()=>{const h=await harness();try{const workspace=new ServerWorkspaceAdapter(h.fetcher),login=await workspace.authenticate("1234");assert.equal(login.identity.user_id,"user-r2a");const created=await workspace.createField(fieldInput);assert.equal(created.authority,"SERVER_LIFECYCLE");assert.match(created.field.field_id,/^field-/);assert.match(created.season.season_id,/^season-/);await workspace.createField({...fieldInput,name:"Second"});const runtime=new GovernedSpaRuntime({workspace,llm:new ServerLLMAdapter({fetcher:h.fetcher}),idProvider:()=>"id-1"});await runtime.synchronize();assert.equal(runtime.lifecycleState.fields.length,2);const field=runtime.lifecycleState.fields.find((item)=>item.name==="Test");assert.deepEqual(runtime.scopeFor(field),{field_id:field.field_id,season_id:field.season_id});const state=await runtime.startCase(field);assert.equal(state.bundle.cases[0].case_id,state.scope.case_id);}finally{await h.close();}});

test("R2A-G3/G4/G12/G13 one utterance records facts, resumes idempotently, and nominates without promotion",async()=>{const h=await harness();try{const workspace=new ServerWorkspaceAdapter(h.fetcher);await workspace.authenticate("1234");await workspace.createField(fieldInput);let id=0;const runtime=new GovernedSpaRuntime({workspace,llm:new ServerLLMAdapter({fetcher:h.fetcher,idProvider:()=>"turn-one"}),idProvider:()=>`learning-${++id}`});await runtime.synchronize();await runtime.startCase(runtime.lifecycleState.fields[0]);const first=await runtime.captureStatement("ตรงนี้ข้าวเหลืองเป็นหย่อมตรงจุดต่ำ น้ำลึกกว่าข้างๆ");assert.equal(first.status,"AVAILABLE");assert.equal(runtime.caseState.bundle.observations.length,1);assert.ok(runtime.caseState.bundle.evidence.length>=3);const counts={observations:runtime.caseState.bundle.observations.length,evidence:runtime.caseState.bundle.evidence.length};const retry=await runtime.captureStatement("ช่วยดูต่อหน่อย");assert.equal(retry.governed_response.question==null||typeof retry.governed_response.question==="string",true);assert.equal(runtime.caseState.bundle.observations.length,counts.observations);assert.equal(runtime.caseState.bundle.evidence.length,counts.evidence);assert.equal(casePresentation(runtime.caseState).question_limit_per_turn,1);const learning=await runtime.nominateCase();assert.equal(learning.canonical_knowledge_changed,false);assert.equal(learning.nomination_is_claim,false);assert.match(learning.friendly_message,/ยังไม่เปลี่ยนความรู้หลัก/);}finally{await h.close();}});

test("R2A-G5/G14 active Case photo uses B1 and manual review survives absent B2",async()=>{const h=await harness();try{const workspace=new ServerWorkspaceAdapter(h.fetcher);await workspace.authenticate("1234");await workspace.createField(fieldInput);const runtime=new GovernedSpaRuntime({workspace,llm:new ServerLLMAdapter({fetcher:h.fetcher})});await runtime.synchronize();await runtime.startCase(runtime.lifecycleState.fields[0]);await runtime.captureStatement("ข้าวเหลืองเป็นหย่อม");const bytes=new TextEncoder().encode("r2a-image"),file={name:"field.png",type:"image/png",size:bytes.byteLength,arrayBuffer:async()=>bytes.buffer};const uploaded=await runtime.uploadPhoto(file);assert.equal(uploaded.image.ve_level,"VE0_RAW_IMAGE_ONLY");assert.equal(uploaded.image.boundaries.image_is_diagnosis,false);await runtime.manualPhotoReview(uploaded.image.image_evidence_id);const visual=casePresentation(runtime.caseState).visual[0];assert.equal(visual.level,"VE1_QUALITY_AND_CONTEXT_ESTABLISHED");assert.match(visual.boundary,/ไม่ใช่การวินิจฉัย/);const degraded=await workspace.requestVisualPerception({image_evidence_id:uploaded.image.image_evidence_id,request_id:"b2-off"});assert.equal(degraded.analysis_performed,false);}finally{await h.close();}});

test("R2A-G10/G11/G15 presentation has no fake reminder count, draft authority, outbreak, or browser science",async()=>{const local={field_id:"local-old",season_id:"local-season",name:"Test"},workspace={session:async()=>({identity:{user_id:"server-user"}}),lifecycle:async()=>({fields:[{field_id:"server-field",season_id:"server-season",name:"Server"}],seasons:[]}),getDueReminders:async()=>({due:[]}),getLocalPatternCandidates:async()=>({candidates:[{local_pattern_candidate_id:"pattern-1"}]})},runtime=new GovernedSpaRuntime({workspace,llm:{}});await runtime.synchronize();const fields=runtime.presentFields([local]);assert.equal(fields.find((item)=>item.field_id==="local-old").authority_state,"LOCAL_DRAFT");assert.equal(runtime.scopeFor(local),null);await assert.rejects(()=>runtime.startCase(local),/ร่างบนอุปกรณ์/);assert.equal(runtime.due.length,0);assert.match((await runtime.localPatterns())[0].bounded_message,/ยังเรียกว่าเป็นการระบาดไม่ได้/);const app=await readFile(new URL("../assets/field-app.js",import.meta.url),"utf8");assert.doesNotMatch(app,/notification-button[^`]+<span>3<\/span>/);assert.match(app,/governedRuntime\.selectManagementOption/);});

test("R2A server restart reconstructs Field, Case, and Conversation from normalized records",async()=>{const root=await mkdtemp(join(tmpdir(),"cpmoakb-r2a-restart-")),dbPath=join(root,"pilot.sqlite"),exportDir=join(root,"exports"),uploadDir=join(root,"uploads");let server=await startServer({port:0,dbPath,exportDir,uploadDir,pilotUserId:"user-r2a",investigationCandidateProvider:createEmptyCandidateProvider()});try{let base=`http://127.0.0.1:${server.address().port}`,cookie="",fetcher=async(path,options={})=>{const headers=new Headers(options.headers);if(cookie)headers.set("cookie",cookie);const response=await fetch(base+path,{...options,headers});if(response.headers.get("set-cookie"))cookie=response.headers.get("set-cookie").split(";")[0];return response;},workspace=new ServerWorkspaceAdapter(fetcher);await workspace.authenticate("1234");await workspace.createField(fieldInput);let runtime=new GovernedSpaRuntime({workspace,llm:new ServerLLMAdapter({fetcher})});await runtime.synchronize();await runtime.startCase(runtime.lifecycleState.fields[0]);await runtime.captureStatement("ข้าวเหลืองเป็นหย่อม");const ids={field:runtime.caseState.scope.field_id,case:runtime.caseState.scope.case_id,conversation:runtime.caseState.conversation_id};await new Promise((done)=>server.close(done));server=await startServer({port:0,dbPath,exportDir,uploadDir,pilotUserId:"user-r2a",investigationCandidateProvider:createEmptyCandidateProvider()});base=`http://127.0.0.1:${server.address().port}`;cookie="";workspace=new ServerWorkspaceAdapter(fetcher);await workspace.authenticate("1234");const lifecycle=await workspace.lifecycle(),conversations=await(await fetcher("/api/pilot/conversations")).json(),bundle=await workspace.getInvestigationBundle({field_id:ids.field,season_id:lifecycle.fields[0].season_id,case_id:ids.case});assert.equal(lifecycle.fields[0].field_id,ids.field);assert.equal(bundle.cases[0].case_id,ids.case);assert.ok(conversations.conversations.some((item)=>item.conversation_id===ids.conversation));}finally{if(server.listening)await new Promise((done)=>server.close(done));await rm(root,{recursive:true,force:true,maxRetries:5,retryDelay:100});}});
