import test from "node:test";
import assert from "node:assert/strict";
import { createHash } from "node:crypto";
import { mkdtemp, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { ConversationProvider, CONVERSATION_ENUMS, CONVERSATION_ORCHESTRATOR_VERSION, OpenAIConversationProvider, createTestOnlyConversationProvider } from "../conversation-orchestrator.mjs";
import { createEmptyCandidateProvider } from "../candidate-provider.mjs";
import { PilotStore } from "../pilot-store.mjs";
import { startServer } from "../server.mjs";

const now = "2026-08-27T04:00:00.000Z";
const scope = { field_id:"field-conversation", season_id:"season-conversation" };
function ids(prefix="conversation-id") { let value=0; return ()=>`${prefix}-${++value}`; }
function lifecycle(userId="user-a", fields=[scope]) {
  return {schema_version:2,users:[{user_id:userId,role:"SPA"}],fields:fields.map((item,index)=>({field_id:item.field_id,owner_user_id:userId,name:`นา ${index+1}`,polygon:{type:"Polygon",coordinates:[[[100,13],[100.01,13],[100,13.01],[100,13]]]},crop:"rice",planting_date:"2026-07-01",current_crop_stage:{code:"TILLERING",label:"แตกกอ",model_version:"field-stage-model/v1"},current_cmp_stage:{stage_id:"CMP-03",label:"ระยะแตกกอ",model_version:"field-stage-model/v1"},season_id:item.season_id,stage_provenance:"USER_CONFIRMED",created_at:"2026-07-01T00:00:00.000Z",updated_at:"2026-08-20T00:00:00.000Z"})),seasons:fields.map((item)=>({season_id:item.season_id,field_id:item.field_id,crop:"rice",status:"ACTIVE"})),guidance:[],activities:[],cases:[],observations:[],evidence:[],conversations:[],messages:[],decision_logs:[],case_summaries:[],weather_snapshots:[]};
}
async function setup({provider=null,fields=[scope],userId="user-a"}={}) {
  const root=await mkdtemp(join(tmpdir(),"cpmoakb-conversation-")),store=await new PilotStore({dbPath:join(root,"pilot.sqlite"),exportDir:join(root,"exports"),investigationCandidateProvider:createEmptyCandidateProvider(),conversationProvider:provider,conversationClock:()=>new Date(now),conversationIdProvider:ids(),intelligenceClock:()=>new Date(now),intelligenceIdProvider:ids("assessment"),guidanceClock:()=>new Date(now),guidanceIdProvider:ids("guidance")}).open();
  store.putWorkspace(userId,lifecycle(userId,fields));
  return {root,store,close:async()=>{store.close();await rm(root,{recursive:true,force:true});}};
}
const request=(message,extra={})=>({request_id:extra.request_id??`request-${Math.random().toString(16).slice(2)}`,message,entry_point:"FIELD",...scope,...extra});

test("Step E publishes closed output vocabularies and a versioned runtime",()=>{assert.match(CONVERSATION_ORCHESTRATOR_VERSION,/governed-conversation-orchestrator/);assert.ok(CONVERSATION_ENUMS.intents.includes("USER_HYPOTHESIS"));assert.ok(CONVERSATION_ENUMS.responseTypes.includes("NO_ADDITIONAL_ACTION"));assert.ok(CONVERSATION_ENUMS.uiActions.includes("OPEN_VISUAL_REVIEW"));});

test("golden E1 extracts four explicit dimensions and records three typed evidence records",async()=>{const h=await setup();try{const result=await h.store.orchestrateConversationTurn("user-a",request("ข้าวเหลืองเป็นหย่อมตรงจุดต่ำ น้ำลึกกว่าข้างๆ",{request_id:"golden-e1"}));assert.deepEqual(result.explicit_facts.map((item)=>item.governed_code),["YELLOWING","PATCH","LOW_SPOT","DEEPER_WATER_CONTEXT"]);assert.equal(result.fact_record_references.length,3);assert.deepEqual(result.fact_record_references.map((item)=>item.record_type),["MORPHOLOGY_EVIDENCE","SPATIAL_EVIDENCE","WATER_CONTEXT"]);assert.equal(result.actions.length,1);assert.equal(result.question,null);const bundle=h.store.getInvestigationBundle("user-a",{...scope,case_id:result.context.case_id});assert.equal(bundle.observations.length,1);assert.equal(bundle.evidence.length,3);assert.equal(bundle.evidence.find((item)=>item.evidence_type==="WATER").water_state,"UNEVEN_WATER");}finally{await h.close();}});

test("golden E2 asks the backend first and reuses an existing Case and Guidance",async()=>{const h=await setup();try{h.store.createInvestigationRecord("user-a","CASE",{...scope,case_id:"case-known",purpose:"known field state"});h.store.createInvestigationRecord("user-a","OBSERVATION",{...scope,case_id:"case-known",observation_id:"obs-known",source:"FIELD_OBSERVED",note:"known observation"});h.store.createInvestigationRecord("user-a","MORPHOLOGY_EVIDENCE",{...scope,case_id:"case-known",observation_id:"obs-known",evidence_id:"evidence-known",source:"FIELD_OBSERVED",evidence_level:"MO1_DIRECT_OBSERVATION",payload:{plant_part:"WHOLE_PLANT",primary_phenotypes:["YELLOWING"]}});const before=h.store.db.prepare("SELECT COUNT(*) count FROM investigation_observations").get().count,result=await h.store.orchestrateConversationTurn("user-a",request("ช่วยดูหน่อย",{request_id:"golden-e2"}));assert.equal(result.context.case_id,"case-known");assert.ok(result.assessment_reference);assert.ok(result.guidance_reference);assert.equal(result.question,null);assert.equal(h.store.db.prepare("SELECT COUNT(*) count FROM investigation_observations").get().count,before);assert.doesNotMatch(result.text,/แปลงไหน|ฤดูไหน|ระยะอะไร/);}finally{await h.close();}});

test("every extracted fact retains exact span, governed mapping, and extraction provenance",async()=>{const h=await setup();try{const message="ตรงนี้ข้าวเหลืองเป็นหย่อม",result=await h.store.orchestrateConversationTurn("user-a",request(message,{request_id:"fact-provenance"}));for(const fact of result.explicit_facts){assert.equal(message.slice(fact.source_span.start,fact.source_span.end),fact.source_span.text);assert.equal(fact.status,"EXPLICIT");assert.equal(fact.provider_origin,"SERVER_GOVERNED_PHRASE_MAP");assert.ok(fact.vocabulary_mapping);}}finally{await h.close();}});

test("fact extraction retains provider/version and turn timestamp provenance",async()=>{const h=await setup();try{const result=await h.store.orchestrateConversationTurn("user-a",request("ข้าวเหลือง",{request_id:"fact-timestamp"})),fact=result.explicit_facts[0];assert.equal(fact.extracted_at,now);assert.equal(result.created_at,now);assert.equal(result.provider.provider_version,"none");assert.equal(result.provider.scientific_authority,false);}finally{await h.close();}});

test("explicit facts execute only through the thin governed Capture Adapter",async()=>{const h=await setup();try{const calls=[],adapter=h.store.conversationOrchestrator.captureAdapter,original=adapter.create.bind(adapter);adapter.create=(...args)=>{calls.push({request_id:args[1],record_type:args[2]});return original(...args);};const result=await h.store.orchestrateConversationTurn("user-a",request("ข้าวเหลืองเป็นหย่อม น้ำลึกกว่าข้างๆ",{request_id:"capture-adapter-spy"}));assert.deepEqual(calls.map((item)=>item.record_type),["CASE","OBSERVATION","MORPHOLOGY_EVIDENCE","SPATIAL_EVIDENCE","WATER_CONTEXT"]);assert.ok(calls.every((item)=>item.request_id.startsWith(result.turn_id)));}finally{await h.close();}});

test("the orchestrator consumes the existing Step C and Step D services after capture",async()=>{const h=await setup();try{let assessments=0,guidanceCalls=0,assessment=h.store.investigationIntelligence.assess.bind(h.store.investigationIntelligence),guidance=h.store.guidanceIntelligence.current.bind(h.store.guidanceIntelligence);h.store.investigationIntelligence.assess=(...args)=>{assessments+=1;return assessment(...args);};h.store.guidanceIntelligence.current=(...args)=>{guidanceCalls+=1;return guidance(...args);};const result=await h.store.orchestrateConversationTurn("user-a",request("ข้าวเหลือง",{request_id:"step-c-d-spy"}));assert.ok(assessments>=1);assert.equal(guidanceCalls,1);assert.ok(result.assessment_reference);assert.ok(result.guidance_reference);}finally{await h.close();}});

test("retrying a turn is idempotent and does not duplicate observations",async()=>{const h=await setup();try{const input=request("ข้าวเหลืองเป็นหย่อม",{request_id:"retry-e1"}),first=await h.store.orchestrateConversationTurn("user-a",input),second=await h.store.orchestrateConversationTurn("user-a",input);assert.equal(second.idempotent_replay,true);assert.equal(second.turn_id,first.turn_id);const bundle=h.store.getInvestigationBundle("user-a",{...scope,case_id:first.context.case_id});assert.equal(bundle.observations.length,1);assert.equal(bundle.evidence.length,2);}finally{await h.close();}});

test("concurrent same-request turns share one in-flight execution",async()=>{const provider=createTestOnlyConversationProvider(async()=>{await new Promise((done)=>setTimeout(done,5));return {intent:"FIELD_OBSERVATION",explicit_facts:[],user_hypothesis:null};}),h=await setup({provider});try{const input=request("ข้าวเหลือง",{request_id:"concurrent-retry"}),[a,b]=await Promise.all([h.store.orchestrateConversationTurn("user-a",input),h.store.orchestrateConversationTurn("user-a",input)]);assert.equal(a.turn_id,b.turn_id);assert.equal(h.store.db.prepare("SELECT COUNT(*) count FROM governed_conversation_turns").get().count,1);assert.equal(h.store.db.prepare("SELECT COUNT(*) count FROM investigation_observations").get().count,1);}finally{await h.close();}});

test("vague wording does not infer yellowing or morphology",async()=>{const h=await setup();try{const result=await h.store.orchestrateConversationTurn("user-a",request("ข้าวดูไม่ดี",{request_id:"vague"}));assert.equal(result.explicit_facts.length,0);assert.equal(result.fact_record_references.length,0);assert.doesNotMatch(JSON.stringify(result),/YELLOWING/);}finally{await h.close();}});

test("explicit negation is not converted into positive yellowing evidence",async()=>{const h=await setup();try{const result=await h.store.orchestrateConversationTurn("user-a",request("ใบไม่ได้เหลือง",{request_id:"negated-yellow"}));assert.equal(result.explicit_facts.length,0);assert.equal(result.fact_record_references.length,0);}finally{await h.close();}});

test("unsupported provider vocabulary is retained as unsupported and never captured",async()=>{const provider=createTestOnlyConversationProvider({intent:"FIELD_OBSERVATION",explicit_facts:[{dimension:"MORPHOLOGY",governed_code:"NEW_SYMPTOM",quoted_text:"อาการแปลก",status:"EXPLICIT"}],user_hypothesis:null}),h=await setup({provider});try{const result=await h.store.orchestrateConversationTurn("user-a",request("พบอาการแปลก",{request_id:"unsupported-vocab"}));assert.equal(result.explicit_facts[0].status,"UNSUPPORTED_INFERENCE");assert.equal(result.fact_record_references.length,0);assert.equal(h.store.db.prepare("SELECT COUNT(*) count FROM investigation_evidence").get().count,0);}finally{await h.close();}});

test("golden E4 stores a user hypothesis separately without morphology or diagnosis",async()=>{const h=await setup();try{const result=await h.store.orchestrateConversationTurn("user-a",request("น่าจะโรคไหม้",{request_id:"hypothesis"}));assert.equal(result.intent,"USER_HYPOTHESIS");assert.equal(result.explicit_facts.length,0);assert.ok(result.hypothesis_reference);const bundle=h.store.getInvestigationBundle("user-a",{...scope,case_id:result.context.case_id});assert.equal(bundle.candidates[0].authorship,"USER_HYPOTHESIS");assert.equal(bundle.candidates[0].support_state,"OPEN");assert.equal(bundle.evidence.length,0);assert.equal("diagnosis" in result,false);}finally{await h.close();}});

test("golden E5 asks one field clarification and never guesses across active fields",async()=>{const fields=[scope,{field_id:"field-second",season_id:"season-second"}],h=await setup({fields});try{const result=await h.store.orchestrateConversationTurn("user-a",{request_id:"ambiguous-field",message:"ช่วยดูหน่อย",entry_point:"HOME"});assert.equal(result.response_type,"CLARIFICATION");assert.equal(result.actions.length,1);assert.equal(result.actions[0].options.length,2);assert.equal((result.text.match(/\?/g)??[]).length<=1,true);assert.equal(result.context.resolved,false);}finally{await h.close();}});

test("a prior conversation makes แปลงเดิม deterministic without another field question",async()=>{const fields=[scope,{field_id:"field-second",season_id:"season-second"}],h=await setup({fields});try{const first=await h.store.orchestrateConversationTurn("user-a",request("ข้าวเหลือง",{request_id:"same-field-first"})),second=await h.store.orchestrateConversationTurn("user-a",{request_id:"same-field-second",conversation_id:first.conversation_id,message:"แปลงเดิมช่วยดูหน่อย",entry_point:"FIELD"});assert.equal(second.context.field_id,scope.field_id);assert.notEqual(second.response_type,"CLARIFICATION");assert.equal(second.question,null);}finally{await h.close();}});

test("multiple open cases produce one case clarification",async()=>{const h=await setup();try{for(const case_id of ["case-one","case-two"])h.store.createInvestigationRecord("user-a","CASE",{...scope,case_id,purpose:"open"});const result=await h.store.orchestrateConversationTurn("user-a",request("ข้าวเหลือง",{request_id:"ambiguous-case"}));assert.equal(result.response_type,"CLARIFICATION");assert.equal(result.context.ambiguity.type,"CASE");assert.equal(result.actions[0].options.length,2);}finally{await h.close();}});

test("an explicit case is reused instead of opening a duplicate",async()=>{const h=await setup();try{h.store.createInvestigationRecord("user-a","CASE",{...scope,case_id:"case-existing",purpose:"existing"});const result=await h.store.orchestrateConversationTurn("user-a",request("ข้าวเหลือง",{request_id:"existing-case",case_id:"case-existing"}));assert.equal(result.context.case_id,"case-existing");assert.equal(h.store.getInvestigationBundle("user-a",{...scope,case_id:"case-existing"}).cases.length,1);}finally{await h.close();}});

test("explicit reference outranks route context while route context works when no reference exists",async()=>{const fields=[scope,{field_id:"field-second",season_id:"season-second"}],h=await setup({fields});try{const explicit=await h.store.orchestrateConversationTurn("user-a",{request_id:"explicit-priority",message:"ช่วยดู",entry_point:"HOME",explicit_reference:scope,route_context:{field_id:"field-second",season_id:"season-second"}}),route=await h.store.orchestrateConversationTurn("user-a",{request_id:"route-context",message:"ช่วยดู",entry_point:"FIELD",route_context:{field_id:"field-second",season_id:"season-second"}});assert.equal(explicit.context.field_id,scope.field_id);assert.equal(explicit.context.resolution_source,"EXPLICIT_REFERENCE");assert.equal(route.context.field_id,"field-second");assert.equal(route.context.resolution_source,"ROUTE");}finally{await h.close();}});

test("unique active Field and CropSeason avoid foundational clarification",async()=>{const h=await setup();try{const result=await h.store.orchestrateConversationTurn("user-a",{request_id:"unique-active",message:"ช่วยดูหน่อย",entry_point:"HOME"});assert.equal(result.context.field_id,scope.field_id);assert.equal(result.context.season_id,scope.season_id);assert.equal(result.context.resolution_source,"UNIQUE_ACTIVE_FIELD");assert.equal(result.question,null);}finally{await h.close();}});

test("known authoritative Stage is reused in the context package and never asked again",async()=>{const h=await setup();try{const result=await h.store.orchestrateConversationTurn("user-a",request("ช่วยดูหน่อย",{request_id:"known-stage",audience:"SPA"}));assert.equal(result.technical_detail.context_package.stage.crop_stage.code,"TILLERING");assert.equal(result.technical_detail.context_package.stage.provenance,"USER_CONFIRMED");assert.equal(result.question,null);assert.doesNotMatch(result.text,/ระยะอะไร|ปลูกเมื่อไร/);}finally{await h.close();}});

test("known management history is reused as references and is not re-interviewed",async()=>{const h=await setup();try{h.store.createInvestigationRecord("user-a","CASE",{...scope,case_id:"case-management-known",purpose:"known management"});h.store.createInvestigationRecord("user-a","MANAGEMENT_EVENT",{...scope,case_id:"case-management-known",management_event_id:"management-known",event_type:"IRRIGATION",event_at:"2026-08-26T04:00:00.000Z",time_precision:"EXACT",source:"USER_REPORTED"});const result=await h.store.orchestrateConversationTurn("user-a",request("ช่วยดูสถานะ",{request_id:"known-management",case_id:"case-management-known",audience:"SPA"}));assert.equal(result.technical_detail.context_package.investigation.management_refs[0].management_event_id,"management-known");assert.equal(result.question,null);assert.doesNotMatch(result.text,/เคยทำอะไร|จัดการอะไร|ให้น้ำเมื่อไร/);}finally{await h.close();}});

test("conversation ownership and field boundaries are enforced",async()=>{const h=await setup();try{const first=await h.store.orchestrateConversationTurn("user-a",request("ช่วยดูหน่อย",{request_id:"owned"}));assert.throws(()=>h.store.getGovernedConversationHistory("user-b",first.conversation_id),/conversation scope/);await assert.rejects(()=>h.store.orchestrateConversationTurn("user-a",{request_id:"cross-field",conversation_id:first.conversation_id,message:"ช่วยดู",entry_point:"FIELD",field_id:"other-field",season_id:"other-season"}),/cannot silently cross fields/);}finally{await h.close();}});

test("conversation request contract rejects secrets, extra fields, and invalid entry points",async()=>{const h=await setup();try{await assert.rejects(()=>h.store.orchestrateConversationTurn("user-a",request("ช่วยดู",{request_id:"secret-field",api_key:"secret"})),/unsupported field/);await assert.rejects(()=>h.store.orchestrateConversationTurn("user-a",request("ช่วยดู",{request_id:"bad-entry",entry_point:"UNKNOWN_ENTRY"})),/invalid entry_point/);}finally{await h.close();}});

test("server conversation memory supports list, append-only history, and raw-message audit",async()=>{const h=await setup();try{const first=await h.store.orchestrateConversationTurn("user-a",request("ข้าวเหลือง",{request_id:"history-one"}));await h.store.orchestrateConversationTurn("user-a",request("ช่วยดูหน่อย",{request_id:"history-two",conversation_id:first.conversation_id}));const listed=h.store.listGovernedConversations("user-a"),history=h.store.getGovernedConversationHistory("user-a",first.conversation_id);assert.equal(listed.conversations.length,1);assert.equal(history.turns.length,2);assert.equal(history.turns[0].raw_message,"ข้าวเหลือง");assert.equal(history.turns[0].raw_message_is_evidence,false);assert.equal(history.conversation.authority,"SERVER_CONVERSATION_MEMORY");}finally{await h.close();}});

test("server conversation memory survives process/store restart",async()=>{const h=await setup();let reopened;try{const first=await h.store.orchestrateConversationTurn("user-a",request("ข้าวเหลือง",{request_id:"persist-restart"}));h.store.close();reopened=await new PilotStore({dbPath:join(h.root,"pilot.sqlite"),exportDir:join(h.root,"exports"),investigationCandidateProvider:createEmptyCandidateProvider()}).open();const history=reopened.getGovernedConversationHistory("user-a",first.conversation_id);assert.equal(history.turns.length,1);assert.equal(history.turns[0].raw_message,"ข้าวเหลือง");}finally{reopened?.close();await rm(h.root,{recursive:true,force:true});}});

test("conversation history alone never appears in the Investigation Evidence bundle",async()=>{const h=await setup();try{const result=await h.store.orchestrateConversationTurn("user-a",request("ขอบคุณครับ",{request_id:"history-not-evidence"})),history=h.store.getGovernedConversationHistory("user-a",result.conversation_id),bundle=h.store.getInvestigationBundle("user-a",scope);assert.equal(history.turns.length,1);assert.equal(bundle.evidence.length,0);assert.equal(bundle.observations.length,0);}finally{await h.close();}});

test("a correction appends a new turn and preserves the original immutable message",async()=>{const h=await setup();try{const first=await h.store.orchestrateConversationTurn("user-a",request("ข้าวเหลือง",{request_id:"correction-original"}));await h.store.orchestrateConversationTurn("user-a",request("แก้ไข: ใบไม่ได้เหลือง",{request_id:"correction-new",conversation_id:first.conversation_id,corrects_turn_id:first.turn_id}));const history=h.store.getGovernedConversationHistory("user-a",first.conversation_id);assert.equal(history.turns[0].raw_message,"ข้าวเหลือง");assert.equal(history.turns[1].corrects_turn_id,first.turn_id);}finally{await h.close();}});

test("stale conversation revision fails closed before mutation",async()=>{const h=await setup();try{const first=await h.store.orchestrateConversationTurn("user-a",request("ช่วยดูหน่อย",{request_id:"revision-one"}));await assert.rejects(()=>h.store.orchestrateConversationTurn("user-a",request("ข้าวเหลือง",{request_id:"revision-stale",conversation_id:first.conversation_id,expected_conversation_revision:99})),/conversation changed before turn/);const history=h.store.getGovernedConversationHistory("user-a",first.conversation_id);assert.equal(history.turns.length,1);}finally{await h.close();}});

test("provider failure is recorded as safe conversation limitation without scientific writes",async()=>{const provider=createTestOnlyConversationProvider(()=>{throw new Error("offline");}),h=await setup({provider});try{const result=await h.store.orchestrateConversationTurn("user-a",request("ข้าวเหลือง",{request_id:"provider-failure"}));assert.equal(result.response_type,"SYSTEM_LIMITATION");assert.equal(result.error_code,"CONVERSATION_UNAVAILABLE");assert.equal(result.fact_record_references.length,0);assert.equal(h.store.db.prepare("SELECT COUNT(*) count FROM investigation_observations").get().count,0);assert.equal(h.store.db.prepare("SELECT COUNT(*) count FROM governed_conversation_turns").get().count,1);}finally{await h.close();}});

test("provider failure leaves lifecycle, Field inspection data, and governed capture usable",async()=>{const provider=createTestOnlyConversationProvider(()=>{throw new Error("offline");}),h=await setup({provider});try{await h.store.orchestrateConversationTurn("user-a",request("ช่วยดู",{request_id:"failure-field-usable"}));assert.equal(h.store.getLifecycle("user-a").fields[0].field_id,scope.field_id);const caseRecord=h.store.createInvestigationRecord("user-a","CASE",{...scope,case_id:"case-after-chat-failure",purpose:"field still works"}),observation=h.store.createInvestigationRecord("user-a","OBSERVATION",{...scope,case_id:caseRecord.case_id,observation_id:"obs-after-chat-failure",source:"FIELD_OBSERVED"});assert.equal(observation.observation_id,"obs-after-chat-failure");}finally{await h.close();}});

test("provider API key and authorization never appear in persisted turn output",async()=>{const provider=new OpenAIConversationProvider({apiKey:"super-secret-key",model:"model-test",fetcher:async()=>({ok:false,status:503,json:async()=>({})})}),h=await setup({provider});try{const result=await h.store.orchestrateConversationTurn("user-a",request("ช่วยดู",{request_id:"key-not-exposed"})),persisted=h.store.db.prepare("SELECT response_json,provider_json FROM governed_conversation_turns WHERE request_id='key-not-exposed'").get();assert.doesNotMatch(JSON.stringify(result),/super-secret-key|authorization/i);assert.doesNotMatch(`${persisted.response_json}${persisted.provider_json}`,/super-secret-key|authorization/i);}finally{await h.close();}});

test("provider cannot select diagnosis, probability, guidance, management, or actions",async()=>{const provider=createTestOnlyConversationProvider({intent:"QUESTION",explicit_facts:[],user_hypothesis:null,diagnosis:"blast"}),h=await setup({provider});try{const result=await h.store.orchestrateConversationTurn("user-a",request("ช่วยดู",{request_id:"provider-prohibited"}));assert.equal(result.response_type,"SYSTEM_LIMITATION");assert.equal(result.error_code,"CONVERSATION_UNAVAILABLE");}finally{await h.close();}});

test("test-only ConversationProvider type cannot be constructed as production",()=>{assert.throws(()=>new ConversationProvider({providerId:"bad-test-provider",providerVersion:"test/v1",providerType:"TEST_ONLY_CONVERSATION_PROVIDER",available:true}),/cannot load in normal runtime/);});

test("provider receives minimum context without unrelated Field history or Candidate names",async()=>{let received;const provider=createTestOnlyConversationProvider((input)=>{received=input;return {intent:"QUESTION",explicit_facts:[],user_hypothesis:null};}),fields=[scope,{field_id:"field-private",season_id:"season-private"}],h=await setup({provider,fields});try{h.store.createInvestigationRecord("user-a","CASE",{...scope,case_id:"case-private-context",purpose:"privacy"});h.store.createInvestigationRecord("user-a","CANDIDATE",{...scope,case_id:"case-private-context",candidate_id:"candidate-secret-name",candidate_class:"DISEASE",label:"ชื่อที่ไม่ควรส่ง",support_state:"OPEN"});await h.store.orchestrateConversationTurn("user-a",request("ช่วยดู",{request_id:"minimum-context",case_id:"case-private-context"}));const serialized=JSON.stringify(received.minimumContext);assert.equal(received.minimumContext.identity.field_id,scope.field_id);assert.doesNotMatch(serialized,/field-private|season-private|candidate-secret-name|ชื่อที่ไม่ควรส่ง/);assert.ok(Array.isArray(received.minimumContext.known_fact_types));}finally{await h.close();}});

test("OpenAI provider uses strict structured output, store false, timeout signal, and no API key in payload",async()=>{let call;const fetcher=async(url,options)=>{call={url,options};return {ok:true,json:async()=>({id:"response-1",output:[{content:[{type:"output_text",text:JSON.stringify({intent:"QUESTION",explicit_facts:[],user_hypothesis:null})}]}]})};},provider=new OpenAIConversationProvider({apiKey:"server-secret",model:"model-test",fetcher,timeoutMs:1000}),result=await provider.interpret({message:"ช่วยดู",minimumContext:{identity:{field_id:"field-1"}}}),body=JSON.parse(call.options.body);assert.equal(result.intent,"QUESTION");assert.equal(body.store,false);assert.equal(body.text.format.strict,true);assert.equal(call.options.headers.authorization,"Bearer server-secret");assert.doesNotMatch(call.options.body,/server-secret/);assert.ok(call.options.signal);});

test("disabled provider makes no hidden provider call and governed phrase capture still works",async()=>{const provider=new ConversationProvider(),h=await setup({provider});try{const result=await h.store.orchestrateConversationTurn("user-a",request("ข้าวเหลือง",{request_id:"provider-disabled"}));assert.equal(result.provider.network_calls,false);assert.equal(result.explicit_facts[0].governed_code,"YELLOWING");}finally{await h.close();}});

test("golden E3 reuses the active B1/B2 target for ถ่ายแบบนี้ได้ไหม without restating it",async()=>{const h=await setup();try{h.store.createInvestigationRecord("user-a","CASE",{...scope,case_id:"case-visual-chat",purpose:"visual chat"});h.store.createInvestigationRecord("user-a","OBSERVATION",{...scope,case_id:"case-visual-chat",observation_id:"obs-visual-chat",source:"FIELD_OBSERVED"});const bytes=Buffer.from("visual-chat"),image=h.store.createImageEvidence("user-a",{field_id:scope.field_id,crop_season_id:scope.season_id,case_id:"case-visual-chat",observation_id:"obs-visual-chat",captured_at:now,source:"UPLOAD",capture_intent:"ROOT",plant_part_scope:"ROOT_SYSTEM",spatial_scope:"SAMPLED_OBJECT",view_type:"ROOT_COMPARISON",original_filename:"root.png",media_type:"image/png",size_bytes:bytes.length,content_hash:createHash("sha256").update(bytes).digest("hex"),storage_key:"root.png",comparison_role:"UNKNOWN_ROLE",comparison_role_source:"UNKNOWN"});let received;h.store.visualEvidence.nextRequest=()=>({request_type:"PHOTO",target:"ROOT_COMPARISON",view_type:"ROOT_COMPARISON"});h.store.visualPerception.history=()=>({history:[]});h.store.visualPerception.request=async(_user,input)=>{received=input;return {status:"COMPLETED",request:{analysis_request_id:"analysis-chat"},result:{perception_result_id:"result-chat",next_visual_action:{action:"NONE"}}};};const result=await h.store.orchestrateConversationTurn("user-a",request("ถ่ายแบบนี้ได้ไหม",{request_id:"golden-e3",case_id:"case-visual-chat",image_evidence_id:image.image_evidence_id,entry_point:"IMAGE"}));assert.equal(received.requested_target,null);assert.equal(result.response_type,"VISUAL_GUIDANCE");assert.equal(result.ui_action,"OPEN_VISUAL_REVIEW");assert.equal(result.question,null);assert.ok(result.visual_references.includes(image.image_evidence_id));}finally{await h.close();}});

test("golden E9 says the image is stored when automatic visual reading fails",async()=>{const h=await setup();try{h.store.createInvestigationRecord("user-a","CASE",{...scope,case_id:"case-visual-fail",purpose:"visual failure"});h.store.createInvestigationRecord("user-a","OBSERVATION",{...scope,case_id:"case-visual-fail",observation_id:"obs-visual-fail",source:"FIELD_OBSERVED"});const bytes=Buffer.from("visual-fail"),image=h.store.createImageEvidence("user-a",{field_id:scope.field_id,crop_season_id:scope.season_id,case_id:"case-visual-fail",observation_id:"obs-visual-fail",captured_at:now,source:"UPLOAD",capture_intent:"LEAF",plant_part_scope:"LEAF_BLADE",spatial_scope:"SAMPLED_OBJECT",view_type:"DETAIL",original_filename:"leaf.png",media_type:"image/png",size_bytes:bytes.length,content_hash:createHash("sha256").update(bytes).digest("hex"),storage_key:"leaf.png",comparison_role:"UNKNOWN_ROLE",comparison_role_source:"UNKNOWN"});h.store.visualEvidence.nextRequest=()=>({request_type:"PHOTO",target:"YELLOWING",view_type:"DETAIL"});h.store.visualPerception.history=()=>({history:[]});h.store.visualPerception.request=async()=>({status:"FAILED",perception_outcome:"PERCEPTION_UNAVAILABLE",request:{analysis_request_id:"analysis-failed"},result:null});const result=await h.store.orchestrateConversationTurn("user-a",request("ดูภาพนี้ให้หน่อย",{request_id:"golden-e9",case_id:"case-visual-fail",image_evidence_id:image.image_evidence_id,entry_point:"IMAGE"}));assert.equal(result.response_type,"SYSTEM_LIMITATION");assert.match(result.text,/เก็บภาพไว้แล้ว/);assert.doesNotMatch(result.text,/ไม่พบอะไร|ไม่มีอาการ/);}finally{await h.close();}});

test("wrong image quality produces exactly one better-view action and no checklist",async()=>{const h=await setup();try{h.store.createInvestigationRecord("user-a","CASE",{...scope,case_id:"case-better-view",purpose:"better view"});h.store.createInvestigationRecord("user-a","OBSERVATION",{...scope,case_id:"case-better-view",observation_id:"obs-better-view",source:"FIELD_OBSERVED"});const bytes=Buffer.from("better-view"),image=h.store.createImageEvidence("user-a",{field_id:scope.field_id,crop_season_id:scope.season_id,case_id:"case-better-view",observation_id:"obs-better-view",captured_at:now,source:"UPLOAD",capture_intent:"ROOT",plant_part_scope:"ROOT_SYSTEM",spatial_scope:"SAMPLED_OBJECT",view_type:"FIELD_CONTEXT",original_filename:"context.png",media_type:"image/png",size_bytes:bytes.length,content_hash:createHash("sha256").update(bytes).digest("hex"),storage_key:"context.png",comparison_role:"UNKNOWN_ROLE",comparison_role_source:"UNKNOWN"});h.store.visualEvidence.nextRequest=()=>({request_type:"PHOTO",target:"ROOT_COMPARISON",view_type:"ROOT_COMPARISON"});h.store.visualPerception.history=()=>({history:[]});h.store.visualPerception.request=async()=>({status:"COMPLETED",request:{analysis_request_id:"analysis-better"},result:{perception_result_id:"result-better",next_visual_action:{action:"BETTER_VIEW_REQUIRED",target:"ROOT_COMPARISON"}}});const result=await h.store.orchestrateConversationTurn("user-a",request("ดูภาพนี้",{request_id:"better-view",case_id:"case-better-view",image_evidence_id:image.image_evidence_id,entry_point:"IMAGE"}));assert.equal(result.actions.length,1);assert.equal(result.actions[0].action,"REQUEST_VISUAL_EVIDENCE");assert.equal(result.ui_action,"OPEN_CAMERA");assert.equal(result.question,null);assert.doesNotMatch(result.text,/1\.|2\.|3\./);}finally{await h.close();}});

test("perception unavailable creates no negative Investigation Evidence",async()=>{const h=await setup();try{h.store.createInvestigationRecord("user-a","CASE",{...scope,case_id:"case-no-negative",purpose:"no negative"});h.store.createInvestigationRecord("user-a","OBSERVATION",{...scope,case_id:"case-no-negative",observation_id:"obs-no-negative",source:"FIELD_OBSERVED"});const bytes=Buffer.from("no-negative"),image=h.store.createImageEvidence("user-a",{field_id:scope.field_id,crop_season_id:scope.season_id,case_id:"case-no-negative",observation_id:"obs-no-negative",captured_at:now,source:"UPLOAD",capture_intent:"LEAF",plant_part_scope:"LEAF_BLADE",spatial_scope:"SAMPLED_OBJECT",view_type:"DETAIL",original_filename:"none.png",media_type:"image/png",size_bytes:bytes.length,content_hash:createHash("sha256").update(bytes).digest("hex"),storage_key:"none.png",comparison_role:"UNKNOWN_ROLE",comparison_role_source:"UNKNOWN"});h.store.visualEvidence.nextRequest=()=>({request_type:"PHOTO",target:"YELLOWING"});h.store.visualPerception.history=()=>({history:[]});h.store.visualPerception.request=async()=>({status:"FAILED",request:{analysis_request_id:"analysis-none"},result:null});const before=h.store.getInvestigationBundle("user-a",{...scope,case_id:"case-no-negative"}).evidence.length;await h.store.orchestrateConversationTurn("user-a",request("ดูภาพนี้",{request_id:"no-negative",case_id:"case-no-negative",image_evidence_id:image.image_evidence_id,entry_point:"IMAGE"}));const after=h.store.getInvestigationBundle("user-a",{...scope,case_id:"case-no-negative"}).evidence.length;assert.equal(after,before);}finally{await h.close();}});

test("golden E10 management query reads Step F1 and contains no product advice",async()=>{const h=await setup();try{const result=await h.store.orchestrateConversationTurn("user-a",request("ควรพ่นยาอะไร อัตราเท่าไร",{request_id:"management"}));assert.equal(result.intent,"MANAGEMENT_QUERY");assert.equal(result.response_type,"MANAGEMENT_REVIEW_SUMMARY");assert.equal(result.actions[0].action,"PRESENT_MANAGEMENT_REVIEW");assert.doesNotMatch(result.text,/มล\.ลิตร|กรัม|tricyclazole|ชื่อการค้า/i);}finally{await h.close();}});

test("management boundary emits no pesticide, active ingredient, commercial product, or dose/rate field",async()=>{const h=await setup();try{const result=await h.store.orchestrateConversationTurn("user-a",request("ใช้สารอะไร ยี่ห้อไหน โดสเท่าไร",{request_id:"management-fields"})),serialized=JSON.stringify(result);for(const prohibited of [/pesticide_selection/i,/active_ingredient/i,/commercial_product/i,/dose\s*:/i,/rate\s*:/i,/ผลิตภัณฑ์\s*:/i])assert.doesNotMatch(serialized,prohibited);}finally{await h.close();}});

test("golden E6 obeys Step D no-additional stop with no follow-up question",async()=>{const h=await setup();try{h.store.createInvestigationRecord("user-a","CASE",{...scope,case_id:"case-stop",purpose:"stopped"});h.store.guidanceIntelligence.current=()=>({guidance_id:"guidance-stop",status:"GENERATED",guidance_type:"NO_ADDITIONAL_INSPECTION",inspection_domain:"GENERAL_FIELD_INSPECTION",title:"ยังไม่ต้องตรวจเพิ่ม",instruction:"คงหลักฐานไว้",why_now:"พอสำหรับตอนนี้",what_to_inspect:"ไม่มี",where_to_inspect:"ไม่มี",how_to_inspect:"ไม่สร้างงานซ้ำ",reason_code:"USER_DECLINED",context_hash:"guidance-stop-hash",limitations:[]});const result=await h.store.orchestrateConversationTurn("user-a",request("ช่วยดูสถานะตอนนี้",{request_id:"golden-e6",case_id:"case-stop"}));assert.equal(result.response_type,"NO_ADDITIONAL_ACTION");assert.equal(result.actions[0].action,"NO_ADDITIONAL_ACTION");assert.equal(result.question,null);}finally{await h.close();}});

test("golden E7 presents one expert handoff without another evidence checklist",async()=>{const h=await setup();try{h.store.createInvestigationRecord("user-a","CASE",{...scope,case_id:"case-expert",purpose:"expert handoff"});h.store.guidanceIntelligence.current=()=>({guidance_id:"guidance-expert",status:"GENERATED",guidance_type:"FOLLOW_EXISTING_CASE",inspection_domain:"GENERAL_FIELD_INSPECTION",title:"ส่งต่อเคส",instruction:"ส่งต่อ",why_now:"หลักฐานภาคสนามหมดแล้ว",what_to_inspect:"SPECIALIST_CASE_REVIEW",where_to_inspect:"ชุดหลักฐาน",how_to_inspect:"ส่งต่อ",reason_code:"EXPERT_REVIEW_REQUIRED",context_hash:"guidance-expert-hash",limitations:[]});const result=await h.store.orchestrateConversationTurn("user-a",request("ทำอะไรต่อ",{request_id:"golden-e7",case_id:"case-expert"}));assert.equal(result.response_type,"EXPERT_HANDOFF");assert.equal(result.actions.length,1);assert.equal(result.actions[0].action,"REQUEST_EXPERT_REVIEW");assert.equal(result.question,null);assert.doesNotMatch(result.text,/1\.|2\.|3\./);}finally{await h.close();}});

test("lab stop produces one lab handoff and no question",async()=>{const h=await setup();try{h.store.createInvestigationRecord("user-a","CASE",{...scope,case_id:"case-lab",purpose:"lab handoff"});h.store.guidanceIntelligence.current=()=>({guidance_id:"guidance-lab",status:"GENERATED",guidance_type:"FOLLOW_EXISTING_CASE",inspection_domain:"GENERAL_FIELD_INSPECTION",title:"ส่งห้องปฏิบัติการ",instruction:"ส่งต่อ",why_now:"ต้องใช้หลักฐานห้องปฏิบัติการ",what_to_inspect:"LABORATORY_EVIDENCE_HANDOFF",where_to_inspect:"ชุดหลักฐาน",how_to_inspect:"ส่งต่อ",reason_code:"LAB_EVIDENCE_REQUIRED",context_hash:"guidance-lab-hash",limitations:[]});const result=await h.store.orchestrateConversationTurn("user-a",request("ทำอะไรต่อ",{request_id:"lab-stop",case_id:"case-lab"}));assert.equal(result.response_type,"LAB_HANDOFF");assert.equal(result.actions[0].action,"REQUEST_LAB_EVIDENCE");assert.equal(result.question,null);}finally{await h.close();}});

test("knowledge query is presented separately and never creates a field finding",async()=>{const h=await setup();try{const result=await h.store.orchestrateConversationTurn("user-a",request("ขอความรู้ทั่วไปว่าใบข้าวคืออะไร",{request_id:"knowledge"}));assert.equal(result.response_type,"GENERAL_KNOWLEDGE");assert.equal(result.ui_action,"OPEN_KNOWLEDGE");assert.equal(result.fact_record_references.length,0);}finally{await h.close();}});

test("GENERAL_CHAT social and knowledge turns can remain deliberately unscoped",async()=>{const h=await setup({fields:[scope,{field_id:"field-second",season_id:"season-second"}]});try{const social=await h.store.orchestrateConversationTurn("user-a",{request_id:"general-social",message:"สวัสดีครับ",entry_point:"GENERAL_CHAT"}),knowledge=await h.store.orchestrateConversationTurn("user-a",{request_id:"general-knowledge",message:"ขอความรู้ทั่วไปเรื่องข้าว",entry_point:"GENERAL_CHAT"});assert.equal(social.context.scope,"GENERAL");assert.equal(social.response_type,"ACKNOWLEDGEMENT");assert.equal(knowledge.response_type,"GENERAL_KNOWLEDGE");assert.equal(knowledge.fact_record_references.length,0);}finally{await h.close();}});

test("SP hides governed enums while SPA gets a separate technical detail object",async()=>{const h=await setup();try{const sp=await h.store.orchestrateConversationTurn("user-a",request("ข้าวเหลือง",{request_id:"sp",audience:"SP"})),spa=await h.store.orchestrateConversationTurn("user-a",request("ข้าวเหลือง",{request_id:"spa",audience:"SPA"}));assert.equal(sp.technical_detail,null);assert.doesNotMatch(sp.text,/YELLOWING|MO0_REPORTED/);assert.ok(spa.technical_detail.governed_codes.includes("YELLOWING"));}finally{await h.close();}});

test("friendly SP response stays concise, Thai-first, and free of Candidate percentages",async()=>{const h=await setup();try{const result=await h.store.orchestrateConversationTurn("user-a",request("ข้าวเหลืองเป็นหย่อม",{request_id:"friendly-thai"}));assert.ok(result.text.length<240);assert.match(result.text,/[฀-๿]/u);assert.doesNotMatch(result.text,/\d+%|probability|diagnosis|Candidate|YELLOWING|PATCH/i);assert.equal(result.question,null);}finally{await h.close();}});

test("all responses have one best action and at most one question",async()=>{const h=await setup();try{for(const [index,message] of ["ข้าวเหลือง","ช่วยดูหน่อย","ควรพ่นยาอะไร","ขอบคุณ"] .entries()){const result=await h.store.orchestrateConversationTurn("user-a",request(message,{request_id:`budget-${index}`}));assert.equal(result.actions.length,1);assert.ok(result.question==null||typeof result.question==="string");assert.equal(Array.isArray(result.question),false);}}finally{await h.close();}});

test("context hashes rebuild after governed evidence changes for cross-device resume",async()=>{const h=await setup();try{const first=await h.store.orchestrateConversationTurn("user-a",request("ช่วยดูหน่อย",{request_id:"resume-first"})),before=h.store.rebuildGovernedConversationContext("user-a",first.conversation_id);const caseId=first.context.case_id??h.store.createInvestigationRecord("user-a","CASE",{...scope,case_id:"case-resume",purpose:"resume"}).case_id;if(!first.context.case_id)h.store.db.prepare("UPDATE governed_conversations SET case_id=? WHERE conversation_id=?").run(caseId,first.conversation_id);h.store.createInvestigationRecord("user-a","OBSERVATION",{...scope,case_id:caseId,observation_id:"obs-resume",source:"FIELD_OBSERVED",note:"new server evidence"});const after=h.store.rebuildGovernedConversationContext("user-a",first.conversation_id);assert.notEqual(after.context.context_hash,before.context.context_hash);assert.ok(after.conversation.revision>before.conversation.revision);}finally{await h.close();}});

test("a stage change supersedes prior Step D guidance and presents only current guidance",async()=>{const h=await setup();try{const first=await h.store.orchestrateConversationTurn("user-a",request("น่าจะโรคไหม้",{request_id:"guidance-first"})),firstGuidance=first.guidance_reference.guidance_id,state=lifecycle();state.fields[0].current_crop_stage={code:"PANICLE_INITIATION",label:"สร้างรวง",model_version:"field-stage-model/v1"};state.fields[0].updated_at="2026-08-28T00:00:00.000Z";h.store.putWorkspace("user-a",state);const second=await h.store.orchestrateConversationTurn("user-a",request("ช่วยดูต่อ",{request_id:"guidance-current",conversation_id:first.conversation_id})),history=h.store.getGovernedGuidanceHistory("user-a",{...scope,case_id:first.context.case_id});assert.notEqual(second.guidance_reference.guidance_id,firstGuidance);assert.equal(history.find((item)=>item.guidance_id===firstGuidance).status,"SUPERSEDED");assert.notEqual(second.guidance_reference.status,"SUPERSEDED");}finally{await h.close();}});

test("the response contract always declares authority, versions, references, and timestamp",async()=>{const h=await setup();try{const result=await h.store.orchestrateConversationTurn("user-a",request("ข้าวเหลือง",{request_id:"output-contract"}));for(const key of ["turn_id","conversation_id","context","intent","explicit_facts","fact_record_references","actions","assessment_reference","guidance_reference","visual_references","response_type","text","question","ui_action","limitations","authority","provider","created_at","output_version"])assert.ok(key in result,key);assert.ok(CONVERSATION_ENUMS.responseTypes.includes(result.response_type));assert.ok(CONVERSATION_ENUMS.uiActions.includes(result.ui_action));assert.equal(result.authority.provider_scientific_authority,false);}finally{await h.close();}});

test("all supported entry points remain a closed accepted vocabulary",async()=>{for(const entryPoint of CONVERSATION_ENUMS.entryPoints){const h=await setup();try{const result=await h.store.orchestrateConversationTurn("user-a",request("ช่วยดู",{request_id:`entry-${entryPoint}`,entry_point:entryPoint}));assert.equal(result.context.field_id,scope.field_id);}finally{await h.close();}}});

test("chat-disabled architecture leaves the non-chat Field flow independent",async()=>{const h=await setup({provider:new ConversationProvider()});try{const lifecycleState=h.store.getLifecycle("user-a"),caseRecord=h.store.createInvestigationRecord("user-a","CASE",{...scope,case_id:"case-no-chat",purpose:"non-chat inspection"}),observation=h.store.createInvestigationRecord("user-a","OBSERVATION",{...scope,case_id:caseRecord.case_id,observation_id:"obs-no-chat",source:"FIELD_OBSERVED"}),bundle=h.store.getInvestigationBundle("user-a",{...scope,case_id:caseRecord.case_id});assert.equal(lifecycleState.fields.length,1);assert.equal(observation.observation_id,"obs-no-chat");assert.equal(bundle.observations.length,1);}finally{await h.close();}});

test("raw browser workspace conversation is not authoritative server conversation memory",async()=>{const h=await setup();try{const state=lifecycle();state.conversations=[{conversation_id:"browser-only",user_id:"user-a",...scope,scope:"FIELD_SCOPED"}];state.messages=[{message_id:"browser-message",conversation_id:"browser-only",user_id:"user-a",...scope,content:"local"}];h.store.putWorkspace("user-a",state);assert.equal(h.store.listGovernedConversations("user-a").conversations.length,0);assert.throws(()=>h.store.getGovernedConversationHistory("user-a","browser-only"),/conversation scope/);}finally{await h.close();}});

test("conversation HTTP APIs are session scoped and legacy field chat cannot bypass orchestration",async()=>{const root=await mkdtemp(join(tmpdir(),"cpmoakb-conversation-api-")),dbPath=join(root,"pilot.sqlite"),exportDir=join(root,"exports"),seed=await new PilotStore({dbPath,exportDir,investigationCandidateProvider:createEmptyCandidateProvider()}).open();seed.putWorkspace("user-a",lifecycle());seed.close();const server=await startServer({port:0,dbPath,exportDir,uploadDir:join(root,"uploads"),pilotUserId:"user-a"});try{const base=`http://127.0.0.1:${server.address().port}`,login=await fetch(`${base}/api/pilot/session`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({password:"1234"})}),cookie=login.headers.get("set-cookie").split(";")[0],turn=await fetch(`${base}/api/pilot/conversation-turns`,{method:"POST",headers:{cookie,"content-type":"application/json"},body:JSON.stringify(request("ข้าวเหลืองเป็นหย่อม",{request_id:"api-turn"}))}),payload=await turn.json();assert.equal(turn.status,201);assert.equal(payload.status,"TURN_COMPLETED");assert.equal(payload.explicit_facts.length,2);const history=await fetch(`${base}/api/pilot/conversation-history?conversation_id=${payload.conversation_id}`,{headers:{cookie}});assert.equal(history.status,200);const unauth=await fetch(`${base}/api/pilot/conversations`);assert.equal(unauth.status,401);const legacy=await fetch(`${base}/api/assistant/chat`,{method:"POST",headers:{cookie,"content-type":"application/json"},body:JSON.stringify({message:"ข้าวเหลือง",scope:"FIELD_SCOPED",...scope})}),legacyPayload=await legacy.json();assert.equal(legacy.status,410);assert.equal(legacyPayload.legacy_free_form_authoritative,false);}finally{await new Promise((done)=>server.close(done));await rm(root,{recursive:true,force:true});}});
