import test from "node:test";
import assert from "node:assert/strict";
import { mkdtemp, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { createEmptyCandidateProvider } from "../candidate-provider.mjs";
import { createTestOnlyConversationProvider } from "../conversation-orchestrator.mjs";
import { StaticInvestigationRuleProvider } from "../investigation-intelligence.mjs";
import { createTestOnlyManagementRuleProvider } from "../management-option-runtime.mjs";
import { DECISION_ACTION_OUTCOME_ENUMS } from "../decision-action-outcome-runtime.mjs";
import { PilotStore } from "../pilot-store.mjs";
import { startServer } from "../server.mjs";

const scope={field_id:"field-f2",season_id:"season-f2",case_id:"case-f2"};
const now="2026-08-28T02:00:00.000Z";
function ids(){let value=0;return()=>`00000000-0000-4000-8000-${String(++value).padStart(12,"0")}`;}
function lifecycle(userId="user-a"){return{schema_version:2,users:[{user_id:userId}],fields:[{field_id:scope.field_id,owner_user_id:userId,name:"นา F2",crop:"rice",planting_date:"2026-07-01",current_crop_stage:{code:"TILLERING",label:"แตกกอ",model_version:"field-stage-model/v1"},current_cmp_stage:{stage_id:"CMP-03",label:"ระยะแตกกอ",model_version:"field-stage-model/v1"},season_id:scope.season_id,stage_provenance:"USER_CONFIRMED",created_at:now,updated_at:now}],seasons:[{season_id:scope.season_id,field_id:scope.field_id,crop:"rice",status:"ACTIVE"}],guidance:[],activities:[],cases:[],observations:[],evidence:[],conversations:[],messages:[],decision_logs:[],case_summaries:[],weather_snapshots:[]};}
const stepC=()=>new StaticInvestigationRuleProvider({rule_version:"step-c-f2/v1",rule_authority:"BOUNDED_RUNTIME_RULE",rule_review_state:"HUMAN_REVIEWED",sufficiency_state:"SUFFICIENT_FOR_MANAGEMENT_OPTION_REVIEW",rules:[]});
const regulatory=(complete=false)=>({jurisdiction:"TH",authority_class:"PRIMARY_OFFICIAL_REGULATOR",current:complete,conflicting:false,defensible_join_key:complete,exact_chain:complete?{crop:"rice",target:"TEST_ONLY_TARGET",use:"TEST_ONLY_USE",registration:"TEST-REGISTRATION-001"}:{crop:"rice",target:null,use:null,registration:"IDENTITY-ONLY-001"},authority_refs:[complete?"TEST-ONLY-CURRENT-THAI-AUTHORITY/v1":"GS-DOA-HAZARDOUS-REGISTRY-2026-001/v1"],limitation:"Bounded test authority."});
const rules=(state="MANAGEMENT_REVIEW_JUSTIFIED",{chemical=false,relationships}={})=>createTestOnlyManagementRuleProvider({need_for_action:{state,reason:`Governed ${state} fixture.`,supporting_evidence_refs:[],missing_evidence_refs:[],source_rule_id:`NFA-${state}/v1`,source_refs:["TEST-GOVERNED-ACTION-SOURCE/v1"],limitations:["Fixture is bounded to deterministic tests."]},management_relationships:relationships??[{rule_id:"WATER-F2/v1",option_class:"WATER_MANAGEMENT",case_relevant:true,reason:"Governed water relationship supports review.",source_refs:["TEST-WATER-SOURCE/v1"],limitations:["No water level prescribed."]}],regulatory_authority:regulatory(chemical)});
async function setup({managementProvider=rules(),userId="user-a",conversationProvider=null}={}){const root=await mkdtemp(join(tmpdir(),"cpmoakb-f2-")),idProvider=ids(),store=await new PilotStore({dbPath:join(root,"pilot.sqlite"),exportDir:join(root,"exports"),investigationRuleProvider:stepC(),investigationCandidateProvider:createEmptyCandidateProvider(),managementRuleProvider:managementProvider,conversationProvider,intelligenceClock:()=>new Date(now),managementClock:()=>new Date(now),decisionActionOutcomeClock:()=>new Date(now),intelligenceIdProvider:idProvider,managementIdProvider:idProvider,decisionActionOutcomeIdProvider:idProvider}).open();store.putWorkspace(userId,lifecycle(userId));store.createInvestigationRecord(userId,"CASE",{...scope,purpose:"Governed F2 test Case"});return{root,store,userId,close:async()=>{store.close();await rm(root,{recursive:true,force:true});}};}
const find=(review,optionClass)=>review.all_option_evaluations.find((item)=>item.option_class===optionClass);
function decisionInput(review,selected,requestId="decision-1",extra={}){return{request_id:requestId,...scope,management_review_id:review.management_review_id,decision_type:"SELECT_MANAGEMENT_OPTION",selected_option_id:selected?.management_option_id,selection_source:"AUTHENTICATED_UI",selection_raw_text:"ฉันเลือกทางนี้",selection_source_span:{start:0,end:16,text:"ฉันเลือกทางนี้"},explicit_confirmation:true,expected_current_decision_id:null,supersedes_decision_id:null,...extra};}
function planInput(decision,requestId="action-plan-1",extra={}){return{request_id:requestId,...scope,decision_id:decision.decision_id,action_kind:"PLAN",action_source:"HUMAN_AUTHORED_PLAN",action_description:"แผนจัดการที่ผู้ใช้ยืนยัน",actor_source:"AUTHENTICATED_USER",explicit_confirmation:true,expected_current_action_id:null,supersedes_action_id:null,...extra};}
function performedInput(decision,plan,requestId="action-done-1",extra={}){return{request_id:requestId,...scope,decision_id:decision.decision_id,action_kind:"CONFIRM_PERFORMED",action_source:"HUMAN_EXECUTION_CONFIRMATION",actor_source:"AUTHENTICATED_USER",performed_at:"2026-08-28T03:00:00.000Z",explicit_confirmation:true,expected_current_action_id:plan.management_action_id,supersedes_action_id:plan.management_action_id,management_event_type:"WEED_CONTROL",...extra};}
function outcomeInput(decision,action,phase,revision,extra={}){return{request_id:`outcome-${phase}-${revision}`,...scope,decision_id:decision.decision_id,management_action_id:action.management_action_id,phase,observed_at:`2026-08-${phase==="T0"?"27":"29"}T04:00:00.000Z`,elapsed_relation_to_action:phase==="T0"?"BEFORE_ACTION":"AFTER_ACTION",subject:"จำนวนจุดที่พบ",raw_value:10-revision,unit:"count",denominator:"10 จุด",count_basis:"visible plants",sample_size:10,sampling_method:"fixed ten points",sampling_context:{route:"same transect"},spatial_scope:"same plot",visual_evidence_refs:[],source:"USER_SUBMITTED",evidence_state:"MEASURED",limitations:[],explicit_submission:true,expected_outcome_revision:revision,...extra};}
async function ready(h){const review=h.store.assessManagementOptions(h.userId,scope),selected=find(review,"CULTURAL_MANAGEMENT"),decision=h.store.createHumanDecision(h.userId,decisionInput(review,selected)),plan=h.store.createManagementAction(h.userId,planInput(decision)),action=h.store.createManagementAction(h.userId,performedInput(decision,plan));return{review,selected,decision,plan,action};}

test("F2 publishes closed decision, action, phase, and comparability vocabularies",()=>{assert.deepEqual(DECISION_ACTION_OUTCOME_ENUMS.outcomePhases,["T0","T1","T2"]);assert.ok(DECISION_ACTION_OUTCOME_ENUMS.decisionTypes.includes("CANCEL_PRIOR_DECISION"));assert.deepEqual(DECISION_ACTION_OUTCOME_ENUMS.samplingComparability,["SUPPORTED","COMPARISON_LIMITED","NOT_COMPARABLE","UNKNOWN"]);});

test("golden F2-1 human selects monitoring without forcing action, reminder, or Case resolution",async()=>{const h=await setup({managementProvider:rules("CONTINUE_MONITORING",{relationships:[]})});try{const review=h.store.assessManagementOptions(h.userId,scope),selected=find(review,"CONTINUE_MONITORING"),decision=h.store.createHumanDecision(h.userId,decisionInput(review,selected,"decision-monitor",{decision_type:"CONTINUE_MONITORING"}));assert.equal(decision.decision_state,"CONFIRMED");assert.equal(decision.immutable_snapshot,true);assert.equal(decision.f1_context_hash,review.context_hash);assert.equal(decision.investigation_bundle_hash,review.assessment_reference.source_bundle_hash);assert.ok(decision.visible_option_ids.includes(selected.management_option_id));assert.equal(decision.field_action_created,false);assert.equal(decision.reminder_created,false);assert.equal(h.store.getManagementActionHistory(h.userId,scope).length,0);assert.equal(h.store.getInvestigationBundle(h.userId,scope).cases[0].status,"OPEN");}finally{await h.close();}});

test("stale, blocked, unsupported, and non-explicit selections cannot become confirmed decisions",async()=>{const h=await setup();try{const review=h.store.assessManagementOptions(h.userId,scope),chemical=find(review,"CHEMICAL_REVIEW"),unsupported=find(review,"MECHANICAL_MANAGEMENT"),supported=find(review,"CULTURAL_MANAGEMENT");for(const [requestId,selected] of [["blocked",chemical],["unsupported",unsupported]])assert.throws(()=>h.store.createHumanDecision(h.userId,decisionInput(review,selected,requestId)),/cannot become/);assert.throws(()=>h.store.createHumanDecision(h.userId,decisionInput(review,supported,"not-explicit",{explicit_confirmation:false})),/requires|explicit/);assert.throws(()=>h.store.createHumanDecision(h.userId,decisionInput(review,supported,"stale",{management_review_id:"management-review-stale"})),/stale/);}finally{await h.close();}});

test("monitoring and no-action remain bounded explicit decision types",async()=>{for(const [state,type,optionClass] of [["CONTINUE_MONITORING","CONTINUE_MONITORING","CONTINUE_MONITORING"],["NO_ACTION_DETERMINATION_SUPPORTED","NO_ACTION_CURRENTLY","NO_ACTION_CURRENTLY_JUSTIFIED"]]){const h=await setup({managementProvider:rules(state,{relationships:[]})});try{const review=h.store.assessManagementOptions(h.userId,scope),selected=find(review,optionClass),decision=h.store.createHumanDecision(h.userId,decisionInput(review,selected,`decision-${type}`,{decision_type:type}));assert.equal(decision.decision_state,"CONFIRMED");assert.equal(decision.case_resolved,false);assert.equal(h.store.getInvestigationBundle(h.userId,scope).cases[0].status,"OPEN");}finally{await h.close();}}});

test("golden F2-3 blocked Chemical Review cannot become a Decision or application task",async()=>{const h=await setup();try{const response=await h.store.orchestrateConversationTurn(h.userId,{request_id:"blocked-chemical-step-e",...scope,entry_point:"CASE",message:"เลือกทางยา"});assert.equal(response.response_type,"MANAGEMENT_REVIEW_SUMMARY");assert.equal(h.store.getHumanDecisionHistory(h.userId,scope).length,0);assert.equal(h.store.getManagementActionHistory(h.userId,scope).length,0);assert.doesNotMatch(response.text,/ผลิตภัณฑ์|อัตรา|โดส|พ่นซ้ำ/iu);}finally{await h.close();}});

test("golden F2-14 expert handoff stays review-required with no transmission or expert conclusion",async()=>{const h=await setup({managementProvider:rules("HUMAN_REVIEW_REQUIRED",{relationships:[]})});try{const review=h.store.assessManagementOptions(h.userId,scope),selected=find(review,"EXPERT_REVIEW"),decision=h.store.createHumanDecision(h.userId,decisionInput(review,selected,"review-decision",{decision_type:"REQUEST_EXPERT_REVIEW"}));assert.equal(decision.decision_state,"REVIEW_REQUIRED");assert.equal(decision.expert_handoff.transmission,"NOT_PERFORMED");assert.equal(decision.expert_handoff.expert_conclusion,null);assert.throws(()=>h.store.createManagementAction(h.userId,planInput(decision)),/confirmed Human Decision/);}finally{await h.close();}});

test("golden F2-4 Chemical Review opens only the downstream governed layer and never an application action",async()=>{const h=await setup({managementProvider:rules("MANAGEMENT_REVIEW_JUSTIFIED",{chemical:true})});try{const review=h.store.assessManagementOptions(h.userId,scope),selected=find(review,"CHEMICAL_REVIEW"),decision=h.store.createHumanDecision(h.userId,decisionInput(review,selected));assert.equal(decision.decision_state,"CONFIRMED");assert.equal(decision.downstream_governed_layer,"FUTURE_GOVERNED_CHEMICAL_REVIEW_LAYER");assert.throws(()=>h.store.createManagementAction(h.userId,planInput(decision)),/Chemical Review/);assert.doesNotMatch(JSON.stringify(decision),/active_ingredient|tank_mix|drone_setting|spray_volume/i);}finally{await h.close();}});

test("decision change, decline, defer, and cancellation preserve immutable supersession history",async()=>{const h=await setup();try{const review=h.store.assessManagementOptions(h.userId,scope),selected=find(review,"CULTURAL_MANAGEMENT"),first=h.store.createHumanDecision(h.userId,decisionInput(review,selected)),second=h.store.createHumanDecision(h.userId,decisionInput(review,null,"decision-defer",{decision_type:"DEFER_DECISION",selected_option_id:undefined,expected_current_decision_id:first.decision_id,supersedes_decision_id:first.decision_id})),third=h.store.createHumanDecision(h.userId,decisionInput(review,null,"decision-cancel",{decision_type:"CANCEL_PRIOR_DECISION",selected_option_id:undefined,expected_current_decision_id:second.decision_id,supersedes_decision_id:second.decision_id})),history=h.store.getHumanDecisionHistory(h.userId,scope);assert.deepEqual(history.map((item)=>item.history_state),["SUPERSEDED","SUPERSEDED","CANCELLED"]);assert.equal(second.decision_state,"DEFERRED");assert.equal(third.decision_state,"CANCELLED");assert.equal(first.decision_state,"CONFIRMED");}finally{await h.close();}});

test("golden F2-5 planned action is not actual and explicit performed confirmation creates an auditable management event",async()=>{const h=await setup();try{const review=h.store.assessManagementOptions(h.userId,scope),decision=h.store.createHumanDecision(h.userId,decisionInput(review,find(review,"CULTURAL_MANAGEMENT"))),plan=h.store.createManagementAction(h.userId,planInput(decision));assert.equal(plan.status,"PLANNED");assert.equal(plan.actual_execution_confirmed,false);assert.equal(h.store.getInvestigationBundle(h.userId,scope).management_events.length,0);const action=h.store.createManagementAction(h.userId,performedInput(decision,plan));assert.equal(action.status,"PERFORMED");assert.equal(action.actual_execution_confirmed,true);assert.ok(action.management_event_ref);assert.equal(h.store.getInvestigationBundle(h.userId,scope).management_events.length,1);assert.equal(h.store.getManagementActionHistory(h.userId,scope)[0].status,"PLANNED");}finally{await h.close();}});

test("golden F2-6 historical human-reported input and rate are facts, never recommendations",async()=>{const h=await setup();try{const review=h.store.assessManagementOptions(h.userId,scope),decision=h.store.createHumanDecision(h.userId,decisionInput(review,find(review,"CULTURAL_MANAGEMENT"))),action=h.store.createManagementAction(h.userId,{...planInput(decision,"historical-action"),action_kind:"RECORD_HISTORICAL_ACTION",action_source:"USER_REPORTED_ACTION",performed_at:"2026-08-27T03:00:00Z",product_or_input_ref:"ชื่อที่ผู้ใช้รายงาน",rate_record:{value:2,unit:"USER_REPORTED_UNIT"},management_event_type:"UNKNOWN_MANAGEMENT_EVENT"});assert.equal(action.status,"PERFORMED");assert.equal(action.system_recommendation,false);assert.equal(action.legality_inferred,false);assert.equal(action.efficacy_inferred,false);assert.equal(action.repetition_recommended,false);}finally{await h.close();}});

test("Investigation Field Action and Management Action remain separate architectures",async()=>{const h=await setup();try{const {action}=await ready(h),context=h.store.getDecisionActionOutcomeContext(h.userId,scope);assert.equal(action.investigation_field_action_ref,null);assert.equal(context.boundaries.investigation_field_action_is_management_action,false);assert.equal(context.current_outcome_reviews[0].investigation_field_action_architecture,"field-action-handoff/v1");}finally{await h.close();}});

test("golden F2-7 explicit comparable T0/T1/T2 and Human Comparison remain descriptive",async()=>{const h=await setup();try{const {decision,action,review}=await ready(h),before=h.store.assessInvestigation(h.userId,scope);let result;for(const [index,phase] of ["T0","T1","T2"].entries())result=h.store.createOutcomeObservation(h.userId,outcomeInput(decision,action,phase,index,{raw_value:[10,6,3][index]}));result=h.store.createOutcomeComparison(h.userId,{request_id:"comparison-decrease",...scope,decision_id:decision.decision_id,management_action_id:action.management_action_id,comparison_state:"DECREASE_OBSERVED",statement:"ลดลงตามที่สังเกต",source:"AUTHENTICATED_USER",limitations:[],explicit_submission:true,expected_comparison_revision:0});assert.equal(result.outcome_review.sampling_comparability.state,"SUPPORTED");assert.equal(result.comparison.comparison_state,"DECREASE_OBSERVED");assert.deepEqual(result.outcome_review.missing_phases,[]);assert.equal(h.store.getInvestigationBundle(h.userId,scope).outcomes.length,3);assert.notEqual(result.outcome_review.step_c_reassessment.assessment_id,before.assessment_id);assert.notEqual(result.outcome_review.f1_reassessment.management_review_id,review.management_review_id);assert.equal(result.outcome_review.non_conclusions.efficacy_percentage,null);assert.equal(result.outcome_review.non_conclusions.causal_effect,null);}finally{await h.close();}});

test("golden F2-8 mismatched sampling is NOT_COMPARABLE and no conversion or normalization is invented",async()=>{const h=await setup();try{const {decision,action}=await ready(h);h.store.createOutcomeObservation(h.userId,outcomeInput(decision,action,"T0",0));const result=h.store.createOutcomeObservation(h.userId,outcomeInput(decision,action,"T1",1,{unit:"percent",denominator:"100 plants",sampling_method:"walkthrough"}));assert.equal(result.outcome_review.sampling_comparability.state,"NOT_COMPARABLE");assert.equal(result.outcome_review.sampling_comparability.conversion_applied,false);assert.equal(result.outcome_review.sampling_comparability.normalization_applied,false);}finally{await h.close();}});

test("golden F2-10 outcome correction preserves the original and reruns bounded review",async()=>{const h=await setup();try{const {decision,action}=await ready(h),first=h.store.createOutcomeObservation(h.userId,outcomeInput(decision,action,"T1",0,{raw_value:7})).observation,corrected=h.store.createOutcomeObservation(h.userId,outcomeInput(decision,action,"T1",1,{request_id:"outcome-correction",raw_value:6,supersedes_outcome_observation_id:first.outcome_observation_id})),history=h.store.decisionActionOutcomes.observationHistory(h.userId,action.management_action_id);assert.equal(history.length,2);assert.equal(history[0].raw_value,7);assert.equal(history[1].raw_value,6);assert.equal(corrected.outcome_review.correction_history.length,1);assert.equal(corrected.outcome_review.effective_observations.T1.raw_value,6);}finally{await h.close();}});

test("golden F2-9 poor outcome preserves uncertainty without resistance, dose, repeat, or MoA inference",async()=>{const h=await setup();try{const {decision,action}=await ready(h),result=h.store.createOutcomeComparison(h.userId,{request_id:"poor-outcome",...scope,decision_id:decision.decision_id,management_action_id:action.management_action_id,comparison_state:"NO_CLEAR_CHANGE",statement:"ยังเยอะเหมือนเดิม",source:"AUTHENTICATED_USER",limitations:[],explicit_submission:true,expected_comparison_revision:0}),review=result.outcome_review;assert.equal(review.follow_up_needed,true);assert.equal(review.non_conclusions.resistance,null);assert.equal(review.non_conclusions.need_for_higher_dose,null);assert.equal(review.non_conclusions.need_for_reapplication,null);assert.equal(review.non_conclusions.need_for_moa_switch,null);assert.equal(review.case_resolved,false);assert.equal(review.reminder_scheduled,false);}finally{await h.close();}});

test("golden F2-11 new evidence and F1 revision create a new Decision Snapshot without rewriting the old",async()=>{const h=await setup();try{const firstReview=h.store.assessManagementOptions(h.userId,scope),first=h.store.createHumanDecision(h.userId,decisionInput(firstReview,find(firstReview,"CULTURAL_MANAGEMENT")));h.store.createInvestigationRecord(h.userId,"OBSERVATION",{...scope,observation_id:"new-evidence-after-decision",source:"FIELD_OBSERVED",note:"new evidence"});const secondReview=h.store.assessManagementOptions(h.userId,scope),second=h.store.createHumanDecision(h.userId,decisionInput(secondReview,find(secondReview,"CULTURAL_MANAGEMENT"),"changed-decision",{expected_current_decision_id:first.decision_id,supersedes_decision_id:first.decision_id})),history=h.store.getHumanDecisionHistory(h.userId,scope);assert.notEqual(second.f1_assessment_id,first.f1_assessment_id);assert.notEqual(second.investigation_bundle_hash,first.investigation_bundle_hash);assert.equal(history[0].decision_id,first.decision_id);assert.equal(history[0].history_state,"SUPERSEDED");assert.equal(history[1].decision_id,second.decision_id);}finally{await h.close();}});

test("golden F2-12 provider failure creates no Decision, Action, or Outcome corruption and leaves F1 usable",async()=>{const provider=createTestOnlyConversationProvider(()=>{throw new Error("offline");}),h=await setup({managementProvider:rules("CONTINUE_MONITORING",{relationships:[]}),conversationProvider:provider});try{const response=await h.store.orchestrateConversationTurn(h.userId,{request_id:"provider-f2-failure",...scope,entry_point:"CASE",message:"เอาทางติดตามต่อ"});assert.equal(response.response_type,"SYSTEM_LIMITATION");assert.equal(h.store.getHumanDecisionHistory(h.userId,scope).length,0);assert.equal(h.store.getManagementActionHistory(h.userId,scope).length,0);assert.equal(h.store.db.prepare("SELECT COUNT(*) count FROM governed_outcome_observations").get().count,0);assert.equal(h.store.getCurrentManagementReview(h.userId,scope).status,"CURRENT");}finally{await h.close();}});

test("conversation provider cannot manufacture selection intent even when a UI option ID is present",async()=>{const provider=createTestOnlyConversationProvider({intent:"MANAGEMENT_SELECTION",explicit_facts:[],user_hypothesis:null}),h=await setup({conversationProvider:provider});try{const review=h.store.assessManagementOptions(h.userId,scope),selected=find(review,"CULTURAL_MANAGEMENT"),response=await h.store.orchestrateConversationTurn(h.userId,{request_id:"provider-cannot-select",...scope,entry_point:"CASE",message:"ช่วยดูข้อมูลนี้",management_option_id:selected.management_option_id});assert.equal(response.response_type,"CLARIFICATION");assert.equal(h.store.getHumanDecisionHistory(h.userId,scope).length,0);}finally{await h.close();}});

test("golden F2-13 confirmed no-action creates no treatment, task, reminder, or Case resolution",async()=>{const h=await setup({managementProvider:rules("NO_ACTION_DETERMINATION_SUPPORTED",{relationships:[]})});try{const review=h.store.assessManagementOptions(h.userId,scope),selected=find(review,"NO_ACTION_CURRENTLY_JUSTIFIED"),decision=h.store.createHumanDecision(h.userId,decisionInput(review,selected,"no-action-decision",{decision_type:"NO_ACTION_CURRENTLY"}));assert.equal(decision.decision_state,"CONFIRMED");assert.equal(decision.field_action_created,false);assert.equal(decision.reminder_created,false);assert.equal(h.store.getManagementActionHistory(h.userId,scope).length,0);assert.equal(h.store.getInvestigationBundle(h.userId,scope).cases[0].status,"OPEN");}finally{await h.close();}});

test("idempotency, optimistic concurrency, user scope, and secret-field rejection fail closed",async()=>{const h=await setup();try{const review=h.store.assessManagementOptions(h.userId,scope),selected=find(review,"CULTURAL_MANAGEMENT"),input=decisionInput(review,selected),decision=h.store.createHumanDecision(h.userId,input),replay=h.store.createHumanDecision(h.userId,input);assert.equal(replay.decision_id,decision.decision_id);assert.equal(replay.idempotent_replay,true);assert.throws(()=>h.store.createHumanDecision(h.userId,{...input,user_note:"different"}),/request_id/);assert.throws(()=>h.store.createHumanDecision(h.userId,decisionInput(review,selected,"conflict",{expected_current_decision_id:null,supersedes_decision_id:null})),/changed|supersession/);assert.throws(()=>h.store.getHumanDecisionHistory("user-b",scope),/scope|context/);assert.throws(()=>h.store.createManagementAction(h.userId,planInput(decision,"secret-plan",{action_parameters:{api_key:"not accepted"}})),/secret/);}finally{await h.close();}});

test("golden F2-2 ambiguous selection asks one question and writes no Decision or Action",async()=>{const h=await setup({managementProvider:rules("MANAGEMENT_REVIEW_JUSTIFIED")});try{const response=await h.store.orchestrateConversationTurn(h.userId,{request_id:"step-e-ambiguous",...scope,entry_point:"CASE",message:"เอาทางนี้"});assert.equal(response.response_type,"CLARIFICATION");assert.equal(response.actions.length,1);assert.equal(response.question?1:0,1);assert.equal(h.store.getHumanDecisionHistory(h.userId,scope).length,0);assert.equal(h.store.getManagementActionHistory(h.userId,scope).length,0);}finally{await h.close();}});

test("Step E requires an explicit performed time, then records action and bounded human outcome comparison",async()=>{const h=await setup();try{const review=h.store.assessManagementOptions(h.userId,scope),decision=h.store.createHumanDecision(h.userId,decisionInput(review,find(review,"CULTURAL_MANAGEMENT"))),plan=h.store.createManagementAction(h.userId,planInput(decision)),missing=await h.store.orchestrateConversationTurn(h.userId,{request_id:"step-e-action-missing",...scope,entry_point:"CASE",message:"ทำแล้ว",management_action_id:plan.management_action_id});assert.equal(missing.response_type,"CLARIFICATION");assert.equal(h.store.getManagementActionHistory(h.userId,scope).length,1);const done=await h.store.orchestrateConversationTurn(h.userId,{request_id:"step-e-action-done",...scope,entry_point:"CASE",message:"ทำแล้ว",management_action_id:plan.management_action_id,performed_at:"2026-08-28T03:00:00Z"});assert.equal(done.response_type,"ACTION_RECORDED");const actionId=done.decision_action_outcome_reference.management_action_id,outcome=await h.store.orchestrateConversationTurn(h.userId,{request_id:"step-e-outcome",...scope,entry_point:"CASE",message:"วันนี้เห็นว่าลดลง",management_action_id:actionId});assert.equal(outcome.response_type,"OUTCOME_RECORDED");assert.match(outcome.text,/ไม่สรุปประสิทธิผล/);assert.equal(outcome.actions.length,1);assert.equal(outcome.question,null);}finally{await h.close();}});

test("authenticated APIs expose governed decision/action/outcome state and reject anonymous access",async()=>{const root=await mkdtemp(join(tmpdir(),"cpmoakb-f2-api-")),dbPath=join(root,"pilot.sqlite"),exportDir=join(root,"exports"),investigationProvider=stepC(),managementProvider=rules(),seed=await new PilotStore({dbPath,exportDir,investigationRuleProvider:investigationProvider,investigationCandidateProvider:createEmptyCandidateProvider(),managementRuleProvider:managementProvider}).open();seed.putWorkspace("user-a",lifecycle());seed.createInvestigationRecord("user-a","CASE",{...scope,purpose:"F2 API"});const review=seed.assessManagementOptions("user-a",scope),selected=find(review,"CULTURAL_MANAGEMENT");seed.close();const server=await startServer({port:0,dbPath,exportDir,uploadDir:join(root,"uploads"),investigationRuleProvider:investigationProvider,investigationCandidateProvider:createEmptyCandidateProvider(),managementRuleProvider:managementProvider});try{const base=`http://127.0.0.1:${server.address().port}`,login=await fetch(`${base}/api/pilot/session`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({password:"1234",user_id:"user-a"})}),cookie=login.headers.get("set-cookie").split(";")[0],created=await fetch(`${base}/api/pilot/human-decisions`,{method:"POST",headers:{cookie,"content-type":"application/json"},body:JSON.stringify(decisionInput(review,selected))});assert.equal(created.status,201);const query=new URLSearchParams(scope);for(const endpoint of ["human-decision-history","management-action-history","decision-action-outcome-context"]){const response=await fetch(`${base}/api/pilot/${endpoint}?${query}`,{headers:{cookie}});assert.equal(response.status,200,endpoint);}assert.equal((await fetch(`${base}/api/pilot/human-decision-history?${query}`)).status,401);}finally{await new Promise((done)=>server.close(done));await rm(root,{recursive:true,force:true});}});
