import test from "node:test";
import assert from "node:assert/strict";
import { createHash } from "node:crypto";
import { mkdtemp, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { PilotStore } from "../pilot-store.mjs";
import { startServer } from "../server.mjs";
import { createEmptyCandidateProvider } from "../candidate-provider.mjs";
import { createTestOnlyConversationProvider, guardComposedResponse } from "../conversation-orchestrator.mjs";
import { GovernedSpaRuntime } from "../assets/governed-spa-runtime.js";

const scope={field_id:"field-fw01",season_id:"season-fw01"};
const users=[
  {login_id:"owner",user_id:"owner",password:"owner-secret",role:"FIELD_USER",tenant_id:"tenant-a",enabled:true},
  {login_id:"other",user_id:"other",password:"other-secret",role:"FIELD_USER",tenant_id:"tenant-a",enabled:true},
  {login_id:"reviewer",user_id:"reviewer",password:"reviewer-secret",role:"SPA",tenant_id:"tenant-a",enabled:true},
  {login_id:"coordinator",user_id:"coordinator",password:"coordinator-secret",role:"SPA",tenant_id:"tenant-a",capabilities:["REVIEW_COORDINATE"],enabled:true},
  {login_id:"foreign",user_id:"foreign",password:"foreign-secret",role:"SPA",tenant_id:"tenant-b",enabled:true},
];
const identities=users.map(({user_id,role,tenant_id,enabled,capabilities})=>({user_id,role,tenant_id,enabled,capabilities}));
function lifecycle(){return{schema_version:2,users:[{user_id:"owner",role:"FIELD_USER"}],fields:[{...scope,owner_user_id:"owner",name:"FW01 rice field",crop:"rice",planting_date:"2026-08-01",current_crop_stage:{code:"TILLERING",label:"แตกกอ",model_version:"field-stage-model/v1"},current_cmp_stage:{stage_id:"CMP-03",label:"ระยะแตกกอ",model_version:"field-stage-model/v1"},stage_provenance:"USER_CONFIRMED",created_at:"2026-09-01T00:00:00.000Z",updated_at:"2026-09-01T00:00:00.000Z"}],seasons:[{...scope,crop:"rice",status:"ACTIVE"}],guidance:[],activities:[],cases:[],observations:[],evidence:[],conversations:[],messages:[],decision_logs:[],case_summaries:[],weather_snapshots:[]};}
async function setup(options={}){const root=await mkdtemp(join(tmpdir(),"cpmoakb-fw01-")),dbPath=join(root,"pilot.sqlite"),exportDir=join(root,"exports"),uploadDir=join(root,"uploads"),store=await new PilotStore({dbPath,exportDir,pilotProfile:"FIELD_CAPTURE_ALPHA",scopedIdentities:identities,investigationCandidateProvider:createEmptyCandidateProvider(),...options}).open();store.putWorkspace("owner",lifecycle());return{root,dbPath,exportDir,uploadDir,store,close:async()=>{store.close();await rm(root,{recursive:true,force:true,maxRetries:5,retryDelay:50});}};}
async function report(store,message="ข้าวเหลืองเป็นหย่อม"){return store.orchestrateConversationTurn("owner",{request_id:`fw01-${crypto.randomUUID()}`,message,entry_point:"FIELD_INSPECTION",...scope});}
function attachmentInput(result){const bytes=Buffer.from("%PDF-1.7\nfield notes");return{field_id:scope.field_id,season_id:scope.season_id,case_id:result.context.case_id,conversation_id:result.conversation_id,original_filename:"notes.pdf",mime_type:"application/pdf",size_bytes:bytes.length,storage_reference:`attachment-${crypto.randomUUID()}.pdf`,sha256:createHash("sha256").update(bytes).digest("hex")};}

test("FW01 report stays unreviewed, one Case is reused, and Field History excludes the report",async()=>{const h=await setup();try{const first=await report(h.store),second=await report(h.store,"ตรงจุดต่ำข้าวเหลืองเป็นหย่อม"),bundle=h.store.getInvestigationBundle("owner",{...scope,case_id:first.context.case_id});assert.equal(first.context.case_id,second.context.case_id);assert.equal(bundle.cases.length,1);assert.equal(bundle.observations.length,2);assert.equal(bundle.observations[0].review_state,"UNREVIEWED");assert.equal(h.store.getFieldHistory("owner",scope).events.length,0);assert.equal(h.store.getGovernedConversationHistory("owner",first.conversation_id).turns[0].raw_message,"ข้าวเหลืองเป็นหย่อม");assert.ok(first.actions.length<=1);assert.ok(second.actions.length<=1);if(first.evidence_action)assert.equal(first.evidence_action.one_primary_action,true);}finally{await h.close();}});

test("FW01 opening Inspection resumes one existing Case and never creates a duplicate",async()=>{let created=0;const workspace={getInvestigationBundle:async()=>({cases:[{case_id:"case-existing",status:"OPEN"}]}),createInvestigationRecord:async()=>{created++;throw new Error("duplicate Case");}},runtime=new GovernedSpaRuntime({workspace});runtime.lifecycleState.fields=[{...scope}];runtime.refreshCase=async()=>runtime.caseState;const state=await runtime.startCase({...scope});assert.equal(state.scope.case_id,"case-existing");assert.equal(created,0);workspace.getInvestigationBundle=async()=>({cases:[{case_id:"case-a",status:"OPEN"},{case_id:"case-b",status:"OPEN"}]});await assert.rejects(()=>runtime.startCase({...scope}),/เลือกเคส/);assert.equal(created,0);});

test("FW01 Case grant is explicit, attachment access is scoped, and revocation removes it",async()=>{const h=await setup();try{const result=await report(h.store),caseRow=h.store.db.prepare("SELECT * FROM investigation_cases WHERE case_id=?").get(result.context.case_id),attachment=h.store.createUserAttachment("owner",attachmentInput(result));assert.equal(h.store.access.canReadCase("reviewer",caseRow),false);assert.throws(()=>h.store.getUserAttachment("reviewer",attachment.attachment_id,{reviewer:true}),/attachment not found/);const grant=h.store.access.grant("coordinator",{subject_user_id:"reviewer",scope_type:"CASE",scope_id:caseRow.case_id,capability:"CASE_REVIEW",reason:"Assigned to review this Case"});assert.equal(h.store.access.canReadCase("reviewer",caseRow),true);assert.equal(h.store.getUserAttachment("reviewer",attachment.attachment_id).attachment_id,attachment.attachment_id);h.store.access.revoke("coordinator",grant.grant_id,"Review assignment ended");assert.equal(h.store.access.canReadCase("reviewer",caseRow),false);assert.throws(()=>h.store.getUserAttachment("reviewer",attachment.attachment_id),/attachment not found/);assert.equal(h.store.db.prepare("SELECT revoked_by FROM governed_access_grants WHERE grant_id=?").get(grant.grant_id).revoked_by,"coordinator");}finally{await h.close();}});

test("FW01 operational Field grant does not confer review authority and cross-tenant grant fails",async()=>{const h=await setup();try{const result=await report(h.store),observation=h.store.getInvestigationBundle("owner",{...scope,case_id:result.context.case_id}).observations[0];h.store.access.grant("coordinator",{subject_user_id:"reviewer",scope_type:"FIELD",scope_id:scope.field_id,capability:"FIELD_OPERATE",reason:"Operational field responsibility"});assert.equal(h.store.access.visibleFields("reviewer").length,1);assert.equal(h.store.access.canReviewObservation("reviewer",observation),false);assert.throws(()=>h.store.access.grant("coordinator",{subject_user_id:"foreign",scope_type:"CASE",scope_id:result.context.case_id,capability:"CASE_REVIEW",reason:"Invalid foreign assignment"}),/cross-tenant/);}finally{await h.close();}});

test("FW01 Case reviewer cannot browse another Field's attachments",async()=>{const h=await setup();try{const first=await report(h.store),state=lifecycle(),fieldB={...state.fields[0],field_id:"field-fw01-b",season_id:"season-fw01-b",name:"Another Field"};state.fields.push(fieldB);state.seasons.push({field_id:fieldB.field_id,season_id:fieldB.season_id,crop:"rice",status:"ACTIVE"});h.store.putWorkspace("owner",state);const caseB=h.store.createInvestigationRecord("owner","CASE",{field_id:fieldB.field_id,season_id:fieldB.season_id,case_id:"case-fw01-b",purpose:"Separate Field Case"}),conversation=h.store.ensureGovernedConversation("owner",{field_id:fieldB.field_id,season_id:fieldB.season_id,case_id:caseB.case_id,entry_point:"CASE"}),second=h.store.createUserAttachment("owner",{...attachmentInput(first),field_id:fieldB.field_id,season_id:fieldB.season_id,case_id:caseB.case_id,conversation_id:conversation.conversation_id,storage_reference:`attachment-${crypto.randomUUID()}.pdf`});h.store.access.grant("coordinator",{subject_user_id:"reviewer",scope_type:"CASE",scope_id:first.context.case_id,capability:"CASE_REVIEW",reason:"Only the first Case"});assert.equal(h.store.listUserAttachments("reviewer",{case_id:caseB.case_id}).length,0);assert.throws(()=>h.store.getUserAttachment("reviewer",second.attachment_id),/attachment not found/);assert.equal(h.store.access.visibleFields("reviewer").length,0);assert.equal(h.store.access.visibleCases("reviewer").filter((item)=>item.case_id===caseB.case_id).length,0);}finally{await h.close();}});

test("FW01 explicit split/merge lineage links Cases without moving or deleting history",async()=>{const h=await setup();try{const first=await report(h.store),second=h.store.createInvestigationRecord("owner","CASE",{...scope,case_id:"case-fw01-independent",purpose:"Independent weed issue"}),before=h.store.db.prepare("SELECT COUNT(*) count FROM investigation_observations").get().count,split=h.store.access.linkCaseLineage("owner",{source_case_id:first.context.case_id,target_case_id:second.case_id,action:"SPLIT_LINK",reason:"Evidence supports a separate issue"}),merge=h.store.access.linkCaseLineage("owner",{source_case_id:second.case_id,target_case_id:first.context.case_id,action:"MERGE_LINK",reason:"Later review relates the two investigations"});assert.equal(split.records_moved,false);assert.equal(merge.source_case_preserved,true);assert.equal(h.store.access.caseLineage("owner",first.context.case_id).length,2);assert.equal(h.store.db.prepare("SELECT COUNT(*) count FROM investigation_observations").get().count,before);assert.equal(h.store.db.prepare("SELECT COUNT(*) count FROM investigation_cases").get().count,2);assert.throws(()=>h.store.access.linkCaseLineage("reviewer",{source_case_id:first.context.case_id,target_case_id:second.case_id,action:"MERGE_LINK",reason:"Unauthorized"}),/operation scope/);}finally{await h.close();}});

test("FW01 migration classifies legacy unassigned Case and review item for coordinator triage",async()=>{const h=await setup();let reopened;try{h.store.createInvestigationRecord("owner","CASE",{...scope,case_id:"case-fw01-legacy",purpose:"Legacy open Case"});const result=await report(h.store,"ไม่รู้"),caseId=result.context.case_id,signalId=result.learning_signals[0].signal_id;h.store.db.exec("DROP TABLE governed_observation_review_events; DROP TABLE governed_legacy_case_triage; DROP TABLE governed_legacy_review_triage; DROP TABLE governed_access_grants; DELETE FROM investigation_schema_migrations WHERE version=15;");h.store.db.prepare("UPDATE pilot_meta SET value='14' WHERE key='pilot_schema_version'").run();h.store.db.prepare("UPDATE pilot_meta SET value='pre-fw01' WHERE key='pilot_schema_fingerprint'").run();h.store.close();reopened=await new PilotStore({dbPath:h.dbPath,exportDir:h.exportDir,pilotProfile:"FIELD_CAPTURE_ALPHA",scopedIdentities:identities,investigationCandidateProvider:createEmptyCandidateProvider()}).open();assert.ok(reopened.access.legacyCaseTriage("coordinator").some((item)=>item.case_id===caseId));assert.ok(reopened.access.legacyTriage("coordinator").some((item)=>item.signal_id===signalId));assert.throws(()=>reopened.access.legacyTriage("reviewer"),/triage capability/);assert.equal(reopened.access.visibleSignals("reviewer").length,0);const grant=reopened.access.grant("coordinator",{subject_user_id:"reviewer",scope_type:"REVIEW_ITEM",scope_id:signalId,capability:"REVIEW_ITEM_REVIEW",reason:"Assigned from legacy triage"});assert.equal(reopened.access.visibleSignals("reviewer").includes(signalId),true);assert.equal(reopened.access.legacyTriage("coordinator").some((item)=>item.signal_id===signalId),false);assert.equal(grant.granted_by,"coordinator");}finally{reopened?.close();h.store?.close();await rm(h.root,{recursive:true,force:true,maxRetries:5,retryDelay:50});}});

test("FW01 controlled review confirms and corrects without erasing the raw report",async()=>{const h=await setup();try{const first=await report(h.store),bundle=h.store.getInvestigationBundle("owner",{...scope,case_id:first.context.case_id}),observation=bundle.observations[0],evidenceIds=bundle.evidence.filter((item)=>item.observation_id===observation.observation_id).map((item)=>item.evidence_id);assert.ok(evidenceIds.length>0);h.store.access.grant("coordinator",{subject_user_id:"reviewer",scope_type:"CASE",scope_id:first.context.case_id,capability:"CASE_REVIEW",reason:"Review observed evidence"});assert.throws(()=>h.store.access.reviewObservation("owner",{observation_id:observation.observation_id,expected_revision:1,action:"CONFIRM",evidence_ids:evidenceIds,reason:"Owner self confirmation"}),/review scope/);assert.throws(()=>h.store.access.reviewObservation("coordinator",{observation_id:observation.observation_id,expected_revision:1,action:"CONFIRM",evidence_ids:evidenceIds,reason:"Triage does not imply scientific review"}),/review scope/);const reviewed=h.store.access.reviewObservation("reviewer",{observation_id:observation.observation_id,expected_revision:1,action:"CONFIRM",evidence_ids:evidenceIds,reason:"Field evidence supports the bounded finding"});assert.equal(reviewed.new_state,"HUMAN_REVIEWED");assert.equal(h.store.getFieldHistory("owner",scope).events[0].record_id,observation.observation_id);const second=await report(h.store,"ใบเหลืองเป็นหย่อมอีกจุด"),updated=h.store.getInvestigationBundle("owner",{...scope,case_id:first.context.case_id}),next=updated.observations.find((item)=>item.observation_id!==observation.observation_id),nextIds=updated.evidence.filter((item)=>item.observation_id===next.observation_id).map((item)=>item.evidence_id),corrected=h.store.access.reviewObservation("reviewer",{observation_id:next.observation_id,expected_revision:1,action:"CORRECT",evidence_ids:nextIds,corrected_note:"ตรวจทานแล้วพบเฉพาะขอบใบซีด ไม่ใช่ใบเหลืองทั้งใบ",reason:"Human correction after evidence review"});assert.ok(corrected.corrected_observation_id);assert.equal(h.store.db.prepare("SELECT review_state FROM investigation_observations WHERE observation_id=?").get(next.observation_id).review_state,"SUPERSEDED");assert.ok(h.store.getFieldHistory("owner",scope).events.some((item)=>item.record_id===corrected.corrected_observation_id));assert.equal(h.store.getGovernedConversationHistory("owner",second.conversation_id).turns.at(-1).raw_message,"ใบเหลืองเป็นหย่อมอีกจุด");assert.equal(h.store.db.prepare("SELECT COUNT(*) count FROM governed_observation_review_events").get().count,2);}finally{await h.close();}});

test("FW01 stage report creates a conflict without changing authoritative Crop Season",async()=>{const h=await setup();try{const result=await report(h.store,"ตอนนี้ตั้งท้องแล้ว"),conflict=h.store.db.prepare("SELECT * FROM governed_context_conflicts WHERE turn_id=?").get(result.turn_id);assert.equal(conflict.dimension,"CROP_STAGE");assert.equal(conflict.reported_code,"BOOTING");assert.equal(conflict.stored_code,"TILLERING");assert.equal(conflict.status,"UNRESOLVED");assert.equal(result.response_type,"CLARIFICATION");assert.equal(h.store.db.prepare("SELECT crop_stage_json FROM stage_assessments WHERE field_id=?").get(scope.field_id).crop_stage_json.includes("TILLERING"),true);}finally{await h.close();}});

test("FW01 composer guard accepts only server-approved transition and blocks injected diagnosis",()=>{const plan={required_text:"ช่วยถ่ายภาพโคนต้นให้ชัดครับ",required_question:null};assert.equal(guardComposedResponse({transition:"โอเคครับ"},plan).text,"โอเคครับ ช่วยถ่ายภาพโคนต้นให้ชัดครับ");assert.throws(()=>guardComposedResponse({transition:"เป็นโรคไหม้แน่นอน"},plan),/unsupported wording/);assert.throws(()=>guardComposedResponse({transition:"โอเคครับ",diagnosis:"blast"},plan),/unsupported field/);});

test("FW01 provider Pass 2 changes only a safe transition and unsafe output falls back",async()=>{const proposal={intent:"SOCIAL_OR_OTHER",explicit_facts:[],user_hypothesis:null},safe=createTestOnlyConversationProvider(proposal,{transition:"โอเคครับ"}),h=await setup({conversationProvider:safe});try{const result=await report(h.store,"ขอบคุณ");assert.equal(result.composition_state,"GUARDED_PROVIDER_COMPOSITION");assert.match(result.text,/^โอเคครับ/);h.store.conversationOrchestrator.provider=createTestOnlyConversationProvider(proposal,{transition:"เป็นโรคไหม้แน่นอน"});const unsafe=await report(h.store,"ขอบคุณครับ");assert.equal(unsafe.composition_state,"DETERMINISTIC_RESPONSE_FALLBACK");assert.doesNotMatch(unsafe.text,/โรคไหม้/);}finally{await h.close();}});

test("FW01 provider outage keeps deterministic inspection but never confirms a finding",async()=>{const provider=createTestOnlyConversationProvider(()=>{throw new Error("offline");}),h=await setup({conversationProvider:provider});try{const result=await report(h.store);assert.equal(result.provider_input_state,"DETERMINISTIC_FALLBACK");assert.equal(h.store.getFieldHistory("owner",scope).events.length,0);assert.equal(h.store.db.prepare("SELECT COUNT(*) count FROM investigation_observations WHERE review_state='HUMAN_REVIEWED'").get().count,0);}finally{await h.close();}});

test("FW01 HTTP rejects generic Observation confirmation and foreign history",async()=>{const h=await setup();let server;try{const result=await report(h.store),observation=h.store.getInvestigationBundle("owner",{...scope,case_id:result.context.case_id}).observations[0];h.store.close();server=await startServer({port:0,dbPath:h.dbPath,exportDir:h.exportDir,uploadDir:h.uploadDir,pilotProfile:"FIELD_CAPTURE_ALPHA",pilotUsers:users,investigationCandidateProvider:createEmptyCandidateProvider()});const base=`http://127.0.0.1:${server.address().port}`,login=async(user)=>{const response=await fetch(`${base}/api/pilot/session`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({login_id:user.login_id,password:user.password})});return response.headers.get("set-cookie").split(";")[0];},ownerCookie=await login(users[0]),otherCookie=await login(users[1]),headers={cookie:ownerCookie,"content-type":"application/json"};const create=await fetch(`${base}/api/pilot/investigation-records`,{method:"POST",headers,body:JSON.stringify({record_type:"OBSERVATION",record:{...scope,case_id:result.context.case_id,source:"USER_CONVERSATION",note:"claimed confirmed",review_state:"HUMAN_REVIEWED"}})});assert.equal(create.status,400);const patch=await fetch(`${base}/api/pilot/investigation-records`,{method:"PATCH",headers,body:JSON.stringify({record_type:"OBSERVATION",record_id:observation.observation_id,expected_revision:1,request_id:"fw01-illegal-patch",record:{observation_id:observation.observation_id,...scope,case_id:result.context.case_id,observed_at:observation.observed_at,source:observation.source,confidence:observation.confidence,review_state:"HUMAN_REVIEWED",note:observation.note}})});assert.equal(patch.status,400);const history=await(await fetch(`${base}/api/pilot/field-history?field_id=${scope.field_id}&season_id=${scope.season_id}`,{headers:{cookie:ownerCookie}})).json();assert.equal(history.events.length,0);assert.equal((await fetch(`${base}/api/pilot/field-history?field_id=${scope.field_id}&season_id=${scope.season_id}`,{headers:{cookie:otherCookie}})).status,403);}finally{if(server)await new Promise((done)=>server.close(done));else h.store?.close();await rm(h.root,{recursive:true,force:true,maxRetries:5,retryDelay:50});}});
