import test from "node:test";
import assert from "node:assert/strict";
import { createHash } from "node:crypto";
import { mkdtemp, readFile, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { createEmptyCandidateProvider } from "../candidate-provider.mjs";
import { PILOT_SCHEMA_COMPONENTS, PILOT_SCHEMA_VERSION } from "../pilot-hardening-runtime.mjs";
import { PilotStore } from "../pilot-store.mjs";
import { startServer } from "../server.mjs";
import { USER_ATTACHMENT_MAX_BYTES, USER_ATTACHMENT_MIME_TYPES, validateAttachmentBytes, validateAttachmentFilename } from "../user-attachment.mjs";

const scope={field_id:"field-m0e2",season_id:"season-m0e2"},now="2026-09-04T00:00:00.000Z";
const users=[{login_id:"field-a",user_id:"user-a",password:"secret-a",role:"FIELD_USER",enabled:true},{login_id:"field-b",user_id:"user-b",password:"secret-b",role:"FIELD_USER",enabled:true},{login_id:"admin",user_id:"admin",password:"secret-admin",role:"ADMIN",enabled:true}];
const [app,css,adapter,serverSource]=await Promise.all([readFile(new URL("../assets/field-app.js",import.meta.url),"utf8"),readFile(new URL("../assets/field-shell.css",import.meta.url),"utf8"),readFile(new URL("../assets/server-workspace-adapter.js",import.meta.url),"utf8"),readFile(new URL("../server.mjs",import.meta.url),"utf8")]);

function lifecycle(userId="user-a"){return{schema_version:2,users:[{user_id:userId,role:"FIELD_USER"}],fields:[{...scope,owner_user_id:userId,name:"นา M0E.2",crop:"rice",planting_date:"2026-07-01",variety:"ข้าวหอม",polygon:{type:"Polygon",coordinates:[[[100.5,13.75],[100.51,13.75],[100.505,13.76],[100.5,13.75]]]},area:{rai:1,hectares:.16},current_crop_stage:{code:"TILLERING",label:"แตกกอ",model_version:"field-stage-model/v1"},current_cmp_stage:{stage_id:"CMP-03",label:"ระยะแตกกอ",model_version:"field-stage-model/v1"},stage_provenance:"USER_CONFIRMED",created_at:now,updated_at:now}],seasons:[{...scope,crop:"rice",status:"ACTIVE"}],guidance:[],activities:[],cases:[],observations:[],evidence:[],conversations:[],messages:[],decision_logs:[],case_summaries:[],weather_snapshots:[]};}
async function harness(){const root=await mkdtemp(join(tmpdir(),"cpmoakb-m0e2-")),dbPath=join(root,"pilot.sqlite"),exportDir=join(root,"exports"),uploadDir=join(root,"uploads"),store=await new PilotStore({dbPath,exportDir,pilotProfile:"FIELD_CAPTURE_ALPHA",scopedIdentities:users.map(({user_id,role,enabled})=>({user_id,role,enabled,tenant_id:"single-pilot"})),investigationCandidateProvider:createEmptyCandidateProvider()}).open();store.putWorkspace("user-a",lifecycle());return{root,dbPath,exportDir,uploadDir,store,close:async()=>{store.close();await rm(root,{recursive:true,force:true,maxRetries:5,retryDelay:50});}};}
async function context(store,message="ทดสอบส่งข้อความ"){const caseId=`case-${crypto.randomUUID()}`;store.createInvestigationRecord("user-a","CASE",{...scope,case_id:caseId,purpose:"M0E.2 shared field case"});const conversation=store.ensureGovernedConversation("user-a",{...scope,case_id:caseId,entry_point:"CASE"}),result=await store.orchestrateConversationTurn("user-a",{request_id:`request-${crypto.randomUUID()}`,message,entry_point:"CASE",...scope,case_id:caseId,conversation_id:conversation.conversation_id});return{...result.context,conversation_id:result.conversation_id,result};}
function attachmentInput(ctx,overrides={}){const bytes=overrides.bytes??Buffer.from("%PDF-1.7\nfield report");return{...ctx,original_filename:"report.pdf",mime_type:"application/pdf",size_bytes:bytes.length,storage_reference:`attachment-${crypto.randomUUID()}.pdf`,sha256:createHash("sha256").update(bytes).digest("hex"),...overrides};}
function matches(name,pattern){test(name,()=>assert.match(app,pattern));}

matches("M0E.2 01 Home remains reachable in capture profile",/\[\"home\", \"⌂\", \"หน้าหลัก\"\]/);
matches("M0E.2 02 Field navigation remains reachable",/\[\"fields\", \"▦\", \"แปลง\"\]/);
matches("M0E.2 03 Chat remains reachable",/\[\"free-chat\", \"▢\", \"แชท\"\]/);
matches("M0E.2 04 Knowledge remains reachable",/\[\"learn\", \"▤\", \"เรียนรู้\"\]/);
matches("M0E.2 05 Profile remains reachable",/\[\"profile\", \"♙\", \"โปรไฟล์\"\]/);
matches("M0E.2 06 SPA Learning Inbox remains role-gated",/isReviewAdministrator\(\).*learning-inbox/);
matches("M0E.2 07 brand returns to Home",/const destination="home"/);
matches("M0E.2 08 opening a Field returns Field Detail",/caseAttachments=\[\];route = "field-detail"/);
matches("M0E.2 09 Inspection is a first-class route",/route === "inspection"\) renderInspection/);
matches("M0E.2 10 Timeline is a first-class route",/route === "history"\) renderHistory/);
matches("M0E.2 11 capture boot no longer starts at Fields",/route=currentUser\(\)\?"home":"login"/);
matches("M0E.2 12 Inspection resumes the Field conversation",/startInspection[\s\S]*await resumeFieldConversation\(\)/);
matches("M0E.2 13 Inspection ensures authoritative shared context",/ensureAuthoritativeChatContext\(field,"INSPECTION"\)/);
matches("M0E.2 14 Chat and Inspection use one caseState",/governedRuntime\.caseState\.scope\.case_id/);
matches("M0E.2 15 camera is explicit",/📷 ถ่ายภาพ/);
matches("M0E.2 16 camera requests environment capture",/capture="environment" data-\$\{surface\}-camera/);
matches("M0E.2 17 image chooser is separate",/🖼 เลือกรูป/);
matches("M0E.2 18 image chooser has no forced capture",/accept="image\/\*" data-\$\{surface\}-photo/);
matches("M0E.2 19 file attachment is explicit",/📎 แนบไฟล์/);
matches("M0E.2 20 Chat exposes attachment input",/data-chat-attachment/);
matches("M0E.2 21 Inspection exposes attachment input",/data-inspection-attachment/);
matches("M0E.2 22 selected state is visible",/เลือกไฟล์แล้ว/);
matches("M0E.2 23 uploading state is visible",/กำลังอัปโหลด…/);
matches("M0E.2 24 attached state is visible",/แนบไฟล์แล้ว/);
matches("M0E.2 25 failed, retry, and remove states are visible",/อัปโหลดไม่สำเร็จ[\s\S]*ลองใหม่[\s\S]*ลบไฟล์/);
matches("M0E.2 26 file-first resolves authoritative context",/ensureAuthoritativeChatContext\(field,"ATTACHMENT"\)/);
test("M0E.2 27 attachment adapter sends Case and Conversation",()=>assert.match(adapter,/case_id:context\.case_id,conversation_id:context\.conversation_id/));
matches("M0E.2 28 Timeline labels attachment and image provenance factually",/label:"ภาพดิบ\/หลักฐานภาพ"[\s\S]*label:"ไฟล์แนบ"/);
matches("M0E.2 29 Field History explicitly rejects causal inference",/ไม่ใช่ข้อสรุปสาเหตุหรือประสิทธิผล/);
matches("M0E.2 30 capture summary uses natural unavailable state",/ยังไม่เสนอแนวทางจัดการ/);
matches("M0E.2 31 capture summary hides internal authority controls",/if\(governedRuntime\.captureOnly\(\)\).*return;/s);
matches("M0E.2 32 attachment card states its authority boundary",/ยังไม่ใช่หลักฐานทางวิทยาศาสตร์หรือคำแนะนำ/);
matches("M0E.2 33 Learning Inbox hierarchy remains present",/รายการใหม่[\s\S]*รอตรวจ[\s\S]*ขอข้อมูลเพิ่ม[\s\S]*ตรวจแล้ว[\s\S]*ปฏิเสธ[\s\S]*Learning Candidates/);
matches("M0E.2 34 Field user Learning Inbox remains guarded",/if\(!isReviewAdministrator\(\)\)\{route="fields"/);
test("M0E.2 35 supported MIME contract is exact",()=>assert.deepEqual(Object.keys(USER_ATTACHMENT_MIME_TYPES).sort(),["application/pdf","application/vnd.openxmlformats-officedocument.spreadsheetml.sheet","application/vnd.openxmlformats-officedocument.wordprocessingml.document","image/jpeg","image/png","image/webp","text/csv","text/plain"].sort()));
test("M0E.2 36 size limit is 10 MB",()=>assert.equal(USER_ATTACHMENT_MAX_BYTES,10*1024*1024));
test("M0E.2 37 path traversal filenames are rejected",()=>assert.throws(()=>validateAttachmentFilename("../secret.txt"),/invalid attachment filename/));
test("M0E.2 38 executable MIME is rejected",()=>assert.throws(()=>validateAttachmentBytes(Buffer.from("MZ executable"),"application/x-msdownload","tool.exe"),/unsupported attachment type/));
test("M0E.2 39 mismatched content signature is rejected",()=>assert.throws(()=>validateAttachmentBytes(Buffer.from("not a pdf"),"application/pdf","report.pdf"),/does not match/));
test("M0E.2 40 valid PDF signature is accepted",()=>assert.equal(validateAttachmentBytes(Buffer.from("%PDF-1.7\nreport"),"application/pdf","report.pdf"),"pdf"));
test("M0E.2 41 valid PNG signature is accepted",()=>assert.equal(validateAttachmentBytes(Buffer.from([0x89,0x50,0x4e,0x47,1]),"image/png","plot.png"),"png"));
test("M0E.2 42 server uses a random trusted storage key",()=>assert.match(serverSource,/storageReference=`attachment-\$\{randomUUID\(\)\}/));
test("M0E.2 43 storage directory is not a public filename path",()=>assert.doesNotMatch(serverSource,/resolve\(uploadDir,payload\.original_filename\)/));

test("M0E.2 44 governed attachment persists complete metadata",async()=>{const h=await harness();try{const ctx=await context(h.store),item=h.store.createUserAttachment("user-a",attachmentInput(ctx));assert.equal(item.source_type,"USER_ATTACHMENT");assert.equal(item.review_state,"UNREVIEWED");assert.equal(item.owner_user_id,"user-a");assert.equal(item.case_id,ctx.case_id);assert.equal(item.conversation_id,ctx.conversation_id);assert.match(item.sha256,/^[a-f0-9]{64}$/);}finally{await h.close();}});
test("M0E.2 45 attachment is never promoted to evidence or authority",async()=>{const h=await harness();try{const item=h.store.createUserAttachment("user-a",attachmentInput(await context(h.store)));assert.deepEqual(item.authority_boundary,{is_visual_evidence:false,is_scientific_source:false,is_canonical_knowledge:false,is_diagnosis:false,is_recommendation:false,automatic_ingestion:false});}finally{await h.close();}});
test("M0E.2 46 owner isolation rejects foreign attachment access",async()=>{const h=await harness();try{const item=h.store.createUserAttachment("user-a",attachmentInput(await context(h.store)));assert.throws(()=>h.store.getUserAttachment("user-b",item.attachment_id),/attachment not found/);}finally{await h.close();}});
test("M0E.2 47 Admin policy can inspect metadata but reviewer flag cannot bypass scope",async()=>{const h=await harness();try{const item=h.store.createUserAttachment("user-a",attachmentInput(await context(h.store)));assert.equal(h.store.getUserAttachment("admin",item.attachment_id).attachment_id,item.attachment_id);assert.throws(()=>h.store.getUserAttachment("user-b",item.attachment_id,{reviewer:true}),/attachment not found/);}finally{await h.close();}});
test("M0E.2 48 foreign Case or Conversation scope is rejected",async()=>{const h=await harness();try{const ctx=await context(h.store);assert.throws(()=>h.store.createUserAttachment("user-a",attachmentInput({...ctx,case_id:"foreign-case"})),/context not found/);}finally{await h.close();}});
test("M0E.2 49 attachment survives restart",async()=>{const h=await harness();let reopened;try{const item=h.store.createUserAttachment("user-a",attachmentInput(await context(h.store)));h.store.close();reopened=await new PilotStore({dbPath:h.dbPath,exportDir:h.exportDir,pilotProfile:"FIELD_CAPTURE_ALPHA",investigationCandidateProvider:createEmptyCandidateProvider()}).open();assert.equal(reopened.getUserAttachment("user-a",item.attachment_id).original_filename,"report.pdf");reopened.close();reopened=null;}finally{reopened?.close();h.store?.close();await rm(h.root,{recursive:true,force:true,maxRetries:5,retryDelay:50});}});
test("M0E.2 50 scoped Admin learning review detail retains attachment context",async()=>{const h=await harness();try{const ctx=await context(h.store,"ทดสอบส่งข้อความ"),signal=ctx.result.learning_signals[0];assert.ok(signal);h.store.createUserAttachment("user-a",attachmentInput(ctx));const detail=h.store.getLearningReviewDetail(signal.signal_id,"admin");assert.equal(detail.current_case_context.attachments.length,1);assert.equal(detail.current_case_context.attachments[0].conversation_id,ctx.conversation_id);}finally{await h.close();}});
test("M0E.2 51 one idempotent turn creates no duplicate Learning Signal",async()=>{const h=await harness();try{const input={request_id:"m0e2-stable",message:"ทดสอบส่งข้อความ",entry_point:"CASE",...scope},first=await h.store.orchestrateConversationTurn("user-a",input),again=await h.store.orchestrateConversationTurn("user-a",input);assert.equal(again.idempotent_replay,true);assert.equal(h.store.getGovernedConversationHistory("user-a",first.conversation_id).turns.length,1);assert.equal(h.store.getLearningSignals("user-a").filter((item)=>item.turn_id===first.turn_id).length,first.learning_signals.length);}finally{await h.close();}});
test("M0E.2 52 schema migration retains attachments",()=>{assert.equal(PILOT_SCHEMA_VERSION,16);assert.ok(PILOT_SCHEMA_COMPONENTS.includes("governed_user_attachments"));});
test("M0E.2 53 server rejects unauthenticated attachment access",async()=>{const h=await harness();h.store.close();const server=await startServer({port:0,dbPath:h.dbPath,exportDir:h.exportDir,uploadDir:h.uploadDir,pilotProfile:"FIELD_CAPTURE_ALPHA",pilotUsers:users,investigationCandidateProvider:createEmptyCandidateProvider()});try{const base=`http://127.0.0.1:${server.address().port}`,response=await fetch(`${base}/api/pilot/attachments`);assert.equal(response.status,401);}finally{await new Promise((done)=>server.close(done));await rm(h.root,{recursive:true,force:true,maxRetries:5,retryDelay:50});}});
test("M0E.2 54 Field user cannot access admin review",async()=>{const h=await harness();h.store.close();const server=await startServer({port:0,dbPath:h.dbPath,exportDir:h.exportDir,uploadDir:h.uploadDir,pilotProfile:"FIELD_CAPTURE_ALPHA",pilotUsers:users,investigationCandidateProvider:createEmptyCandidateProvider()});try{const base=`http://127.0.0.1:${server.address().port}`,login=await fetch(`${base}/api/pilot/session`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({login_id:"field-a",password:"secret-a"})}),cookie=login.headers.get("set-cookie").split(";")[0],response=await fetch(`${base}/api/pilot/admin/learning-review/dashboard`,{headers:{cookie}});assert.equal(response.status,403);}finally{await new Promise((done)=>server.close(done));await rm(h.root,{recursive:true,force:true,maxRetries:5,retryDelay:50});}});
test("M0E.2 55 attachment API validates declared content server-side",()=>{assert.match(serverSource,/validateAttachmentBytes\(bytes,payload\.mime_type,filename\)/);assert.match(adapter,/uploadUserAttachment/);assert.match(css,/\.multimodal-controls/);});
test("M0E.2 56 authenticated file-first HTTP flow stores, lists, downloads, and isolates",async()=>{const h=await harness(),ctx=await context(h.store);h.store.close();const server=await startServer({port:0,dbPath:h.dbPath,exportDir:h.exportDir,uploadDir:h.uploadDir,pilotProfile:"FIELD_CAPTURE_ALPHA",pilotUsers:users,investigationCandidateProvider:createEmptyCandidateProvider()});try{const base=`http://127.0.0.1:${server.address().port}`,signIn=async(login_id,password)=>{const response=await fetch(`${base}/api/pilot/session`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({login_id,password})});return response.headers.get("set-cookie").split(";")[0];},ownerCookie=await signIn("field-a","secret-a"),foreignCookie=await signIn("field-b","secret-b"),bytes=Buffer.from("%PDF-1.7\nfield report"),created=await fetch(`${base}/api/pilot/attachments`,{method:"POST",headers:{cookie:ownerCookie,"content-type":"application/json"},body:JSON.stringify({field_id:ctx.field_id,season_id:ctx.season_id,case_id:ctx.case_id,conversation_id:ctx.conversation_id,original_filename:"field-report.pdf",mime_type:"application/pdf",size_bytes:bytes.length,content_base64:bytes.toString("base64")})}),body=await created.json();assert.equal(created.status,201);assert.equal(body.attachment.original_filename,"field-report.pdf");assert.notEqual(body.attachment.storage_reference,"field-report.pdf");const listed=await fetch(`${base}/api/pilot/attachments?case_id=${ctx.case_id}`,{headers:{cookie:ownerCookie}}),listBody=await listed.json();assert.equal(listBody.attachments.length,1);const downloaded=await fetch(`${base}/api/pilot/attachment-content?attachment_id=${body.attachment.attachment_id}`,{headers:{cookie:ownerCookie}});assert.equal(downloaded.status,200);assert.deepEqual(Buffer.from(await downloaded.arrayBuffer()),bytes);const foreign=await fetch(`${base}/api/pilot/attachment?attachment_id=${body.attachment.attachment_id}`,{headers:{cookie:foreignCookie}});assert.equal(foreign.status,404);}finally{await new Promise((done)=>server.close(done));await rm(h.root,{recursive:true,force:true,maxRetries:5,retryDelay:50});}});
test("M0E.2 57 reviewer UI receives bounded attachment drill-down",()=>{assert.match(app,/ดูบริบทไฟล์/);assert.match(app,/USER_ATTACHMENT · รอการทบทวน/);});
test("M0E.2 58 valid DOCX container is accepted",()=>assert.equal(validateAttachmentBytes(Buffer.from([0x50,0x4b,3,4]),"application/vnd.openxmlformats-officedocument.wordprocessingml.document","notes.docx"),"docx"));
test("M0E.2 59 valid XLSX container is accepted",()=>assert.equal(validateAttachmentBytes(Buffer.from([0x50,0x4b,3,4]),"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet","counts.xlsx"),"xlsx"));
test("M0E.2 60 valid CSV text is accepted",()=>assert.equal(validateAttachmentBytes(Buffer.from("plot,count\nA,4"),"text/csv","counts.csv"),"csv"));
test("M0E.2 61 valid TXT text is accepted",()=>assert.equal(validateAttachmentBytes(Buffer.from("field note"),"text/plain","note.txt"),"txt"));
test("M0E.2 62 oversized file is rejected without touching Case",()=>assert.throws(()=>validateAttachmentBytes(Buffer.alloc(USER_ATTACHMENT_MAX_BYTES+1),"text/plain","large.txt"),/10 MB/));
test("M0E.2 63 investigation UI allows bounded cannot-answer and defer wording",()=>{assert.match(app,/ไม่รู้/);assert.match(app,/ไว้ดูทีหลัง/);assert.match(app,/ถามเพิ่มไม่เกินหนึ่งคำถามต่อรอบ/);});
test("M0E.2 64 Inspection activity generates the same governed Learning flow",async()=>{const h=await harness();try{const ctx=await context(h.store,"พ่นแล้วแมลงยังเยอะ");assert.ok(ctx.result.learning_signals.some((item)=>item.signal_class==="FAILED_CONTROL_REPORT_CANDIDATE"));assert.equal(h.store.getLearningReviewDashboard({case_id:ctx.case_id}).summary.total,ctx.result.learning_signals.length);}finally{await h.close();}});
test("M0E.2 65 capture profile keeps management and advanced authority unavailable",()=>{assert.match(app,/ยังไม่เสนอแนวทางจัดการ/);assert.match(app,/if\(!governedRuntime\.featureEnabled\("f1_management_review"\)\)/);assert.match(app,/if\(!governedRuntime\.featureEnabled\("step_h_local_pattern"\)\)/);assert.match(app,/if\(!governedRuntime\.featureEnabled\("step_i_learning"\)\)/);});
test("M0E.2 66 bottom-nav Chat reconstructs server state before rendering",()=>assert.match(app,/next==="free-chat"&&selectedField\(\).*resumeFieldConversation\(\).*refreshCaseAttachments\(\)/));
