import test from "node:test";
import assert from "node:assert/strict";
import { mkdtemp, readFile, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { PilotStore } from "../pilot-store.mjs";
import { createEmptyCandidateProvider } from "../candidate-provider.mjs";

const users=[
  {user_id:"owner-p2a",role:"FIELD_USER",tenant_id:"tenant-a",enabled:true},
  {user_id:"spa-p2a",role:"SPA",tenant_id:"tenant-a",enabled:true},
  {user_id:"coordinator-p2a",role:"SPA",tenant_id:"tenant-a",capabilities:["REVIEW_COORDINATE"],enabled:true},
  {user_id:"foreign-p2a",role:"SPA",tenant_id:"tenant-b",enabled:true},
];
const field={field_id:"field-p2a",season_id:"season-p2a",owner_user_id:"owner-p2a",name:"P2A rice field",crop:"rice",planting_date:"2026-08-01",current_crop_stage:{code:"TILLERING",label:"แตกกอ"},current_cmp_stage:{stage_id:"CMP-03",label:"ระยะแตกกอ"},created_at:"2026-09-01T00:00:00.000Z",updated_at:"2026-09-01T00:00:00.000Z"};
function lifecycle(){return{schema_version:2,users:[{user_id:field.owner_user_id,role:"FIELD_USER"}],fields:[field],seasons:[{field_id:field.field_id,season_id:field.season_id,crop:"rice",status:"ACTIVE"}],guidance:[],activities:[],cases:[],observations:[],evidence:[],conversations:[],messages:[],decision_logs:[],case_summaries:[],weather_snapshots:[]};}
async function fixture(){const root=await mkdtemp(join(tmpdir(),"cpmoakb-p2a-")),store=await new PilotStore({dbPath:join(root,"pilot.sqlite"),exportDir:join(root,"exports"),scopedIdentities:users,investigationCandidateProvider:createEmptyCandidateProvider()}).open();store.putWorkspace(field.owner_user_id,lifecycle());const caseItem=store.createInvestigationRecord(field.owner_user_id,"CASE",{field_id:field.field_id,season_id:field.season_id,case_id:"case-p2a",purpose:"P2A open work"});return{root,store,caseItem,close:async()=>{store.close();await rm(root,{recursive:true,force:true,maxRetries:5,retryDelay:50});}};}
const grant=(h,input)=>h.store.access.grant("coordinator-p2a",{subject_user_id:"spa-p2a",reason:"P2A bounded assignment",...input});

test("FW01P2A focused scope presentation scenarios",async(t)=>{
  await t.test("1 SPA role without review grant has no Inbox capability",async()=>{const h=await fixture();try{const summary=h.store.access.accessSummary("spa-p2a"),source=await readFile(new URL("../assets/field-app.js",import.meta.url),"utf8");assert.equal(summary.permissions.can_view_review_inbox,false);assert.doesNotMatch(source,/role\s*===?\s*["']SPA["'].*learning-inbox/);for(const marker of ["canViewReviewInbox","บัญชีนี้ยังไม่มีงานหรือสิทธิ์สำหรับการทบทวน","ไม่มีงานที่ต้องทบทวนในขณะนี้","ยังโหลดรายการทบทวนไม่ได้"])assert.match(source,new RegExp(marker));}finally{await h.close();}});
  await t.test("2 REVIEW_ITEM assigned SPA has Inbox capability",async()=>{const h=await fixture();try{const result=await h.store.orchestrateConversationTurn(field.owner_user_id,{request_id:"p2a-review-item",field_id:field.field_id,season_id:field.season_id,case_id:h.caseItem.case_id,entry_point:"CASE",message:"ไม่รู้"}),signal=result.learning_signals[0];grant(h,{scope_type:"REVIEW_ITEM",scope_id:signal.signal_id,capability:"REVIEW_ITEM_REVIEW"});assert.equal(h.store.access.accessSummary("spa-p2a").permissions.can_view_review_inbox,true);assert.deepEqual(h.store.access.visibleSignals("spa-p2a"),[signal.signal_id]);}finally{await h.close();}});
  await t.test("3 revoked review grant removes Inbox capability",async()=>{const h=await fixture();try{const item=await h.store.orchestrateConversationTurn(field.owner_user_id,{request_id:"p2a-revoke-review",field_id:field.field_id,season_id:field.season_id,case_id:h.caseItem.case_id,entry_point:"CASE",message:"ไม่รู้"}),g=grant(h,{scope_type:"REVIEW_ITEM",scope_id:item.learning_signals[0].signal_id,capability:"REVIEW_ITEM_REVIEW"});h.store.access.revoke("coordinator-p2a",g.grant_id,"review completed");assert.equal(h.store.access.accessSummary("spa-p2a").permissions.can_view_review_inbox,false);assert.deepEqual(h.store.access.visibleSignals("spa-p2a"),[]);}finally{await h.close();}});
  await t.test("4 coordinator Inbox is available from projected authority",async()=>{const h=await fixture();try{const summary=h.store.access.accessSummary("coordinator-p2a");assert.equal(summary.permissions.can_view_review_inbox,true);assert.equal(summary.permissions.can_coordinate_review,true);}finally{await h.close();}});
  await t.test("5 cross-tenant review work remains invisible",async()=>{const h=await fixture();try{const result=await h.store.orchestrateConversationTurn(field.owner_user_id,{request_id:"p2a-tenant",field_id:field.field_id,season_id:field.season_id,case_id:h.caseItem.case_id,entry_point:"CASE",message:"ไม่รู้"});assert.equal(h.store.access.canReviewSignal("foreign-p2a",h.store.learningReview.signal(result.learning_signals[0].signal_id)),false);assert.deepEqual(h.store.access.visibleSignals("foreign-p2a"),[]);}finally{await h.close();}});
  await t.test("6 Home owner sees owned work",async()=>{const h=await fixture();try{const home=h.store.access.operationalHome(field.owner_user_id);assert.equal(home.cards.fields.owned_count,1);assert.equal(home.cards.cases.open_count,1);assert.equal(home.cards.continue_work.target.case_id,h.caseItem.case_id);}finally{await h.close();}});
  await t.test("7 assigned SPA sees assigned Field and Case work",async()=>{const h=await fixture();try{grant(h,{scope_type:"FIELD",scope_id:field.field_id,capability:"FIELD_OPERATE"});const home=h.store.access.operationalHome("spa-p2a");assert.equal(home.cards.fields.assigned_count,1);assert.equal(home.cards.cases.assigned_count,1);}finally{await h.close();}});
  await t.test("8 Case-only grant appears as Case work and not Field work",async()=>{const h=await fixture();try{grant(h,{scope_type:"CASE",scope_id:h.caseItem.case_id,capability:"CASE_OPERATE"});const home=h.store.access.operationalHome("spa-p2a");assert.equal(home.cards.fields.assigned_count,0);assert.equal(home.cards.cases.assigned_count,1);}finally{await h.close();}});
  await t.test("9 Home review card appears only for authorized users",async()=>{const h=await fixture();try{assert.equal("review_work" in h.store.access.operationalHome("spa-p2a").cards,false);grant(h,{scope_type:"CASE",scope_id:h.caseItem.case_id,capability:"CASE_REVIEW"});assert.equal(h.store.access.operationalHome("spa-p2a").cards.review_work.status,"AVAILABLE");}finally{await h.close();}});
  await t.test("10 revoked object disappears from Home",async()=>{const h=await fixture();try{const g=grant(h,{scope_type:"FIELD",scope_id:field.field_id,capability:"FIELD_OPERATE"});assert.equal(h.store.access.operationalHome("spa-p2a").cards.fields.assigned_count,1);h.store.access.revoke("coordinator-p2a",g.grant_id,"assignment ended");assert.equal(h.store.access.operationalHome("spa-p2a").cards.fields.assigned_count,0);assert.equal(h.store.access.operationalHome("spa-p2a").cards.cases.open_count,0);}finally{await h.close();}});
  await t.test("11 stale Home target is denied when reopened after revocation",async()=>{const h=await fixture();try{const g=grant(h,{scope_type:"CASE",scope_id:h.caseItem.case_id,capability:"CASE_OPERATE"}),stale=h.store.access.operationalHome("spa-p2a").cards.continue_work.target;h.store.access.revoke("coordinator-p2a",g.grant_id,"assignment ended");const row=h.store.db.prepare("SELECT * FROM investigation_cases WHERE case_id=?").get(stale.case_id);assert.equal(h.store.access.canReadCase("spa-p2a",row),false);}finally{await h.close();}});
  await t.test("12 partial Home failure degrades one card without corrupting others",async()=>{const h=await fixture();try{const home=h.store.access.operationalHome(field.owner_user_id,{loadFields:()=>{throw new Error("field source unavailable");}});assert.equal(home.cards.fields.status,"UNAVAILABLE");assert.equal(home.cards.cases.status,"AVAILABLE");assert.equal(home.cards.cases.items[0].case_id,h.caseItem.case_id);assert.ok(!JSON.stringify(home).includes("foreign-p2a"));}finally{await h.close();}});
  await t.test("13 Profile projection has no access mutation surface",async()=>{const h=await fixture();try{const summary=h.store.access.accessSummary("spa-p2a");for(const key of ["grant","revoke","grant_id","subject_user_id","granted_by"])assert.equal(Object.hasOwn(summary,key),false,key);}finally{await h.close();}});
  await t.test("14 Profile projection reflects revocation on reload",async()=>{const h=await fixture();try{const g=grant(h,{scope_type:"CASE",scope_id:h.caseItem.case_id,capability:"CASE_OPERATE"});assert.equal(h.store.access.accessSummary("spa-p2a").counts.assigned_case_count,1);h.store.access.revoke("coordinator-p2a",g.grant_id,"assignment ended");assert.equal(h.store.access.accessSummary("spa-p2a").counts.assigned_case_count,0);}finally{await h.close();}});
  await t.test("15 tenant and capability display contains no secrets or raw grants",async()=>{const h=await fixture();try{grant(h,{scope_type:"CASE",scope_id:h.caseItem.case_id,capability:"CASE_OPERATE"});const text=JSON.stringify(h.store.access.accessSummary("spa-p2a"));assert.match(text,/tenant-a/);assert.match(text,/ASSIGNED_CASE_WORK/);assert.doesNotMatch(text,/password|secret|token|grant_id|subject_user_id|granted_by|revoke_reason/i);}finally{await h.close();}});
});
