import test from "node:test";
import assert from "node:assert/strict";
import { mkdtemp, readFile, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { PilotStore } from "../pilot-store.mjs";
import { createEmptyCandidateProvider } from "../candidate-provider.mjs";
import { createTestOnlyConversationProvider, guardComposedResponse } from "../conversation-orchestrator.mjs";

const users=[
  {login_id:"owner",user_id:"owner-p2b",password:"owner-secret",display_name:"Owner",role:"FIELD_USER",tenant_id:"tenant-a",enabled:true},
  {login_id:"spa",user_id:"spa-p2b",password:"spa-secret",display_name:"SPA",role:"SPA",tenant_id:"tenant-a",enabled:true},
  {login_id:"coordinator",user_id:"coordinator-p2b",password:"coordinator-secret",display_name:"Coordinator",role:"SPA",tenant_id:"tenant-a",capabilities:["REVIEW_COORDINATE"],enabled:true},
  {login_id:"foreign",user_id:"foreign-p2b",password:"foreign-secret",display_name:"Foreign",role:"SPA",tenant_id:"tenant-b",enabled:true},
  {login_id:"empty",user_id:"empty-p2b",password:"empty-secret",display_name:"Empty",role:"FIELD_USER",tenant_id:"tenant-a",enabled:true},
];
const fieldOne={field_id:"field-p2b-one",season_id:"season-p2b-one",owner_user_id:"owner-p2b",name:"Field One",crop:"rice",planting_date:"2026-01-01",current_crop_stage:{code:"TILLERING",label:"แตกกอ"},current_cmp_stage:{stage_id:"CMP-03",label:"ระยะแตกกอ"},stage_provenance:"USER_CONFIRMED",created_at:"2026-01-01T00:00:00Z",updated_at:"2026-01-01T00:00:00Z"};
const fieldTwo={...fieldOne,field_id:"field-p2b-two",season_id:"season-p2b-two",name:"Field Two"};
const foreignField={...fieldOne,field_id:"field-p2b-foreign",season_id:"season-p2b-foreign",owner_user_id:"foreign-p2b",name:"Foreign Field"};
function state(owner,fields){return{schema_version:2,users:[{user_id:owner,role:"FIELD_USER"}],fields,seasons:fields.map((field)=>({field_id:field.field_id,season_id:field.season_id,crop:"rice",planting_date:field.planting_date,status:"ACTIVE",created_at:field.created_at,updated_at:field.updated_at})),guidance:[],activities:[],cases:[],observations:[],evidence:[],conversations:[],messages:[],decision_logs:[],case_summaries:[],weather_snapshots:[]};}
async function fixture({twoFields=true,provider=null}={}){const root=await mkdtemp(join(tmpdir(),"cpmoakb-p2b-")),dbPath=join(root,"pilot.sqlite"),store=await new PilotStore({dbPath,exportDir:join(root,"exports"),scopedIdentities:users,investigationCandidateProvider:createEmptyCandidateProvider(),...(provider?{conversationProvider:provider}:{})}).open();store.putWorkspace("owner-p2b",state("owner-p2b",twoFields?[fieldOne,fieldTwo]:[fieldOne]));store.putWorkspace("foreign-p2b",state("foreign-p2b",[foreignField]));const oldCase=store.createInvestigationRecord("owner-p2b","CASE",{field_id:fieldOne.field_id,season_id:fieldOne.season_id,case_id:"case-p2b-one",purpose:"P2B case"});const next=store.transitionCropSeason("owner-p2b",{field_id:fieldOne.field_id,expected_current_season_id:fieldOne.season_id,crop:"rice",variety:"new",planting_method:"DIRECT_SEEDING",planting_date:"2026-08-01"});return{root,dbPath,store,oldCase,currentSeason:next.season.season_id,close:async()=>{store.close();await rm(root,{recursive:true,force:true,maxRetries:5,retryDelay:50});}};}
const grant=(h,input)=>h.store.access.grant("coordinator-p2b",{subject_user_id:"spa-p2b",reason:"P2B governed assignment",...input});

test("FW01P2B thirty adversarial product-surface scenarios",async(t)=>{
  await t.test("1 Season 1 historical and Season 2 current are selectable",async()=>{const h=await fixture();try{const p=h.store.access.cropSeasons("owner-p2b",fieldOne.field_id);assert.equal(p.seasons.length,2);assert.equal(p.seasons.find((x)=>x.season_id===fieldOne.season_id).status,"COMPLETED");assert.equal(p.seasons.find((x)=>x.season_id===h.currentSeason).current,true);}finally{await h.close();}});
  await t.test("2 viewing Season 1 does not modify current pointer",async()=>{const h=await fixture();try{const before=h.store.db.prepare("SELECT season_id FROM lifecycle_fields WHERE field_id=?").get(fieldOne.field_id).season_id;h.store.access.fieldHistory("owner-p2b",fieldOne.field_id,fieldOne.season_id,(owner,scope)=>h.store.getFieldHistory(owner,scope));assert.equal(h.store.db.prepare("SELECT season_id FROM lifecycle_fields WHERE field_id=?").get(fieldOne.field_id).season_id,before);}finally{await h.close();}});
  await t.test("3 restart preserves both seasons",async()=>{const h=await fixture();let reopened;try{h.store.close();reopened=await new PilotStore({dbPath:h.dbPath,exportDir:join(h.root,"exports"),scopedIdentities:users,investigationCandidateProvider:createEmptyCandidateProvider()}).open();assert.equal(reopened.access.cropSeasons("owner-p2b",fieldOne.field_id).seasons.length,2);reopened.close();reopened=null;}finally{reopened?.close();await rm(h.root,{recursive:true,force:true,maxRetries:5,retryDelay:50});}});
  await t.test("4 forged unrelated season is rejected",async()=>{const h=await fixture();try{assert.throws(()=>h.store.access.fieldHistory("owner-p2b",fieldOne.field_id,"season-does-not-exist",()=>null),/not found/);}finally{await h.close();}});
  await t.test("5 cross-Field season is rejected",async()=>{const h=await fixture();try{assert.throws(()=>h.store.access.fieldHistory("owner-p2b",fieldOne.field_id,fieldTwo.season_id,()=>null),/not found/);}finally{await h.close();}});
  await t.test("6 cross-tenant season is rejected",async()=>{const h=await fixture();try{assert.throws(()=>h.store.access.fieldHistory("owner-p2b",foreignField.field_id,foreignField.season_id,()=>null),/not found/);}finally{await h.close();}});
  await t.test("7 normal SPA cannot open Assignment screen",async()=>{const h=await fixture();try{assert.throws(()=>h.store.access.assignmentManagement("spa-p2b"),/capability required/);}finally{await h.close();}});
  await t.test("8 authorized Coordinator can view assignments",async()=>{const h=await fixture();try{assert.equal(h.store.access.assignmentManagement("coordinator-p2b").permissions.can_manage_access,true);}finally{await h.close();}});
  await t.test("9 valid Field grant succeeds",async()=>{const h=await fixture();try{const g=grant(h,{scope_type:"FIELD",scope_id:fieldOne.field_id,capability:"FIELD_OPERATE"});assert.equal(g.capability,"FIELD_OPERATE");assert.equal(h.store.access.canReadField("spa-p2b",h.store.db.prepare("SELECT * FROM lifecycle_fields WHERE field_id=?").get(fieldOne.field_id)),true);}finally{await h.close();}});
  await t.test("10 Field grant does not grant REVIEW_PERFORM",async()=>{const h=await fixture();try{grant(h,{scope_type:"FIELD",scope_id:fieldOne.field_id,capability:"FIELD_OPERATE"});assert.equal(h.store.access.canReviewObservation("spa-p2b",h.store.db.prepare("SELECT * FROM investigation_cases WHERE case_id=?").get(h.oldCase.case_id)),false);}finally{await h.close();}});
  await t.test("11 Case grant does not grant Field-wide access",async()=>{const h=await fixture();try{grant(h,{scope_type:"CASE",scope_id:h.oldCase.case_id,capability:"CASE_OPERATE"});assert.equal(h.store.access.canReadField("spa-p2b",h.store.db.prepare("SELECT * FROM lifecycle_fields WHERE field_id=?").get(fieldOne.field_id)),false);}finally{await h.close();}});
  await t.test("12 Review-item grant does not grant Case workspace",async()=>{const h=await fixture();try{const currentCase=h.store.createInvestigationRecord("owner-p2b","CASE",{field_id:fieldOne.field_id,season_id:h.currentSeason,case_id:"case-p2b-current",purpose:"Current case"}),turn=await h.store.orchestrateConversationTurn("owner-p2b",{request_id:"signal-p2b",entry_point:"CASE",field_id:fieldOne.field_id,season_id:h.currentSeason,case_id:currentCase.case_id,message:"ไม่รู้"}),signal=turn.learning_signals[0];grant(h,{scope_type:"REVIEW_ITEM",scope_id:signal.signal_id,capability:"REVIEW_ITEM_REVIEW"});assert.equal(h.store.access.canReadCase("spa-p2b",h.store.db.prepare("SELECT * FROM investigation_cases WHERE case_id=?").get(currentCase.case_id)),false);}finally{await h.close();}});
  await t.test("13 self-assignment is denied under current policy",async()=>{const h=await fixture();try{assert.throws(()=>h.store.access.grant("coordinator-p2b",{subject_user_id:"coordinator-p2b",scope_type:"FIELD",scope_id:fieldOne.field_id,capability:"FIELD_OPERATE",reason:"self"}),/self-assignment denied/);}finally{await h.close();}});
  await t.test("14 cross-tenant grant is denied",async()=>{const h=await fixture();try{assert.throws(()=>h.store.access.grant("coordinator-p2b",{subject_user_id:"foreign-p2b",scope_type:"FIELD",scope_id:fieldOne.field_id,capability:"FIELD_OPERATE",reason:"cross"}),/cross-tenant/);}finally{await h.close();}});
  await t.test("15 revocation immediately removes reachability",async()=>{const h=await fixture();try{const g=grant(h,{scope_type:"CASE",scope_id:h.oldCase.case_id,capability:"CASE_OPERATE"}),row=h.store.db.prepare("SELECT * FROM investigation_cases WHERE case_id=?").get(h.oldCase.case_id);assert.equal(h.store.access.canReadCase("spa-p2b",row),true);h.store.access.revoke("coordinator-p2b",g.grant_id,"ended");assert.equal(h.store.access.canReadCase("spa-p2b",row),false);}finally{await h.close();}});
  await t.test("16 authorized notification target opens",async()=>{const h=await fixture();try{grant(h,{scope_type:"CASE",scope_id:h.oldCase.case_id,capability:"CASE_OPERATE"});const n=h.store.access.notifications("spa-p2b").items.find((x)=>x.category==="ASSIGNMENT_CREATED");assert.equal(n.target.case_id,h.oldCase.case_id);assert.equal(h.store.access.canReadCase("spa-p2b",h.store.db.prepare("SELECT * FROM investigation_cases WHERE case_id=?").get(n.target.case_id)),true);}finally{await h.close();}});
  await t.test("17 revoked target after notification fails",async()=>{const h=await fixture();try{const g=grant(h,{scope_type:"CASE",scope_id:h.oldCase.case_id,capability:"CASE_OPERATE"}),stale=h.store.access.notifications("spa-p2b").items[0];h.store.access.revoke("coordinator-p2b",g.grant_id,"ended");assert.equal(h.store.access.canReadCase("spa-p2b",h.store.db.prepare("SELECT * FROM investigation_cases WHERE case_id=?").get(stale.target.case_id)),false);}finally{await h.close();}});
  await t.test("18 notification grants no authority",async()=>{const h=await fixture();try{const before=h.store.db.prepare("SELECT COUNT(*) count FROM governed_access_grants").get().count;h.store.access.notifications("spa-p2b");assert.equal(h.store.db.prepare("SELECT COUNT(*) count FROM governed_access_grants").get().count,before);}finally{await h.close();}});
  await t.test("19 hidden object details do not leak through revoked notification",async()=>{const h=await fixture();try{const g=grant(h,{scope_type:"CASE",scope_id:h.oldCase.case_id,capability:"CASE_OPERATE"});h.store.access.revoke("coordinator-p2b",g.grant_id,"ended");const text=JSON.stringify(h.store.access.notifications("spa-p2b"));assert.doesNotMatch(text,/case-p2b-one|P2B case/);}finally{await h.close();}});
  await t.test("20 CHAT-01 works without Field",async()=>{const h=await fixture();try{const r=await h.store.orchestrateConversationTurn("empty-p2b",{request_id:"general-empty",entry_point:"GENERAL_CHAT",remain_general:true,message:"สวัสดี"});assert.equal(r.context.scope,"GENERAL");}finally{await h.close();}});
  await t.test("21 General chat can remain general",async()=>{const h=await fixture();try{const r=await h.store.orchestrateConversationTurn("owner-p2b",{request_id:"general-remain",entry_point:"GENERAL_CHAT",remain_general:true,message:"ข้าวเหลืองเป็นหย่อม"});assert.equal(r.context.scope,"GENERAL");assert.equal(r.fact_record_references.length,0);}finally{await h.close();}});
  await t.test("22 one safe context candidate can be presented",async()=>{const h=await fixture({twoFields:false});try{h.store.db.prepare("UPDATE investigation_cases SET status='COMPLETED' WHERE case_id=?").run(h.oldCase.case_id);const p=h.store.access.chatContextCandidates("owner-p2b");assert.equal(p.fields.length+p.cases.length,1);assert.equal(p.selection_required,false);assert.equal(p.fields[0].field_id,fieldOne.field_id);assert.ok(p.fields[0].label&&p.fields[0].permissions.field_view);}finally{await h.close();}});
  await t.test("23 ambiguous contexts require user choice",async()=>{const h=await fixture();try{const p=h.store.access.chatContextCandidates("owner-p2b");assert.equal(p.selection_required,true);const r=await h.store.orchestrateConversationTurn("owner-p2b",{request_id:"general-ambiguous",entry_point:"GENERAL_CHAT",message:"ช่วยดู"});assert.equal(r.context.resolved,false);assert.equal(r.context.ambiguity.type,"FIELD");}finally{await h.close();}});
  await t.test("24 explicit context selection binds correctly",async()=>{const h=await fixture();try{const r=await h.store.orchestrateConversationTurn("owner-p2b",{request_id:"general-select",entry_point:"GENERAL_CHAT",field_id:fieldOne.field_id,season_id:h.currentSeason,message:"สวัสดี"});assert.equal(r.context.field_id,fieldOne.field_id);assert.equal(h.store.getGovernedConversationHistory("owner-p2b",r.conversation_id).conversation.field_id,fieldOne.field_id);}finally{await h.close();}});
  await t.test("25 unauthorized context cannot be selected",async()=>{const h=await fixture();try{await assert.rejects(h.store.orchestrateConversationTurn("owner-p2b",{request_id:"general-foreign",entry_point:"GENERAL_CHAT",field_id:foreignField.field_id,season_id:foreignField.season_id,message:"สวัสดี"}),/field context not found/);}finally{await h.close();}});
  await t.test("26 unscoped chat cannot create confirmed Observation",async()=>{const h=await fixture();try{await h.store.orchestrateConversationTurn("owner-p2b",{request_id:"general-no-confirm",entry_point:"GENERAL_CHAT",remain_general:true,message:"ใบเหลือง"});assert.equal(h.store.db.prepare("SELECT COUNT(*) count FROM investigation_observations WHERE review_state IN ('HUMAN_REVIEWED','DOMAIN_APPROVED')").get().count,0);}finally{await h.close();}});
  await t.test("27 unscoped chat cannot silently create Case truth",async()=>{const h=await fixture();try{const before=h.store.db.prepare("SELECT COUNT(*) count FROM investigation_cases").get().count;await h.store.orchestrateConversationTurn("owner-p2b",{request_id:"general-no-case",entry_point:"GENERAL_CHAT",remain_general:true,message:"ใบเหลืองเป็นหย่อม"});assert.equal(h.store.db.prepare("SELECT COUNT(*) count FROM investigation_cases").get().count,before);}finally{await h.close();}});
  await t.test("28 CHAT-01 to CHAT-02 transition preserves conversation safely",async()=>{const h=await fixture();try{const a=await h.store.orchestrateConversationTurn("owner-p2b",{request_id:"general-first",entry_point:"GENERAL_CHAT",remain_general:true,message:"สวัสดี"}),b=await h.store.orchestrateConversationTurn("owner-p2b",{request_id:"general-bind",conversation_id:a.conversation_id,expected_conversation_revision:a.conversation_revision,entry_point:"GENERAL_CHAT",field_id:fieldOne.field_id,season_id:h.currentSeason,message:"เชื่อมบริบท"});assert.equal(b.conversation_id,a.conversation_id);assert.equal(b.context.field_id,fieldOne.field_id);assert.equal(h.store.getGovernedConversationHistory("owner-p2b",a.conversation_id).turns.length,2);}finally{await h.close();}});
  await t.test("29 provider failure remains safe",async()=>{const provider=createTestOnlyConversationProvider(()=>{throw new Error("offline");}),h=await fixture({provider});try{const before=h.store.db.prepare("SELECT COUNT(*) count FROM investigation_cases").get().count,r=await h.store.orchestrateConversationTurn("owner-p2b",{request_id:"general-provider-fail",entry_point:"GENERAL_CHAT",remain_general:true,message:"ใบเหลือง"});assert.equal(r.provider_input_state,"DETERMINISTIC_FALLBACK");assert.equal(h.store.db.prepare("SELECT COUNT(*) count FROM investigation_cases").get().count,before);}finally{await h.close();}});
  await t.test("30 Pass 2 diagnosis and recommendation injection remains blocked",async()=>{assert.throws(()=>guardComposedResponse({transition:"วินิจฉัยว่าเป็นโรคและควรพ่นสาร"},{required_text:"ข้อความที่ระบบกำกับ",required_question:null}),/unsupported wording/);const source=await readFile(new URL("../assets/field-app.js",import.meta.url),"utf8");for(const marker of ["FIELD-HISTORY-01","ASSIGNMENT-01","NOTIFICATION-01","CHAT-01"])assert.match(source,new RegExp(marker));});
});
