import test from "node:test";
import assert from "node:assert/strict";
import { mkdtemp, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { createGoldenTestOnlyCandidateProvider } from "../candidate-provider.mjs";
import { GUIDANCE_INTELLIGENCE_ENUMS, GuidanceIntelligenceEngine, GuidanceRuleProvider, createTestOnlyGuidanceRuleProvider } from "../guidance-intelligence.mjs";
import { PilotStore } from "../pilot-store.mjs";
import { startServer } from "../server.mjs";

const scope={field_id:"field-guidance",season_id:"season-guidance",case_id:"case-guidance"};
const now="2026-08-27T03:00:00.000Z";
function ids(prefix="id"){let n=0;return()=>`${prefix}-${String(++n).padStart(4,"0")}`;}
function lifecycle(userId="user-a",stage="TILLERING"){return {schema_version:2,users:[{user_id:userId}],fields:[{field_id:scope.field_id,owner_user_id:userId,name:"นา guidance",crop:"rice",planting_date:"2026-07-01",current_crop_stage:{code:stage,label:stage,model_version:"field-stage-model/v1"},current_cmp_stage:{stage_id:"CMP-03",label:"ระยะแตกกอ",model_version:"field-stage-model/v1"},season_id:scope.season_id,stage_provenance:"USER_CONFIRMED",created_at:"2026-07-01T00:00:00.000Z",updated_at:"2026-08-20T00:00:00.000Z"}],seasons:[{season_id:scope.season_id,field_id:scope.field_id,crop:"rice",status:"ACTIVE"}],guidance:[],activities:[],cases:[],observations:[],evidence:[],conversations:[],messages:[],decision_logs:[],case_summaries:[],weather_snapshots:[]};}
function bundle(overrides={}){return {authority:"SERVER",user_id:"user-a",field_id:scope.field_id,season_id:scope.season_id,field_context:{crop:"rice",authority:"SERVER_LIFECYCLE"},stage_assessment:{stage_assessment_id:"stage-season-guidance",provenance:"USER_CONFIRMED",crop_stage:{code:"TILLERING"},cmp_stage:{stage_id:"CMP-03"}},cases:[{case_id:scope.case_id,status:"OPEN"}],observations:[{observation_id:"obs-guidance"}],evidence:[],management_events:[],follow_up_plans:[],...overrides};}
function assessment(overrides={}){return {authority:"SERVER_DERIVED_INVESTIGATION_ASSESSMENT",assessment_id:"assessment-guidance",assessment_revision:1,scope:{user_id:"user-a",...scope,observation_ids:["obs-guidance"]},result_state:"ASSESSED",candidate_assessments:[{candidate_id:"candidate-a"}],evidence_sufficiency:{state:"SUFFICIENT_FOR_NARROWING",reason:"More evidence is needed for the bounded purpose."},next_best_evidence:{type:"FIELD_CHECK",target:"ROOT_COMPARISON",comparison:"AFFECTED_VS_NORMAL",purpose:"DISTINGUISH",discrimination_goal:"Compare",value:"HIGH",reason:"This is the most discriminating feasible evidence.",related_candidate_ids:["candidate-a"],existing_evidence_gap_refs:["gap-root"],stop_if:"Comparable roots are recorded."},stop_condition:null,source_bundle_hash:"a".repeat(64),rule_version:"step-c/v1",rule_hash:"b".repeat(64),...overrides};}
const fixtureRule=(overrides={})=>({rule_id:"fixture-routine",guidance_type:"ROUTINE_INSPECTION",inspection_domain:"CROP_DEVELOPMENT",priority:"P3",title:"ตรวจตามรอบ",instruction:"ตรวจสิ่งที่กฎระบุ",reason_code:"GOVERNED_ROUTINE",why_now:"ถึงช่วงตรวจตามกฎทดสอบ",what_to_inspect:"การพัฒนาของพืช",where_to_inspect:"จุดตัวแทนในแปลง",how_to_inspect:"บันทึกสิ่งที่เห็น",evidence_concept:"CROP_STAGE_OBSERVATION",comparison:null,source_type:"TEST_ONLY_FIXTURE",stage_ids:["CMP-03"],context_tokens:[],...overrides});
const engine=()=>new GuidanceIntelligenceEngine({clock:()=>new Date(now)});

test("Guidance types are the five governed categorical values",()=>assert.deepEqual(GUIDANCE_INTELLIGENCE_ENUMS.guidanceTypes,["ROUTINE_INSPECTION","CONTEXT_RISK_INSPECTION","FOLLOW_EXISTING_CASE","EVIDENCE_COMPLETION","NO_ADDITIONAL_INSPECTION"]));
test("inspection domains contain the exact governed domain set",()=>assert.deepEqual(GUIDANCE_INTELLIGENCE_ENUMS.inspectionDomains,["CROP_DEVELOPMENT","DISEASE_INSPECTION","INSECT_INSPECTION","WEED_INSPECTION","ABIOTIC_INSPECTION","WATER_INSPECTION","ROOT_INSPECTION","MANAGEMENT_HISTORY_CHECK","SAMPLING_COMPLETION","VISUAL_EVIDENCE","GENERAL_FIELD_INSPECTION"]));
test("priorities are categorical and contain no score",()=>assert.deepEqual(GUIDANCE_INTELLIGENCE_ENUMS.priorities,["P0","P1","P2","P3"]));
test("durable lifecycle statuses are complete",()=>assert.deepEqual(GUIDANCE_INTELLIGENCE_ENUMS.statuses,["GENERATED","SHOWN","ACKNOWLEDGED","IN_PROGRESS","COMPLETED","DISMISSED","EXPIRED","SUPERSEDED"]));
test("source authorities are explicit and bounded",()=>assert.deepEqual(GUIDANCE_INTELLIGENCE_ENUMS.sourceTypes,["INVESTIGATION_NEXT_BEST_EVIDENCE","ACTIVE_CASE_FOLLOW_UP","GOVERNED_STAGE_INSPECTION_RULE","GOVERNED_CONTEXT_INSPECTION_RULE","WORKFLOW_GUIDANCE_RULE","TEST_ONLY_FIXTURE"]));
test("TEST_ONLY_FIXTURE cannot load in normal runtime",()=>assert.throws(()=>new GuidanceRuleProvider({authority:"TEST_ONLY_FIXTURE",reviewState:"TEST_ONLY"}),/cannot load in normal runtime/));
test("test-only provider requires an explicit factory",()=>assert.equal(createTestOnlyGuidanceRuleProvider([fixtureRule()]).getManifest().authority,"TEST_ONLY_FIXTURE"));
test("fixture provider rejects an unsupported guidance enum",()=>assert.throws(()=>createTestOnlyGuidanceRuleProvider([fixtureRule({guidance_type:"AUTONOMOUS_ADVICE"})]),/invalid guidance_type/));
test("engine rejects a non-authoritative bundle",()=>assert.throws(()=>engine().derive({...bundle(),authority:"LOCAL_DRAFT_ONLY"},assessment()),/authoritative server/));
test("engine rejects anything other than the current Step C contract",()=>assert.throws(()=>engine().derive(bundle(),{...assessment(),authority:"LOCAL_INFERENCE"}),/current Step C/));

test("D1 maps Step C root comparison to one evidence-completion action",()=>{const result=engine().derive(bundle(),assessment());assert.equal(result.guidance_type,"EVIDENCE_COMPLETION");assert.equal(Array.isArray(result),false);});
test("D1 maps root comparison to ROOT_INSPECTION",()=>assert.equal(engine().derive(bundle(),assessment()).inspection_domain,"ROOT_INSPECTION"));
test("D1 high-value evidence becomes P1 without numeric scoring",()=>{const result=engine().derive(bundle(),assessment());assert.equal(result.priority,"P1");assert.equal("score" in result,false);});
test("D1 gives one affected-versus-normal task",()=>{const result=engine().derive(bundle(),assessment());assert.equal(result.title,"ตรวจรากเปรียบเทียบ");assert.equal(result.comparison,"AFFECTED_VS_NORMAL");});
test("D1 reuses known field, case, observation, assessment, and Candidate context",()=>{const result=engine().derive(bundle(),assessment());assert.deepEqual(result.related_candidate_ids,["candidate-a"]);assert.equal(result.assessment_id,"assessment-guidance");assert.equal(result.stage_assessment_id,"stage-season-guidance");});
test("D1 does not re-ask already known field context",()=>assert.doesNotMatch(engine().derive(bundle(),assessment()).instruction,/which field|what crop|which season/i));
for(const known of ["YELLOWING","PATCH","LOW_SPOT","DEEPER_WATER","MANAGEMENT_HISTORY"]){test(`D1 does not request already-known ${known} again`,()=>{const result=engine().derive(bundle(),assessment());assert.doesNotMatch(`${result.what_to_inspect} ${result.instruction}`,new RegExp(known,"i"));});}
test("D3 enough-for-current-decision produces no additional inspection",()=>{const result=engine().derive(bundle(),assessment({stop_condition:"ENOUGH_FOR_CURRENT_DECISION",next_best_evidence:null}));assert.equal(result.guidance_type,"NO_ADDITIONAL_INSPECTION");assert.equal(result.reason_code,"ENOUGH_FOR_CURRENT_DECISION");});
test("management-option-review sufficiency suppresses additional inspection",()=>assert.equal(engine().derive(bundle(),assessment({next_best_evidence:null,evidence_sufficiency:{state:"SUFFICIENT_FOR_MANAGEMENT_OPTION_REVIEW",reason:"Enough for this purpose."}})).guidance_type,"NO_ADDITIONAL_INSPECTION"));
test("USER_DECLINED stop condition suppresses further inspection",()=>assert.equal(engine().derive(bundle(),assessment({next_best_evidence:null,stop_condition:"USER_DECLINED"})).reason_code,"USER_DECLINED"));
test("resolved case stop condition suppresses further inspection",()=>assert.equal(engine().derive(bundle(),assessment({next_best_evidence:null,stop_condition:"CASE_RESOLVED"})).guidance_type,"NO_ADDITIONAL_INSPECTION"));
test("D4 exhausted field evidence produces expert handoff only",()=>{const result=engine().derive(bundle(),assessment({stop_condition:"FIELD_EVIDENCE_EXHAUSTED",evidence_sufficiency:{state:"UNRESOLVABLE_WITH_CURRENT_FIELD_EVIDENCE",reason:"Field evidence is exhausted."},next_best_evidence:{type:"EXPERT_REVIEW",target:"SPECIALIST_CASE_REVIEW",value:"HIGH",reason:"Escalate.",related_candidate_ids:["candidate-a"],existing_evidence_gap_refs:["gap-specialist"]}}));assert.equal(result.evidence_concept,"EXPERT_REVIEW");assert.equal(result.priority,"P0");assert.equal(result.guidance_type,"FOLLOW_EXISTING_CASE");});
test("explicit specialist requirement produces expert handoff",()=>assert.equal(engine().derive(bundle(),assessment({stop_condition:"EXPERT_REVIEW_REQUIRED",next_best_evidence:null})).evidence_concept,"EXPERT_REVIEW"));
test("laboratory requirement produces lab handoff without a result claim",()=>{const result=engine().derive(bundle(),assessment({stop_condition:"LAB_EVIDENCE_REQUIRED",next_best_evidence:null}));assert.equal(result.evidence_concept,"LAB_TEST");assert.match(result.limitations[0],/ไม่ยืนยันผล/);});
test("guidance runtime contains no weather fetch URL",()=>assert.doesNotMatch(JSON.stringify(engine().derive(bundle(),assessment())),/https?:\/\//));
test("photo request maps to visual evidence",()=>assert.equal(engine().derive(bundle(),assessment({next_best_evidence:{...assessment().next_best_evidence,type:"PHOTO",target:"DISTINGUISHING_SHEATH_VIEW"}})).inspection_domain,"VISUAL_EVIDENCE"));
test("sampling request maps to sampling completion",()=>assert.equal(engine().derive(bundle(),assessment({next_best_evidence:{...assessment().next_best_evidence,type:"SAMPLING",target:"REPRESENTATIVE_SAMPLING"}})).inspection_domain,"SAMPLING_COMPLETION"));
test("management record request maps to management history",()=>assert.equal(engine().derive(bundle(),assessment({next_best_evidence:{...assessment().next_best_evidence,type:"MANAGEMENT_RECORD",target:"MANAGEMENT_EVENT_DETAIL"}})).inspection_domain,"MANAGEMENT_HISTORY_CHECK"));
test("water request maps to water inspection",()=>assert.equal(engine().derive(bundle(),assessment({next_best_evidence:{...assessment().next_best_evidence,type:"FIELD_CHECK",target:"WATER_LEVEL_COMPARISON"}})).inspection_domain,"WATER_INSPECTION"));
test("unmapped Step C request remains a general evidence task",()=>assert.equal(engine().derive(bundle(),assessment({next_best_evidence:{...assessment().next_best_evidence,type:"QUESTION",target:"OTHER_BOUNDED_FACT"}})).inspection_domain,"GENERAL_FIELD_INSPECTION"));
test("active case follow-up is selected when Step C has no request",()=>{const follow={follow_up_id:"follow-1",case_id:scope.case_id,purpose:"Repeat comparable observation",check_items:["repeat count"],where_to_check:"affected and comparison",comparison_required:true,status:"PLANNED"};const result=engine().derive(bundle({follow_up_plans:[follow]}),assessment({next_best_evidence:null}));assert.equal(result.source_type,"ACTIVE_CASE_FOLLOW_UP");assert.equal(result.source_ref,"follow-1");});
test("due case follow-up receives P1",()=>{const follow={follow_up_id:"follow-1",purpose:"Repeat check",check_items:[],status:"DUE"};assert.equal(engine().derive(bundle({follow_up_plans:[follow]}),assessment({next_best_evidence:null})).priority,"P1");});
test("active case suppresses duplicate routine inspection",()=>{const provider=createTestOnlyGuidanceRuleProvider([fixtureRule()]),runtime=new GuidanceIntelligenceEngine({ruleProvider:provider});assert.equal(runtime.derive(bundle(),assessment({next_best_evidence:null})).guidance_type,"NO_ADDITIONAL_INSPECTION");});
test("D2 targeted Step C evidence wins over same-domain routine guidance",()=>{const provider=createTestOnlyGuidanceRuleProvider([fixtureRule({inspection_domain:"INSECT_INSPECTION"})]),runtime=new GuidanceIntelligenceEngine({ruleProvider:provider}),targeted=assessment({next_best_evidence:{...assessment().next_best_evidence,type:"COUNT",target:"TARGETED_DAMAGE_COUNT"}}),result=runtime.derive(bundle(),targeted);assert.equal(result.guidance_type,"EVIDENCE_COMPLETION");assert.equal(Array.isArray(result),false);});
test("governed context inspection precedes routine inspection",()=>{const provider=createTestOnlyGuidanceRuleProvider([fixtureRule(),fixtureRule({rule_id:"fixture-context",guidance_type:"CONTEXT_RISK_INSPECTION",inspection_domain:"WATER_INSPECTION",title:"ตรวจบริบท",source_type:"TEST_ONLY_FIXTURE",context_tokens:["rice"]})]),runtime=new GuidanceIntelligenceEngine({ruleProvider:provider});const result=runtime.derive(bundle({cases:[]}),assessment({next_best_evidence:null}));assert.equal(result.guidance_type,"CONTEXT_RISK_INSPECTION");});
test("production knowledge gap is an explicit no-inspection result",()=>{const result=engine().derive(bundle({cases:[]}),assessment({next_best_evidence:null}));assert.equal(result.reason_code,"GUIDANCE_KNOWLEDGE_GAP");assert.equal(result.guidance_type,"NO_ADDITIONAL_INSPECTION");});
test("governed stage fixture can select a routine inspection",()=>{const runtime=new GuidanceIntelligenceEngine({ruleProvider:createTestOnlyGuidanceRuleProvider([fixtureRule()])});assert.equal(runtime.derive(bundle({cases:[]}),assessment({next_best_evidence:null})).guidance_type,"ROUTINE_INSPECTION");});
test("context fixture is ineligible when required context is absent",()=>{const runtime=new GuidanceIntelligenceEngine({ruleProvider:createTestOnlyGuidanceRuleProvider([fixtureRule({guidance_type:"CONTEXT_RISK_INSPECTION",context_tokens:["MISSING_TOKEN"]})])});assert.equal(runtime.derive(bundle({cases:[]}),assessment({next_best_evidence:null})).reason_code,"GUIDANCE_KNOWLEDGE_GAP");});
test("unknown stage remains valid when Step C supplies next-best evidence",()=>assert.equal(engine().derive(bundle({stage_assessment:{stage_assessment_id:"stage-unknown",provenance:"SYSTEM_ESTIMATED",crop_stage:null,cmp_stage:null}}),assessment()).guidance_type,"EVIDENCE_COMPLETION"));
test("authoritative user-confirmed stage provenance is retained",()=>assert.equal(engine().derive(bundle(),assessment()).stage_provenance,"USER_CONFIRMED"));
test("duplicate identical fixture rules collapse deterministically",()=>{const provider=createTestOnlyGuidanceRuleProvider([fixtureRule(),fixtureRule()]);assert.equal(provider.getRules().length,1);});
test("conflicting duplicate fixture rules are rejected",()=>assert.throws(()=>createTestOnlyGuidanceRuleProvider([fixtureRule(),fixtureRule({title:"conflict"})]),/conflicting duplicate/));

function create(store,type,record){return store.createInvestigationRecord("user-a",type,{field_id:scope.field_id,season_id:scope.season_id,...record});}
function seedGolden(store){
  const caseRecord=create(store,"CASE",{case_id:scope.case_id,purpose:"Step D golden case"});
  const observation=create(store,"OBSERVATION",{observation_id:"obs-guidance",case_id:caseRecord.case_id,observed_at:"2026-08-20T08:30:00Z",source:"FIELD_OBSERVED",note:"ข้าวเหลืองเป็นหย่อมตรงจุดต่ำ น้ำลึกกว่าข้างๆ"});
  create(store,"SPATIAL_EVIDENCE",{evidence_id:"ev-guidance-spatial",observation_id:observation.observation_id,case_id:caseRecord.case_id,source:"FIELD_OBSERVED",evidence_level:"SP2_MULTI_ZONE_SUPPORTED",payload:{observation_scope:"PATCH",geometry:"PATCH",field_positions:["LOW_SPOT"],patterns:["PATCH"],field_extent:"LOCAL",location_provenance:"FIELD_MAP_SELECTED"}});
  create(store,"MORPHOLOGY_EVIDENCE",{evidence_id:"ev-guidance-morphology",observation_id:observation.observation_id,case_id:caseRecord.case_id,source:"FIELD_OBSERVED",evidence_level:"MO1_DIRECT_OBSERVATION",payload:{plant_part:"LEAF_SHEATH",primary_phenotypes:["YELLOWING","LESION"],negative_evidence:[]}});
  create(store,"WATER_CONTEXT",{evidence_id:"ev-guidance-water",observation_id:observation.observation_id,case_id:caseRecord.case_id,source:"FIELD_OBSERVED",evidence_level:"WT2_ZONE_COMPARISON",payload:{water_state:"DEEP_PONDED",zone_reference:"affected low spot deeper than comparison",water_depth:{value:12,unit:"CM"},source:"FIELD_OBSERVED"}});
  const management=create(store,"MANAGEMENT_EVENT",{management_event_id:"management-guidance",case_id:caseRecord.case_id,event_type:"FERTILIZER_APPLICATION",event_at:"2026-08-19T04:00:00Z",time_precision:"EXACT",source:"USER_REPORTED",reported_product_name:"unresolved report",product_identity_confidence:"UNKNOWN"});
  const earliest=create(store,"TEMPORAL_EVIDENCE",{temporal_evidence_id:"time-guidance",case_id:caseRecord.case_id,observation_id:observation.observation_id,event_kind:"EARLIEST_EVIDENCE_AT",event_at:"2026-08-19T03:00:00Z",time_precision:"EXACT",evidence_level:"TC2_DATE_SUPPORTED",source:"PHOTO_METADATA"});
  create(store,"TEMPORAL_RELATIONSHIP",{temporal_relationship_id:"relation-guidance",case_id:caseRecord.case_id,subject_type:"MANAGEMENT_EVENT",subject_id:management.management_event_id,object_type:"TEMPORAL_EVIDENCE",object_id:earliest.temporal_evidence_id,relation:"AFTER",incompatible_with_initial_cause:true,rationale:"Symptoms predate application."});
  return {caseRecord,observation};
}
async function setup(){const root=await mkdtemp(join(tmpdir(),"cpmoakb-guidance-")),store=await new PilotStore({dbPath:join(root,"pilot.sqlite"),exportDir:join(root,"exports"),investigationCandidateProvider:createGoldenTestOnlyCandidateProvider(),intelligenceClock:()=>new Date(now),intelligenceIdProvider:ids("assessment-id"),guidanceClock:()=>new Date(now),guidanceIdProvider:ids("guidance-id")}).open();store.putWorkspace("user-a",lifecycle());const seeded=seedGolden(store);return {root,store,...seeded,close:async()=>{store.close();await rm(root,{recursive:true,force:true});}};}

test("schema migration v5 creates durable guidance and transition tables",async()=>{const h=await setup();try{assert.equal(h.store.db.prepare("SELECT COUNT(*) count FROM investigation_schema_migrations WHERE version=5").get().count,1);assert.ok(h.store.db.prepare("SELECT name FROM sqlite_master WHERE name='governed_guidance_transitions'").get());}finally{await h.close();}});
test("current guidance is persisted and replay-stable",async()=>{const h=await setup();try{const first=h.store.getCurrentGovernedGuidance("user-a",scope),second=h.store.getCurrentGovernedGuidance("user-a",scope);assert.equal(first.guidance_id,second.guidance_id);assert.equal(first.context_hash,second.context_hash);assert.equal(first.status,"GENERATED");}finally{await h.close();}});
test("generated guidance can be shown",async()=>{const h=await setup();try{const item=h.store.getCurrentGovernedGuidance("user-a",scope),shown=h.store.transitionGovernedGuidance("user-a",{guidance_id:item.guidance_id,action:"SHOW",expected_status:"GENERATED"});assert.equal(shown.status,"SHOWN");assert.equal(shown.transition_history.length,1);}finally{await h.close();}});
test("acknowledged is not completed",async()=>{const h=await setup();try{const item=h.store.getCurrentGovernedGuidance("user-a",scope),result=h.store.transitionGovernedGuidance("user-a",{guidance_id:item.guidance_id,action:"ACKNOWLEDGE"});assert.equal(result.status,"ACKNOWLEDGED");assert.equal(result.completed_at,null);}finally{await h.close();}});
test("guidance lifecycle reaches completed through explicit actions",async()=>{const h=await setup();try{let item=h.store.getCurrentGovernedGuidance("user-a",scope);for(const action of ["SHOW","ACKNOWLEDGE","START","COMPLETE"])item=h.store.transitionGovernedGuidance("user-a",{guidance_id:item.guidance_id,action});assert.equal(item.status,"COMPLETED");assert.ok(item.completed_at);assert.equal(item.transition_history.length,4);}finally{await h.close();}});
test("terminal guidance rejects invalid transitions",async()=>{const h=await setup();try{let item=h.store.getCurrentGovernedGuidance("user-a",scope);item=h.store.transitionGovernedGuidance("user-a",{guidance_id:item.guidance_id,action:"COMPLETE"});assert.throws(()=>h.store.transitionGovernedGuidance("user-a",{guidance_id:item.guidance_id,action:"SHOW"}),/invalid from COMPLETED/);}finally{await h.close();}});
test("expected status protects concurrent lifecycle actions",async()=>{const h=await setup();try{const item=h.store.getCurrentGovernedGuidance("user-a",scope);h.store.transitionGovernedGuidance("user-a",{guidance_id:item.guidance_id,action:"SHOW"});assert.throws(()=>h.store.transitionGovernedGuidance("user-a",{guidance_id:item.guidance_id,action:"START",expected_status:"GENERATED"}),/status changed/);}finally{await h.close();}});
test("recently completed equivalent guidance is suppressed",async()=>{const h=await setup();try{const item=h.store.getCurrentGovernedGuidance("user-a",scope);h.store.transitionGovernedGuidance("user-a",{guidance_id:item.guidance_id,action:"COMPLETE"});const next=h.store.getCurrentGovernedGuidance("user-a",scope);assert.notEqual(next.guidance_id,item.guidance_id);assert.equal(next.guidance_type,"NO_ADDITIONAL_INSPECTION");assert.equal(next.reason_code,"RECENTLY_COMPLETED_EQUIVALENT_GUIDANCE");}finally{await h.close();}});
test("D5 dismissed guidance does not immediately repeat",async()=>{const h=await setup();try{const item=h.store.getCurrentGovernedGuidance("user-a",scope);h.store.transitionGovernedGuidance("user-a",{guidance_id:item.guidance_id,action:"DISMISS",rationale:"User declined this inspection now."});const next=h.store.getCurrentGovernedGuidance("user-a",scope);assert.equal(next.guidance_type,"NO_ADDITIONAL_INSPECTION");assert.equal(next.reason_code,"USER_DECLINED_EQUIVALENT_GUIDANCE");}finally{await h.close();}});
test("finishing a suppression item cannot resurrect the equivalent inspection",async()=>{const h=await setup();try{const original=h.store.getCurrentGovernedGuidance("user-a",scope);h.store.transitionGovernedGuidance("user-a",{guidance_id:original.guidance_id,action:"COMPLETE"});const suppressed=h.store.getCurrentGovernedGuidance("user-a",scope);h.store.transitionGovernedGuidance("user-a",{guidance_id:suppressed.guidance_id,action:"COMPLETE"});const reopened=h.store.getCurrentGovernedGuidance("user-a",scope);assert.equal(reopened.guidance_type,"NO_ADDITIONAL_INSPECTION");assert.equal(reopened.guidance_id,suppressed.guidance_id);}finally{await h.close();}});
test("new authoritative evidence supersedes active guidance",async()=>{const h=await setup();try{const first=h.store.getCurrentGovernedGuidance("user-a",scope),updated={observation_id:h.observation.observation_id,field_id:scope.field_id,season_id:scope.season_id,case_id:scope.case_id,observed_at:h.observation.observed_at,source:h.observation.source,confidence:h.observation.confidence,review_state:h.observation.review_state,note:"authoritative evidence changed"};h.store.updateInvestigationRecord("user-a","OBSERVATION",h.observation.observation_id,1,updated,"request-guidance-update");const second=h.store.getCurrentGovernedGuidance("user-a",scope),history=h.store.getGovernedGuidanceHistory("user-a",scope);assert.notEqual(second.context_hash,first.context_hash);assert.equal(history[0].status,"SUPERSEDED");assert.equal(second.supersedes_guidance_id,first.guidance_id);}finally{await h.close();}});
test("authoritative stage revision supersedes affected current guidance",async()=>{const h=await setup();try{const first=h.store.getCurrentGovernedGuidance("user-a",scope);h.store.putWorkspace("user-a",lifecycle("user-a","PANICLE_INITIATION"));const second=h.store.getCurrentGovernedGuidance("user-a",scope),history=h.store.getGovernedGuidanceHistory("user-a",scope);assert.notEqual(second.context_hash,first.context_hash);assert.equal(history[0].status,"SUPERSEDED");assert.equal(second.crop_stage.code,"PANICLE_INITIATION");}finally{await h.close();}});
test("guidance provider version change safely invalidates current guidance",async()=>{const h=await setup();try{const first=h.store.getCurrentGovernedGuidance("user-a",scope);h.store.guidanceIntelligence.engine.ruleProvider=new GuidanceRuleProvider({version:"1.0.1"});const second=h.store.getCurrentGovernedGuidance("user-a",scope),history=h.store.getGovernedGuidanceHistory("user-a",scope);assert.notEqual(second.context_hash,first.context_hash);assert.equal(history[0].status,"SUPERSEDED");assert.equal(second.provider_manifest.provider_version,"1.0.1");}finally{await h.close();}});
test("history preserves every transition snapshot",async()=>{const h=await setup();try{let item=h.store.getCurrentGovernedGuidance("user-a",scope);item=h.store.transitionGovernedGuidance("user-a",{guidance_id:item.guidance_id,action:"SHOW"});item=h.store.transitionGovernedGuidance("user-a",{guidance_id:item.guidance_id,action:"START"});const history=h.store.getGovernedGuidanceHistory("user-a",scope);assert.deepEqual(history[0].transition_history.map((entry)=>entry.to_status),["SHOWN","IN_PROGRESS"]);assert.equal(history[0].generated_at,now);}finally{await h.close();}});
test("diagnostics report active, terminal, superseded, and suppression counts",async()=>{const h=await setup();try{const item=h.store.getCurrentGovernedGuidance("user-a",scope);h.store.transitionGovernedGuidance("user-a",{guidance_id:item.guidance_id,action:"DISMISS"});h.store.getCurrentGovernedGuidance("user-a",scope);const diagnostics=h.store.getGovernedGuidanceDiagnostics("user-a",scope);assert.equal(diagnostics.total,2);assert.equal(diagnostics.active,1);assert.equal(diagnostics.terminal,1);assert.equal(diagnostics.suppressed_equivalents,1);}finally{await h.close();}});
test("completing guidance creates neither evidence nor case resolution",async()=>{const h=await setup();try{const before=h.store.getInvestigationBundle("user-a",scope),item=h.store.getCurrentGovernedGuidance("user-a",scope);h.store.transitionGovernedGuidance("user-a",{guidance_id:item.guidance_id,action:"COMPLETE"});const after=h.store.getInvestigationBundle("user-a",scope);assert.equal(after.evidence.length,before.evidence.length);assert.equal(after.cases[0].status,"OPEN");}finally{await h.close();}});
test("durable item exposes rich provenance and explicit boundaries",async()=>{const h=await setup();try{const item=h.store.getCurrentGovernedGuidance("user-a",scope);for(const key of ["guidance_id","field_id","season_id","case_id","assessment_id","assessment_revision","guidance_type","inspection_domain","title","instruction","priority","reason_code","why_now","what_to_inspect","where_to_inspect","how_to_inspect","evidence_concept","source_type","rule_version","rule_hash","stage_assessment_id","authoritative_evidence_refs","management_context_refs","limitations","status","generated_at","context_hash","semantic_key","boundaries"])assert.ok(key in item,key);assert.ok(item.authoritative_evidence_refs.includes("ev-guidance-spatial"));assert.ok(item.management_context_refs.includes("management-guidance"));assert.equal(item.boundaries.completion_creates_evidence,false);assert.equal(item.boundaries.openai_generation,false);}finally{await h.close();}});

async function login(base,user_id){const response=await fetch(`${base}/api/pilot/session`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({password:"1234",user_id})});return response.headers.get("set-cookie").split(";")[0];}
test("guidance API requires authentication",async()=>{const h=await setup();h.store.close();const server=await startServer({port:0,dbPath:join(h.root,"pilot.sqlite"),exportDir:join(h.root,"exports"),uploadDir:join(h.root,"uploads"),investigationCandidateProvider:createGoldenTestOnlyCandidateProvider()});try{const base=`http://127.0.0.1:${server.address().port}`,response=await fetch(`${base}/api/pilot/guidance?field_id=${scope.field_id}&season_id=${scope.season_id}&case_id=${scope.case_id}`);assert.equal(response.status,401);}finally{await new Promise((done)=>server.close(done));await rm(h.root,{recursive:true,force:true});}});
test("guidance current, action, history, and diagnostics APIs are server-scoped",async()=>{const h=await setup();h.store.close();const server=await startServer({port:0,dbPath:join(h.root,"pilot.sqlite"),exportDir:join(h.root,"exports"),uploadDir:join(h.root,"uploads"),investigationCandidateProvider:createGoldenTestOnlyCandidateProvider()});try{const base=`http://127.0.0.1:${server.address().port}`,cookie=await login(base,"user-a"),query=`field_id=${scope.field_id}&season_id=${scope.season_id}&case_id=${scope.case_id}`,currentResponse=await fetch(`${base}/api/pilot/guidance?${query}`,{headers:{cookie}}),current=await currentResponse.json();assert.equal(currentResponse.status,200);assert.equal(current.guidance.authority,"SERVER_DERIVED_GUIDANCE");const actionResponse=await fetch(`${base}/api/pilot/guidance-actions`,{method:"POST",headers:{cookie,"content-type":"application/json"},body:JSON.stringify({guidance_id:current.guidance.guidance_id,action:"ACKNOWLEDGE"})}),action=await actionResponse.json();assert.equal(action.guidance.status,"ACKNOWLEDGED");const history=await (await fetch(`${base}/api/pilot/guidance-history?${query}`,{headers:{cookie}})).json(),diagnostics=await (await fetch(`${base}/api/pilot/guidance-diagnostics?${query}`,{headers:{cookie}})).json();assert.equal(history.history.length,1);assert.equal(diagnostics.active,1);}finally{await new Promise((done)=>server.close(done));await rm(h.root,{recursive:true,force:true});}});
test("foreign session cannot read another user's governed guidance",async()=>{const h=await setup();h.store.close();const server=await startServer({port:0,dbPath:join(h.root,"pilot.sqlite"),exportDir:join(h.root,"exports"),uploadDir:join(h.root,"uploads"),investigationCandidateProvider:createGoldenTestOnlyCandidateProvider()});try{const base=`http://127.0.0.1:${server.address().port}`,cookie=await login(base,"user-b"),response=await fetch(`${base}/api/pilot/guidance?field_id=${scope.field_id}&season_id=${scope.season_id}&case_id=${scope.case_id}`,{headers:{cookie}});assert.equal(response.status,403);}finally{await new Promise((done)=>server.close(done));await rm(h.root,{recursive:true,force:true});}});
test("cross-field and cross-season scope access is rejected",async()=>{const h=await setup();try{assert.throws(()=>h.store.getCurrentGovernedGuidance("user-a",{field_id:"other-field",season_id:scope.season_id,case_id:scope.case_id}),/scope not found/);assert.throws(()=>h.store.getCurrentGovernedGuidance("user-a",{field_id:scope.field_id,season_id:"other-season",case_id:scope.case_id}),/scope not found/);}finally{await h.close();}});
test("Guidance contract contains no diagnosis, chemical, product, rate, reminder, or rank field",async()=>{const h=await setup();try{const item=h.store.getCurrentGovernedGuidance("user-a",scope),keys=Object.keys(item).map((key)=>key.toLowerCase());for(const prohibited of ["diagnosis","chemical","product","rate","reminder","rank","score"])assert.equal(keys.includes(prohibited),false);}finally{await h.close();}});
