import test from "node:test";
import assert from "node:assert/strict";
import { mkdtemp, readFile, readdir, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { startServer } from "../server.mjs";
import { validatePilotConfiguration } from "../pilot-hardening-runtime.mjs";
import { createEmptyCandidateProvider } from "../candidate-provider.mjs";
import { ServerWorkspaceAdapter } from "../assets/server-workspace-adapter.js";
import { ServerLLMAdapter } from "../assets/server-llm-adapter.js";
import { GovernedSpaRuntime } from "../assets/governed-spa-runtime.js";

const users=[
  {login_id:"spa",user_id:"pilot-spa",password:"secret-spa",enabled:true,display_name:"SPA reviewer",role:"SPA"},
  {login_id:"field-a",user_id:"pilot-field-a",password:"secret-a",enabled:true,display_name:"Field User A",role:"FIELD_USER"},
  {login_id:"field-b",user_id:"pilot-field-b",password:"secret-b",enabled:true,display_name:"Field User B",role:"FIELD_USER"},
];
const fieldInput={name:"HTTPS pilot field",polygon:{type:"Polygon",coordinates:[[[100,13],[100.01,13],[100,13.01],[100,13]]]},centroid:{latitude:13.003,longitude:100.003},area:{rai:1.2},crop:"rice",variety:"test",planting_method:"TRANSPLANTED",planting_date:"2026-07-01",expected_planting_date:null,current_crop_stage:{code:"TILLERING",label:"แตกกอ",model_version:"field-stage-model/v1"},current_cmp_stage:{stage_id:"CMP-03",label:"ระยะแตกกอ",model_version:"field-stage-model/v1"},stage_provenance:"USER_CONFIRMED"};

async function login(base,user=users[1]){const response=await fetch(`${base}/api/pilot/session`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({login_id:user.login_id,password:user.password})});assert.equal(response.status,200);return{cookie:response.headers.get("set-cookie").split(";")[0],setCookie:response.headers.get("set-cookie"),body:await response.json()};}
function fetcherFor(base,state){return async(path,options={})=>{const headers=new Headers(options.headers);if(state.cookie)headers.set("cookie",state.cookie);const response=await fetch(base+path,{...options,headers});const setCookie=response.headers.get("set-cookie");if(setCookie)state.cookie=setCookie.split(";")[0];return response;};}

test("M0C external FIELD_CAPTURE_ALPHA requires an exact HTTPS public origin",()=>{
  const base={profile:"FIELD_CAPTURE_ALPHA",host:"0.0.0.0",allow_external_binding:true,db_path:"pilot.sqlite",export_dir:"exports",upload_dir:"uploads"};
  assert.throws(()=>validatePilotConfiguration(base),/PILOT_PUBLIC_BASE_URL/);
  assert.throws(()=>validatePilotConfiguration({...base,public_base_url:"http://pilot.example.test"}),/HTTPS/);
  assert.throws(()=>validatePilotConfiguration({...base,public_base_url:"https://pilot.example.test/mobile"}),/invalid public_base_url/);
  const result=validatePilotConfiguration({...base,public_base_url:"https://pilot.example.test"});assert.equal(result.secure_cookie,true);assert.equal(result.mode,"FIELD_CAPTURE_ALPHA");
});

test("M0C HTTPS session, bounded health/readiness, and browser-facing Google configuration preserve secret boundaries",async()=>{
  const root=await mkdtemp(join(tmpdir(),"cpmoakb-m0c-contract-")),server=await startServer({port:0,publicBaseUrl:"https://pilot.example.test",pilotProfile:"FIELD_CAPTURE_ALPHA",pilotUsers:users,googleMapsBrowserKey:"browser-key-for-test",dbPath:join(root,"pilot.sqlite"),exportDir:join(root,"exports"),uploadDir:join(root,"uploads"),investigationCandidateProvider:createEmptyCandidateProvider()}),base=`http://127.0.0.1:${server.address().port}`;
  try{const authenticated=await login(base);assert.match(authenticated.setCookie,/HttpOnly/);assert.match(authenticated.setCookie,/SameSite=Strict/);assert.match(authenticated.setCookie,/Secure/);assert.doesNotMatch(JSON.stringify(authenticated.body),/secret-a/);assert.equal((await fetch(`${base}/api/pilot/map-configuration`)).status,401);const map=await(await fetch(`${base}/api/pilot/map-configuration`,{headers:{cookie:authenticated.cookie}})).json();assert.deepEqual(map,{provider:"GOOGLE_SATELLITE",available:true,browser_key:"browser-key-for-test",referrer_restriction_required:true});for(const path of ["/health","/readiness"]){const text=await(await fetch(base+path)).text();assert.doesNotMatch(text,/browser-key-for-test|secret-a|OPENAI_API_KEY|pilot\.sqlite|uploads/u);}assert.equal(server.pilotRuntime.profile,"FIELD_CAPTURE_ALPHA");assert.equal(server.pilotRuntime.secure_cookie,true);}finally{await new Promise(done=>server.close(done));await rm(root,{recursive:true,force:true,maxRetries:5,retryDelay:100});}
});

test("M0C same-user restart preserves Field, Case, Conversation, B1 metadata and image bytes while another user is denied",async()=>{
  const root=await mkdtemp(join(tmpdir(),"cpmoakb-m0c-restart-")),options={port:0,publicBaseUrl:"https://pilot.example.test",pilotProfile:"FIELD_CAPTURE_ALPHA",pilotUsers:users,dbPath:join(root,"pilot.sqlite"),exportDir:join(root,"exports"),uploadDir:join(root,"uploads"),investigationCandidateProvider:createEmptyCandidateProvider()};let server=await startServer(options);
  try{let base=`http://127.0.0.1:${server.address().port}`,state={cookie:""},fetcher=fetcherFor(base,state),workspace=new ServerWorkspaceAdapter(fetcher);await workspace.authenticate("secret-a","field-a");await workspace.createField(fieldInput);let runtime=new GovernedSpaRuntime({workspace,llm:new ServerLLMAdapter({fetcher})});await runtime.synchronize();await runtime.startCase(runtime.lifecycleState.fields[0]);await runtime.captureStatement("ข้าวมีใบเหลืองเป็นหย่อม");const bytes=new TextEncoder().encode("m0c-image"),file={name:"field.png",type:"image/png",size:bytes.length,arrayBuffer:async()=>bytes.buffer},uploaded=await runtime.uploadPhoto(file),ids={field:runtime.caseState.scope.field_id,season:runtime.caseState.scope.season_id,case:runtime.caseState.scope.case_id,conversation:runtime.caseState.conversation_id,image:uploaded.image.image_evidence_id};assert.equal((await readdir(options.uploadDir)).length,1);await new Promise(done=>server.close(done));server=await startServer(options);base=`http://127.0.0.1:${server.address().port}`;state={cookie:""};fetcher=fetcherFor(base,state);workspace=new ServerWorkspaceAdapter(fetcher);await workspace.authenticate("secret-a","field-a");const lifecycle=await workspace.lifecycle(),conversations=await(await fetcher("/api/pilot/conversations")).json(),visual=await workspace.getVisualEvidenceBundle({field_id:ids.field,season_id:ids.season,case_id:ids.case});assert.equal(lifecycle.fields[0].field_id,ids.field);assert.ok(conversations.conversations.some(item=>item.conversation_id===ids.conversation));assert.ok(visual.images.some(item=>item.image_evidence_id===ids.image));const other=await login(base,users[2]),foreign=await fetch(`${base}/api/pilot/visual-evidence-bundle?field_id=${ids.field}&crop_season_id=${ids.season}&case_id=${ids.case}`,{headers:{cookie:other.cookie}});assert.equal(foreign.status,403);assert.equal((await readdir(options.uploadDir)).length,1);
    assert.equal((await fetch(`${base}/api/pilot/verified-backups`,{method:"POST",headers:{cookie:state.cookie,"content-type":"application/json"},body:"{}"})).status,403);const administrator=await login(base,users[0]),backup=await(await fetch(`${base}/api/pilot/verified-backups`,{method:"POST",headers:{cookie:administrator.cookie,"content-type":"application/json"},body:"{}"})).json();assert.equal(backup.image_count,1);assert.equal(backup.image_integrity_state,"PASS");const restored=await(await fetch(`${base}/api/pilot/restore-verifications`,{method:"POST",headers:{cookie:administrator.cookie,"content-type":"application/json"},body:JSON.stringify({backup_file:backup.backup_file})})).json();assert.equal(restored.restore_verified,true);assert.equal(restored.image_integrity_state,"PASS");assert.equal(restored.image_count,1);
  }finally{if(server.listening)await new Promise(done=>server.close(done));await rm(root,{recursive:true,force:true,maxRetries:5,retryDelay:100});}
});

test("M0C deployment and browser assets declare persistent HTTPS hosting without localhost or client secrets",async()=>{
  const [render,operations,environment,index,fieldApp,mapAdapter]=await Promise.all([readFile(new URL("../../../render.yaml",import.meta.url),"utf8"),readFile(new URL("../HTTPS_MOBILE_PILOT_OPERATIONS.md",import.meta.url),"utf8"),readFile(new URL("../pilot-mobile.env.example",import.meta.url),"utf8"),readFile(new URL("../index.html",import.meta.url),"utf8"),readFile(new URL("../assets/field-app.js",import.meta.url),"utf8"),readFile(new URL("../assets/browser-map-adapter.js",import.meta.url),"utf8")]);
  for(const required of ["PILOT_PROFILE","FIELD_CAPTURE_ALPHA","PILOT_PUBLIC_BASE_URL","PILOT_USERS_JSON","GOOGLE_MAPS_BROWSER_KEY","/var/data/pilot.sqlite","/var/data/uploads","healthCheckPath: /health","autoDeploy: false"])assert.match(render,new RegExp(required.replace(/[.*+?^${}()|[\]\\]/g,"\\$&")));
  assert.match(operations,/https:\/\/<pilot-domain>\/\*/);assert.match(operations,/Android Chrome/);assert.match(operations,/iPhone Safari/);assert.match(operations,/database-plus-images restore rehearsal/);assert.doesNotMatch(environment,/secret-[ab]|browser-key-for-test/);assert.match(fieldApp,/accept="image\/\*"/);assert.match(fieldApp,/capture="environment"/);for(const source of [index,fieldApp,mapAdapter])assert.doesNotMatch(source,/https?:\/\/(?:localhost|127\.0\.0\.1)/);assert.doesNotMatch(`${index}\n${fieldApp}`,/OPENAI_API_KEY|localStorage\.setItem\([^)]*session|pilot_session=/);assert.match(mapAdapter,/api\/pilot\/map-configuration/);assert.match(mapAdapter,/OpenStreetMap/);
});
