import test from "node:test";
import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import { mkdtemp, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { createEmptyCandidateProvider } from "../candidate-provider.mjs";
import { PilotStore } from "../pilot-store.mjs";
import { GovernedSpaRuntime } from "../assets/governed-spa-runtime.js";

const scope={field_id:"field-rfv1-r1",season_id:"season-rfv1-r1"};
function lifecycle(){return{schema_version:2,users:[{user_id:"user-rfv1",role:"FIELD_USER"}],fields:[{...scope,owner_user_id:"user-rfv1",name:"แปลงทดสอบ RFV1",crop:"rice",planting_date:"2026-08-01",current_crop_stage:{code:"TILLERING",label:"แตกกอ",model_version:"field-stage-model/v1"},current_cmp_stage:{stage_id:"CMP-03",label:"ระยะแตกกอ",model_version:"field-stage-model/v1"},stage_provenance:"USER_CONFIRMED",created_at:"2026-09-01T00:00:00.000Z",updated_at:"2026-09-01T00:00:00.000Z"}],seasons:[{...scope,crop:"rice",status:"ACTIVE"}],guidance:[],activities:[],cases:[],observations:[],evidence:[],conversations:[],messages:[],decision_logs:[],case_summaries:[],weather_snapshots:[]};}
async function harness(){const root=await mkdtemp(join(tmpdir(),"cpmoakb-rfv1-r1-")),store=await new PilotStore({dbPath:join(root,"pilot.sqlite"),exportDir:join(root,"exports"),pilotProfile:"FIELD_CAPTURE_ALPHA",investigationCandidateProvider:createEmptyCandidateProvider()}).open();store.putWorkspace("user-rfv1",lifecycle());return{store,close:async()=>{store.close();await rm(root,{recursive:true,force:true});}};}
const turn=(message,extra={})=>({request_id:`rfv1-${crypto.randomUUID()}`,message,entry_point:"FIELD_INSPECTION",context_policy:"NEW_INSPECTION_SESSION",...scope,...extra});

test("RFV1-R1 exact Thai report yields one wide-photo action and an unreviewed authoritative Case binding",async()=>{const h=await harness();try{const result=await h.store.orchestrateConversationTurn("user-rfv1",turn("ใบข้าวเริ่มเหลืองบางกอ"));assert.equal(result.actions.length,1);assert.equal(result.actions[0].action,"REQUEST_VISUAL_EVIDENCE");assert.equal(result.evidence_action?.one_primary_action,true);assert.equal(result.evidence_action?.method,"IMAGE");assert.match(result.text,/ภาพมุมกว้าง/u);assert.match(result.text,/ต้นรอบข้าง/u);assert.ok(result.context.case_id);const bundle=h.store.getInvestigationBundle("user-rfv1",{...scope,case_id:result.context.case_id});assert.equal(bundle.cases.length,1);assert.equal(bundle.observations.length,1);assert.equal(bundle.observations[0].review_state,"UNREVIEWED");assert.equal(bundle.evidence[0].review_state,"UNREVIEWED");}finally{await h.close();}});

test("RFV1-R1 new inspection stays unbound for a generic report and does not silently resume an open Case",async()=>{const h=await harness();try{h.store.createInvestigationRecord("user-rfv1","CASE",{...scope,case_id:"case-existing",purpose:"เคสเดิม"});const before=h.store.db.prepare("SELECT COUNT(*) count FROM investigation_cases").get().count,result=await h.store.orchestrateConversationTurn("user-rfv1",turn("วันนี้เข้ามาดูแปลง"));assert.equal(result.context.case_id,null);assert.equal(result.evidence_action,null);assert.equal(h.store.db.prepare("SELECT COUNT(*) count FROM investigation_cases").get().count,before);assert.notEqual(h.store.getGovernedConversationHistory("user-rfv1",result.conversation_id).conversation.case_id,"case-existing");}finally{await h.close();}});

test("RFV1-R1 unbound inspection retains the governed no-action response without creating a Case",async()=>{const response={status:"AVAILABLE",message:"บันทึกรอบตรวจไว้แล้วครับ",governed_response:{conversation_id:"conversation-unbound",context:{...scope,case_id:null},evidence_action:null}},runtime=new GovernedSpaRuntime({workspace:{},llm:{chat:async()=>response},idProvider:()=>"rfv1-session"}),field={...scope,authority_state:"SERVER_CONFIRMED"};runtime.lifecycleState.fields=[field];runtime.beginInspectionCycle(field);const result=await runtime.captureStatement("วันนี้เข้ามาดูแปลง");assert.equal(result,response);assert.equal(runtime.caseState,null);assert.equal(runtime.inspectionState.conversation_id,"conversation-unbound");assert.equal(runtime.inspectionState.lastResponse,response);});

test("RFV1-R1 inspection surface exposes explicit entry choice, three upload controls, binding receipt, and safe fallback state",async()=>{const app=await readFile(new URL("../assets/field-app.js",import.meta.url),"utf8"),runtime=await readFile(new URL("../assets/governed-spa-runtime.js",import.meta.url),"utf8"),adapter=await readFile(new URL("../assets/server-llm-adapter.js",import.meta.url),"utf8"),css=await readFile(new URL("../assets/field-shell.css",import.meta.url),"utf8");assert.match(app,/inspection-choice/);assert.match(app,/เริ่มรอบตรวจใหม่/);assert.match(app,/ตรวจต่อในเคสเดิม/);assert.match(app,/data-governed-case-view/);assert.match(app,/capture="environment"/);assert.match(app,/📷 ถ่ายภาพ/);assert.match(app,/🖼 เลือกรูป/);assert.match(app,/📎 แนบไฟล์/);assert.match(app,/รับหลักฐานแล้ว/);assert.match(app,/กำลังใช้โหมดสำรอง/);assert.match(app,/session\.lastResponse/);assert.match(app,/case_label/);assert.match(runtime,/beginInspectionCycle/);assert.match(runtime,/NEW_INSPECTION_SESSION/);assert.match(adapter,/force_new_conversation/);assert.match(adapter,/context_policy/);assert.match(css,/inspection-binding-receipt/);assert.match(css,/overflow-wrap:anywhere/);});
