import test from "node:test";
import assert from "node:assert/strict";
import { mkdtemp, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { InvestigationCaptureAdapter, InvestigationDraftRepository } from "../assets/investigation-capture-adapter.js";
import { InvestigationIntelligenceEngine, StaticInvestigationRuleProvider } from "../investigation-intelligence.mjs";
import { PilotStore } from "../pilot-store.mjs";
import { startServer } from "../server.mjs";
import { MemoryStorage } from "./support.mjs";

const scope={field_id:"field-intelligence",season_id:"season-intelligence"};

function lifecycle(userId="user-a",stage="TILLERING",provenance="USER_CONFIRMED"){
  return {schema_version:2,users:[{user_id:userId}],fields:[{field_id:scope.field_id,owner_user_id:userId,name:"นา intelligence",polygon:{type:"Polygon",coordinates:[[[100,13],[100.01,13],[100,13.01],[100,13]]]},crop:"rice",planting_date:"2026-07-01",current_crop_stage:{code:stage,label:stage,model_version:"field-stage-model/v1"},current_cmp_stage:{stage_id:"CMP-03",label:"ระยะแตกกอ",model_version:"field-stage-model/v1"},season_id:scope.season_id,stage_provenance:provenance,created_at:"2026-07-01T00:00:00.000Z",updated_at:"2026-08-20T00:00:00.000Z"}],seasons:[{season_id:scope.season_id,field_id:scope.field_id,crop:"rice",status:"ACTIVE"}],guidance:[],activities:[],cases:[],observations:[],evidence:[],conversations:[],messages:[],decision_logs:[],case_summaries:[],weather_snapshots:[]};
}

function deterministicIds(){let value=0;return ()=>`00000000-0000-4000-8000-${String(++value).padStart(12,"0")}`;}
async function setup(ruleProvider=null){const root=await mkdtemp(join(tmpdir(),"cpmoakb-intelligence-")),store=await new PilotStore({dbPath:join(root,"pilot.sqlite"),exportDir:join(root,"exports"),investigationRuleProvider:ruleProvider,intelligenceClock:()=>new Date("2026-08-27T01:00:00Z"),intelligenceIdProvider:deterministicIds()}).open();store.putWorkspace("user-a",lifecycle());return {root,store,close:async()=>{store.close();await rm(root,{recursive:true,force:true});}};}
function create(store,type,record){return store.createInvestigationRecord("user-a",type,{...scope,...record});}

function goldenProvider(){return new StaticInvestigationRuleProvider({
  rule_version:"golden-step-c-fixture/v1",rule_authority:"BOUNDED_RUNTIME_RULE",rule_review_state:"HUMAN_REVIEWED",sufficiency_state:"SUFFICIENT_FOR_NARROWING",rules:[
    {rule_id:"rule-water-context",candidate_id:"candidate-water-root",dimension:"ENVIRONMENT",relation:"SUPPORTS",constraint:"COMMON",reason:"The explicit fixture declares affected-zone ponding relevant to this candidate without asserting cause.",source_refs:[{record_type:"WATER",record_id:"ev-water"}]},
    {rule_id:"rule-water-root-gap",candidate_id:"candidate-water-root",dimension:"ABIOTIC",relation:"REQUIRED_BUT_MISSING",constraint:"REQUIRED",reason:"Affected-versus-normal root condition remains required for this bounded comparison.",source_refs:[],missing_evidence:{gap_ref:"gap-root-comparison",concept:"ROOT_COMPARISON",importance:"REQUIRED",reason:"Root comparison is not present in the authoritative bundle."},next_best_evidence:{type:"FIELD_CHECK",target:"ROOT_COMPARISON",comparison:"AFFECTED_VS_NORMAL",purpose:"DISTINGUISH_COMPETING_FIELD_EXPLANATIONS",discrimination_goal:"Compare the water/root path with the sheath-related path.",value:"HIGH",reason:"The governed fixture identifies root comparison as the most discriminating feasible field evidence.",related_candidate_ids:["candidate-water-root","candidate-sheath"],existing_evidence_gap_refs:["gap-root-comparison"],stop_if:"Comparable root condition is recorded for affected and normal sites."}},
    {rule_id:"rule-sheath-stage",candidate_id:"candidate-sheath",dimension:"BIOLOGICAL_STAGE",relation:"WEAKLY_SUPPORTS",constraint:"POSSIBLE",reason:"The explicit fixture marks the authoritative stage as compatible, not identifying.",source_refs:[{record_type:"STAGE_ASSESSMENT",record_id:"stage-season-intelligence"}]},
    {rule_id:"rule-sheath-gap",candidate_id:"candidate-sheath",dimension:"MORPHOLOGY",relation:"REQUIRED_BUT_MISSING",constraint:"TYPICAL",reason:"Additional distinguishing morphology remains useful.",source_refs:[],missing_evidence:{gap_ref:"gap-sheath-detail",concept:"DISTINGUISHING_SHEATH_MORPHOLOGY",importance:"USEFUL",reason:"The current morphology is supportive but not resolving."},next_best_evidence:{type:"PHOTO",target:"DISTINGUISHING_SHEATH_VIEW",purpose:"DOCUMENT_REQUIRED_VIEW",discrimination_goal:"Record additional morphology without identifying a condition.",value:"MEDIUM",reason:"A governed additional view could address the morphology gap.",related_candidate_ids:["candidate-sheath"],existing_evidence_gap_refs:["gap-sheath-detail"]}},
    {rule_id:"rule-application-management",candidate_id:"candidate-application",dimension:"MANAGEMENT_HISTORY",relation:"WEAKLY_SUPPORTS",constraint:"POSSIBLE",reason:"A recent application is relevant context but not causal attribution.",source_refs:[{record_type:"MANAGEMENT_EVENT",record_id:"management-recent"}]},
    {rule_id:"rule-application-morphology",candidate_id:"candidate-application",dimension:"MORPHOLOGY",relation:"WEAKLY_SUPPORTS",constraint:"POSSIBLE",reason:"The fixture marks the morphology as compatible but nonspecific.",source_refs:[{record_type:"MORPHOLOGY",record_id:"ev-morphology"}]},
    {rule_id:"rule-application-temporal",candidate_id:"candidate-application",dimension:"TEMPORAL",relation:"CONTRADICTS",constraint:"CONTRADICTORY",reason:"Authoritative symptom evidence predates the recorded application, weakening it as the primary onset explanation without proving another cause.",source_refs:[{record_type:"TEMPORAL_RELATIONSHIP",record_id:"relation-symptom-before-application"}]},
  ],
});}

function buildGolden(store){
  const caseRecord=create(store,"CASE",{case_id:"case-step-c",purpose:"Compare explicitly authored hypotheses without diagnosis"}),observation=create(store,"OBSERVATION",{observation_id:"obs-step-c",case_id:caseRecord.case_id,observed_at:"2026-08-20T08:30:00Z",source:"FIELD_OBSERVED",note:"low-spot patch, yellowing, leaf-sheath lesion"});
  const spatial=create(store,"SPATIAL_EVIDENCE",{evidence_id:"ev-spatial",observation_id:observation.observation_id,case_id:caseRecord.case_id,source:"FIELD_OBSERVED",evidence_level:"SP2_MULTI_ZONE_SUPPORTED",payload:{observation_scope:"PATCH",geometry:"PATCH",field_positions:["LOW_SPOT"],patterns:["PATCH"],field_extent:"LOCAL",direction:"NO_CLEAR_DIRECTION",affected_status:"AFFECTED",location_provenance:"FIELD_MAP_SELECTED"}});
  const morphology=create(store,"MORPHOLOGY_EVIDENCE",{evidence_id:"ev-morphology",observation_id:observation.observation_id,case_id:caseRecord.case_id,source:"FIELD_OBSERVED",evidence_level:"MO1_DIRECT_OBSERVATION",payload:{plant_part:"LEAF_SHEATH",primary_phenotypes:["YELLOWING","LESION"],negative_evidence:[]}});
  const sampling=create(store,"SAMPLING_SESSION",{evidence_id:"ev-sampling",observation_id:observation.observation_id,case_id:caseRecord.case_id,source:"FIELD_OBSERVED",evidence_level:"SM2_MULTI_SITE_SAMPLED",payload:{sampling_mode:"S2_GUIDED_INVESTIGATION",sampling_unit:"TILLER",sites_count:4,units_per_site:25,sampling_method:"affected and comparison sites",affected_sites_count:2,comparison_sites_count:2,representativeness:"MULTI_ZONE_REPRESENTATIVE"}});
  const severity=create(store,"SEVERITY_MEASUREMENT",{evidence_id:"ev-severity",observation_id:observation.observation_id,case_id:caseRecord.case_id,source:"FIELD_OBSERVED",evidence_level:"SV3_SAMPLING_SUPPORTED",payload:{measurement_concept:"AFFECTED_TILLERS_PER_OBSERVED_TILLERS",numerator:18,denominator:100,unit:"COUNT_RATIO",sampling_reference_id:sampling.evidence_id,plant_part:"TILLER"}});assert.equal(severity.payload.derived_percent,18);
  create(store,"WATER_CONTEXT",{evidence_id:"ev-water",observation_id:observation.observation_id,case_id:caseRecord.case_id,source:"FIELD_OBSERVED",evidence_level:"WT2_ZONE_COMPARISON",payload:{water_state:"DEEP_PONDED",zone_reference:"affected area deeper than comparison",water_depth:{value:12,unit:"CM"},source:"FIELD_OBSERVED"}});
  const management=create(store,"MANAGEMENT_EVENT",{management_event_id:"management-recent",case_id:caseRecord.case_id,event_type:"FERTILIZER_APPLICATION",event_at:"2026-08-19T04:00:00Z",time_precision:"EXACT",source:"USER_REPORTED",reported_product_name:"unresolved report",product_identity_confidence:"UNKNOWN"});
  const earliest=create(store,"TEMPORAL_EVIDENCE",{temporal_evidence_id:"time-earliest",case_id:caseRecord.case_id,observation_id:observation.observation_id,event_kind:"EARLIEST_EVIDENCE_AT",event_at:"2026-08-19T03:00:00Z",time_precision:"EXACT",evidence_level:"TC2_DATE_SUPPORTED",source:"PHOTO_METADATA"});
  create(store,"TEMPORAL_RELATIONSHIP",{temporal_relationship_id:"relation-symptom-before-application",case_id:caseRecord.case_id,subject_type:"MANAGEMENT_EVENT",subject_id:management.management_event_id,object_type:"TEMPORAL_EVIDENCE",object_id:earliest.temporal_evidence_id,relation:"AFTER",incompatible_with_initial_cause:true,rationale:"Symptom evidence predates application."});
  for(const candidate of [{candidate_id:"candidate-water-root",candidate_class:"ROOT_ZONE_STRESS",label:"WATER_ROOT_STRESS"},{candidate_id:"candidate-sheath",candidate_class:"DISEASE",label:"SHEATH_RELATED_PROBLEM"},{candidate_id:"candidate-application",candidate_class:"APPLICATION_INJURY",label:"APPLICATION_INJURY"}])create(store,"CANDIDATE",{...candidate,case_id:caseRecord.case_id,support_state:"OPEN"});
  for(const link of [{candidate_evidence_link_id:"link-water-spatial",candidate_id:"candidate-water-root",relation:"SUPPORTING",evidence_id:spatial.evidence_id},{candidate_evidence_link_id:"link-water-spatial-duplicate",candidate_id:"candidate-water-root",relation:"SUPPORTING",evidence_id:spatial.evidence_id},{candidate_evidence_link_id:"link-sheath-morph",candidate_id:"candidate-sheath",relation:"SUPPORTING",evidence_id:morphology.evidence_id}])create(store,"CANDIDATE_EVIDENCE_LINK",{...link,case_id:caseRecord.case_id});
  return {caseRecord,observation};
}

test("only an authoritative bundle may enter scientific adjudication",()=>{
  const engine=new InvestigationIntelligenceEngine();
  assert.throws(()=>engine.assess({authority:"LOCAL_DRAFT_ONLY",candidates:[]}),/authoritative server Investigation Bundle/);
});

test("golden Step C assessment preserves competitors and selects one discriminating field check",async()=>{
  const h=await setup(goldenProvider());try{
    const {caseRecord}=buildGolden(h.store),assessment=h.store.assessInvestigation("user-a",{...scope,case_id:caseRecord.case_id}),byId=Object.fromEntries(assessment.candidate_assessments.map((item)=>[item.candidate_id,item]));
    assert.equal(assessment.scientific_input,"AUTHORITATIVE_INVESTIGATION_BUNDLE_ONLY");assert.equal(assessment.scope.case_id,caseRecord.case_id);assert.equal(assessment.candidate_assessments.length,3);
    assert.equal(byId["candidate-water-root"].state,"SUPPORTED");assert.equal(byId["candidate-water-root"].compatibility.SPATIAL,"SUPPORTIVE");assert.equal(byId["candidate-water-root"].compatibility.ENVIRONMENT,"SUPPORTIVE");assert.equal(byId["candidate-water-root"].supporting_evidence.filter((item)=>item.evidence_id==="ev-spatial").length,1,"duplicate links cannot double-count one evidence relation");
    assert.equal(byId["candidate-sheath"].state,"SUPPORTED");assert.equal(byId["candidate-sheath"].compatibility.MORPHOLOGY,"SUPPORTIVE");assert.equal(byId["candidate-application"].state,"WEAKENED");assert.equal(byId["candidate-application"].compatibility.MORPHOLOGY,"SUPPORTIVE");assert.equal(byId["candidate-application"].compatibility.TEMPORAL,"CONTRADICTORY");
    assert.equal(assessment.evidence_sufficiency.state,"SUFFICIENT_FOR_NARROWING");assert.equal(assessment.evidence_sufficiency.purpose_states.MANAGEMENT_OPTION_REVIEW,"INSUFFICIENT_FOR_NARROWING");
    assert.deepEqual({type:assessment.next_best_evidence.type,target:assessment.next_best_evidence.target,comparison:assessment.next_best_evidence.comparison,value:assessment.next_best_evidence.value},{type:"FIELD_CHECK",target:"ROOT_COMPARISON",comparison:"AFFECTED_VS_NORMAL",value:"HIGH"});assert.equal(Array.isArray(assessment.next_best_evidence),false);
    assert.equal(assessment.boundaries.candidate_is_diagnosis,false);assert.equal(assessment.boundaries.ranking_is_probability,false);assert.equal(assessment.boundaries.management_option_selected,false);assert.doesNotMatch(JSON.stringify(assessment),/"diagnosis"|"probability"|"product"|"active_ingredient"|"rate"|"recommendation"/i);
    const replay=h.store.assessInvestigation("user-a",{...scope,case_id:caseRecord.case_id});assert.equal(replay.assessment_id,assessment.assessment_id);assert.equal(replay.assessment_revision,1);
  }finally{await h.close();}
});

test("a local unsynced draft cannot alter the authoritative assessment",async()=>{
  const h=await setup(goldenProvider());try{
    const {caseRecord}=buildGolden(h.store),before=h.store.assessInvestigation("user-a",{...scope,case_id:caseRecord.case_id}),drafts=new InvestigationDraftRepository(new MemoryStorage()),capture=new InvestigationCaptureAdapter({draftRepository:drafts,server:{},cryptoProvider:{randomUUID:deterministicIds()}}),local=capture.createDraft(scope,{note:"non-authoritative pending hypothesis: anything"});
    assert.equal(local.state,"DRAFT_LOCAL");assert.equal(local.authority,"LOCAL_DRAFT_ONLY");
    const after=h.store.assessInvestigation("user-a",{...scope,case_id:caseRecord.case_id});assert.equal(after.assessment_id,before.assessment_id);assert.equal(after.source_bundle_hash,before.source_bundle_hash);assert.equal(JSON.stringify(after.candidate_assessments).includes(local.observation.note),false);
  }finally{await h.close();}
});

test("unknown and method-limited non-detection do not become contradiction",async()=>{
  const provider=new StaticInvestigationRuleProvider({rule_version:"negative-evidence-fixture/v1",rule_authority:"BOUNDED_RUNTIME_RULE",rule_review_state:"HUMAN_REVIEWED",rules:[
    {rule_id:"rule-unknown-negative",candidate_id:"candidate-unknown",dimension:"MORPHOLOGY",relation:"CONTRADICTS",constraint:"TYPICAL",reason:"Test unknown negative state.",source_refs:[{record_type:"MORPHOLOGY",record_id:"ev-negative"}],semantic_basis:"NEGATIVE_EVIDENCE",negative_feature:"unknown feature",inspection_method_appropriate:true},
    {rule_id:"rule-method-limited",candidate_id:"candidate-method",dimension:"MORPHOLOGY",relation:"CONTRADICTS",constraint:"TYPICAL",reason:"Test method-limited search.",source_refs:[{record_type:"MORPHOLOGY",record_id:"ev-negative"}],semantic_basis:"NEGATIVE_EVIDENCE",negative_feature:"searched feature",inspection_method_appropriate:false},
    {rule_id:"rule-valid-search",candidate_id:"candidate-valid",dimension:"MORPHOLOGY",relation:"CONTRADICTS",constraint:"TYPICAL",reason:"Appropriate observable search may weaken this candidate.",source_refs:[{record_type:"MORPHOLOGY",record_id:"ev-negative"}],semantic_basis:"NEGATIVE_EVIDENCE",negative_feature:"searched feature",inspection_method_appropriate:true},
  ]}),h=await setup(provider);try{
    const caseRecord=create(h.store,"CASE",{case_id:"case-negative",purpose:"negative evidence semantics"}),observation=create(h.store,"OBSERVATION",{observation_id:"obs-negative",case_id:caseRecord.case_id,source:"FIELD_OBSERVED"});
    create(h.store,"MORPHOLOGY_EVIDENCE",{evidence_id:"ev-negative",observation_id:observation.observation_id,case_id:caseRecord.case_id,source:"FIELD_OBSERVED",evidence_level:"MO1_DIRECT_OBSERVATION",payload:{plant_part:"LEAF_BLADE",primary_phenotypes:["YELLOWING"],negative_evidence:[{feature:"unknown feature",state:"UNKNOWN"},{feature:"searched feature",state:"SEARCHED_NOT_FOUND",search_method:"declared capable field inspection",target_observable:true}]}});
    for(const candidate_id of ["candidate-unknown","candidate-method","candidate-valid"])create(h.store,"CANDIDATE",{candidate_id,case_id:caseRecord.case_id,candidate_class:"UNKNOWN",support_state:"OPEN"});
    const result=h.store.assessInvestigation("user-a",{...scope,case_id:caseRecord.case_id}),byId=Object.fromEntries(result.candidate_assessments.map((item)=>[item.candidate_id,item]));
    assert.equal(byId["candidate-unknown"].state,"OPEN");assert.equal(byId["candidate-unknown"].compatibility.MORPHOLOGY,"NEUTRAL");assert.equal(byId["candidate-method"].state,"OPEN");assert.equal(byId["candidate-valid"].state,"WEAKENED");assert.equal(byId["candidate-valid"].compatibility.MORPHOLOGY,"CONTRADICTORY");assert.equal(result.uncertainty.filter((item)=>item.code==="NEGATIVE_EVIDENCE_NOT_DISPOSITIVE").length,2);
  }finally{await h.close();}
});

test("field evidence exhaustion is a successful unresolved result with expert handoff",async()=>{
  const provider=new StaticInvestigationRuleProvider({rule_version:"unresolved-fixture/v1",rule_authority:"BOUNDED_RUNTIME_RULE",rule_review_state:"HUMAN_REVIEWED",field_evidence_exhausted:true,sufficiency_state:"UNRESOLVABLE_WITH_CURRENT_FIELD_EVIDENCE",stop_condition:"FIELD_EVIDENCE_EXHAUSTED",rules:[{rule_id:"rule-specialist-gap",candidate_id:"candidate-unresolved",dimension:"VISUAL",relation:"REQUIRED_BUT_MISSING",constraint:"REQUIRED",reason:"No discriminating field or visual evidence remains feasible.",source_refs:[],missing_evidence:{gap_ref:"gap-specialist",concept:"SPECIALIST_IDENTIFICATION_BASIS",importance:"REQUIRED",reason:"The case cannot be resolved from current field evidence."},next_best_evidence:{type:"EXPERT_REVIEW",target:"SPECIALIST_CASE_REVIEW",purpose:"ESCALATE_UNRESOLVED_CASE",discrimination_goal:"Determine whether specialist or laboratory evidence is warranted.",value:"HIGH",reason:"Field evidence is exhausted without a safe finding.",related_candidate_ids:["candidate-unresolved"],existing_evidence_gap_refs:["gap-specialist"]}}]}),h=await setup(provider);try{
    const caseRecord=create(h.store,"CASE",{case_id:"case-unresolved",purpose:"allow true unresolved"});create(h.store,"CANDIDATE",{candidate_id:"candidate-unresolved",case_id:caseRecord.case_id,candidate_class:"UNKNOWN",support_state:"OPEN"});
    const result=h.store.assessInvestigation("user-a",{...scope,case_id:caseRecord.case_id});assert.equal(result.result_state,"UNRESOLVED");assert.equal(result.evidence_sufficiency.state,"UNRESOLVABLE_WITH_CURRENT_FIELD_EVIDENCE");assert.equal(result.stop_condition,"FIELD_EVIDENCE_EXHAUSTED");assert.equal(result.next_best_evidence.type,"EXPERT_REVIEW");assert.equal(result.candidate_assessments[0].state,"INSUFFICIENT");
  }finally{await h.close();}
});

test("a user hypothesis remains unsupported and never becomes a resolved disease",async()=>{
  const h=await setup();try{
    const caseRecord=create(h.store,"CASE",{case_id:"case-user-hypothesis",purpose:"retain user wording without diagnosis"});create(h.store,"CANDIDATE",{candidate_id:"candidate-user-hypothesis",case_id:caseRecord.case_id,candidate_class:"DISEASE",label:"น่าจะโรคไหม้",support_state:"OPEN",review_state:"UNREVIEWED"});
    const result=h.store.assessInvestigation("user-a",{...scope,case_id:caseRecord.case_id}),candidate=result.candidate_assessments[0];assert.equal(candidate.label,"น่าจะโรคไหม้");assert.equal(candidate.state,"INSUFFICIENT");assert.equal(candidate.consideration_basis.type,"PERSISTED_AUTHORED_CANDIDATE");assert.equal(candidate.missing_evidence[0].concept,"INDEPENDENT_SUPPORTING_EVIDENCE");assert.notEqual(candidate.state,"RESOLVED");assert.equal("diagnosis" in result,false);
  }finally{await h.close();}
});

test("no Candidate is a governed non-error outcome and a stop condition suppresses further questioning",async()=>{
  const empty=await setup();try{const caseRecord=create(empty.store,"CASE",{case_id:"case-no-candidates",purpose:"valid empty differential"}),result=empty.store.assessInvestigation("user-a",{...scope,case_id:caseRecord.case_id});assert.equal(result.result_state,"NO_CANDIDATES_AVAILABLE");assert.equal(result.candidate_assessments.length,0);assert.equal(result.evidence_sufficiency.state,"INSUFFICIENT_FOR_NARROWING");}finally{await empty.close();}
  const provider=new StaticInvestigationRuleProvider({rule_version:"stop-fixture/v1",rule_authority:"BOUNDED_RUNTIME_RULE",rule_review_state:"HUMAN_REVIEWED",stop_condition:"ENOUGH_FOR_CURRENT_DECISION",sufficiency_state:"SUFFICIENT_FOR_HUMAN_FINDING",rules:[],next_best_evidence:[{type:"QUESTION",target:"UNNECESSARY_FOLLOW_UP",purpose:"TEST_STOP_BOUNDARY",discrimination_goal:"This request must be suppressed by the stop condition.",value:"HIGH",reason:"Fixture request that must not escape.",related_candidate_ids:["candidate-reviewed"]}]}),stopped=await setup(provider);try{const caseRecord=create(stopped.store,"CASE",{case_id:"case-stopped",purpose:"stop endless questioning"}),observation=create(stopped.store,"OBSERVATION",{observation_id:"obs-stopped",case_id:caseRecord.case_id,source:"FIELD_OBSERVED"}),evidence=create(stopped.store,"SPATIAL_EVIDENCE",{evidence_id:"ev-stopped",observation_id:observation.observation_id,case_id:caseRecord.case_id,source:"FIELD_OBSERVED",evidence_level:"SP1_SITE_SUPPORTED",payload:{observation_scope:"PATCH",geometry:"PATCH",field_extent:"LOCAL",location_provenance:"USER_REPORTED"}});create(stopped.store,"CANDIDATE",{candidate_id:"candidate-reviewed",case_id:caseRecord.case_id,candidate_class:"UNKNOWN",support_state:"RESOLVED",review_state:"HUMAN_REVIEWED"});create(stopped.store,"CANDIDATE_EVIDENCE_LINK",{candidate_evidence_link_id:"link-reviewed-support",case_id:caseRecord.case_id,candidate_id:"candidate-reviewed",relation:"SUPPORTING",evidence_id:evidence.evidence_id,rationale:"Explicit human-reviewed resolution basis retained as a scoped link."});const result=stopped.store.assessInvestigation("user-a",{...scope,case_id:caseRecord.case_id});assert.equal(result.stop_condition,"ENOUGH_FOR_CURRENT_DECISION");assert.equal(result.next_best_evidence,null);assert.equal(result.candidate_assessments[0].state,"RESOLVED");}finally{await stopped.close();}
});

test("human correction preserves the system snapshot and evidence/stage changes invalidate it",async()=>{
  const h=await setup(goldenProvider());try{
    const {caseRecord,observation}=buildGolden(h.store),first=h.store.assessInvestigation("user-a",{...scope,case_id:caseRecord.case_id}),reviewed=h.store.reviewInvestigationAssessment("user-a",{assessment_id:first.assessment_id,action:"CORRECT",rationale:"Reviewer retains the engine output but disputes one candidate state.",corrections:[{target:"CANDIDATE_STATE",candidate_id:"candidate-application",value:"OPEN",reason:"Qualified review requires more context."}]});
    assert.deepEqual(reviewed.system_assessment.candidate_assessments,first.candidate_assessments);assert.equal(reviewed.review.original_system_assessment_preserved,true);assert.equal(reviewed.review.cross_layer_promotion,false);assert.equal(reviewed.review_history.length,1);
    const updated={observation_id:observation.observation_id,...scope,case_id:caseRecord.case_id,observed_at:observation.observed_at,source:observation.source,confidence:observation.confidence,review_state:observation.review_state,note:"updated authoritative observation"};h.store.updateInvestigationRecord("user-a","OBSERVATION",observation.observation_id,1,updated,"request-intelligence-evidence-update");
    const second=h.store.assessInvestigation("user-a",{...scope,case_id:caseRecord.case_id});assert.equal(second.assessment_revision,2);assert.notEqual(second.source_bundle_hash,first.source_bundle_hash);let history=h.store.getInvestigationAssessmentHistory("user-a",{...scope,case_id:caseRecord.case_id});assert.equal(history[0].stale,true);assert.equal(history[0].review_history.length,1);assert.equal(history[1].stale,false);assert.throws(()=>h.store.reviewInvestigationAssessment("user-a",{assessment_id:first.assessment_id,action:"MARK_UNRESOLVED",rationale:"stale review attempt"}),/stale assessment/);
    const findingReview=h.store.reviewInvestigationAssessment("user-a",{assessment_id:second.assessment_id,action:"RESOLVE_FINDING",rationale:"Human-reviewed bounded finding for the declared investigation purpose only.",resolution_level:"FIELD_REVIEWED_FINDING",candidate_findings:[{candidate_id:"candidate-water-root",role:"PRIMARY_FINDING"},{candidate_id:"candidate-sheath",role:"COEXISTING_CONDITION"}]});assert.equal(findingReview.review.candidate_findings.length,2);assert.equal(findingReview.review.cross_layer_promotion,false);assert.ok(findingReview.system_assessment.candidate_assessments.every((item)=>item.resolution_role===null),"human review cannot overwrite the prior engine snapshot");
    h.store.putWorkspace("user-a",lifecycle("user-a","PANICLE_INITIATION","USER_OVERRIDDEN"));const third=h.store.assessInvestigation("user-a",{...scope,case_id:caseRecord.case_id});assert.equal(third.assessment_revision,3);assert.notEqual(third.source_bundle_hash,second.source_bundle_hash);history=h.store.getInvestigationAssessmentHistory("user-a",{...scope,case_id:caseRecord.case_id});assert.deepEqual(history.map((item)=>item.stale),[true,true,false]);
    create(h.store,"CANDIDATE_EVIDENCE_LINK",{candidate_evidence_link_id:"link-after-assessment",case_id:caseRecord.case_id,candidate_id:"candidate-application",relation:"CONTRADICTING",evidence_id:"ev-spatial",rationale:"New explicit relationship requires reassessment."});const fourth=h.store.assessInvestigation("user-a",{...scope,case_id:caseRecord.case_id});assert.equal(fourth.assessment_revision,4);assert.notEqual(fourth.source_bundle_hash,third.source_bundle_hash);history=h.store.getInvestigationAssessmentHistory("user-a",{...scope,case_id:caseRecord.case_id});assert.deepEqual(history.map((item)=>item.stale),[true,true,true,false]);
  }finally{await h.close();}
});

test("assessment API is session-scoped and records attributed review history",async()=>{
  const root=await mkdtemp(join(tmpdir(),"cpmoakb-intelligence-api-")),dbPath=join(root,"pilot.sqlite"),exportDir=join(root,"exports"),seed=await new PilotStore({dbPath,exportDir}).open();seed.putWorkspace("user-a",lifecycle());const caseRecord=create(seed,"CASE",{case_id:"case-api-intelligence",purpose:"API assessment"});create(seed,"CANDIDATE",{candidate_id:"candidate-api",case_id:caseRecord.case_id,candidate_class:"UNKNOWN",support_state:"OPEN"});seed.close();
  const server=await startServer({port:0,dbPath,exportDir,uploadDir:join(root,"uploads")});try{
    const base=`http://127.0.0.1:${server.address().port}`,login=async(user_id)=>{const response=await fetch(`${base}/api/pilot/session`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({password:"1234",user_id})});return response.headers.get("set-cookie").split(";")[0];},cookie=await login("user-a"),url=`${base}/api/pilot/investigation-assessment?field_id=${scope.field_id}&season_id=${scope.season_id}&case_id=${caseRecord.case_id}`,assessmentResponse=await fetch(url,{headers:{cookie}}),assessment=await assessmentResponse.json();
    assert.equal(assessmentResponse.status,200);assert.equal(assessment.authority,"SERVER_DERIVED_INVESTIGATION_ASSESSMENT");const reviewResponse=await fetch(`${base}/api/pilot/investigation-assessment-reviews`,{method:"POST",headers:{cookie,"content-type":"application/json"},body:JSON.stringify({assessment_id:assessment.assessment_id,action:"MARK_UNRESOLVED",rationale:"No finding is authorized from the current evidence."})}),review=await reviewResponse.json();assert.equal(reviewResponse.status,201);assert.equal(review.status,"REVIEW_RECORDED");assert.equal(review.review.reviewer_user_id,"user-a");
    const foreignCookie=await login("user-b"),foreign=await fetch(url,{headers:{cookie:foreignCookie}});assert.equal(foreign.status,403);
  }finally{await new Promise((done)=>server.close(done));await rm(root,{recursive:true,force:true});}
});
