import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtemp, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { readFile } from 'node:fs/promises';
import { PilotStore } from '../pilot-store.mjs';
import { startServer } from '../server.mjs';
import {
  NOMINATION_TYPES,NOMINATION_SOURCES,SOURCE_AUTHORITY_CLASSES,PROMOTION_GATES,GRAPH_EDGE_TYPES
} from '../learning-knowledge-graph-runtime.mjs';

const now='2026-08-28T06:00:00.000Z';
function ids(){let value=0;return()=> 'i-id-'+(++value);}
function lifecycle(userId='user-a'){
  const fields=['a','b'].map((suffix,index)=>({field_id:'field-'+suffix,owner_user_id:userId,name:'private field '+suffix,polygon:{type:'Polygon',coordinates:[[[100+index,13],[100.01+index,13],[100+index,13.01],[100+index,13]]]},centroid:{latitude:13.005,longitude:100.005+index},crop:'rice',planting_date:'2026-07-01',current_crop_stage:{code:'TILLERING',label:'แตกกอ'},current_cmp_stage:{stage_id:'CMP-03',label:'ระยะแตกกอ'},season_id:'season-'+suffix,stage_provenance:'USER_CONFIRMED',created_at:'2026-07-01T00:00:00.000Z',updated_at:'2026-08-20T00:00:00.000Z'}));
  return{schema_version:2,users:[{user_id:userId}],fields,seasons:fields.map((field)=>({season_id:field.season_id,field_id:field.field_id,crop:'rice',status:'ACTIVE'})),guidance:[],activities:[],cases:[],observations:[],evidence:[],conversations:[],messages:[],decision_logs:[],case_summaries:[],weather_snapshots:[]};
}
async function setup(){
  const root=await mkdtemp(join(tmpdir(),'cpmoakb-i-')),store=await new PilotStore({dbPath:join(root,'pilot.sqlite'),exportDir:join(root,'exports'),learningClock:()=>new Date(now),learningIdProvider:ids()}).open(),userId='user-a';store.putWorkspace(userId,lifecycle(userId));
  for(const suffix of ['a','b']){const scope={field_id:'field-'+suffix,season_id:'season-'+suffix};store.createInvestigationRecord(userId,'CASE',{...scope,case_id:'case-'+suffix,purpose:'Step I reviewed learning test',opened_at:'2026-08-20T01:00:00Z'});store.createInvestigationRecord(userId,'OBSERVATION',{...scope,observation_id:'obs-'+suffix,case_id:'case-'+suffix,observed_at:'2026-08-20T02:00:00Z',source:'FIELD_OBSERVED',confidence:'MODERATE',review_state:'HUMAN_REVIEWED',note:'reviewed bounded observation'});}
  return{root,store,userId,close:async()=>{store.close();await rm(root,{recursive:true,force:true});}};
}
function nomination(caseId='case-a',values={}){const suffix=caseId.at(-1);return{request_id:'nom-'+suffix,learning_nomination_id:'learning-'+suffix,type:'CANDIDATE_RELATIONSHIP_GAP',field_id:'field-'+suffix,season_id:'season-'+suffix,case_id:caseId,source_type:'STEP_C_GAP',source_ref:'assessment-'+suffix,subject_entity_id:'concept-leaf-folder',raw_description:'No governed Candidate relationship was available.',structured_gap:{gap_code:'MISSING_CANDIDATE_RELATIONSHIP'},proposed_scope:'rice field investigation',supporting_refs:['assessment-'+suffix],privacy_state:'CLEARED',consent_or_usage_rights_state:'CLEARED',...values};}
function bundle(values={}){return{request_id:'bundle-1',reviewed_case_bundle_id:'bundle-i',case_refs:['case-a','case-b'],included_case_ids:['case-a'],excluded_cases:[{case_id:'case-b',reason:'Reviewer found incompatible sampling context'}],step_c_refs:['assessment-a'],guidance_refs:['guidance-a'],management_review_refs:['f1-a'],decision_refs:['decision-a'],action_refs:['action-a'],outcome_refs:['outcome-a'],reviewed_visual_refs:['visual-a'],supporting_refs:['evidence-a'],contradicting_refs:['evidence-b'],gaps:['SAMPLING_INCOMPATIBLE'],alternative_explanations:['water context'],reviewer:{reviewer_reference:'reviewer-1',role:'DOMAIN_REVIEWER',scope_of_authority:'bounded rice field review',decision:'READY_FOR_ASSERTION_CANDIDATE',rationale:'Case A retained and Case B explicitly excluded.',independence_review_state:'REVIEWED'},privacy_state:'CLEARED',consent_or_usage_rights_state:'CLEARED',limitations:['Field-derived and locally bounded'],...values};}
function assertion(bundleId='bundle-i',values={}){return{request_id:'assertion-1',knowledge_assertion_candidate_id:'assertion-field',subject_entity_id:'concept-leaf-folder',predicate:'RELATED_TO_CONCEPT',object_entity_id:'phenotype-folded-leaf',claim_type:'RELATIONSHIP',scope:'CASE_DERIVED',crop_scope:'rice',stage_scope:'TILLERING',spatial_scope:'reviewed Field only',temporal_scope:'2026 season',source_class:'FIELD_DERIVED_LOCAL_KNOWLEDGE',supporting_refs:['evidence-a'],contradicting_refs:[],reviewed_case_bundle_refs:[bundleId],local_pattern_refs:[],limitations:['Does not establish diagnosis or prevalence'],alternative_explanations:[],identity_state:'RESOLVED',evidence_state:'REVIEWED_CASE_BUNDLE_READY',authority_target:'FIELD_DERIVED_LOCAL_KNOWLEDGE',provenance:['reviewer-1'],...values};}
function review(assertionId='assertion-field',values={}){return{request_id:'promotion-1',promotion_id:'promotion-i',assertion_candidate_id:assertionId,expected_promotion_count:0,reviewed_gates:[],review:{submitted_explicitly:true,reviewer_reference:'domain-reviewer-1',role:'DOMAIN_REVIEWER',scope_of_authority:'bounded local rice knowledge',decision:'APPROVE_FOR_GOVERNED_LOCAL_KNOWLEDGE',rationale:'Approve only as bounded field-derived governed knowledge.',supporting_evidence:['bundle-i'],contradicting_evidence:[],limitations:['Not scientific or regulatory authority'],source_versions:['bundle-i'],context_hash:'review-context'},...values};}

test('Step I publishes closed nominations, source classes, gates, and graph vocabulary',()=>{assert.ok(NOMINATION_TYPES.includes('THAI_LANGUAGE_MAPPING_GAP'));assert.ok(NOMINATION_SOURCES.includes('STEP_H_LOCAL_PATTERN'));assert.deepEqual(SOURCE_AUTHORITY_CLASSES.includes('SCIENTIFIC_AUTHORITY'),true);assert.deepEqual(PROMOTION_GATES,new Set(PROMOTION_GATES).size===PROMOTION_GATES.length?[...PROMOTION_GATES]:[]);assert.ok(GRAPH_EDGE_TYPES.includes('CONFLICTS_WITH'));});

test('I-1/I-3: Learning Nomination and Thai phrase mapping create no Claim or canonical mutation',async()=>{const h=await setup();try{const saved=h.store.createLearningNomination(h.userId,nomination());assert.equal(saved.nomination_is_claim,false);assert.equal(saved.canonical_knowledge_changed,false);assert.equal(saved.candidate_provider_changed,false);assert.equal(saved.training_eligible,false);const thai=h.store.createLearningNomination(h.userId,{request_id:'thai-gap',source_type:'CONVERSATION_MAPPING_GAP',raw_description:'จำคำว่าข้าวจ๋อยไว้หน่อย',subject_entity_id:'phrase-khao-joi'});assert.equal(thai.type,'THAI_LANGUAGE_MAPPING_GAP');assert.equal(thai.structured_gap.original_phrase,'จำคำว่าข้าวจ๋อยไว้หน่อย');assert.match(thai.friendly_thai_response,/ยังไม่เปลี่ยนความรู้หลัก/);assert.equal(h.store.interpretLearningIntent('ไม่แน่ใจ').clarification_count,1);}finally{await h.close();}});

test('I-2/I-12/I-16: deterministic grouping is operational priority, never prevalence or biological risk',async()=>{const h=await setup();try{h.store.createLearningNomination(h.userId,nomination());h.store.createLearningNomination(h.userId,nomination('case-b'));const gaps=h.store.getKnowledgeGaps(h.userId);assert.equal(gaps.length,1);assert.equal(gaps[0].frequency_count,2);assert.equal(gaps[0].distinct_case_count,2);assert.equal(gaps[0].distinct_field_count,2);assert.equal(gaps[0].scientific_claim,false);assert.equal(gaps[0].prevalence_inference,null);const queue=h.store.getKnowledgeWorkQueue(h.userId);assert.equal(queue[0].priority_band,'REVIEW_READY');assert.equal(queue[0].priority_is_biological_risk,false);assert.equal(queue[0].priority_is_prevalence,false);}finally{await h.close();}});

test('Faculty/ChatGPT and source-extraction hooks remain Working or Candidate knowledge',async()=>{const h=await setup();try{assert.throws(()=>h.store.createLearningNomination(h.userId,{request_id:'bad-faculty',type:'KNOWLEDGE_GAP',source_type:'CHATGPT_RESEARCH_NOTE',raw_description:'waterlogging may impair root function'}),/WORKING_KNOWLEDGE/);const note=h.store.createLearningNomination(h.userId,{request_id:'faculty',type:'WORKING_KNOWLEDGE',source_type:'FACULTY_WORKING_KNOWLEDGE',raw_description:'waterlogging may impair root function',structured_gap:{gap_code:'SOURCE_NOT_BOUND'}});assert.equal(note.nomination_is_claim,false);const extraction=h.store.createLearningNomination(h.userId,{request_id:'pdf-hook',type:'SOURCE_EXTRACTION_CANDIDATE',source_type:'SOURCE_EXTRACTION_CANDIDATE',raw_description:'Future PDF source span requires review.',structured_gap:{gap_code:'SOURCE_SPAN_REVIEW_REQUIRED'}});assert.equal(extraction.automatic_learning,false);assert.equal(h.store.db.prepare('SELECT COUNT(*) count FROM governed_knowledge_assertion_candidates').get().count,0);}finally{await h.close();}});

test('I-4: Reviewed Case Bundle is immutable, privacy-scoped, explicit about inclusion, and not Knowledge',async()=>{const h=await setup();try{const saved=h.store.createReviewedCaseBundle(h.userId,bundle());assert.equal(saved.immutable,true);assert.equal(saved.bundle_is_knowledge,false);assert.equal(saved.maturity.level,'LE2');assert.deepEqual(saved.included_case_ids,['case-a']);assert.deepEqual(saved.excluded_cases,[{case_id:'case-b',reason:'Reviewer found incompatible sampling context'}]);assert.equal(saved.independence_review_state,'REVIEWED');assert.equal(saved.independence_detail.state,'ADEQUATE');assert.equal(saved.case_snapshots.some((item)=>'_geometry' in item),false);assert.equal(saved.bundle_hash.length,64);assert.equal(h.store.createReviewedCaseBundle(h.userId,bundle()).idempotent_replay,true);assert.throws(()=>h.store.createReviewedCaseBundle(h.userId,bundle({request_id:'duplicate-bundle',reviewed_case_bundle_id:'duplicate-bundle',case_refs:['case-a','case-a'],included_case_ids:['case-a'],excluded_cases:[]})),/duplicate Case/);assert.equal(h.store.getReviewedCaseBundles('user-b').length,0);}finally{await h.close();}});

test('I-5/I-7/I-15: Entity and Assertions stay separate with four non-inheriting authorities and preserved conflict',async()=>{const h=await setup();try{h.store.createReviewedCaseBundle(h.userId,bundle());const field=h.store.createKnowledgeAssertionCandidate(h.userId,assertion());const scientific=h.store.createKnowledgeAssertionCandidate(h.userId,assertion('bundle-i',{request_id:'assertion-science',knowledge_assertion_candidate_id:'assertion-science',source_class:'SCIENTIFIC_AUTHORITY',scope:'published study scope',reviewed_case_bundle_refs:[],scientific_source_refs:['paper-1'],authority_target:'SCIENTIFIC_AUTHORITY',conflicting_assertion_candidate_ids:[field.knowledge_assertion_candidate_id]}));const regulatory=h.store.createKnowledgeAssertionCandidate(h.userId,assertion('bundle-i',{request_id:'assertion-reg',knowledge_assertion_candidate_id:'assertion-reg',source_class:'REGULATORY_AUTHORITY',scope:'Thailand registration identity only',reviewed_case_bundle_refs:[],regulatory_source_refs:['official-reg-1'],authority_target:'REGULATORY_AUTHORITY'}));const manufacturer=h.store.createKnowledgeAssertionCandidate(h.userId,assertion('bundle-i',{request_id:'assertion-mfg',knowledge_assertion_candidate_id:'assertion-mfg',source_class:'MANUFACTURER_COMMERCIAL_SOURCE',scope:'attributed product claim',reviewed_case_bundle_refs:[],manufacturer_source_refs:['manufacturer-1'],authority_target:'MANUFACTURER_COMMERCIAL_SOURCE'}));const graph=h.store.getUnifiedKnowledgeGraph(h.userId,'concept-leaf-folder');assert.equal(graph.nodes.filter((item)=>item.node_type==='ENTITY'&&item.node_id==='concept-leaf-folder').length,1);assert.equal(graph.assertions.length,4);assert.deepEqual(new Set(graph.assertions.map((item)=>item.source_class)),new Set(['FIELD_DERIVED_LOCAL_KNOWLEDGE','SCIENTIFIC_AUTHORITY','REGULATORY_AUTHORITY','MANUFACTURER_COMMERCIAL_SOURCE']));assert.equal(graph.authority_classes.every((item)=>item.inherits_from.length===0),true);assert.ok(graph.conflicts.some((item)=>item.from===scientific.knowledge_assertion_candidate_id&&item.to===field.knowledge_assertion_candidate_id));assert.equal(regulatory.regulatory_authority,true);assert.equal(manufacturer.scientific_authority,false);}finally{await h.close();}});

test('identity cannot be merged by label and authority cannot be transferred',async()=>{const h=await setup();try{h.store.createReviewedCaseBundle(h.userId,bundle());assert.throws(()=>h.store.createKnowledgeAssertionCandidate(h.userId,assertion('bundle-i',{authority_target:'SCIENTIFIC_AUTHORITY'})),/transfer source authority/);const a=h.store.createKnowledgeAssertionCandidate(h.userId,assertion('bundle-i',{request_id:'identity-a',knowledge_assertion_candidate_id:'identity-a',subject_entity_id:'concept-a',literal_value:'ข้าวจ๋อย',object_entity_id:undefined})),b=h.store.createKnowledgeAssertionCandidate(h.userId,assertion('bundle-i',{request_id:'identity-b',knowledge_assertion_candidate_id:'identity-b',subject_entity_id:'concept-b',literal_value:'ข้าวจ๋อย',object_entity_id:undefined}));const graph=h.store.getUnifiedKnowledgeGraph(h.userId);assert.equal(graph.nodes.filter((item)=>item.node_type==='ENTITY'&&['concept-a','concept-b'].includes(item.node_id)).length,2);assert.notEqual(a.subject_entity_id,b.subject_entity_id);}finally{await h.close();}});

test('I-7: explicit gates and Domain Review approve only field-derived governed knowledge',async()=>{const h=await setup();try{h.store.createReviewedCaseBundle(h.userId,bundle());h.store.createKnowledgeAssertionCandidate(h.userId,assertion());const promotion=h.store.createKnowledgePromotionReview(h.userId,review());assert.equal(promotion.gate_results.length,PROMOTION_GATES.length);assert.equal(promotion.gate_results.every((item)=>item.hidden_weight===null),true);assert.equal(promotion.all_gates_passed,true);assert.equal(promotion.to_state,'DOMAIN_REVIEWED_GOVERNED_ASSERTION');assert.equal(promotion.maturity.level,'LE4');assert.equal(promotion.governed_assertion.state,'FIELD_DERIVED_GOVERNED_KNOWLEDGE');assert.equal(promotion.governed_assertion.scientific_authority,false);assert.equal(promotion.governed_assertion.regulatory_authority,false);assert.equal(promotion.training_eligible,false);assert.equal(promotion.candidate_provider_changed,false);assert.equal(promotion.management_rules_changed,false);assert.equal(promotion.confidence_percentage,null);}finally{await h.close();}});

test('I-8: canonical review queue creates no canonical or runtime rule mutation',async()=>{const h=await setup();try{h.store.createReviewedCaseBundle(h.userId,bundle());h.store.createKnowledgeAssertionCandidate(h.userId,assertion());const result=h.store.createKnowledgePromotionReview(h.userId,review('assertion-field',{request_id:'canonical-review',promotion_id:'canonical-promotion',review:{...review().review,decision:'APPROVE_FOR_CANONICAL_REVIEW_QUEUE'}}));assert.equal(result.to_state,'CANONICAL_REVIEW_CANDIDATE');assert.equal(result.canonical_review_candidate,true);assert.equal(result.canonical_knowledge_changed,false);assert.equal(result.candidate_provider_changed,false);const providerBefore=await readFile(new URL('../candidate-provider-package.json',import.meta.url),'utf8'),providerAfter=await readFile(new URL('../candidate-provider-package.json',import.meta.url),'utf8');assert.equal(providerAfter,providerBefore);}finally{await h.close();}});

test('rejection, deferral, and split remain durable history with lineage',async()=>{const h=await setup();try{h.store.createReviewedCaseBundle(h.userId,bundle());h.store.createKnowledgeAssertionCandidate(h.userId,assertion());const rejected=h.store.createKnowledgePromotionReview(h.userId,review('assertion-field',{request_id:'reject',promotion_id:'reject-id',review:{...review().review,decision:'REJECT_ASSERTION'}}));const deferred=h.store.createKnowledgePromotionReview(h.userId,review('assertion-field',{request_id:'defer',promotion_id:'defer-id',expected_promotion_count:1,review:{...review().review,decision:'DEFER'}}));const split=h.store.createKnowledgePromotionReview(h.userId,review('assertion-field',{request_id:'split',promotion_id:'split-id',expected_promotion_count:2,review:{...review().review,decision:'SPLIT_ASSERTION'},split_assertions:[{knowledge_assertion_candidate_id:'split-child',subject_entity_id:'concept-leaf-folder',predicate:'RELATED_TO_CONCEPT',object_entity_id:'phenotype-folded-leaf-local',provenance:['split-review']}]}));assert.equal(rejected.to_state,'REJECTED');assert.equal(deferred.to_state,'DEFERRED');assert.deepEqual(split.split_lineage.child_assertion_candidate_ids,['split-child']);assert.equal(h.store.getKnowledgePromotionHistory(h.userId).length,3);assert.equal(h.store.getKnowledgeAssertionCandidates(h.userId).find((item)=>item.knowledge_assertion_candidate_id==='split-child').supersedes_candidate_id,'assertion-field');}finally{await h.close();}});

test('I-13: source correction marks Bundle, Candidate, and prior promotion stale without erasing snapshots',async()=>{const h=await setup();try{h.store.createReviewedCaseBundle(h.userId,bundle());h.store.createKnowledgeAssertionCandidate(h.userId,assertion());h.store.createKnowledgePromotionReview(h.userId,review());h.store.updateInvestigationRecord(h.userId,'OBSERVATION','obs-a',1,{observation_id:'obs-a',field_id:'field-a',season_id:'season-a',case_id:'case-a',observed_at:'2026-08-20T02:00:00Z',source:'FIELD_OBSERVED',confidence:'MODERATE',review_state:'HUMAN_REVIEWED',note:'corrected bounded observation'},'correct-i-source');assert.equal(h.store.getReviewedCaseBundles(h.userId)[0].projected_review_state,'STALE_REVIEW_REQUIRED');assert.equal(h.store.getKnowledgeAssertionCandidates(h.userId)[0].projected_promotion_state,'STALE_REVIEW_REQUIRED');const history=h.store.getKnowledgePromotionHistory(h.userId);assert.equal(history[0].projected_to_state,'STALE_REVIEW_REQUIRED');assert.equal(history.length,1);assert.equal(h.store.db.prepare('SELECT COUNT(*) count FROM governed_reviewed_case_bundles').get().count,1);}finally{await h.close();}});

test('idempotency and optimistic promotion concurrency fail closed',async()=>{const h=await setup();try{h.store.createReviewedCaseBundle(h.userId,bundle());h.store.createKnowledgeAssertionCandidate(h.userId,assertion());const first=h.store.createKnowledgePromotionReview(h.userId,review());assert.equal(h.store.createKnowledgePromotionReview(h.userId,review()).idempotent_replay,true);assert.throws(()=>h.store.createKnowledgePromotionReview(h.userId,review('assertion-field',{request_id:'stale-write',promotion_id:'stale-id',expected_promotion_count:0})),/changed before submission/);assert.equal(h.store.getKnowledgePromotionHistory(h.userId).filter((item)=>item.promotion_id===first.promotion_id).length,1);}finally{await h.close();}});

test('Timeline references learning lifecycle records but never treats them as Evidence',async()=>{const h=await setup();try{h.store.createLearningNomination(h.userId,nomination());h.store.createReviewedCaseBundle(h.userId,bundle());h.store.createKnowledgeAssertionCandidate(h.userId,assertion());h.store.createKnowledgePromotionReview(h.userId,review());const timeline=h.store.getAuthoritativeTimeline(h.userId,{field_id:'field-a',season_id:'season-a',case_id:'case-a'}),types=new Set(timeline.events.map((item)=>item.source_record_type));for(const type of ['LEARNING_NOMINATION','REVIEWED_CASE_BUNDLE','KNOWLEDGE_ASSERTION_CANDIDATE','KNOWLEDGE_PROMOTION_REVIEW'])assert.ok(types.has(type));assert.equal(timeline.events.filter((item)=>types.has(item.source_record_type)).every((item)=>!item.summary.includes('created Evidence')),true);assert.match(timeline.events.find((item)=>item.source_record_type==='KNOWLEDGE_PROMOTION_REVIEW').summary,/not Evidence/);}finally{await h.close();}});

test('Step I APIs are authenticated, cross-device reconstructable, and privacy scoped',async()=>{const h=await setup();h.store.createLearningNomination(h.userId,nomination());h.store.close();const server=await startServer({port:0,dbPath:join(h.root,'pilot.sqlite'),exportDir:join(h.root,'exports'),uploadDir:join(h.root,'uploads'),learningClock:()=>new Date(now),learningIdProvider:ids()});try{const base='http://127.0.0.1:'+server.address().port,login=await fetch(base+'/api/pilot/session',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({password:'1234',user_id:'user-a'})}),cookie=login.headers.get('set-cookie').split(';')[0];assert.equal((await fetch(base+'/api/pilot/learning-nominations')).status,401);const inbox=await (await fetch(base+'/api/pilot/learning-nominations',{headers:{cookie}})).json();assert.equal(inbox.nominations.length,1);assert.equal((await fetch(base+'/api/pilot/knowledge-gaps',{headers:{cookie}})).status,200);assert.equal((await fetch(base+'/api/pilot/knowledge-work-queue',{headers:{cookie}})).status,200);assert.equal((await fetch(base+'/api/pilot/knowledge-graph',{headers:{cookie}})).status,200);const created=await fetch(base+'/api/pilot/learning-nominations',{method:'POST',headers:{cookie,'content-type':'application/json'},body:JSON.stringify(nomination('case-b'))});assert.equal(created.status,201);}finally{await new Promise((done)=>server.close(done));await rm(h.root,{recursive:true,force:true});}});
