import test from "node:test";
import assert from "node:assert/strict";
import { createHash } from "node:crypto";
import { mkdtemp, readFile, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { runRecoverableChatSubmission } from "../assets/chat-recovery.js";
import { GovernedSpaRuntime } from "../assets/governed-spa-runtime.js";
import { PilotStore } from "../pilot-store.mjs";
import { createEmptyCandidateProvider } from "../candidate-provider.mjs";
import { startServer } from "../server.mjs";

const scope={field_id:"field-m0e1",season_id:"season-m0e1"},now="2026-09-04T00:00:00.000Z";
const users=[{login_id:"field-a",user_id:"user-a",password:"secret-a",role:"FIELD_USER",enabled:true},{login_id:"field-b",user_id:"user-b",password:"secret-b",role:"FIELD_USER",enabled:true},{login_id:"admin",user_id:"admin",password:"secret-admin",role:"SPA",enabled:true}];
const [app,css,adapterSource]=await Promise.all([readFile(new URL("../assets/field-app.js",import.meta.url),"utf8"),readFile(new URL("../assets/field-shell.css",import.meta.url),"utf8"),readFile(new URL("../assets/server-workspace-adapter.js",import.meta.url),"utf8")]);
function lifecycle(userId="user-a"){return{schema_version:2,users:[{user_id:userId,role:"FIELD_USER"}],fields:[{...scope,owner_user_id:userId,name:"นา M0E.1",crop:"rice",planting_date:"2026-07-01",current_crop_stage:{code:"TILLERING",label:"แตกกอ",model_version:"field-stage-model/v1"},current_cmp_stage:{stage_id:"CMP-03",label:"ระยะแตกกอ",model_version:"field-stage-model/v1"},stage_provenance:"USER_CONFIRMED",created_at:now,updated_at:now}],seasons:[{...scope,crop:"rice",status:"ACTIVE"}],guidance:[],activities:[],cases:[],observations:[],evidence:[],conversations:[],messages:[],decision_logs:[],case_summaries:[],weather_snapshots:[]};}
async function harness(){const root=await mkdtemp(join(tmpdir(),"cpmoakb-m0e1-")),dbPath=join(root,"pilot.sqlite"),store=await new PilotStore({dbPath,exportDir:join(root,"exports"),pilotProfile:"FIELD_CAPTURE_ALPHA",investigationCandidateProvider:createEmptyCandidateProvider()}).open();store.putWorkspace("user-a",lifecycle());return{root,dbPath,store,close:async()=>{store.close();await rm(root,{recursive:true,force:true,maxRetries:5,retryDelay:50});}};}
function caseRecord(store,userId="user-a",caseId="case-m0e1"){return store.createInvestigationRecord(userId,"CASE",{...scope,case_id:caseId,purpose:"M0E.1 capture"});}
function turn(message,extra={}){return{request_id:extra.request_id??`request-${Math.random()}`,message,entry_point:"CASE",...scope,...extra};}
function imageInput(conversationId,caseId="case-m0e1"){const bytes=Buffer.from("m0e1-image");return{image_evidence_id:"image-m0e1",field_id:scope.field_id,crop_season_id:scope.season_id,case_id:caseId,conversation_id:conversationId,captured_at:now,source:"UPLOAD",capture_intent:"PLANT_CONTEXT",plant_part_scope:"WHOLE_PLANT",spatial_scope:"SAMPLED_OBJECT",view_type:"DETAIL",media_type:"image/png",original_filename:"field.png",size_bytes:bytes.length,content_hash:createHash("sha256").update(bytes).digest("hex"),storage_key:"field.png",comparison_role:"UNKNOWN_ROLE",comparison_role_source:"UNKNOWN"};}

test("M0E.1 01 onPending(true) failure is observable",async()=>{const result=await runRecoverableChatSubmission({onPending(value){if(value)throw new Error("render");},submit:async()=>assert.fail("submit must not run after failed transition"),onSuccess:async()=>{},onFailure:async()=>{}});assert.equal(result.ok,false);assert.match(result.error.message,/render/);});
test("M0E.1 02 onPending(false) failure is safely reported",async()=>{const result=await runRecoverableChatSubmission({onPending(value){if(!value)throw new Error("release");},submit:async()=>({status:"AVAILABLE",message:"ok"}),onSuccess:async()=>{},onFailure:async()=>{}});assert.equal(result.ok,true);assert.match(result.pendingReleaseError.message,/release/);});
test("M0E.1 03 first message creates an authoritative Case",async()=>{const h=await harness();try{const created=caseRecord(h.store,"user-a","case-first-message");assert.equal(h.store.getInvestigationBundle("user-a",{...scope,case_id:created.case_id}).cases.length,1);assert.match(app,/await governedRuntime\.startCase\(field/);}finally{await h.close();}});
test("M0E.1 04 first message creates an authoritative Conversation",async()=>{const h=await harness();try{const result=await h.store.orchestrateConversationTurn("user-a",turn("ทดสอบส่งข้อความ",{request_id:"first-conversation"}));assert.equal(h.store.getGovernedConversationHistory("user-a",result.conversation_id).conversation.case_id,result.context.case_id);}finally{await h.close();}});
test("M0E.1 05 client builds context only after Case and Conversation ensure",()=>{assert.ok(app.indexOf("ensureAuthoritativeChatContext(field)")<app.indexOf("captureStatement(text"));assert.match(app,/activeCaseId=governedRuntime\.caseState\.scope\.case_id;activeConversationId=await serverLLM\.ensureConversation/);});
test("M0E.1 06 first chat reaches the real HTTP adapter/server path",async()=>{const root=await mkdtemp(join(tmpdir(),"cpmoakb-m0e1-http-")),dbPath=join(root,"pilot.sqlite"),seed=await new PilotStore({dbPath,exportDir:join(root,"exports"),investigationCandidateProvider:createEmptyCandidateProvider()}).open();seed.putWorkspace("user-a",lifecycle());caseRecord(seed,"user-a","case-http");seed.close();const server=await startServer({port:0,dbPath,exportDir:join(root,"exports"),uploadDir:join(root,"uploads"),pilotProfile:"FIELD_CAPTURE_ALPHA",pilotUsers:users,investigationCandidateProvider:createEmptyCandidateProvider()});try{const base=`http://127.0.0.1:${server.address().port}`,login=await fetch(`${base}/api/pilot/session`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({login_id:"field-a",password:"secret-a"})}),cookie=login.headers.get("set-cookie").split(";")[0],created=await fetch(`${base}/api/pilot/conversations`,{method:"POST",headers:{cookie,"content-type":"application/json"},body:JSON.stringify({...scope,case_id:"case-http",entry_point:"CASE"})}),conversation=(await created.json()).conversation,turnResponse=await fetch(`${base}/api/pilot/conversation-turns`,{method:"POST",headers:{cookie,"content-type":"application/json"},body:JSON.stringify(turn("ทดสอบส่งข้อความ",{request_id:"http-first",case_id:"case-http",conversation_id:conversation.conversation_id}))});assert.equal(created.status,201);assert.equal(turnResponse.status,201);assert.equal((await turnResponse.json()).conversation_id,conversation.conversation_id);}finally{await new Promise((done)=>server.close(done));await rm(root,{recursive:true,force:true,maxRetries:5,retryDelay:50});}});
test("M0E.1 07 raw User turn persists server-side",async()=>{const h=await harness();try{const result=await h.store.orchestrateConversationTurn("user-a",turn("ทดสอบส่งข้อความ",{request_id:"persist-user"}));assert.equal(h.store.getGovernedConversationHistory("user-a",result.conversation_id).turns[0].raw_message,"ทดสอบส่งข้อความ");}finally{await h.close();}});
test("M0E.1 08 second message reuses the Case",async()=>{const h=await harness();try{const first=await h.store.orchestrateConversationTurn("user-a",turn("ข้อความแรก",{request_id:"same-case-1"})),second=await h.store.orchestrateConversationTurn("user-a",turn("ข้อความสอง",{request_id:"same-case-2",case_id:first.context.case_id,conversation_id:first.conversation_id}));assert.equal(second.context.case_id,first.context.case_id);}finally{await h.close();}});
test("M0E.1 09 second message reuses the Conversation",async()=>{const h=await harness();try{const first=await h.store.orchestrateConversationTurn("user-a",turn("ข้อความแรก",{request_id:"same-conversation-1"})),second=await h.store.orchestrateConversationTurn("user-a",turn("ข้อความสอง",{request_id:"same-conversation-2",case_id:first.context.case_id,conversation_id:first.conversation_id}));assert.equal(second.conversation_id,first.conversation_id);}finally{await h.close();}});
test("M0E.1 10 reload reconstructs both server turns",async()=>{const h=await harness();let reopened;try{const first=await h.store.orchestrateConversationTurn("user-a",turn("ข้อความแรก",{request_id:"reload-1"}));await h.store.orchestrateConversationTurn("user-a",turn("ข้อความสอง",{request_id:"reload-2",case_id:first.context.case_id,conversation_id:first.conversation_id}));h.store.close();reopened=await new PilotStore({dbPath:h.dbPath,exportDir:join(h.root,"exports"),pilotProfile:"FIELD_CAPTURE_ALPHA",investigationCandidateProvider:createEmptyCandidateProvider()}).open();assert.deepEqual(reopened.getGovernedConversationHistory("user-a",first.conversation_id).turns.map((item)=>item.raw_message),["ข้อความแรก","ข้อความสอง"]);reopened.close();reopened=null;}finally{reopened?.close();h.store?.close();await rm(h.root,{recursive:true,force:true,maxRetries:5,retryDelay:50});}});
test("M0E.1 11 retry request id is idempotent and creates no duplicate turn",async()=>{const h=await harness();try{const input=turn("ลองอีกครั้ง",{request_id:"stable-retry"}),first=await h.store.orchestrateConversationTurn("user-a",input),again=await h.store.orchestrateConversationTurn("user-a",input);assert.equal(again.idempotent_replay,true);assert.equal(h.store.getGovernedConversationHistory("user-a",first.conversation_id).turns.length,1);}finally{await h.close();}});

function gatedRuntime(){const calls=[],workspace=new Proxy({},{get:(_target,name)=>async()=>{calls.push(String(name));return name==="getInvestigationBundle"?{observations:[],evidence:[]}:name==="getVisualEvidenceBundle"?{images:[]}:null;}}),runtime=new GovernedSpaRuntime({workspace});runtime.capabilityState={mode:"FIELD_CAPTURE_ALPHA",capture_only:true,capabilities:[{feature:"f1_management_review",availability:"DISABLED"},{feature:"f2_management_action",availability:"DISABLED"},{feature:"step_i_learning",availability:"DISABLED"}]};runtime.caseState={scope:{...scope,case_id:"case-gated"}};return{runtime,calls};}
test("M0E.1 12 disabled management endpoint is not called",async()=>{const{runtime,calls}=gatedRuntime();await runtime.refreshCase();assert.ok(!calls.includes("getManagementOptions"));});
test("M0E.1 13 disabled decision/action endpoint is not called",async()=>{const{runtime,calls}=gatedRuntime();await runtime.refreshCase();assert.ok(!calls.includes("getDecisionActionOutcomeContext"));});
test("M0E.1 14 learning follow-up is capability and valid-scope gated",()=>{assert.match(app,/featureEnabled\("step_i_learning"\)&&activeConversationId&&activeCaseId/);assert.doesNotMatch(app,/if\(activeConversationId\)\{const followup/);});
test("M0E.1 15 camera control has a visible label",()=>{assert.match(app,/📷 เพิ่มรูป/);assert.match(app,/aria-label="เพิ่มรูปจากอุปกรณ์"/);});
test("M0E.1 16 desktop image picker has no forced capture mode",()=>{assert.match(app,/accept="image\/\*" data-chat-photo/);});
test("M0E.1 17 mobile rear-camera contract remains available",()=>{assert.match(app,/accept="image\/\*" capture="environment" data-chat-camera/);assert.match(css,/mobile-camera/);});
test("M0E.1 18 image-first flow ensures Case and Conversation",()=>{assert.match(app,/ensureAuthoritativeChatContext\(field,"IMAGE"\)/);assert.match(app,/governedRuntime\.startCase\(field,entryPoint==="IMAGE"/);});
test("M0E.1 19 image upload persists its Conversation association",async()=>{const h=await harness();try{caseRecord(h.store);const conversation=h.store.ensureGovernedConversation("user-a",{...scope,case_id:"case-m0e1",entry_point:"IMAGE"}),image=h.store.createImageEvidence("user-a",imageInput(conversation.conversation_id));assert.equal(image.conversation_id,conversation.conversation_id);}finally{await h.close();}});
test("M0E.1 20 failed image upload retains retry state",()=>{assert.match(app,/chatPhotoStatus="FAILED";chatPhotoError=error\.message/);assert.match(app,/อัปโหลดไม่สำเร็จ · ลองใหม่/);});
test("M0E.1 21 image metadata survives store reopen",async()=>{const h=await harness();let reopened;try{caseRecord(h.store);const conversation=h.store.ensureGovernedConversation("user-a",{...scope,case_id:"case-m0e1",entry_point:"IMAGE"});h.store.createImageEvidence("user-a",imageInput(conversation.conversation_id));h.store.close();reopened=await new PilotStore({dbPath:h.dbPath,exportDir:join(h.root,"exports"),pilotProfile:"FIELD_CAPTURE_ALPHA",investigationCandidateProvider:createEmptyCandidateProvider()}).open();assert.equal(reopened.getImageEvidence("user-a","image-m0e1").conversation_id,conversation.conversation_id);reopened.close();reopened=null;}finally{reopened?.close();h.store?.close();await rm(h.root,{recursive:true,force:true,maxRetries:5,retryDelay:50});}});
test("M0E.1 22 cross-user image access remains denied",async()=>{const h=await harness();try{caseRecord(h.store);const conversation=h.store.ensureGovernedConversation("user-a",{...scope,case_id:"case-m0e1",entry_point:"IMAGE"});h.store.createImageEvidence("user-a",imageInput(conversation.conversation_id));assert.throws(()=>h.store.getImageEvidence("user-b","image-m0e1"),/scope not found/);}finally{await h.close();}});
test("M0E.1 23 Field receipt exposes no diagnostic authority",()=>{assert.match(app,/รับภาพไว้เป็นข้อมูลประกอบแล้วครับ ภาพนี้ยังไม่ได้ใช้ยืนยันสาเหตุ/);assert.doesNotMatch(app,/รับภาพเข้า B1|หาก B2/u);assert.match(adapterSource,/conversation_id/);});
