import test from "node:test";
import assert from "node:assert/strict";
import { mkdtemp, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { createEmptyCandidateProvider } from "../candidate-provider.mjs";
import { StaticInvestigationRuleProvider } from "../investigation-intelligence.mjs";
import { ManagementRuleProvider, createTestOnlyManagementRuleProvider, MANAGEMENT_OPTION_ENUMS } from "../management-option-runtime.mjs";
import { PilotStore } from "../pilot-store.mjs";
import { startServer } from "../server.mjs";

const scope={field_id:"field-f1",season_id:"season-f1",case_id:"case-f1"};
const now="2026-08-28T01:00:00.000Z";
function ids(start=0){let value=start;return()=>`00000000-0000-4000-8000-${String(++value).padStart(12,"0")}`;}
function lifecycle(userId="user-a",fieldId=scope.field_id,seasonId=scope.season_id){return {schema_version:2,users:[{user_id:userId}],fields:[{field_id:fieldId,owner_user_id:userId,name:"นา F1",crop:"rice",planting_date:"2026-07-01",current_crop_stage:{code:"TILLERING",label:"แตกกอ",model_version:"field-stage-model/v1"},current_cmp_stage:{stage_id:"CMP-03",label:"ระยะแตกกอ",model_version:"field-stage-model/v1"},season_id:seasonId,stage_provenance:"USER_CONFIRMED",created_at:now,updated_at:now}],seasons:[{season_id:seasonId,field_id:fieldId,crop:"rice",status:"ACTIVE"}],guidance:[],activities:[],cases:[],observations:[],evidence:[],conversations:[],messages:[],decision_logs:[],case_summaries:[],weather_snapshots:[]};}
const stepC=(state="SUFFICIENT_FOR_MANAGEMENT_OPTION_REVIEW")=>new StaticInvestigationRuleProvider({rule_version:`step-c-${state.toLowerCase()}/v1`,rule_authority:"BOUNDED_RUNTIME_RULE",rule_review_state:"HUMAN_REVIEWED",sufficiency_state:state,rules:[]});
const regulatory=(complete=false,extras={})=>({jurisdiction:"TH",authority_class:"PRIMARY_OFFICIAL_REGULATOR",current:complete,conflicting:false,defensible_join_key:complete,exact_chain:complete?{crop:"rice",target:"TEST_ONLY_TARGET",use:"TEST_ONLY_USE",registration:"TEST-REGISTRATION-001"}:{crop:"rice",target:null,use:null,registration:"IDENTITY-ONLY-001"},authority_refs:[complete?"TEST-ONLY-CURRENT-THAI-AUTHORITY/v1":"GS-DOA-HAZARDOUS-REGISTRY-2026-001/v1"],limitation:complete?"Test-only complete current chain.":"Identity alone does not complete the chain.",...extras});
const rules=(state="MANAGEMENT_REVIEW_JUSTIFIED",overrides={})=>createTestOnlyManagementRuleProvider({need_for_action:{state,reason:`Governed ${state} fixture.`,supporting_evidence_refs:[],missing_evidence_refs:state==="MORE_EVIDENCE_REQUIRED"?["MISSING_ACTION_EVIDENCE"]:[],source_rule_id:`NFA-${state}/v1`,source_refs:["TEST-GOVERNED-ACTION-SOURCE/v1"],limitations:["Fixture is bounded to deterministic tests."]},management_relationships:[],regulatory_authority:regulatory(false),...overrides});
async function setup({investigationProvider=stepC(),managementProvider=rules(),userId="user-a",fieldId=scope.field_id,seasonId=scope.season_id}={}){const root=await mkdtemp(join(tmpdir(),"cpmoakb-f1-")),store=await new PilotStore({dbPath:join(root,"pilot.sqlite"),exportDir:join(root,"exports"),investigationRuleProvider:investigationProvider,investigationCandidateProvider:createEmptyCandidateProvider(),managementRuleProvider:managementProvider,intelligenceClock:()=>new Date(now),managementClock:()=>new Date(now),intelligenceIdProvider:ids(),managementIdProvider:ids(),conversationClock:()=>new Date(now),conversationIdProvider:ids()}).open();store.putWorkspace(userId,lifecycle(userId,fieldId,seasonId));store.createInvestigationRecord(userId,"CASE",{field_id:fieldId,season_id:seasonId,case_id:scope.case_id,purpose:"Governed F1 test Case"});return {root,store,userId,scope:{field_id:fieldId,season_id:seasonId,case_id:scope.case_id},close:async()=>{store.close();await rm(root,{recursive:true,force:true});}};}
const option=(review,optionClass)=>review.all_option_evaluations.find((item)=>item.option_class===optionClass);

test("F1 publishes closed categorical vocabularies and rejects production loading of test authority",()=>{
  assert.deepEqual(MANAGEMENT_OPTION_ENUMS.optionClasses,["CONTINUE_MONITORING","CULTURAL_MANAGEMENT","MECHANICAL_MANAGEMENT","BIOLOGICAL_MANAGEMENT","CHEMICAL_REVIEW","EXPERT_REVIEW","NO_ACTION_CURRENTLY_JUSTIFIED"]);
  assert.ok(MANAGEMENT_OPTION_ENUMS.eligibilityStates.includes("BLOCKED_BY_AUTHORITY"));
  assert.throws(()=>new ManagementRuleProvider({manifest:{provider_id:"bad",provider_version:"v1",authority:"TEST_ONLY_FIXTURE",review_state:"TEST_ONLY"},management_relationships:[],regulatory_authority:regulatory(false)}),/TEST_ONLY_FIXTURE cannot load/);
});

test("golden F1-1 Candidate existence and narrowing readiness cannot open management review",async()=>{const h=await setup({investigationProvider:stepC("SUFFICIENT_FOR_NARROWING")});try{
  h.store.createInvestigationRecord(h.userId,"CANDIDATE",{...h.scope,candidate_id:"candidate-alone",candidate_class:"INSECT",label:"candidate only",support_state:"OPEN"});
  const review=h.store.assessManagementOptions(h.userId,h.scope);
  assert.equal(review.need_for_action.state,"MORE_EVIDENCE_REQUIRED");assert.equal(review.need_for_action.next_authority,"STEP_D_GUIDANCE_INTELLIGENCE");assert.equal(review.user_facing_review_options.length,0);
  assert.equal(option(review,"CHEMICAL_REVIEW").eligibility_state,"NOT_SUPPORTED_BY_CURRENT_EVIDENCE");assert.ok(review.all_option_evaluations.every((item)=>item.eligibility_state!=="SUPPORTED_FOR_REVIEW"));
}finally{await h.close();}});

test("golden F1-2 monitoring is a first-class review option without an invented interval",async()=>{const h=await setup({managementProvider:rules("CONTINUE_MONITORING")});try{
  const review=h.store.assessManagementOptions(h.userId,h.scope),monitoring=option(review,"CONTINUE_MONITORING");
  assert.equal(review.need_for_action.state,"CONTINUE_MONITORING");assert.equal(monitoring.eligibility_state,"SUPPORTED_FOR_REVIEW");assert.match(monitoring.limitations.join(" "),/No monitoring interval/);assert.equal(review.user_facing_review_options[0].option_class,"CONTINUE_MONITORING");
}finally{await h.close();}});

test("golden F1-3 multiple non-chemical options coexist in deterministic non-ranking order with transparent water mapping",async()=>{const relationships=[{rule_id:"WATER-CASE/v1",option_class:"WATER_MANAGEMENT",case_relevant:true,reason:"Governed water-context relationship supports review.",source_refs:["TEST-WATER-SOURCE/v1"],limitations:["No water-level change is prescribed."]},{rule_id:"MECHANICAL-CASE/v1",option_class:"MECHANICAL_MANAGEMENT",case_relevant:true,reason:"Governed mechanical relationship supports review.",source_refs:["TEST-MECHANICAL-SOURCE/v1"]},{rule_id:"BIOLOGICAL-CASE/v1",option_class:"BIOLOGICAL_MANAGEMENT",case_relevant:true,reason:"Governed biological relationship supports review.",source_refs:["TEST-BIOLOGICAL-SOURCE/v1"]}],h=await setup({managementProvider:rules("MANAGEMENT_REVIEW_JUSTIFIED",{management_relationships:relationships})});try{
  const review=h.store.assessManagementOptions(h.userId,h.scope),supported=review.all_option_evaluations.filter((item)=>item.eligibility_state==="SUPPORTED_FOR_REVIEW").map((item)=>item.option_class);
  assert.deepEqual(supported,["CULTURAL_MANAGEMENT","MECHANICAL_MANAGEMENT","BIOLOGICAL_MANAGEMENT"]);assert.equal(option(review,"CULTURAL_MANAGEMENT").source_option_class,"WATER_MANAGEMENT");assert.equal(review.presentation_is_ranking,false);assert.deepEqual(review.user_facing_review_options.map((item)=>item.option_class),supported);assert.equal(review.user_facing_review_options.length,3);
}finally{await h.close();}});

test("unsupported non-chemical classes are not invented from generic knowledge",async()=>{const h=await setup();try{const review=h.store.assessManagementOptions(h.userId,h.scope);for(const cls of ["CULTURAL_MANAGEMENT","MECHANICAL_MANAGEMENT","BIOLOGICAL_MANAGEMENT"]){const item=option(review,cls);assert.equal(item.eligibility_state,"NOT_SUPPORTED_BY_CURRENT_EVIDENCE");assert.ok(item.knowledge_gaps.includes("MISSING_MANAGEMENT_RELATIONSHIP"));}}finally{await h.close();}});

test("golden F1-4 Chemical Review fails closed when Key B is incomplete",async()=>{const h=await setup();try{const review=h.store.assessManagementOptions(h.userId,h.scope),chemical=option(review,"CHEMICAL_REVIEW");assert.equal(review.need_for_action.state,"MANAGEMENT_REVIEW_JUSTIFIED");assert.equal(review.regulatory_gate.exact_chain_complete,false);assert.equal(chemical.eligibility_state,"BLOCKED_BY_AUTHORITY");assert.equal(chemical.authority_state,"MISSING_REGULATORY_CHAIN");assert.equal(chemical.human_review_required,true);assert.equal(review.regulatory_gate.human_review_can_waive,false);}finally{await h.close();}});

test("registration identity, product availability, and MoA context cannot create Key B",async()=>{const authority=regulatory(false,{product_available:true,moa_classification:"TEST-MOA"}),h=await setup({managementProvider:rules("MANAGEMENT_REVIEW_JUSTIFIED",{regulatory_authority:authority})});try{const chemical=option(h.store.assessManagementOptions(h.userId,h.scope),"CHEMICAL_REVIEW");assert.equal(chemical.eligibility_state,"BLOCKED_BY_AUTHORITY");assert.equal(chemical.regulatory_gate_state,"BLOCKED_BY_AUTHORITY");}finally{await h.close();}});

test("golden F1-5 a test-only exact current Thai chain passes both keys but emits no selection or application content",async()=>{const h=await setup({managementProvider:rules("MANAGEMENT_REVIEW_JUSTIFIED",{regulatory_authority:regulatory(true)})});try{const review=h.store.assessManagementOptions(h.userId,h.scope),chemical=option(review,"CHEMICAL_REVIEW"),serialized=JSON.stringify(chemical);assert.equal(review.regulatory_gate.satisfied,true);assert.equal(chemical.eligibility_state,"SUPPORTED_FOR_REVIEW");assert.equal(chemical.next_governed_step,"FUTURE_GOVERNED_CHEMICAL_REVIEW_LAYER");for(const prohibited of [/active_ingredient/i,/product_selection/i,/brand/i,/\"rate\"/i,/tank_mix/i,/drone_setting/i,/spray_volume/i,/moa_switch/i])assert.doesNotMatch(serialized,prohibited);}finally{await h.close();}});

test("Chemical Review still requires Key A even when regulatory Key B passes",async()=>{const h=await setup({managementProvider:rules("CONTINUE_MONITORING",{regulatory_authority:regulatory(true)})});try{const chemical=option(h.store.assessManagementOptions(h.userId,h.scope),"CHEMICAL_REVIEW");assert.equal(chemical.eligibility_state,"NOT_SUPPORTED_BY_CURRENT_EVIDENCE");assert.equal(chemical.authority_state,"KEY_A_NOT_SATISFIED");}finally{await h.close();}});

test("golden F1-7 failed control remains auditable context and routes to expert review without resistance or repeat-action inference",async()=>{const h=await setup({managementProvider:rules("HUMAN_REVIEW_REQUIRED",{failed_control_context:{evidence_refs:["management-failed"],limitations:["Target identity, timing, coverage, environment, and susceptibility remain unresolved."]}})});try{
  h.store.createInvestigationRecord(h.userId,"MANAGEMENT_EVENT",{...h.scope,management_event_id:"management-failed",event_type:"INSECTICIDE_APPLICATION",event_at:"2026-08-20T01:00:00Z",time_precision:"EXACT",source:"USER_REPORTED",note:"outcome did not meet expectation"});
  const review=h.store.assessManagementOptions(h.userId,h.scope),expert=option(review,"EXPERT_REVIEW");assert.equal(expert.eligibility_state,"HUMAN_REVIEW_REQUIRED");assert.ok(expert.knowledge_gaps.includes("FAILED_CONTROL_REVIEW_REQUIRED"));assert.equal(review.failed_control_context.resistance_inferred,false);assert.equal(review.failed_control_context.repeat_action_created,false);assert.doesNotMatch(JSON.stringify(review.failed_control_context),/higher.?dose|switch.?moa|tank.?mix/i);
}finally{await h.close();}});

test("golden F1-8 no action is a bounded current state and does not resolve the Case",async()=>{const h=await setup({managementProvider:rules("NO_ACTION_DETERMINATION_SUPPORTED")});try{const review=h.store.assessManagementOptions(h.userId,h.scope),noAction=option(review,"NO_ACTION_CURRENTLY_JUSTIFIED");assert.equal(noAction.eligibility_state,"SUPPORTED_FOR_REVIEW");assert.match(noAction.limitations.join(" "),/not Case resolution/);assert.equal(h.store.getInvestigationBundle(h.userId,h.scope).cases[0].status,"OPEN");assert.equal(noAction.next_governed_step,"HUMAN_DECISION_REVIEW");}finally{await h.close();}});

test("option records retain durable schema, separate scientific/regulatory provenance, and no ranking score",async()=>{const h=await setup();try{const review=h.store.assessManagementOptions(h.userId,h.scope),chemical=option(review,"CHEMICAL_REVIEW");for(const key of ["management_option_id","user_id","field_id","crop_season_id","case_id","assessment_id","assessment_revision","option_class","eligibility_state","need_for_action_state","target_problem_ref","supporting_evidence_refs","missing_evidence_refs","authority_refs","authority_state","human_review_required","reason","limitations","knowledge_gaps","source_rule_id","source_rule_version","source_refs","context_hash","engine_version","generated_at","valid_from","superseded_at","status"])assert.ok(key in chemical,key);assert.ok(chemical.provenance.scientific);assert.ok(chemical.provenance.regulatory);assert.equal(chemical.presentation_is_ranking,false);assert.equal("score" in chemical,false);assert.equal("percentage" in chemical,false);}finally{await h.close();}});

test("evidence and Step C revision changes supersede current F1 state while preserving auditable history",async()=>{const h=await setup();try{const first=h.store.assessManagementOptions(h.userId,h.scope);h.store.createInvestigationRecord(h.userId,"OBSERVATION",{...h.scope,observation_id:"obs-f1-change",source:"FIELD_OBSERVED",note:"new governed Case evidence"});const second=h.store.assessManagementOptions(h.userId,h.scope),history=h.store.getManagementReviewHistory(h.userId,h.scope);assert.notEqual(second.management_review_id,first.management_review_id);assert.notEqual(second.context_hash,first.context_hash);assert.equal(history.length,2);assert.equal(history[0].status,"SUPERSEDED");assert.ok(history[0].superseded_at);assert.ok(history[0].all_option_evaluations.every((item)=>item.status==="SUPERSEDED"));assert.equal(history[1].status,"CURRENT");}finally{await h.close();}});

test("Human Review and management rule changes independently invalidate F1 while preserving every prior snapshot",async()=>{const h=await setup();let reopened=null;try{const first=h.store.assessManagementOptions(h.userId,h.scope),assessment=h.store.assessInvestigation(h.userId,h.scope);h.store.reviewInvestigationAssessment(h.userId,{assessment_id:assessment.assessment_id,action:"ACCEPT",rationale:"Qualified reviewer accepts this bounded Step C snapshot without creating a treatment decision."});const second=h.store.assessManagementOptions(h.userId,h.scope);assert.notEqual(second.context_hash,first.context_hash);h.store.close();reopened=await new PilotStore({dbPath:join(h.root,"pilot.sqlite"),exportDir:join(h.root,"exports"),investigationRuleProvider:stepC(),investigationCandidateProvider:createEmptyCandidateProvider(),managementRuleProvider:rules("CONTINUE_MONITORING"),intelligenceClock:()=>new Date(now),managementClock:()=>new Date(now),intelligenceIdProvider:ids(100),managementIdProvider:ids(100)}).open();const third=reopened.assessManagementOptions(h.userId,h.scope),history=reopened.getManagementReviewHistory(h.userId,h.scope);assert.notEqual(third.source_rule_hash,second.source_rule_hash);assert.equal(history.length,3);assert.deepEqual(history.map((item)=>item.status),["SUPERSEDED","SUPERSEDED","CURRENT"]);}finally{reopened?.close();await rm(h.root,{recursive:true,force:true});}});

test("server scope is authoritative and browser workspace state cannot override F1",async()=>{const h=await setup();try{const local=lifecycle();local.management_options=[{option_class:"CHEMICAL_REVIEW",eligibility_state:"SUPPORTED_FOR_REVIEW"}];h.store.putWorkspace(h.userId,local);const review=h.store.assessManagementOptions(h.userId,h.scope);assert.equal(option(review,"CHEMICAL_REVIEW").eligibility_state,"BLOCKED_BY_AUTHORITY");assert.equal(review.scope.field_id,h.scope.field_id);assert.throws(()=>h.store.assessManagementOptions("user-b",h.scope),/context mismatch|scope/i);assert.throws(()=>h.store.assessManagementOptions(h.userId,{...h.scope,field_id:"field-other"}),/context mismatch|scope/i);}finally{await h.close();}});

test("golden F1-6 Step E verbalizes blocked and reviewable chemical states without model-created options",async()=>{for(const [complete,pattern] of [[false,/ยังไม่ควรเปิดทางเลือกสาร/],[true,/เปิดการทบทวนทางสารเคมี/]]){const h=await setup({managementProvider:rules("MANAGEMENT_REVIEW_JUSTIFIED",{regulatory_authority:regulatory(complete)})});try{const result=await h.store.orchestrateConversationTurn(h.userId,{request_id:`chemical-${complete}`,message:"ใช้ยาอะไรดี?",entry_point:"CASE",...h.scope});assert.equal(result.response_type,"MANAGEMENT_REVIEW_SUMMARY");assert.equal(result.actions[0].action,"PRESENT_MANAGEMENT_REVIEW");assert.match(result.text,pattern);assert.ok(result.management_review_reference);assert.equal(result.authority.provider_scientific_authority,false);assert.doesNotMatch(result.text,/TEST-REGISTRATION|มล\.|กรัม|ยี่ห้อ/i);}finally{await h.close();}}});

test("management APIs are authenticated, scoped, and expose current, history, and context",async()=>{const root=await mkdtemp(join(tmpdir(),"cpmoakb-f1-api-")),dbPath=join(root,"pilot.sqlite"),exportDir=join(root,"exports"),investigationProvider=stepC(),managementProvider=rules(),seed=await new PilotStore({dbPath,exportDir,investigationRuleProvider:investigationProvider,investigationCandidateProvider:createEmptyCandidateProvider(),managementRuleProvider:managementProvider}).open();seed.putWorkspace("user-a",lifecycle());seed.createInvestigationRecord("user-a","CASE",{...scope,purpose:"F1 API"});seed.close();const server=await startServer({port:0,dbPath,exportDir,uploadDir:join(root,"uploads"),pilotUserId:"user-a",investigationRuleProvider:investigationProvider,investigationCandidateProvider:createEmptyCandidateProvider(),managementRuleProvider:managementProvider});try{const base=`http://127.0.0.1:${server.address().port}`,login=await fetch(`${base}/api/pilot/session`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({password:"1234"})}),cookie=login.headers.get("set-cookie").split(";")[0],query=new URLSearchParams({field_id:scope.field_id,season_id:scope.season_id,case_id:scope.case_id});for(const endpoint of ["management-options","management-option-history","management-review-context"]){const response=await fetch(`${base}/api/pilot/${endpoint}?${query}`,{headers:{cookie}});assert.equal(response.status,200,endpoint);}const unauth=await fetch(`${base}/api/pilot/management-options?${query}`);assert.equal(unauth.status,401);}finally{await new Promise((done)=>server.close(done));await rm(root,{recursive:true,force:true});}});
