import test from "node:test";
import assert from "node:assert/strict";
import { mkdtemp, readFile, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { PilotStore } from "../pilot-store.mjs";
import { startServer } from "../server.mjs";
import { validatePilotConfiguration } from "../pilot-hardening-runtime.mjs";
import { LEARNING_SIGNAL_CLASSES } from "../mobile-field-capture-alpha.mjs";
import { createEmptyCandidateProvider } from "../candidate-provider.mjs";
import { createTestOnlyConversationProvider } from "../conversation-orchestrator.mjs";

const scope={field_id:"field-mobile",season_id:"season-mobile"};
const users=[
  {login_id:"field-a",user_id:"user-a",password:"secret-a",role:"FIELD_USER",enabled:true},
  {login_id:"field-b",user_id:"user-b",password:"secret-b",role:"FIELD_USER",enabled:true},
  {login_id:"admin",user_id:"admin",password:"secret-admin",role:"SPA",enabled:true},
];
function lifecycle(userId="user-a") { return {schema_version:2,users:[{user_id:userId,role:"FIELD_USER"}],fields:[{...scope,owner_user_id:userId,name:"นาโมบาย",polygon:{type:"Polygon",coordinates:[[[100,13],[100.01,13],[100,13.01],[100,13]]]},crop:"rice",planting_date:"2026-07-01",current_crop_stage:{code:"TILLERING",label:"แตกกอ",model_version:"field-stage-model/v1"},current_cmp_stage:{stage_id:"CMP-03",label:"ระยะแตกกอ",model_version:"field-stage-model/v1"},stage_provenance:"USER_CONFIRMED",created_at:"2026-07-01T00:00:00.000Z",updated_at:"2026-08-20T00:00:00.000Z"}],seasons:[{...scope,crop:"rice",status:"ACTIVE"}],guidance:[],activities:[],cases:[],observations:[],evidence:[],conversations:[],messages:[],decision_logs:[],case_summaries:[],weather_snapshots:[]}; }
async function harness(){const root=await mkdtemp(join(tmpdir(),"cpmoakb-m0a-")),configuration=validatePilotConfiguration({profile:"FIELD_CAPTURE_ALPHA",host:"127.0.0.1",db_path:join(root,"pilot.sqlite"),export_dir:join(root,"exports"),upload_dir:join(root,"uploads")}),store=await new PilotStore({dbPath:configuration.db_path,exportDir:configuration.export_dir,pilotProfile:configuration.profile,pilotConfiguration:configuration,investigationCandidateProvider:createEmptyCandidateProvider()}).open();store.putWorkspace("user-a",lifecycle());return{root,store,close:async()=>{store.close();await rm(root,{recursive:true,force:true});}};}
const turn=(message,extra={})=>({request_id:extra.request_id??`m0a-${Math.random()}`,message,entry_point:"FIELD",...scope,...extra});

test("M0A profile is capture-only and cannot expose F1/F2 authority",async()=>{const h=await harness();try{const capabilities=h.store.getPilotCapabilities();assert.equal(capabilities.capture_only,true);assert.equal(capabilities.mode,"FIELD_CAPTURE_ALPHA");assert.equal(capabilities.capabilities.find((item)=>item.feature==="f1_management_review").availability,"DISABLED");assert.equal(capabilities.capabilities.find((item)=>item.feature==="f2_management_action").availability,"DISABLED");const response=await h.store.orchestrateConversationTurn("user-a",turn("ควรใช้สารอะไร อัตราเท่าไร",{request_id:"no-management"}));assert.equal(response.response_type,"SYSTEM_LIMITATION");assert.equal(response.management_review_reference,null);assert.equal(response.decision_action_outcome_reference,null);assert.match(response.text,/ไม่แนะนำ/);assert.doesNotMatch(response.text,/\d+\s*(?:มล|กรัม|ซีซี)/u);}finally{await h.close();}});

test("M0A bounded cannot-answer phrases stop without a repeated question",async()=>{const h=await harness();try{for(const [index,message] of ["ไม่รู้","ไม่ได้ดู","จำไม่ได้","ไม่มีรูป","ไว้ดูทีหลัง"].entries()){const response=await h.store.orchestrateConversationTurn("user-a",turn(message,{request_id:`cannot-${index}`}));assert.equal(response.intent,"CANNOT_ANSWER");assert.equal(response.question,null);assert.ok(response.learning_signals.some((item)=>item.signal_class==="UNANSWERED_QUESTION"));}assert.equal(h.store.getLearningSignals("user-a").filter((item)=>item.signal_class==="UNANSWERED_QUESTION").length,5);}finally{await h.close();}});

test("M0A correction preserves raw history, supersedes structured evidence, and appends lineage",async()=>{const h=await harness();try{const first=await h.store.orchestrateConversationTurn("user-a",turn("ข้าวเหลือง",{request_id:"before-correction"})),corrected=await h.store.orchestrateConversationTurn("user-a",turn("ขอแก้ เมื่อกี้ไม่ใช่ข้าวเหลือง แต่เป็นหย่อม",{request_id:"natural-correction",conversation_id:first.conversation_id,case_id:first.context.case_id})),history=h.store.getGovernedConversationHistory("user-a",first.conversation_id),bundle=h.store.getInvestigationBundle("user-a",{...scope,case_id:first.context.case_id});assert.equal(history.turns.length,2);assert.equal(history.turns[0].raw_message,"ข้าวเหลือง");assert.equal(history.turns[1].corrects_turn_id,first.turn_id);assert.equal(bundle.evidence.find((item)=>item.evidence_id===first.fact_record_references[0].record_id).review_state,"SUPERSEDED");assert.ok(corrected.corrected_fact_record_references.length>0);assert.ok(corrected.learning_signals.some((item)=>item.signal_class==="USER_CORRECTION"));}finally{await h.close();}});

test("M0A retains raw and structured provenance and replays idempotently",async()=>{const h=await harness();try{const input=turn("ข้าวเหลืองเป็นหย่อม",{request_id:"idempotent-mobile"}),first=await h.store.orchestrateConversationTurn("user-a",input),second=await h.store.orchestrateConversationTurn("user-a",input),row=h.store.db.prepare("SELECT * FROM governed_conversation_turns WHERE turn_id=?").get(first.turn_id);assert.equal(second.idempotent_replay,true);assert.equal(row.raw_message,input.message);assert.ok(JSON.parse(row.interpretation_json).explicit_facts.length===2);assert.equal(JSON.parse(row.provider_json).scientific_authority,false);assert.equal(h.store.db.prepare("SELECT COUNT(*) count FROM investigation_observations").get().count,1);}finally{await h.close();}});

test("M0A same-user second-device reconstruction comes entirely from server persistence",async()=>{const root=await mkdtemp(join(tmpdir(),"cpmoakb-m0a-device-")),config=validatePilotConfiguration({profile:"FIELD_CAPTURE_ALPHA",host:"127.0.0.1",db_path:join(root,"pilot.sqlite"),export_dir:join(root,"exports"),upload_dir:join(root,"uploads")});let first=await new PilotStore({dbPath:config.db_path,exportDir:config.export_dir,pilotProfile:config.profile,pilotConfiguration:config,investigationCandidateProvider:createEmptyCandidateProvider()}).open(),second;try{first.putWorkspace("user-a",lifecycle());const response=await first.orchestrateConversationTurn("user-a",turn("ข้าวเหลืองเป็นหย่อม",{request_id:"device-one"}));first.close();first=null;second=await new PilotStore({dbPath:config.db_path,exportDir:config.export_dir,pilotProfile:config.profile,pilotConfiguration:config,investigationCandidateProvider:createEmptyCandidateProvider()}).open();const lifecycleState=second.getLifecycle("user-a"),history=second.getGovernedConversationHistory("user-a",response.conversation_id),context=second.rebuildGovernedConversationContext("user-a",response.conversation_id),bundle=second.getInvestigationBundle("user-a",{...scope,case_id:response.context.case_id});assert.equal(lifecycleState.fields[0].field_id,scope.field_id);assert.equal(history.conversation.case_id,response.context.case_id);assert.equal(history.turns[0].raw_message,"ข้าวเหลืองเป็นหย่อม");assert.equal(bundle.evidence.length,2);assert.ok(context.context.assessment);assert.ok(context.context.guidance);}finally{first?.close();second?.close();await rm(root,{recursive:true,force:true});}});

test("M0A asks at most one governed next question and fails closed when language provider is unavailable",async()=>{const h=await harness();try{const first=await h.store.orchestrateConversationTurn("user-a",turn("ข้าวเหลือง",{request_id:"one-question"}));assert.ok(first.question==null||typeof first.question==="string");assert.ok((first.question?.split("?").filter(Boolean).length??0)<=1);h.store.conversationOrchestrator.provider=createTestOnlyConversationProvider(()=>{throw new Error("offline");});const failed=await h.store.orchestrateConversationTurn("user-a",turn("ช่วยบันทึกต่อ",{request_id:"provider-offline",conversation_id:first.conversation_id,case_id:first.context.case_id}));assert.equal(failed.response_type,"SYSTEM_LIMITATION");assert.equal(failed.error_code,"CONVERSATION_UNAVAILABLE");assert.equal(failed.fact_record_references.length,0);}finally{await h.close();}});

test("M0A learning signal taxonomy is complete and signals never promote knowledge",async()=>{assert.equal(LEARNING_SIGNAL_CLASSES.length,10);assert.deepEqual(new Set(LEARNING_SIGNAL_CLASSES),new Set(["UNANSWERED_QUESTION","INTERPRETATION_GAP","MISSING_EVIDENCE","USER_CORRECTION","FAILED_CONTROL_REPORT_CANDIDATE","PRODUCT_QUESTION","ACTIVE_INGREDIENT_QUESTION","MISSING_CANDIDATE","MISSING_MANAGEMENT_RELATIONSHIP","USEFUL_COMPLETED_CASE"]));const h=await harness();try{const result=await h.store.orchestrateConversationTurn("user-a",turn("ไม่รู้",{request_id:"signal-boundary"})),signal=result.learning_signals[0];assert.equal(signal.learning_signal_is_evidence,false);assert.equal(signal.learning_signal_is_learning_candidate,false);assert.equal(signal.learning_signal_is_canonical_knowledge,false);assert.equal(signal.automatic_promotion,false);}finally{await h.close();}});

test("M0A network configuration requires explicit LAN authorization and HTTPS public URL",async()=>{const root=await mkdtemp(join(tmpdir(),"cpmoakb-m0a-config-"));try{const base={profile:"FIELD_CAPTURE_ALPHA",db_path:join(root,"db"),export_dir:join(root,"exports"),upload_dir:join(root,"uploads")};assert.throws(()=>validatePilotConfiguration({...base,host:"0.0.0.0"}),/external binding/);assert.throws(()=>validatePilotConfiguration({...base,host:"0.0.0.0",allow_external_binding:true,public_base_url:"http://192.168.1.5:4173"}),/HTTPS/);const secure=validatePilotConfiguration({...base,host:"0.0.0.0",allow_external_binding:true,public_base_url:"https://capture.example.test"});assert.equal(secure.secure_cookie,true);}finally{await rm(root,{recursive:true,force:true});}});

test("M0A server requires three users, isolates owner signals, protects admin listing, and logs out",async()=>{const root=await mkdtemp(join(tmpdir(),"cpmoakb-m0a-api-")),dbPath=join(root,"pilot.sqlite"),exportDir=join(root,"exports"),seed=await new PilotStore({dbPath,exportDir,investigationCandidateProvider:createEmptyCandidateProvider()}).open();seed.putWorkspace("user-a",lifecycle("user-a"));seed.close();await assert.rejects(startServer({port:0,dbPath,exportDir,uploadDir:join(root,"bad-uploads"),pilotProfile:"FIELD_CAPTURE_ALPHA",pilotUsers:users.slice(0,2)}),/at least three/);const server=await startServer({port:0,dbPath,exportDir,uploadDir:join(root,"uploads"),pilotProfile:"FIELD_CAPTURE_ALPHA",pilotUsers:users});try{const base=`http://127.0.0.1:${server.address().port}`,login=async(user)=>{const response=await fetch(`${base}/api/pilot/session`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({login_id:user.login_id,password:user.password})});return response.headers.get("set-cookie").split(";")[0];},cookieA=await login(users[0]),cookieB=await login(users[1]);await fetch(`${base}/api/pilot/conversation-turns`,{method:"POST",headers:{cookie:cookieA,"content-type":"application/json"},body:JSON.stringify(turn("ไม่รู้",{request_id:"api-signal"}))});const ownA=await (await fetch(`${base}/api/pilot/learning-signals`,{headers:{cookie:cookieA}})).json(),ownB=await (await fetch(`${base}/api/pilot/learning-signals`,{headers:{cookie:cookieB}})).json();assert.equal(ownA.signals.length,1);assert.equal(ownB.signals.length,0);assert.equal((await fetch(`${base}/api/pilot/admin/learning-signals`,{headers:{cookie:cookieA}})).status,403);assert.equal((await fetch(`${base}/api/pilot/admin/learning-signals`,{headers:{cookie:await login(users[2])}})).status,200);assert.equal((await fetch(`${base}/api/pilot/session/logout`,{method:"POST",headers:{cookie:cookieA}})).status,200);assert.equal((await fetch(`${base}/api/pilot/learning-signals`,{headers:{cookie:cookieA}})).status,401);}finally{await new Promise((done)=>server.close(done));await rm(root,{recursive:true,force:true});}});

test("M0A mobile SPA exposes login identity, camera, safe-area composer, server logout, and no horizontal overflow",async()=>{const [app,adapter,css]=await Promise.all([readFile(new URL("../assets/field-app.js",import.meta.url),"utf8"),readFile(new URL("../assets/server-workspace-adapter.js",import.meta.url),"utf8"),readFile(new URL("../assets/field-shell.css",import.meta.url),"utf8")]);assert.match(app,/name="login_id"/);assert.match(app,/capture="environment" data-chat-photo/);assert.match(app,/governedRuntime\.captureStatement\(text\)/);assert.match(app,/serverWorkspace\.logout\(\)/);assert.match(adapter,/\/api\/pilot\/session\/logout/);assert.match(css,/overflow-x:hidden/);assert.match(css,/env\(safe-area-inset-bottom\)/);assert.match(css,/min-height:44px/);});
