import test from "node:test";
import assert from "node:assert/strict";
import { mkdtemp, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { PilotStore } from "../pilot-store.mjs";

const now="2026-09-01T01:00:00.000Z",scope={field_id:"field-p102",season_id:"season-p102",case_id:"case-p102"};
function lifecycle(crop="rice"){return{schema_version:2,users:[{user_id:"user-a"}],fields:[{field_id:scope.field_id,owner_user_id:"user-a",name:"P1-02 field",crop,planting_date:"2026-07-01",current_crop_stage:{code:"TILLERING",label:"Tillering",model_version:"field-stage-model/v1"},current_cmp_stage:{stage_id:"CMP-03",label:"Tillering",model_version:"field-stage-model/v1"},season_id:scope.season_id,stage_provenance:"USER_CONFIRMED",created_at:now,updated_at:now}],seasons:[{season_id:scope.season_id,field_id:scope.field_id,crop,status:"ACTIVE"}],guidance:[],activities:[],cases:[],observations:[],evidence:[],conversations:[],messages:[],decision_logs:[],case_summaries:[],weather_snapshots:[]};}
async function productionCase({crop="rice",conceptId="CO-RDC-001/v1",review=true,resolutionLevel="FIELD_REVIEWED_FINDING",water=false,link="SUPPORTING"}={}){
  const root=await mkdtemp(join(tmpdir(),"cpmoakb-p102-")),store=await new PilotStore({dbPath:join(root,"pilot.sqlite"),exportDir:join(root,"exports")}).open();
  store.putWorkspace("user-a",lifecycle(crop));
  store.createInvestigationRecord("user-a","CASE",{...scope,purpose:"Bounded production Step C to F1 authority test"});
  store.createInvestigationRecord("user-a","OBSERVATION",{...scope,observation_id:"obs-blast",source:"FIELD_OBSERVED",review_state:"HUMAN_REVIEWED",note:"Reviewed blast morphology and current field context"});
  store.createInvestigationRecord("user-a","MORPHOLOGY_EVIDENCE",{...scope,evidence_id:"ev-blast-leaf",observation_id:"obs-blast",source:"FIELD_OBSERVED",review_state:"HUMAN_REVIEWED",evidence_level:"MO1_DIRECT_OBSERVATION",payload:{plant_part:"LEAF_BLADE",primary_phenotypes:["LESION"],shape:"eye-shaped",center:"gray",margin:"brown",negative_evidence:[]}});
  if(water)store.createInvestigationRecord("user-a","WATER_CONTEXT",{...scope,evidence_id:"ev-current-water",observation_id:"obs-blast",source:"FIELD_OBSERVED",review_state:"HUMAN_REVIEWED",evidence_level:"WT1_FIELD_OBSERVED",payload:{water_state:"SATURATED",zone_reference:"affected Case area",source:"FIELD_OBSERVED",source_confidence:"MODERATE"}});
  store.createInvestigationRecord("user-a","CANDIDATE",{...scope,candidate_id:"candidate-blast",candidate_class:"DISEASE",label:"Rice blast",concept_id:conceptId,support_state:"OPEN",review_state:"HUMAN_REVIEWED",authorship:"EXPLICITLY_AUTHORED"});
  store.createInvestigationRecord("user-a","CANDIDATE_EVIDENCE_LINK",{...scope,candidate_evidence_link_id:"link-blast",candidate_id:"candidate-blast",relation:link,...(link==="MISSING"?{missing_description:"Required blast Evidence remains missing"}:{evidence_id:"ev-blast-leaf"}),rationale:"Explicit current Case relationship"});
  const initial=store.assessInvestigation("user-a",scope);
  if(review)store.reviewInvestigationAssessment("user-a",{assessment_id:initial.assessment_id,action:"RESOLVE_FINDING",rationale:"Human-reviewed bounded finding only; not management authority.",resolution_level:resolutionLevel,candidate_findings:[{candidate_id:"candidate-blast",role:"PRIMARY_FINDING"}]});
  return{root,store,initial,current:()=>store.assessInvestigation("user-a",scope),close:async()=>{store.close();await rm(root,{recursive:true,force:true,maxRetries:5,retryDelay:50});}};
}
const cultural=(review)=>review.all_option_evaluations.find((item)=>item.option_class==="CULTURAL_MANAGEMENT");

test("P1-02 golden negative: reviewed Case relationship cannot override explicit Step C insufficiency",async()=>{const h=await productionCase();try{
  const assessment=h.current();assert.equal(assessment.candidate_assessments.find((item)=>item.candidate_id==="candidate-blast").state,"SUPPORTED");assert.equal(assessment.review_history.at(-1).candidate_findings[0].role,"PRIMARY_FINDING");assert.equal(assessment.evidence_sufficiency.purpose_states.MANAGEMENT_OPTION_REVIEW,"INSUFFICIENT_FOR_NARROWING");
  const review=h.store.assessManagementOptions("user-a",scope),option=cultural(review);assert.equal(review.need_for_action.state,"MORE_EVIDENCE_REQUIRED");assert.notEqual(option.eligibility_state,"SUPPORTED_FOR_REVIEW");
  assert.throws(()=>h.store.createHumanDecision("user-a",{request_id:"blocked-decision",...scope,management_review_id:review.management_review_id,decision_type:"SELECT_MANAGEMENT_OPTION",selected_option_id:option.management_option_id,selection_source:"AUTHENTICATED_UI",explicit_confirmation:true,expected_current_decision_id:null,supersedes_decision_id:null}),/cannot become a confirmed decision/);
  assert.equal(h.store.getManagementActionHistory("user-a",scope).length,0);
}finally{await h.close();}});

test("P1-02 positive production slice is opened by Step C and reaches descriptive Outcome",async()=>{const h=await productionCase({water:true});try{
  const assessment=h.current(),adjudication=assessment.management_sufficiency_adjudication;assert.equal(assessment.evidence_sufficiency.purpose_states.MANAGEMENT_OPTION_REVIEW,"SUFFICIENT_FOR_MANAGEMENT_OPTION_REVIEW");assert.equal(h.store.getInvestigationAssessmentHistory("user-a",scope).at(-1).evidence_sufficiency.purpose_states.MANAGEMENT_OPTION_REVIEW,"SUFFICIENT_FOR_MANAGEMENT_OPTION_REVIEW");assert.equal(adjudication.rule_id,"STEP-C-BLAST-DRAINAGE-MANAGEMENT-SUFFICIENCY/v1");assert.equal(adjudication.provider_id,"cp-moakb-step-c-management-sufficiency-provider");assert.equal(adjudication.review_state,"DOMAIN_APPROVED");assert.deepEqual(adjudication.current_authoritative_evidence_refs,["ev-blast-leaf","ev-current-water"]);assert.deepEqual(adjudication.missing_evidence_refs,[]);assert.deepEqual(adjudication.contradicting_evidence_refs,[]);assert.ok(adjudication.source_refs.includes("MO-CPM-008/v1"));assert.equal(adjudication.source_bindings.length,2);assert.ok(adjudication.limitations.length);
  const review=h.store.assessManagementOptions("user-a",scope),option=cultural(review);assert.equal(review.need_for_action.state,"MANAGEMENT_REVIEW_JUSTIFIED");assert.equal(option.eligibility_state,"SUPPORTED_FOR_REVIEW");assert.equal(review.all_option_evaluations.find((item)=>item.option_class==="CHEMICAL_REVIEW").eligibility_state,"BLOCKED_BY_AUTHORITY");
  const decision=h.store.createHumanDecision("user-a",{request_id:"positive-decision",...scope,management_review_id:review.management_review_id,decision_type:"SELECT_MANAGEMENT_OPTION",selected_option_id:option.management_option_id,selection_source:"AUTHENTICATED_UI",selection_raw_text:"review bounded cultural option",explicit_confirmation:true,expected_current_decision_id:null,supersedes_decision_id:null}),plan=h.store.createManagementAction("user-a",{request_id:"positive-plan",...scope,decision_id:decision.decision_id,action_kind:"PLAN",action_source:"HUMAN_AUTHORED_PLAN",action_description:"Human-authored plan",actor_source:"AUTHENTICATED_USER",explicit_confirmation:true,expected_current_action_id:null,supersedes_action_id:null}),performed=h.store.createManagementAction("user-a",{request_id:"positive-performed",...scope,decision_id:decision.decision_id,action_kind:"CONFIRM_PERFORMED",action_source:"HUMAN_EXECUTION_CONFIRMATION",actor_source:"AUTHENTICATED_USER",performed_at:"2026-09-01T02:00:00Z",explicit_confirmation:true,expected_current_action_id:plan.management_action_id,supersedes_action_id:plan.management_action_id,management_event_type:"UNKNOWN_MANAGEMENT_EVENT"});
  const outcome=h.store.createOutcomeObservation("user-a",{request_id:"positive-outcome",...scope,decision_id:decision.decision_id,management_action_id:performed.management_action_id,phase:"T1",observed_at:"2026-09-01T03:00:00Z",elapsed_relation_to_action:"AFTER_ACTION",subject:"descriptive observation",raw_value:1,unit:"count",denominator:"same site",count_basis:"human observation",sample_size:1,sampling_method:"same-site check",sampling_context:{scope:"same plot"},spatial_scope:"same plot",visual_evidence_refs:[],source:"USER_SUBMITTED",evidence_state:"MEASURED",limitations:["No efficacy inference"],explicit_submission:true,expected_outcome_revision:0});assert.equal(decision.system_recommendation,false);assert.equal(plan.actual_execution_confirmed,false);assert.equal(performed.actual_execution_confirmed,true);assert.equal(outcome.observation.efficacy_derived,false);
}finally{await h.close();}});

test("P1-02 production negative matrix fails closed",async()=>{for(const scenario of [{name:"different Candidate",options:{conceptId:"CO-RDC-002/v1",water:true}},{name:"wrong crop",options:{crop:"maize",water:true}},{name:"missing review",options:{review:false,water:true}},{name:"unsupported review",options:{resolutionLevel:"FIELD_SUPPORTED",water:true}},{name:"missing required Evidence",options:{link:"MISSING",water:true}},{name:"Candidate support only",options:{review:false}},{name:"human review only",options:{link:"MISSING"}},{name:"relationship only without management sufficiency",options:{}}]){const h=await productionCase(scenario.options);try{const assessment=h.current(),review=h.store.assessManagementOptions("user-a",scope);assert.notEqual(assessment.evidence_sufficiency.purpose_states.MANAGEMENT_OPTION_REVIEW,"SUFFICIENT_FOR_MANAGEMENT_OPTION_REVIEW",scenario.name);assert.notEqual(cultural(review).eligibility_state,"SUPPORTED_FOR_REVIEW",scenario.name);}finally{await h.close();}}
  const contradicted=await productionCase({water:true});try{contradicted.store.createInvestigationRecord("user-a","CANDIDATE_EVIDENCE_LINK",{...scope,candidate_evidence_link_id:"link-contradiction",candidate_id:"candidate-blast",relation:"CONTRADICTING",evidence_id:"ev-blast-leaf",rationale:"Current contradiction"});const assessment=contradicted.current(),review=contradicted.store.assessManagementOptions("user-a",scope);assert.notEqual(assessment.evidence_sufficiency.purpose_states.MANAGEMENT_OPTION_REVIEW,"SUFFICIENT_FOR_MANAGEMENT_OPTION_REVIEW");assert.notEqual(cultural(review).eligibility_state,"SUPPORTED_FOR_REVIEW");}finally{await contradicted.close();}
});
