import test from "node:test";
import assert from "node:assert/strict";
import { mkdtemp, readFile, rm } from "node:fs/promises";
import { join } from "node:path";
import { tmpdir } from "node:os";
import { DatabaseSync } from "node:sqlite";
import { PilotStore } from "../pilot-store.mjs";
import { PILOT_READINESS_GATES, PILOT_SCHEMA_VERSION, preparePilotSchema, validatePilotConfiguration } from "../pilot-hardening-runtime.mjs";
import { startServer } from "../server.mjs";

const nodeRoot=()=>mkdtemp(join(tmpdir(),"cpmoakb-j-"));
const options=(root,extra={})=>({port:0,dbPath:join(root,"pilot.sqlite"),exportDir:join(root,"exports"),uploadDir:join(root,"uploads"),...extra});
async function login(base,password="1234"){const response=await fetch(base+"/api/pilot/session",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({password})});return{response,cookie:response.headers.get("set-cookie")?.split(";")[0]};}

test("Golden J-1 configuration is fail-safe and never projects its secret",async()=>{const root=await nodeRoot();try{assert.throws(()=>validatePilotConfiguration({profile:"CONTROLLED_PILOT",host:"127.0.0.1",db_path:join(root,"db"),export_dir:join(root,"out"),upload_dir:join(root,"up")}),/authentication/);assert.throws(()=>validatePilotConfiguration({host:"0.0.0.0",db_path:"db",export_dir:"out",upload_dir:"up"}),/PILOT_ALLOW_LAN/);const config=validatePilotConfiguration({profile:"CONTROLLED_PILOT",host:"127.0.0.1",db_path:join(root,"db"),export_dir:join(root,"out"),upload_dir:join(root,"up"),auth_password:"do-not-project"});assert.equal(config.same_origin_required,true);assert.equal(config.debug_private_logging,false);assert.equal(JSON.stringify({...config,auth_password:undefined}).includes("do-not-project"),false);}finally{await rm(root,{recursive:true,force:true});}});

test("Golden J-2/J-3 migration backs up first, preserves pre-J data, and rolls back injected failure",async()=>{const root=await nodeRoot(),dbPath=join(root,"pilot.sqlite"),exportDir=join(root,"exports");let store=await new PilotStore({dbPath,exportDir}).open();store.putWorkspace("user-a",{messages:[{id:"m1",text:"ข้อมูลเดิม"}]});store.db.prepare("DELETE FROM pilot_meta WHERE key='pilot_schema_version'").run();store.close();store=await new PilotStore({dbPath,exportDir,pilotProfile:"CONTROLLED_PILOT"}).open();assert.equal(store.getWorkspace("user-a").state.messages[0].text,"ข้อมูลเดิม");assert.equal(store.hardening.schemaPreparation.pre_migration_backup.verified,true);store.close();const failedPath=join(root,"failed.sqlite"),db=new DatabaseSync(failedPath);assert.rejects(preparePilotSchema(db,{profile:"TEST",dbPath:failedPath,exportDir,migrationFailureInjector:()=>{throw new Error("injected");}}),/failed safely/);assert.equal(db.prepare("SELECT COUNT(*) count FROM sqlite_master WHERE name='pilot_operational_audit'").get().count,0);db.close();await rm(root,{recursive:true,force:true});});

test("unsupported future schemas stop startup",async()=>{const root=await nodeRoot(),dbPath=join(root,"future.sqlite"),db=new DatabaseSync(dbPath);db.exec("CREATE TABLE pilot_meta(key TEXT PRIMARY KEY,value TEXT NOT NULL)");db.prepare("INSERT INTO pilot_meta VALUES('pilot_schema_version',?)").run(String(PILOT_SCHEMA_VERSION+1));db.close();await assert.rejects(new PilotStore({dbPath,exportDir:join(root,"exports")}).open(),(error)=>error.code==="SCHEMA_UNSUPPORTED");await rm(root,{recursive:true,force:true});});

test("Golden J-4/J-10 verified backup restores an isolated reconstructable copy",async()=>{const root=await nodeRoot(),dbPath=join(root,"pilot.sqlite"),exportDir=join(root,"exports"),store=await new PilotStore({dbPath,exportDir}).open();try{store.putWorkspace("user-a",{messages:[{id:"m1",text:"persist"}]});const backup=await store.createVerifiedBackup();assert.equal(backup.integrity_state,"PASS");const restored=await store.verifyBackupRestore(backup.backup_file,join(root,"restore","copy.sqlite"));assert.equal(restored.restore_verified,true);assert.equal(restored.target_is_live,false);assert.equal(store.getPilotReadiness({provider_state:"READY",visual_provider_state:"READY"}).state,"CONTROLLED_PILOT_READY_CANDIDATE");store.close();const reopened=await new PilotStore({dbPath,exportDir}).open();try{assert.equal(reopened.getWorkspace("user-a").state.messages[0].text,"persist");assert.equal(reopened.getPilotReadiness({provider_state:"READY",visual_provider_state:"READY"}).state,"CONTROLLED_PILOT_READY_CANDIDATE");}finally{reopened.close();}}finally{store.close();await rm(root,{recursive:true,force:true});}});

test("Golden J-18/J-20 audit is redacted and any stop condition blocks readiness",async()=>{const root=await nodeRoot(),store=await new PilotStore({dbPath:join(root,"pilot.sqlite"),exportDir:join(root,"exports")}).open();try{store.recordOperationalAudit("PRIVATE_CASE",{correlation_id:"request-1",scope:{private_note:"ห้ามบันทึกข้อความนี้"},detail_code:"BOUNDED"});const events=store.getOperationalAudit(),serialized=JSON.stringify(events);assert.doesNotMatch(serialized,/ห้ามบันทึก|password|OPENAI_API_KEY/);assert.equal(events.at(-1).raw_content_logged,false);const ready=store.getPilotReadiness({blocking_conditions:["CROSS_USER_PRIVACY_BREACH"]});assert.equal(ready.state,"PILOT_BLOCKED");assert.equal(ready.real_field_validation,"NOT_RUN");assert.equal(ready.production_certified,false);assert.equal(ready.gates.length,PILOT_READINESS_GATES.length);}finally{store.close();await rm(root,{recursive:true,force:true});}});

test("validation records are owner scoped, idempotent, and never become science or training",async()=>{const root=await nodeRoot(),store=await new PilotStore({dbPath:join(root,"pilot.sqlite"),exportDir:join(root,"exports")}).open(),input={request_id:"validation-1",validation_round:1,participant_role:"INTERNAL_REVIEWER",synthetic:true,attempted_workflow:"A-J",completion_state:"COMPLETED_WITH_FINDINGS",user_feedback:"หน้าจอช้า"};try{const first=store.createPilotValidationRecord("user-a",input),replay=store.createPilotValidationRecord("user-a",input);assert.equal(replay.idempotent_replay,true);assert.equal(first.feedback_is_scientific_evidence,false);assert.equal(first.knowledge_changed,false);assert.equal(store.getPilotValidationRecords("user-b").length,0);assert.throws(()=>store.createPilotValidationRecord("user-a",{...input,user_feedback:"changed"}),/changed payload/);assert.ok(store.getPilotDebtRegister().some((item)=>item.detail==="REAL_FIELD_VALIDATION_NOT_RUN"));}finally{store.close();await rm(root,{recursive:true,force:true});}});

test("HTTP hardening enforces profile auth, logout, content type, limits, CSRF, feature flags, and correlations",async()=>{const root=await nodeRoot(),server=await startServer(options(root,{pilotProfile:"CONTROLLED_PILOT",authPassword:"pilot-secret",pilotUserId:"user-a",featureFlags:{step_i_learning:false},requestLimits:{json_bytes:1024,chat_text_chars:100,upload_bytes:1024}}));try{const base=`http://127.0.0.1:${server.address().port}`;const health=await fetch(base+"/health"),readiness=await fetch(base+"/readiness");assert.equal(health.status,200);assert.equal((await health.json()).process_alive,true);assert.equal((await readiness.json()).real_field_validation,"NOT_RUN");const denied=await login(base,"1234");assert.equal(denied.response.status,401);const {response,cookie}=await login(base,"pilot-secret");assert.equal(response.status,200);assert.ok(response.headers.get("x-correlation-id"));const disabled=await fetch(base+"/api/pilot/knowledge-graph",{headers:{cookie}});assert.equal(disabled.status,503);const invalidType=await fetch(base+"/api/pilot/feedback",{method:"POST",headers:{cookie},body:"{}"});assert.equal(invalidType.status,415);const csrf=await fetch(base+"/api/pilot/feedback",{method:"POST",headers:{cookie,"content-type":"application/json",origin:"https://evil.example"},body:"{}"});assert.equal(csrf.status,403);const huge=await fetch(base+"/api/pilot/validation-records",{method:"POST",headers:{cookie,"content-type":"application/json"},body:JSON.stringify({padding:"x".repeat(2000)})});assert.equal(huge.status,413);const logout=await fetch(base+"/api/pilot/session/logout",{method:"POST",headers:{cookie}});assert.equal(logout.status,200);assert.equal((await fetch(base+"/api/pilot/debt-register",{headers:{cookie}})).status,401);}finally{await new Promise((done)=>server.close(done));await rm(root,{recursive:true,force:true,maxRetries:5,retryDelay:50});}});

test("user export is isolated and summary exposes no database path",async()=>{const root=await nodeRoot(),dbPath=join(root,"pilot.sqlite"),exportDir=join(root,"exports"),store=await new PilotStore({dbPath,exportDir}).open();try{store.putWorkspace("user-a",{messages:[{id:"a",text:"alpha"}]});store.putWorkspace("user-b",{messages:[{id:"b",text:"private-beta"}]});assert.equal("storage_path" in store.summary(),false);const result=await store.exportUser("user-a"),text=await readFile(join(exportDir,result.json_file),"utf8");assert.match(text,/alpha/);assert.doesNotMatch(text,/private-beta|pilot-secret|OPENAI_API_KEY/);assert.equal(JSON.parse(text).export_scope,"AUTHENTICATED_USER_ONLY");}finally{store.close();await rm(root,{recursive:true,force:true});}});
