import test from "node:test";
import assert from "node:assert/strict";
import { mkdtemp, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { PilotStore } from "../pilot-store.mjs";
import { startServer } from "../server.mjs";
import { createTestOnlyConversationProvider } from "../conversation-orchestrator.mjs";
import { COMPARABILITY_STATES, ADJUDICATION_STATES, PATTERN_GAPS } from "../spatial-local-pattern-runtime.mjs";

const now="2026-08-28T03:00:00.000Z";
function ids(){let value=0;return()=>`h-id-${++value}`;}
function lifecycle(userId="user-a"){
  const fields=["a","b","c"].map((suffix,index)=>({field_id:`field-${suffix}`,owner_user_id:userId,name:`private field ${suffix}`,polygon:{type:"Polygon",coordinates:[[[100+index,13],[100.01+index,13],[100+index,13.01],[100+index,13]]]},centroid:{latitude:13.005,longitude:100.005+index},crop:"rice",planting_date:"2026-07-01",current_crop_stage:{code:"TILLERING",label:"แตกกอ"},current_cmp_stage:{stage_id:"CMP-03",label:"ระยะแตกกอ"},season_id:`season-${suffix}`,stage_provenance:"USER_CONFIRMED",created_at:"2026-07-01T00:00:00.000Z",updated_at:"2026-08-20T00:00:00.000Z"}));
  return{schema_version:2,users:[{user_id:userId}],fields,seasons:fields.map((field)=>({season_id:field.season_id,field_id:field.field_id,crop:"rice",status:"ACTIVE"})),guidance:[],activities:[],cases:[],observations:[],evidence:[],conversations:[],messages:[],decision_logs:[],case_summaries:[],weather_snapshots:[]};
}
async function setup(userId="user-a"){
  const root=await mkdtemp(join(tmpdir(),"cpmoakb-h-")),store=await new PilotStore({dbPath:join(root,"pilot.sqlite"),exportDir:join(root,"exports"),spatialPatternClock:()=>new Date(now),spatialPatternIdProvider:ids()}).open();store.putWorkspace(userId,lifecycle(userId));return{root,store,userId,close:async()=>{store.close();await rm(root,{recursive:true,force:true});}};
}
function create(h,type,scope,record){return h.store.createInvestigationRecord(h.userId,type,{...scope,...record});}
function seedCase(h,suffix,{fieldSuffix=suffix,candidateClass="DISEASE",phenotype="YELLOWING",plantPart="LEAF_BLADE",eventAt=null}={}){
  const scope={field_id:`field-${fieldSuffix}`,season_id:`season-${fieldSuffix}`},caseId=`case-${suffix}`,observedAt=`2026-08-${suffix==="a"?"20":"21"}T02:00:00Z`;
  create(h,"CASE",scope,{case_id:caseId,purpose:"Bounded local pattern review",opened_at:observedAt});
  const observation=create(h,"OBSERVATION",scope,{observation_id:`obs-${suffix}`,case_id:caseId,observed_at:observedAt,source:"FIELD_OBSERVED",confidence:"MODERATE",review_state:"HUMAN_REVIEWED",note:"reviewed field observation"});
  const spatial=create(h,"SPATIAL_EVIDENCE",scope,{evidence_id:`spatial-${suffix}`,observation_id:observation.observation_id,case_id:caseId,observed_at:observedAt,source:"FIELD_OBSERVED",confidence:"MODERATE",evidence_level:"SP1_SITE_SUPPORTED",review_state:"HUMAN_REVIEWED",payload:{observation_scope:"PATCH",geometry:"PATCH",field_positions:["INTERIOR"],patterns:["PATCH"],field_extent:"LOCAL",direction:"NO_CLEAR_DIRECTION",affected_status:"AFFECTED",location_provenance:"FIELD_MAP_SELECTED",zone_reference:`zone-${suffix}`}});
  const morphology=create(h,"MORPHOLOGY_EVIDENCE",scope,{evidence_id:`morph-${suffix}`,observation_id:observation.observation_id,case_id:caseId,observed_at:observedAt,source:"FIELD_OBSERVED",confidence:"MODERATE",evidence_level:"MO1_DIRECT_OBSERVATION",review_state:"HUMAN_REVIEWED",payload:{plant_part:plantPart,primary_phenotypes:[phenotype],color:"yellow",observability:"DIRECT",negative_evidence:[]}});
  const sampling=create(h,"SAMPLING_SESSION",scope,{evidence_id:`sampling-${suffix}`,observation_id:observation.observation_id,case_id:caseId,observed_at:observedAt,source:"FIELD_OBSERVED",confidence:"MODERATE",evidence_level:"SM2_MULTI_SITE_SAMPLED",review_state:"HUMAN_REVIEWED",payload:{sampling_mode:"S2_GUIDED_INVESTIGATION",sampling_unit:"HILL",plant_part:plantPart,sites_count:2,units_per_site:10,sampling_method:"bounded comparison sites",representativeness:"MULTI_ZONE_REPRESENTATIVE"}});
  const measurement=create(h,"SEVERITY_MEASUREMENT",scope,{evidence_id:`measure-${suffix}`,observation_id:observation.observation_id,case_id:caseId,observed_at:observedAt,source:"FIELD_OBSERVED",confidence:"MODERATE",evidence_level:"SV3_SAMPLING_SUPPORTED",review_state:"HUMAN_REVIEWED",payload:{measurement_concept:"AFFECTED_HILLS",numerator:2,denominator:20,unit:"COUNT_RATIO",sampling_reference_id:sampling.evidence_id,plant_part:plantPart}});
  create(h,"WATER_CONTEXT",scope,{evidence_id:`water-${suffix}`,observation_id:observation.observation_id,case_id:caseId,observed_at:observedAt,source:"FIELD_OBSERVED",confidence:"MODERATE",evidence_level:"WT1_FIELD_OBSERVED",review_state:"HUMAN_REVIEWED",payload:{water_state:"MOIST",zone_reference:`zone-${suffix}`,source:"FIELD_OBSERVED"}});
  create(h,"CANDIDATE",scope,{candidate_id:`candidate-${suffix}`,case_id:caseId,candidate_class:candidateClass,label:"reviewed yellowing candidate",support_state:"SUPPORTED",review_state:"HUMAN_REVIEWED"});
  create(h,"TEMPORAL_EVIDENCE",scope,{temporal_evidence_id:`temporal-${suffix}`,case_id:caseId,observation_id:observation.observation_id,event_kind:"OBSERVED_AT",event_at:observedAt,time_precision:"EXACT",progression_state:"STABLE",evidence_level:"TC2_DATE_SUPPORTED",source:"FIELD_OBSERVED"});
  create(h,"MANAGEMENT_EVENT",scope,{management_event_id:`management-${suffix}`,case_id:caseId,event_type:"UNKNOWN_MANAGEMENT_EVENT",event_at:eventAt??observedAt,time_precision:"EXACT",source:"HUMAN_RECORDED",note:"context only"});
  create(h,"OUTCOME",scope,{outcome_id:`outcome-${suffix}`,case_id:caseId,observed_at:observedAt,outcome_dimensions:["VISIBLE_PATTERN"],measurement_references:[measurement.evidence_id],spatial_references:[spatial.evidence_id],morphology_references:[morphology.evidence_id],sampling_references:[sampling.evidence_id],new_damage_status:"UNKNOWN",existing_damage_status:"UNCHANGED",recovery_status:"NOT_ASSESSABLE",comparability:"LIMITED",outcome_confidence:"MODERATE",attribution_confidence:"LOW",evidence_level:"OC3_COMPARABLE_FOLLOWUP",source:"FIELD_OBSERVED",review_state:"HUMAN_REVIEWED"});
  return{...scope,case_id:caseId,observation_id:observation.observation_id};
}
function comparisonInput(cases,values={}){return{request_id:"compare-1",comparison_id:"comparison-h",review_question:"Do these reviewed observations show a compatible local yellowing-patch pattern?",granularity:"PHENOTYPE_LEVEL",case_refs:cases.map(({field_id,season_id,case_id})=>({field_id,season_id,case_id})),spatial_relationship:"SAME_BOUNDED_AREA",spatial_relationship_authority:"HUMAN_REVIEWED_RELATIONSHIP",human_review:{submitted_explicitly:true,decision:"INCLUDE_TOGETHER",include_case_ids:cases.map((item)=>item.case_id),exclusion_reasons:{},rationale:"Explicit 094-style bounded comparison review.",limitations:["Reported Cases only"]},...values};}
function candidateInput(comparison,values={}){return{request_id:"candidate-1",local_pattern_candidate_id:"candidate-h",comparison_id:comparison.comparison_id,comparison_revision:comparison.revision,descriptive_pattern:"Reviewed Cases contain compatible local yellowing-patch observations.",sampling_limitations:["No denominator for all local Fields"],conflicts:[],alternative_explanations:["water context","sampling variation"],...values};}
function adjudicationInput(candidate,values={}){return{request_id:"adjudicate-1",local_pattern_adjudication_id:"adjudication-h",local_pattern_candidate_id:candidate.local_pattern_candidate_id,human_adjudication:{submitted_explicitly:true,state:"SUFFICIENT_FOR_FURTHER_REVIEW",decision:"CONTINUE_STRUCTURED_REVIEW",reviewer_reference:"reviewer-1",reviewer_role:"AGRONOMIC_REVIEWER",reviewer_scope:"bounded local evidence sufficiency",rationale:"Explicit review supports structured local review only.",limitations:["No official surveillance denominator"],conflicts:[],retained_conflicting_case_ids:[]},...values};}

test("H1/H3-H8: authoritative comparison is explainable, bounded, denominator-safe, and candidate-gated",async()=>{const h=await setup();try{const a=seedCase(h,"a"),b=seedCase(h,"b"),comparison=h.store.createCrossCaseComparison(h.userId,comparisonInput([a,b]));assert.ok(COMPARABILITY_STATES.includes(comparison.comparability_state));assert.equal(comparison.review_question.startsWith("Do these reviewed"),true);assert.equal(comparison.granularity,"PHENOTYPE_LEVEL");assert.equal(comparison.deterministic_logic.hidden_weighting,false);assert.equal(comparison.deterministic_logic.comparability_score,null);assert.equal(comparison.dimensions.every((item)=>item.state&&item.hidden_weight===null),true);assert.equal(comparison.spatial_context.transmission_inference,null);assert.deepEqual([comparison.non_conclusions.prevalence,comparison.non_conclusions.incidence,comparison.non_conclusions.risk_probability],[null,null,null]);assert.equal(comparison.denominator_context.local_fields_denominator,null);const candidate=h.store.createLocalPatternCandidate(h.userId,candidateInput(comparison));assert.equal(candidate.canonical,false);assert.equal(candidate.official_outbreak,false);assert.equal(candidate.recommendation,null);assert.deepEqual(candidate.included_case_ids,["case-a","case-b"]);assert.equal(candidate.authorized_field_references.length,2);assert.equal(candidate.maturity.level,"LP1");}finally{await h.close();}});

test("H2/H4/H6: same Field event is not amplified and conflicts lower sufficiency",async()=>{const h=await setup();try{const a=seedCase(h,"a",{fieldSuffix:"a",eventAt:"2026-08-20T03:00:00Z"}),b=seedCase(h,"b",{fieldSuffix:"a",eventAt:"2026-08-20T03:00:00Z"}),comparison=h.store.createCrossCaseComparison(h.userId,comparisonInput([a,b],{spatial_relationship:undefined})),candidate=h.store.createLocalPatternCandidate(h.userId,candidateInput(comparison)),adjudication=h.store.createLocalPatternAdjudication(h.userId,adjudicationInput(candidate));const independence=adjudication.dimensions.find((item)=>item.id==="case_independence");assert.equal(independence.state,"CONFLICTING");assert.ok(independence.same_field_events.length>0);assert.equal(adjudication.adjudication_state,"CONFLICTING_EVIDENCE");assert.equal(adjudication.governed_local_pattern,null);}finally{await h.close();}});

test("H5/H6: phenotype and target incompatibilities remain explicit hard boundaries",async()=>{const h=await setup();try{const a=seedCase(h,"a"),b=seedCase(h,"b",{phenotype:"WILTING",plantPart:"ROOT_SYSTEM",candidateClass:"WATER_STRESS"}),comparison=h.store.createCrossCaseComparison(h.userId,comparisonInput([a,b]));assert.equal(comparison.comparability_state,"NOT_COMPARABLE");for(const dimension of ["morphology_phenotype","plant_part"])assert.equal(comparison.dimensions.find((item)=>item.id===dimension).state,"MATERIAL_DIFFERENCE");assert.throws(()=>h.store.createLocalPatternCandidate(h.userId,candidateInput(comparison)),/Human Review/);}finally{await h.close();}});

test("H7/H12/H18: adjudicated pattern remains descriptive, non-outbreak, and non-product",async()=>{const h=await setup();try{const a=seedCase(h,"a"),b=seedCase(h,"b"),comparison=h.store.createCrossCaseComparison(h.userId,comparisonInput([a,b])),candidate=h.store.createLocalPatternCandidate(h.userId,candidateInput(comparison)),adjudication=h.store.createLocalPatternAdjudication(h.userId,adjudicationInput(candidate));assert.ok(ADJUDICATION_STATES.includes(adjudication.adjudication_state));assert.equal(adjudication.adjudication_state,"SUFFICIENT_FOR_FURTHER_REVIEW");assert.equal(adjudication.governed_local_pattern.state,"GOVERNED_LOCAL_PATTERN");assert.equal(adjudication.governed_local_pattern.official_outbreak_status,"NOT_EVALUATED");assert.equal(adjudication.governed_local_pattern.efficacy_claim,null);assert.equal(adjudication.governed_local_pattern.resistance_claim,null);assert.equal(adjudication.governed_local_pattern.recommendation,null);assert.equal(adjudication.product_comparison_interaction.preferred_product,null);assert.equal(adjudication.regulatory_interaction.authority_changed,false);}finally{await h.close();}});

test("H9/H11: a corrected source revision reopens the immutable prior adjudication",async()=>{const h=await setup();try{const a=seedCase(h,"a"),b=seedCase(h,"b"),comparison=h.store.createCrossCaseComparison(h.userId,comparisonInput([a,b])),candidate=h.store.createLocalPatternCandidate(h.userId,candidateInput(comparison)),adjudication=h.store.createLocalPatternAdjudication(h.userId,adjudicationInput(candidate));h.store.updateInvestigationRecord(h.userId,"OBSERVATION",a.observation_id,1,{observation_id:a.observation_id,field_id:a.field_id,season_id:a.season_id,case_id:a.case_id,observed_at:"2026-08-20T02:00:00Z",source:"FIELD_OBSERVED",confidence:"MODERATE",review_state:"HUMAN_REVIEWED",note:"corrected observation"},"correct-observation");const context=h.store.getLocalPatternContext(h.userId,candidate.local_pattern_candidate_id);assert.equal(context.candidate.stale,true);assert.equal(context.current_adjudication.projected_adjudication_state,"STALE_REVIEW_REQUIRED");assert.equal(h.store.getLocalPatternAdjudications(h.userId,candidate.local_pattern_candidate_id)[0].local_pattern_adjudication_id,adjudication.local_pattern_adjudication_id);assert.equal(h.store.db.prepare("SELECT COUNT(*) count FROM governed_local_pattern_adjudications").get().count,1);}finally{await h.close();}});

test("H10: split retains parent and creates traceable child Candidates",async()=>{const h=await setup();try{const a=seedCase(h,"a"),b=seedCase(h,"b"),comparison=h.store.createCrossCaseComparison(h.userId,comparisonInput([a,b])),candidate=h.store.createLocalPatternCandidate(h.userId,candidateInput(comparison)),input=adjudicationInput(candidate);input.human_adjudication={...input.human_adjudication,state:"CONFLICTING_EVIDENCE",decision:"SPLIT_PATTERN",split_groups:[{local_pattern_candidate_id:"child-a",label:"Field A subgroup",case_ids:[a.case_id]},{local_pattern_candidate_id:"child-b",label:"Field B subgroup",case_ids:[b.case_id]}]};const result=h.store.createLocalPatternAdjudication(h.userId,input);assert.equal(result.pattern_splitting.parent_retained,true);assert.equal(result.pattern_splitting.children.length,2);assert.equal(h.store.getLocalPatternCandidates(h.userId).find((item)=>item.local_pattern_candidate_id==="child-a").parent_pattern_candidate_id,candidate.local_pattern_candidate_id);}finally{await h.close();}});

test("H13/H16/H17: one Step H gap feeds Step D context, never Step G scheduling or Step I learning",async()=>{const h=await setup();try{const a=seedCase(h,"a"),b=seedCase(h,"b"),comparison=h.store.createCrossCaseComparison(h.userId,comparisonInput([a,b])),candidate=h.store.createLocalPatternCandidate(h.userId,candidateInput(comparison)),adjudication=h.store.createLocalPatternAdjudication(h.userId,adjudicationInput(candidate));assert.equal(adjudication.inspection_guidance.count,1);assert.ok(["INSPECT_ADDITIONAL_FIELD","INSPECT_COMPARISON_AREA","COLLECT_MISSING_SPATIAL_EVIDENCE","COLLECT_MISSING_TEMPORAL_EVIDENCE","VERIFY_CASE_INDEPENDENCE","EXPERT_REVIEW"].includes(adjudication.inspection_guidance.action));assert.equal(adjudication.inspection_guidance.treatment_task,false);assert.equal(adjudication.inspection_guidance.reminder_created,false);assert.equal(adjudication.learn.automatic_learning,false);assert.equal(adjudication.learn.knowledge_promotion,false);const context=h.store.getLocalPatternContext(h.userId,candidate.local_pattern_candidate_id);assert.equal(context.step_d_authority,true);assert.equal(context.step_g_reminder_authority,true);assert.equal(context.step_h_scheduler,false);assert.ok(PATTERN_GAPS.includes(context.pattern_gaps[0].code));assert.match(context.conversation_projection.thai,/ยังเรียกว่าเป็นการระบาดไม่ได้/);}finally{await h.close();}});

test("stronger inference fails closed without executing statistics",async()=>{const h=await setup();try{const a=seedCase(h,"a"),b=seedCase(h,"b"),comparison=h.store.createCrossCaseComparison(h.userId,comparisonInput([a,b])),candidate=h.store.createLocalPatternCandidate(h.userId,candidateInput(comparison)),adjudication=h.store.createLocalPatternAdjudication(h.userId,adjudicationInput(candidate,{intended_review_strength:"STRONGER_INFERENCE"}));assert.equal(adjudication.statistical_method.state,"METHOD_REQUIRED_BEFORE_STRONGER_INFERENCE");assert.deepEqual(adjudication.statistical_method.computations_executed,[]);assert.equal(adjudication.statistical_method.stronger_inference_authorized,false);}finally{await h.close();}});

test("H14: ownership and privacy projection reject cross-user reads and hide exact geometry",async()=>{const h=await setup();try{const a=seedCase(h,"a"),b=seedCase(h,"b"),comparison=h.store.createCrossCaseComparison(h.userId,comparisonInput([a,b])),candidate=h.store.createLocalPatternCandidate(h.userId,candidateInput(comparison)),projection=h.store.getSpatialPatternProjection(h.userId,candidate.local_pattern_candidate_id);assert.equal(projection.fields.every((item)=>item.coordinates===null&&item.polygon===null&&item.precise_location_hidden),true);assert.deepEqual(projection.farmer_names,[]);assert.deepEqual(projection.product_history,[]);assert.throws(()=>h.store.getSpatialPatternProjection("user-b",candidate.local_pattern_candidate_id),/not found|privacy/i);assert.throws(()=>h.store.createCrossCaseComparison("user-b",comparisonInput([a,b],{request_id:"cross-user"})),/privacy scope/i);}finally{await h.close();}});

test("idempotency, optimistic concurrency, immutable revisions, and timeline boundaries hold",async()=>{const h=await setup();try{const a=seedCase(h,"a"),b=seedCase(h,"b"),input=comparisonInput([a,b]),first=h.store.createCrossCaseComparison(h.userId,input),replay=h.store.createCrossCaseComparison(h.userId,input);assert.equal(replay.idempotent_replay,true);assert.throws(()=>h.store.createCrossCaseComparison(h.userId,{...input,request_id:"compare-conflict",expected_revision:0,human_review:{...input.human_review,rationale:"another immutable revision"}}),/changed before submission/);const candidateInputValue=candidateInput(first),candidate=h.store.createLocalPatternCandidate(h.userId,candidateInputValue);assert.equal(h.store.createLocalPatternCandidate(h.userId,candidateInputValue).idempotent_replay,true);const adjudicationValue=adjudicationInput(candidate),adjudication=h.store.createLocalPatternAdjudication(h.userId,adjudicationValue);assert.equal(h.store.createLocalPatternAdjudication(h.userId,adjudicationValue).idempotent_replay,true);const timeline=h.store.getAuthoritativeTimeline(h.userId,a),patternEvent=timeline.events.find((item)=>item.source_record_type==="LOCAL_PATTERN_ADJUDICATION");assert.ok(patternEvent);assert.match(patternEvent.summary,/not Evidence/);assert.equal(timeline.boundary.includes("NO_CAUSAL_OR_SCIENTIFIC_INFERENCE"),true);}finally{await h.close();}});

test("H15 APIs are authenticated, server-authoritative, and return bounded failure",async()=>{const root=await mkdtemp(join(tmpdir(),"cpmoakb-h-api-")),dbPath=join(root,"pilot.sqlite"),exportDir=join(root,"exports"),seed=await new PilotStore({dbPath,exportDir,spatialPatternClock:()=>new Date(now),spatialPatternIdProvider:ids()}).open();seed.putWorkspace("user-a",lifecycle());const h={store:seed,userId:"user-a"},a=seedCase(h,"a"),b=seedCase(h,"b");seed.close();const server=await startServer({port:0,dbPath,exportDir,uploadDir:join(root,"uploads"),spatialPatternClock:()=>new Date(now),spatialPatternIdProvider:ids()});try{const base=`http://127.0.0.1:${server.address().port}`,login=await fetch(`${base}/api/pilot/session`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({password:"1234",user_id:"user-a"})}),cookie=login.headers.get("set-cookie").split(";")[0],created=await fetch(`${base}/api/pilot/cross-case-comparisons`,{method:"POST",headers:{cookie,"content-type":"application/json"},body:JSON.stringify(comparisonInput([a,b]))}),payload=await created.json();assert.equal(created.status,201);assert.equal(payload.authority,"SERVER_GOVERNED_CROSS_CASE_COMPARISON");assert.equal((await fetch(`${base}/api/pilot/cross-case-comparisons`,{headers:{cookie}})).status,200);assert.equal((await fetch(`${base}/api/pilot/cross-case-comparisons`)).status,401);const failed=await fetch(`${base}/api/pilot/local-pattern-context?local_pattern_candidate_id=missing`,{headers:{cookie}}),failure=await failed.json();assert.equal(failed.status,403);assert.equal(failure.error_code,"AUTHORIZATION_ERROR");assert.equal(failure.message,"ไม่มีสิทธิ์เข้าถึงข้อมูลการตรวจนี้");}finally{await new Promise((done)=>server.close(done));await rm(root,{recursive:true,force:true});}});

test("Golden H-1/H-2: duplicate Case input is rejected and unknown evidence never becomes a match",async()=>{const h=await setup();try{const a=seedCase(h,"a");assert.throws(()=>h.store.createCrossCaseComparison(h.userId,comparisonInput([a,a])),/duplicate Case/);const b=seedCase(h,"b");h.store.db.prepare("DELETE FROM investigation_evidence WHERE evidence_id=?").run("water-b");const comparison=h.store.createCrossCaseComparison(h.userId,comparisonInput([a,b],{request_id:"unknown-compare",comparison_id:"unknown-comparison"}));assert.equal(comparison.dimensions.find((item)=>item.id==="environment_water_context").state,"UNKNOWN");assert.equal(comparison.comparability_state,"NEEDS_HUMAN_REVIEW");}finally{await h.close();}});

test("Golden H-4/H-7: calendar proximity remains descriptive and reported Cases do not create prevalence",async()=>{const h=await setup();try{const a=seedCase(h,"a"),b=seedCase(h,"b"),comparison=h.store.createCrossCaseComparison(h.userId,comparisonInput([a,b]));assert.equal(comparison.temporal_context.overlap_descriptive_only,true);assert.equal(comparison.temporal_context.transmission_inference,null);assert.equal(comparison.non_conclusions.outbreak,null);assert.equal(comparison.denominator_context.cases_considered,2);assert.equal(comparison.denominator_context.local_fields_denominator,null);assert.equal(comparison.non_conclusions.prevalence,null);assert.equal(comparison.non_conclusions.incidence,null);}finally{await h.close();}});

test("Golden H-8/H-9: explicit exclusions and retained conflicting Case evidence remain visible",async()=>{const h=await setup();try{const a=seedCase(h,"a"),b=seedCase(h,"b"),c=seedCase(h,"c"),input=comparisonInput([a,b,c]);input.human_review.include_case_ids=[a.case_id,b.case_id];input.human_review.exclusion_reasons={[c.case_id]:"different reviewed subgroup"};const comparison=h.store.createCrossCaseComparison(h.userId,input),candidate=h.store.createLocalPatternCandidate(h.userId,candidateInput(comparison));assert.deepEqual(candidate.excluded_cases,[{case_id:c.case_id,reason:"different reviewed subgroup"}]);const adjudicationInputValue=adjudicationInput(candidate);adjudicationInputValue.human_adjudication={...adjudicationInputValue.human_adjudication,retained_conflicting_case_ids:[b.case_id]};const result=h.store.createLocalPatternAdjudication(h.userId,adjudicationInputValue);assert.equal(result.dimensions.find((item)=>item.id==="conflicting_evidence").state,"CONFLICTING");assert.deepEqual(result.human_adjudication.retained_conflicting_case_ids,[b.case_id]);assert.equal(result.adjudication_state,"CONFLICTING_EVIDENCE");}finally{await h.close();}});

test("Golden H-10 rejection is traceable and cannot delete the Candidate",async()=>{const h=await setup();try{const a=seedCase(h,"a"),b=seedCase(h,"b"),comparison=h.store.createCrossCaseComparison(h.userId,comparisonInput([a,b])),candidate=h.store.createLocalPatternCandidate(h.userId,candidateInput(comparison)),input=adjudicationInput(candidate);input.human_adjudication={...input.human_adjudication,state:"INSUFFICIENT_EVIDENCE",decision:"REJECT_PATTERN",rationale:"Evidence provenance is inadequate for this bounded review."};const result=h.store.createLocalPatternAdjudication(h.userId,input);assert.deepEqual(result.rejection,{rejected:true,traceable:true,reason:"Evidence provenance is inadequate for this bounded review."});assert.equal(h.store.getLocalPatternCandidates(h.userId).some((item)=>item.local_pattern_candidate_id===candidate.local_pattern_candidate_id),true);}finally{await h.close();}});

test("Golden H-15 provider failure cannot manufacture a Local Pattern or outbreak answer",async()=>{const root=await mkdtemp(join(tmpdir(),"cpmoakb-h-provider-")),provider=createTestOnlyConversationProvider(()=>{throw new Error("offline");}),store=await new PilotStore({dbPath:join(root,"pilot.sqlite"),exportDir:join(root,"exports"),conversationProvider:provider}).open();try{store.putWorkspace("user-a",lifecycle());const result=await store.orchestrateConversationTurn("user-a",{request_id:"h-provider-failure",message:"แถวนี้มีระบาดไหม",entry_point:"FIELD",field_id:"field-a",season_id:"season-a"});assert.equal(result.response_type,"SYSTEM_LIMITATION");assert.equal(result.fact_record_references.length,0);assert.equal(store.db.prepare("SELECT COUNT(*) count FROM governed_cross_case_comparisons").get().count,0);assert.equal(store.db.prepare("SELECT COUNT(*) count FROM governed_local_pattern_candidates").get().count,0);assert.equal(store.db.prepare("SELECT COUNT(*) count FROM governed_local_pattern_adjudications").get().count,0);assert.doesNotMatch(result.text,/ระบาดแล้ว|OUTBREAK_CONFIRMED/);}finally{store.close();await rm(root,{recursive:true,force:true});}});
