import test from "node:test";
import assert from "node:assert/strict";
import { createHash } from "node:crypto";
import { mkdtemp, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { createEmptyCandidateProvider, createGoldenTestOnlyCandidateProvider } from "../candidate-provider.mjs";
import { PilotStore } from "../pilot-store.mjs";
import { startServer } from "../server.mjs";
import { VISUAL_EVIDENCE_ENUMS, VisualPerceptionProvider, createTestOnlyVisualPerceptionProvider } from "../visual-evidence.mjs";

const scope={field_id:"field-visual",crop_season_id:"season-visual",case_id:"case-visual"},now="2026-08-27T06:00:00.000Z";
function ids(){let n=0;return()=>`00000000-0000-4000-8000-${String(++n).padStart(12,"0")}`;}
function lifecycle(userId="user-a"){return {schema_version:2,users:[{user_id:userId}],fields:[{field_id:scope.field_id,owner_user_id:userId,name:"นา visual",crop:"rice",planting_date:"2026-07-01",current_crop_stage:{code:"TILLERING",label:"TILLERING",model_version:"field-stage-model/v1"},current_cmp_stage:{stage_id:"CMP-03",label:"ระยะแตกกอ",model_version:"field-stage-model/v1"},season_id:scope.crop_season_id,stage_provenance:"USER_CONFIRMED",created_at:"2026-07-01T00:00:00.000Z",updated_at:now}],seasons:[{season_id:scope.crop_season_id,field_id:scope.field_id,crop:"rice",status:"ACTIVE"}],guidance:[],activities:[],cases:[],observations:[],evidence:[],conversations:[],messages:[],decision_logs:[],case_summaries:[],weather_snapshots:[]};}
async function setup(perceptionProvider=null,candidateProvider=createEmptyCandidateProvider()){const root=await mkdtemp(join(tmpdir(),"cpmoakb-visual-")),store=await new PilotStore({dbPath:join(root,"pilot.sqlite"),exportDir:join(root,"exports"),investigationCandidateProvider:candidateProvider,intelligenceClock:()=>new Date(now),intelligenceIdProvider:ids(),guidanceClock:()=>new Date(now),guidanceIdProvider:ids(),visualPerceptionProvider:perceptionProvider,visualClock:()=>new Date(now),visualIdProvider:ids()}).open();store.putWorkspace("user-a",lifecycle());const caseRecord=store.createInvestigationRecord("user-a","CASE",{field_id:scope.field_id,season_id:scope.crop_season_id,case_id:scope.case_id,purpose:"Visual evidence case"}),observation=store.createInvestigationRecord("user-a","OBSERVATION",{field_id:scope.field_id,season_id:scope.crop_season_id,case_id:scope.case_id,observation_id:"obs-visual",source:"FIELD_OBSERVED",observed_at:"2026-08-20T08:00:00Z",note:"yellowing patch low spot"});return {root,store,caseRecord,observation,close:async()=>{store.close();await rm(root,{recursive:true,force:true});}};}
let fileN=0;function imageInput(overrides={}){const value=++fileN,bytes=Buffer.from(`visual-${value}`);return {field_id:scope.field_id,crop_season_id:scope.crop_season_id,case_id:scope.case_id,observation_id:"obs-visual",captured_at:"2026-08-20T08:00:00Z",source:"UPLOAD",capture_intent:"LEAF",plant_part_scope:"LEAF_BLADE",spatial_scope:"SAMPLED_OBJECT",view_type:"DETAIL",media_type:"image/png",original_filename:`leaf-${value}.png`,size_bytes:bytes.length,content_hash:createHash("sha256").update(bytes).digest("hex"),storage_key:`visual-${value}.png`,comparison_role:"UNKNOWN_ROLE",comparison_role_source:"UNKNOWN",...overrides};}
const rootGuidance=(overrides={})=>({guidance_id:"guidance-root",guidance_type:"EVIDENCE_COMPLETION",inspection_domain:"ROOT_INSPECTION",evidence_concept:"ROOT_COMPARISON",why_now:"Root comparison distinguishes the remaining Candidate explanations.",where_to_inspect:"affected patch and nearby normal area",how_to_inspect:"compare both roots",assessment_id:"assessment-root",related_evidence_gap_refs:["gap-root"],stage_assessment_id:"stage-season-visual",...overrides});
const assessment=(overrides={})=>({quality:{FOCUS:"GOOD",EXPOSURE:"ACCEPTABLE"},observability:[{target:"YELLOWING",state:"ASSESSABLE",basis:"detail visible",appropriate_view:true}],features:[{feature_code:"YELLOWING",state:"OBSERVED",review_basis:"visible on sampled leaf"}],assessment_method:"EXPLICIT_STRUCTURED_INPUT",assessment_version:"fixture/v1",...overrides});
async function confirmedImage(h,overrides={}){let image=h.store.createImageEvidence("user-a",imageInput(overrides));image=h.store.addVisualAssessment("user-a",image.image_evidence_id,assessment());return h.store.reviewVisualObservation("user-a",{image_evidence_id:image.image_evidence_id,visual_feature_observation_id:image.visible_features[0].visual_feature_observation_id,action:"CONFIRM_FEATURE",reason:"Reviewer confirms only the visible feature."});}

test("capture intents expose the governed B1 set",()=>assert.ok(VISUAL_EVIDENCE_ENUMS.captureIntents.includes("AFFECTED_VS_NORMAL")));
test("view types include context, detail, pair, and root comparison",()=>assert.ok(["FIELD_CONTEXT","DETAIL","AFFECTED_VS_NORMAL_PAIR","ROOT_COMPARISON"].every((item)=>VISUAL_EVIDENCE_ENUMS.viewTypes.includes(item))));
test("quality dimensions are categorical and contain no total score",()=>{assert.ok(VISUAL_EVIDENCE_ENUMS.qualityDimensions.includes("FOCUS"));assert.equal("score" in VISUAL_EVIDENCE_ENUMS,false);});
test("observability has explicit not-in-view and not-assessable states",()=>assert.ok(["NOT_IN_VIEW","NOT_ASSESSABLE"].every((item)=>VISUAL_EVIDENCE_ENUMS.observabilityStates.includes(item))));
test("VE maturity is categorical",()=>assert.deepEqual(VISUAL_EVIDENCE_ENUMS.evidenceLevels,["VE0_RAW_IMAGE_ONLY","VE1_QUALITY_AND_CONTEXT_ESTABLISHED","VE2_VISIBLE_FEATURE_PROPOSED","VE3_HUMAN_REVIEWED_VISIBLE_FEATURE","VE4_FIELD_LINKED_REVIEWED_VISUAL_EVIDENCE"]));
test("TEST_ONLY perception cannot load normally",()=>assert.throws(()=>new VisualPerceptionProvider({authority:"TEST_ONLY_VISUAL_PERCEPTION_PROVIDER"}),/cannot load in normal runtime/));
test("explicit test-only perception factory is isolated",()=>assert.equal(createTestOnlyVisualPerceptionProvider(assessment()).getManifest().authority,"TEST_ONLY_VISUAL_PERCEPTION_PROVIDER"));

test("raw image remains VE0 and is not Diagnosis",async()=>{const h=await setup();try{const image=h.store.createImageEvidence("user-a",imageInput());assert.equal(image.ve_level,"VE0_RAW_IMAGE_ONLY");assert.equal(image.boundaries.image_is_diagnosis,false);assert.equal("diagnosis" in image,false);}finally{await h.close();}});
test("raw image does not directly change Candidate support",async()=>{const h=await setup();try{const before=h.store.assessInvestigation("user-a",{field_id:scope.field_id,season_id:scope.crop_season_id,case_id:scope.case_id});h.store.createImageEvidence("user-a",imageInput());const after=h.store.assessInvestigation("user-a",{field_id:scope.field_id,season_id:scope.crop_season_id,case_id:scope.case_id});assert.equal(after.assessment_id,before.assessment_id);assert.deepEqual(after.candidate_assessments,before.candidate_assessments);}finally{await h.close();}});
test("Image Evidence retains Field and CropSeason ownership",async()=>{const h=await setup();try{const image=h.store.createImageEvidence("user-a",imageInput());assert.equal(image.field_id,scope.field_id);assert.equal(image.crop_season_id,scope.crop_season_id);assert.equal(image.user_id,"user-a");}finally{await h.close();}});
test("cross-user image access is rejected",async()=>{const h=await setup();try{const image=h.store.createImageEvidence("user-a",imageInput());assert.throws(()=>h.store.getImageEvidence("user-b",image.image_evidence_id),/scope not found/);}finally{await h.close();}});
test("cross-field and season creation is rejected",async()=>{const h=await setup();try{assert.throws(()=>h.store.createImageEvidence("user-a",imageInput({field_id:"other-field"})),/scope not found/);assert.throws(()=>h.store.createImageEvidence("user-a",imageInput({crop_season_id:"other-season"})),/scope not found/);}finally{await h.close();}});
test("capture intent is retained without interpretation",async()=>{const h=await setup();try{assert.equal(h.store.createImageEvidence("user-a",imageInput({capture_intent:"LESION_DETAIL"})).capture_intent,"LESION_DETAIL");}finally{await h.close();}});
test("view type is retained",async()=>{const h=await setup();try{assert.equal(h.store.createImageEvidence("user-a",imageInput({view_type:"MACRO_DETAIL"})).view_type,"MACRO_DETAIL");}finally{await h.close();}});
test("quality and observability remain separate structures",async()=>{const h=await setup();try{let image=h.store.createImageEvidence("user-a",imageInput());image=h.store.addVisualAssessment("user-a",image.image_evidence_id,assessment());assert.equal(image.quality_assessments[0].quality.FOCUS,"GOOD");assert.equal(image.quality_assessments[0].observability[0].state,"ASSESSABLE");}finally{await h.close();}});
test("GOOD image quality can coexist with root NOT_ASSESSABLE",async()=>{const h=await setup();try{let image=h.store.createImageEvidence("user-a",imageInput({view_type:"FIELD_CONTEXT"}));image=h.store.addVisualAssessment("user-a",image.image_evidence_id,assessment({observability:[{target:"ROOT_CONDITION",state:"NOT_IN_VIEW",basis:"canopy-only view",appropriate_view:false}],features:[]}));assert.equal(image.quality_assessments[0].quality.FOCUS,"GOOD");assert.equal(image.quality_assessments[0].observability[0].state,"NOT_IN_VIEW");}finally{await h.close();}});
test("NOT_OBSERVED remains distinct from absence",async()=>{const h=await setup();try{let image=h.store.createImageEvidence("user-a",imageInput());image=h.store.addVisualAssessment("user-a",image.image_evidence_id,assessment({features:[{feature_code:"YELLOWING",state:"NOT_OBSERVED"}]}));assert.equal(image.visible_features[0].state,"NOT_OBSERVED");assert.equal(image.quality_assessments[0].not_visible_is_absent,false);}finally{await h.close();}});
test("SEARCHED_NOT_FOUND requires assessable appropriate view and basis",async()=>{const h=await setup();try{const image=h.store.createImageEvidence("user-a",imageInput());assert.throws(()=>h.store.addVisualAssessment("user-a",image.image_evidence_id,assessment({observability:[{target:"YELLOWING",state:"NOT_IN_VIEW",appropriate_view:false}],features:[{feature_code:"YELLOWING",state:"SEARCHED_NOT_FOUND"}]})),/assessable appropriate view/);}finally{await h.close();}});
test("one leaf image retains sampled-object spatial limitation",async()=>{const h=await setup();try{let image=h.store.createImageEvidence("user-a",imageInput());image=h.store.addVisualAssessment("user-a",image.image_evidence_id,assessment());assert.equal(image.visible_features[0].spatial_limitation,"SAMPLED_OBJECT");assert.equal(image.boundaries.one_image_is_whole_field,false);}finally{await h.close();}});
test("visible count stays image-frame-only",async()=>{const h=await setup();try{let image=h.store.createImageEvidence("user-a",imageInput());image=h.store.addVisualAssessment("user-a",image.image_evidence_id,assessment({features:[{feature_code:"CHEWED",state:"OBSERVED",visible_count:3,count_method:"manual frame count"}]}));assert.equal(image.visible_features[0].visible_count,3);assert.equal(image.visible_features[0].count_basis,"IMAGE_FRAME_ONLY");assert.equal(image.boundaries.visible_count_is_population_density,false);}finally{await h.close();}});
test("exact duplicate binary does not amplify scientific evidence",async()=>{const h=await setup();try{const input=imageInput(),first=h.store.createImageEvidence("user-a",input),second=h.store.createImageEvidence("user-a",input),bundle=h.store.getVisualEvidenceBundle("user-a",scope);assert.equal(second.image_evidence_id,first.image_evidence_id);assert.equal(second.exact_duplicate,true);assert.equal(bundle.images.length,1);assert.equal(second.duplicate_capture_event.scientific_amplification,false);}finally{await h.close();}});
test("comparison role requires User or Human authority",async()=>{const h=await setup();try{assert.throws(()=>h.store.createImageEvidence("user-a",imageInput({comparison_role:"AFFECTED",comparison_role_source:"UNKNOWN"})),/comparison role requires/);}finally{await h.close();}});
test("User-provided normal comparison role is retained",async()=>{const h=await setup();try{const image=h.store.createImageEvidence("user-a",imageInput({comparison_pair_id:"pair-1",comparison_role:"NORMAL_COMPARISON",comparison_role_source:"USER_PROVIDED"}));assert.equal(image.comparison_role,"NORMAL_COMPARISON");assert.equal(image.comparison_role_source,"USER_PROVIDED");}finally{await h.close();}});
test("context and detail images may share one capture session",async()=>{const h=await setup();try{const a=h.store.createImageEvidence("user-a",imageInput({capture_session_id:"session-1",view_type:"PATCH_CONTEXT"})),b=h.store.createImageEvidence("user-a",imageInput({capture_session_id:"session-1",view_type:"DETAIL"}));assert.equal(a.capture_session_id,b.capture_session_id);assert.notEqual(a.image_evidence_id,b.image_evidence_id);}finally{await h.close();}});
test("multiple images do not merge into one visual observation",async()=>{const h=await setup();try{const a=h.store.createImageEvidence("user-a",imageInput()),b=h.store.createImageEvidence("user-a",imageInput());assert.notEqual(a.image_evidence_id,b.image_evidence_id);assert.equal(h.store.getVisualEvidenceBundle("user-a",scope).images.length,2);}finally{await h.close();}});

test("CONFIRM_FEATURE creates human-reviewed VE3 state",async()=>{const h=await setup();try{const image=await confirmedImage(h);assert.equal(image.ve_level,"VE3_HUMAN_REVIEWED_VISIBLE_FEATURE");assert.equal(image.visible_features[0].review_status,"CONFIRMED");}finally{await h.close();}});
test("CORRECT_FEATURE preserves original proposal",async()=>{const h=await setup();try{let image=h.store.createImageEvidence("user-a",imageInput());image=h.store.addVisualAssessment("user-a",image.image_evidence_id,assessment());image=h.store.reviewVisualObservation("user-a",{image_evidence_id:image.image_evidence_id,visual_feature_observation_id:image.visible_features[0].visual_feature_observation_id,action:"CORRECT_FEATURE",corrected_feature_code:"BROWNING",corrected_state:"OBSERVED",reason:"Reviewer corrects the visible phenotype."});assert.equal(image.visible_features[0].feature_code,"BROWNING");assert.equal(image.visible_features[0].original_proposal.feature_code,"YELLOWING");}finally{await h.close();}});
test("REJECT_FEATURE preserves proposal and audit history",async()=>{const h=await setup();try{let image=h.store.createImageEvidence("user-a",imageInput());image=h.store.addVisualAssessment("user-a",image.image_evidence_id,assessment());image=h.store.reviewVisualObservation("user-a",{image_evidence_id:image.image_evidence_id,visual_feature_observation_id:image.visible_features[0].visual_feature_observation_id,action:"REJECT_FEATURE",reason:"Feature is not supported by this view."});assert.equal(image.visible_features[0].review_status,"REJECTED");assert.equal(image.review_history[0].original_proposal_preserved,true);}finally{await h.close();}});
test("human review never produces Diagnosis",async()=>{const h=await setup();try{const image=await confirmedImage(h);assert.equal(image.review_history[0].diagnosis_created,false);assert.equal("diagnosis" in image.review_history[0],false);}finally{await h.close();}});
test("VE level is maturity and not Candidate confidence",async()=>{const h=await setup();try{const image=await confirmedImage(h);assert.equal("candidate_confidence" in image,false);assert.equal("probability" in image,false);}finally{await h.close();}});
test("unreviewed proposal cannot link to Investigation Evidence",async()=>{const h=await setup();try{let image=h.store.createImageEvidence("user-a",imageInput());image=h.store.addVisualAssessment("user-a",image.image_evidence_id,assessment());assert.throws(()=>h.store.reviewVisualObservation("user-a",{image_evidence_id:image.image_evidence_id,action:"LINK_TO_OBSERVATION",observation_id:"obs-visual",plant_part:"LEAF_BLADE",reason:"attempt raw link"}),/only human-reviewed/);}finally{await h.close();}});
test("reviewed feature may link to authoritative Investigation Evidence",async()=>{const h=await setup();try{const image=await confirmedImage(h),result=h.store.reviewVisualObservation("user-a",{image_evidence_id:image.image_evidence_id,action:"LINK_TO_OBSERVATION",observation_id:"obs-visual",plant_part:"LEAF_BLADE",reason:"Link reviewed visible feature."});assert.equal(result.image.ve_level,"VE4_FIELD_LINKED_REVIEWED_VISUAL_EVIDENCE");assert.equal(result.investigation_evidence.review_state,"HUMAN_REVIEWED");assert.deepEqual(result.investigation_evidence.payload.primary_phenotypes,["YELLOWING"]);}finally{await h.close();}});
test("reviewed link invalidates Step C through existing bundle hash",async()=>{const h=await setup();try{const before=h.store.assessInvestigation("user-a",{field_id:scope.field_id,season_id:scope.crop_season_id,case_id:scope.case_id}),image=await confirmedImage(h);h.store.reviewVisualObservation("user-a",{image_evidence_id:image.image_evidence_id,action:"LINK_TO_OBSERVATION",observation_id:"obs-visual",plant_part:"LEAF_BLADE",reason:"reviewed link"});const after=h.store.assessInvestigation("user-a",{field_id:scope.field_id,season_id:scope.crop_season_id,case_id:scope.case_id});assert.equal(after.assessment_revision,before.assessment_revision+1);assert.notEqual(after.source_bundle_hash,before.source_bundle_hash);}finally{await h.close();}});
test("exact image and provider provenance are retained without client storage path",async()=>{const h=await setup();try{const image=h.store.createImageEvidence("user-a",imageInput());assert.match(image.content_hash,/^[a-f0-9]{64}$/);assert.equal(image.provenance.perception_provider.network_calls,false);assert.equal(image.storage_reference,"SERVER_MANAGED");assert.equal(image.storage_key,undefined);}finally{await h.close();}});
test("historical review revisions are auditable",async()=>{const h=await setup();try{let image=await confirmedImage(h);image=h.store.reviewVisualObservation("user-a",{image_evidence_id:image.image_evidence_id,action:"MARK_UNRESOLVED",reason:"Retain uncertainty."});assert.deepEqual(image.review_history.map((item)=>item.review_revision),[1,2]);}finally{await h.close();}});
test("default upload remains CASE_ONLY",async()=>{const h=await setup();try{assert.equal(h.store.createImageEvidence("user-a",imageInput()).learning_state,"CASE_ONLY");}finally{await h.close();}});
test("upload is not TRAINING_ELIGIBLE",async()=>{const h=await setup();try{const image=h.store.createImageEvidence("user-a",imageInput());assert.equal(image.training_eligible,false);assert.equal(image.boundaries.upload_is_training_permission,false);}finally{await h.close();}});
test("unsupported visible term becomes VISUAL_VOCABULARY_GAP",async()=>{const provider=createTestOnlyVisualPerceptionProvider(assessment({features:[{feature_code:"ROOT_BROWNING",state:"OBSERVED"}]})),h=await setup(provider);try{const image=h.store.createImageEvidence("user-a",imageInput());assert.equal(image.visible_features.length,0);assert.equal(image.quality_assessments[0].vocabulary_gaps[0].code,"VISUAL_VOCABULARY_GAP");}finally{await h.close();}});
test("TEST_ONLY fixture may propose visible ontology features",async()=>{const provider=createTestOnlyVisualPerceptionProvider({...assessment(),assessment_method:"TEST_ONLY_VISUAL_PERCEPTION_PROVIDER"}),h=await setup(provider);try{const image=h.store.createImageEvidence("user-a",imageInput());assert.equal(image.ve_level,"VE2_VISIBLE_FEATURE_PROPOSED");assert.equal(image.visible_features[0].source,"TEST_ONLY_VISUAL_PERCEPTION_PROVIDER");}finally{await h.close();}});
test("production provider performs no network perception",()=>{const provider=new VisualPerceptionProvider();assert.equal(provider.perceive({}),null);assert.equal(provider.getManifest().network_calls,false);});

test("Step D ROOT_COMPARISON maps to one visual request",async()=>{const h=await setup();try{h.store.visualEvidence.guidanceService={current:()=>rootGuidance()};const request=h.store.getNextVisualRequest("user-a",scope);assert.equal(request.target,"ROOT_COMPARISON");assert.equal(request.request_type,"PHOTO");assert.equal(request.one_primary_request,true);}finally{await h.close();}});
test("visual request reuses known backend context",async()=>{const h=await setup();try{h.store.visualEvidence.guidanceService={current:()=>rootGuidance()};const request=h.store.getNextVisualRequest("user-a",scope);assert.equal(request.known_context_reused.new_field_facts_required,false);assert.equal(request.known_context_reused.field_id,scope.field_id);}finally{await h.close();}});
test("visual request contains why, where, and how",async()=>{const h=await setup();try{h.store.visualEvidence.guidanceService={current:()=>rootGuidance()};const request=h.store.getNextVisualRequest("user-a",scope);assert.ok(request.why_needed&&request.where&&request.how);}finally{await h.close();}});
test("one visual request is not a photography checklist",async()=>{const h=await setup();try{h.store.visualEvidence.guidanceService={current:()=>rootGuidance()};const request=h.store.getNextVisualRequest("user-a",scope);assert.equal(request.photo_checklist,false);assert.equal(Array.isArray(request),false);}finally{await h.close();}});
test("NO_MORE_VISUAL_EVIDENCE_NEEDED works",async()=>{const h=await setup();try{h.store.visualEvidence.guidanceService={current:()=>rootGuidance({guidance_type:"NO_ADDITIONAL_INSPECTION"})};assert.equal(h.store.getNextVisualRequest("user-a",scope).stop_condition,"NO_MORE_VISUAL_EVIDENCE_NEEDED");}finally{await h.close();}});
test("reviewed root evidence satisfies a superseding Guidance identity",async()=>{const h=await setup();try{let image=await confirmedImage(h,{capture_intent:"ROOT",plant_part_scope:"ROOT_SYSTEM",view_type:"ROOT_COMPARISON"});h.store.reviewVisualObservation("user-a",{image_evidence_id:image.image_evidence_id,action:"LINK_TO_OBSERVATION",observation_id:"obs-visual",plant_part:"ROOT_SYSTEM",reason:"Reviewed root view is field-linked."});h.store.visualEvidence.guidanceService={current:()=>rootGuidance({guidance_id:"guidance-superseding"})};assert.equal(h.store.getNextVisualRequest("user-a",scope).stop_condition,"NO_MORE_VISUAL_EVIDENCE_NEEDED");}finally{await h.close();}});
test("FIELD_CHECK_REQUIRED_INSTEAD stops photo loop",async()=>{const h=await setup();try{h.store.visualEvidence.guidanceService={current:()=>rootGuidance({inspection_domain:"MANAGEMENT_HISTORY_CHECK",evidence_concept:"MANAGEMENT_EVENT_DETAIL"})};assert.equal(h.store.getNextVisualRequest("user-a",scope).stop_condition,"FIELD_CHECK_REQUIRED_INSTEAD");}finally{await h.close();}});
test("COUNT_REQUIRED_INSTEAD stops photo loop",async()=>{const h=await setup();try{h.store.visualEvidence.guidanceService={current:()=>rootGuidance({evidence_concept:"TARGETED_DAMAGE_COUNT"})};assert.equal(h.store.getNextVisualRequest("user-a",scope).stop_condition,"COUNT_REQUIRED_INSTEAD");}finally{await h.close();}});
test("MEASUREMENT_REQUIRED_INSTEAD stops photo loop",async()=>{const h=await setup();try{h.store.visualEvidence.guidanceService={current:()=>rootGuidance({evidence_concept:"WATER_MEASUREMENT"})};assert.equal(h.store.getNextVisualRequest("user-a",scope).stop_condition,"MEASUREMENT_REQUIRED_INSTEAD");}finally{await h.close();}});
test("EXPERT_REVIEW_REQUIRED stops photo loop",async()=>{const h=await setup();try{h.store.visualEvidence.guidanceService={current:()=>rootGuidance({evidence_concept:"EXPERT_REVIEW"})};assert.equal(h.store.getNextVisualRequest("user-a",scope).stop_condition,"EXPERT_REVIEW_REQUIRED");}finally{await h.close();}});
test("LAB_EVIDENCE_REQUIRED stops photo loop",async()=>{const h=await setup();try{h.store.visualEvidence.guidanceService={current:()=>rootGuidance({evidence_concept:"LAB_TEST"})};assert.equal(h.store.getNextVisualRequest("user-a",scope).stop_condition,"LAB_EVIDENCE_REQUIRED");}finally{await h.close();}});
test("Golden wrong canopy photo produces another root request, not false normal",async()=>{const fixture=createTestOnlyVisualPerceptionProvider(assessment({observability:[{target:"ROOT_CONDITION",state:"NOT_IN_VIEW",basis:"whole canopy only",appropriate_view:false}],features:[],assessment_method:"TEST_ONLY_VISUAL_PERCEPTION_PROVIDER"})),h=await setup(fixture);try{h.store.visualEvidence.guidanceService={current:()=>rootGuidance()};const image=h.store.createImageEvidence("user-a",imageInput({guidance_id:null,view_type:"FIELD_CONTEXT",capture_intent:"PLANT_CONTEXT"})),request=h.store.getNextVisualRequest("user-a",scope);assert.equal(image.quality_assessments[0].quality.FOCUS,"GOOD");assert.equal(image.quality_assessments[0].observability[0].state,"NOT_IN_VIEW");assert.equal(request.target,"ROOT_COMPARISON");assert.doesNotMatch(JSON.stringify(image),/roots are normal/i);}finally{await h.close();}});
test("Golden B3 visible yellowing remains sampled-leaf evidence",async()=>{const h=await setup();try{let image=h.store.createImageEvidence("user-a",imageInput({spatial_scope:"SAMPLED_OBJECT"}));image=h.store.addVisualAssessment("user-a",image.image_evidence_id,assessment());assert.equal(image.visible_features[0].spatial_limitation,"SAMPLED_OBJECT");assert.equal("field_incidence" in image.visible_features[0],false);assert.equal("field_severity" in image.visible_features[0],false);}finally{await h.close();}});
test("visual schema migration v6 is recorded",async()=>{const h=await setup();try{assert.equal(h.store.db.prepare("SELECT COUNT(*) count FROM investigation_schema_migrations WHERE version=6").get().count,1);}finally{await h.close();}});

async function login(base,user_id){const response=await fetch(`${base}/api/pilot/session`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({password:"1234",user_id})});return response.headers.get("set-cookie").split(";")[0];}
test("visual API requires authentication",async()=>{const h=await setup();h.store.close();const server=await startServer({port:0,dbPath:join(h.root,"pilot.sqlite"),exportDir:join(h.root,"exports"),uploadDir:join(h.root,"uploads")});try{const response=await fetch(`http://127.0.0.1:${server.address().port}/api/pilot/visual-evidence?image_evidence_id=missing`);assert.equal(response.status,401);}finally{await new Promise((done)=>server.close(done));await rm(h.root,{recursive:true,force:true});}});
test("visual API stores binary separately and hides storage path",async()=>{const h=await setup();h.store.close();const server=await startServer({port:0,dbPath:join(h.root,"pilot.sqlite"),exportDir:join(h.root,"exports"),uploadDir:join(h.root,"uploads")});try{const base=`http://127.0.0.1:${server.address().port}`,cookie=await login(base,"user-a"),bytes=Buffer.from("visual-api"),payload={field_id:scope.field_id,crop_season_id:scope.crop_season_id,case_id:scope.case_id,observation_id:"obs-visual",captured_at:now,source:"UPLOAD",capture_intent:"LEAF",plant_part_scope:"LEAF_BLADE",spatial_scope:"SAMPLED_OBJECT",view_type:"DETAIL",original_filename:"leaf.png",media_type:"image/png",size_bytes:bytes.length,comparison_role:"UNKNOWN_ROLE",comparison_role_source:"UNKNOWN",content_base64:bytes.toString("base64")},response=await fetch(`${base}/api/pilot/visual-evidence`,{method:"POST",headers:{cookie,"content-type":"application/json"},body:JSON.stringify(payload)}),body=await response.json();assert.equal(response.status,201);assert.equal(body.image.storage_reference,"SERVER_MANAGED");assert.equal("storage_key" in body.image,false);assert.match(body.image.content_hash,/^[a-f0-9]{64}$/);}finally{await new Promise((done)=>server.close(done));await rm(h.root,{recursive:true,force:true});}});
test("visual API rejects foreign scoped read",async()=>{const h=await setup();const image=h.store.createImageEvidence("user-a",imageInput());h.store.close();const server=await startServer({port:0,dbPath:join(h.root,"pilot.sqlite"),exportDir:join(h.root,"exports"),uploadDir:join(h.root,"uploads")});try{const base=`http://127.0.0.1:${server.address().port}`,cookie=await login(base,"user-b"),response=await fetch(`${base}/api/pilot/visual-evidence?image_evidence_id=${image.image_evidence_id}`,{headers:{cookie}});assert.equal(response.status,403);}finally{await new Promise((done)=>server.close(done));await rm(h.root,{recursive:true,force:true});}});
test("Visual runtime emits no pesticide, product, rate, probability, or Diagnosis field",async()=>{const h=await setup();try{const image=h.store.createImageEvidence("user-a",imageInput()),keys=Object.keys(image).map((key)=>key.toLowerCase());for(const value of ["pesticide","product","rate","probability","diagnosis"])assert.equal(keys.includes(value),false);}finally{await h.close();}});
